### ISSUE TITLE
Account Settings: Primary site option is available even when the user has no sites

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#12372] opened 2020-07-08 00:17 UTC
### Expected behavior
I expect that the "Primary site" setting won't be available if I don't have any sites.

### Actual behavior
The "Primary site" setting is available even if I don't have any sites and displays an empty site picker dialog.

### Steps to reproduce the behavior
1. Login to the app with an WP.com account that have no sites
2. Press the avatar icon at the top right corner of the screen
3. On the Me screen, select **Account Settings**
4. On the Account Settings screen, notice that the **Primary site** option is available
5. Select **Primary site**
6. Notice that the site picker dialog is empty

##### Tested on Pixel 3 XL, Android 9, WPAndroid 15.2-rc-1

Note: these steps were originally provided by @guarani in pbMoDN-ET-p2#comment-1206

**Comment by SowmiaS** [comment] 2022-03-09 05:53
Hello @renanferrari 👋 
In either case 
1. when no sites
2. when only one site is available 

we can **only avoid displaying the site picker dialog**.


In the above-mentioned cases, It still seems meaningful to display the `Primary Site` option under `Account Settings`.
Because, 
1. when no sites - the user can still understand the primary site will be shown under Account Settings.
2. when only one site is available - The user can see the primary site.

Please correct me if I am wrong.

Thanks

**Comment by guarani** [comment] 2022-03-09 11:57
I agree that when the user has **zero** sites there's benefit in not removing part of UI (the section that shows the default site), we could leave it in place with an indication that they have no sites (as you suggest, @SowmiaS).
Similarly, I agree that when the user has **one** site, there's benefit in leaving the site name there since it is of course the primary site.

What I think needs changing is how in both cases, tapping on the "primary site" section reveals an empty picker (as noted in Step 6 of the steps to reproduce above). 

For both cases (zero or one site), one option could be to disable or "grey out" the primary site picker. That way it still displays a message to the user, while remaining disabled.

Thanks for this suggestion, @SowmiaS!

**Comment by SowmiaS** [comment] 2022-04-20 10:48
Hi 👋 

In the Account Settings feature, I noticed that everything (UI, business logic, etc) is written in a single class [AccountsSettingsFragment](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/prefs/AccountSettingsFragment.java). So I have refactored the code following MVVM architecture and reactive approach using Flow. And then fixed this issue.

I have split the task into subtasks for ease of Review.
- [x] Create AccountSettings usecases https://github.com/wordpress-mobile/WordPress-Android/pull/16368
- [x] Create AccountSettingsViewModel https://github.com/wordpress-mobile/WordPress-Android/pull/16369
- [x] Implement LifecycleOwner for PreferenceFragment https://github.com/wordpress-mobile/WordPress-Android/pull/16370
- [x] Refactor AccountSettingsFragment  https://github.com/wordpress-mobile/WordPress-Android/pull/16371
- [ ] Restricts from showing an empty dialog when the user doesn’t have multiple sites. https://github.com/wordpress-mobile/WordPress-Android/pull/16383

Thanks 🙂

**Comment by ashiagr** [comment] 2022-04-27 05:48
This is amazing, @SowmiaS! 👏
We should be able to review PRs by early next week. Thank you for your patience. 🙇‍♀️

**Comment by thehenrybyrd** [comment] 2022-11-01 09:07
@SowmiaS it looks like most of your PRs related to this issue have been reviewed and merged! 👏 
Are we still waiting on the final PR (#16383)? 
Otherwise, can this issue be closed? cc: @ashiagr and @AjeshRPai as you've done reviewing for this issue 😄

**Comment by SowmiaS** [comment] 2022-11-01 09:36
> @SowmiaS it looks like most of your PRs related to this issue have been reviewed and merged! 👏 Are we still waiting on the final PR (#16383)? Otherwise, can this issue be closed? cc: @ashiagr and @AjeshRPai as you've done reviewing for this issue 😄

@thehenrybyrd  Sorry about the delay. I went busy with some other work. You can expect the final PR by tomorrow. Once it is done, we can close this issue.

Thanks.

**Closed** 2022-12-16 06:08 UTC
Labels: [Type] Bug, [Pri] Low, /Me, good first issue
