### ISSUE TITLE
Highly erratic scrolling, display and overview over posts in postlist

### ISSUE THREAD

**Issue by actcontpr** [wordpress-mobile/WordPress-Android#4844] opened 2016-11-28 14:54 UTC
### Expected behavior
The list of posts should be in a predictable stable order and scrolling through the list should reveal posts without the contents of the list repeating itself or the list jumping to the beginning again. Scrolling behaviour should be predictable.

### Actual behavior
Scrolling through the list of posts is erratic and unpredictable and requires multiple attempts to find the desired content. Order of posts listed often changes after second flick to scroll. Content items repeat itself in the list while scrolling.

### Steps to reproduce the behavior
This problem occurs on a website that is registered as second website in the app, 30 - 50 posts and has all posts set to privat (no idea if these points could have any influence on the bug)

##### Tested on [device], Android [version]
Moto G2, Marshmallow (Android 6)

**Comment by hoverduck** [comment] 2017-01-19 22:01
@actcontpr I'm unable to reproduce this bug on my Nexus 6P, Android 7.1.1.  Are you still seeing the problem?  A couple points may help clarify the issue:

1) What version of the app are you running? (found under Help & Support)
2) Is this a WordPress.com site, or self-hosted?

**Comment by maxme** [comment] 2017-05-29 06:22
I can't repro either and we didn't get any other report like this. Post list backend code changed a lot since 2016 (via FluxC), so I'm closing this.

**Closed by maxme** 2017-05-29 06:22 UTC
Labels: Post List, [Pri] Medium, [Type] Bug
