### ISSUE TITLE
RuntimeException: Unable to start service org.wordpress.android.login.LoginWpcomService@2155942 with Intent { cmp=o...

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#17466] opened 2022-11-15 11:01 UTC
**Sentry Url**: https://sentry.io/share/issue/c986b14e6af643c79a19824082fbac44/
**User Count**: 31
**Count**: 441
**First Release**: 21.0-rc-2
**First Seen**: 2022-10-24T17:54:09.292000Z
**Last Seen**: 2022-11-15T09:32:09Z
**24 Hours**: 42
**30 Days**: 443

```
RuntimeException: Unable to start service org.wordpress.android.login.LoginWpcomService@2155942 with Intent { cmp=org.wordpress.android/.login.LoginWpcomService (has extras) }: java.lang.IllegalArgumentException: org.wordpress.android: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
     at org.wordpress.android.util.AutoForegroundNotification.getNotificationBuilder(AutoForegroundNotification.java:45)
     at org.wordpress.android.util.AutoForegroundNotification.progress(AutoForegroundNotification.java:55)
     at org.wordpress.android.login.LoginWpcomService$LoginNotification.progress(LoginWpcomService.java:122)
     at org.wordpress.android.login.LoginWpcomService.getNotification(LoginWpcomService.java:206)
     at org.wordpress.android.login.LoginWpcomService.getNotification(LoginWpcomService.java:42)
     at org.wordpress.android.util.AutoForeground.notifyState(AutoForeground.java:208)
     at org.wordpress.android.util.AutoForeground.setState(AutoForeground.java:170)
     at org.wordpress.android.login.LoginWpcomService.setState(LoginWpcomService.java:232)
     at org.wordpress.android.login.LoginWpcomService.onStartCommand(LoginWpcomService.java:257)
...
(13 additional frame(s) were not displayed)
```

**Comment by ovitrif** [comment] 2022-11-15 15:49
I'm closing this issue in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/17465, which point to the same root cause in the stack trace and has affected more users as of today. The fix for that issue should handle both crashes.

**Closed as completed by ovitrif** 2022-11-15 15:49 UTC
Labels: [Type] Crash
