### ISSUE TITLE
File Block: Can't select documents from Drive

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#14603] opened 2021-05-06 12:52 UTC
### Expected behavior
When choosing a file to upload to the File Block, I expected I'd be able to upload files from Google Drive.

### Actual behavior
When I select "Choose from device" and then tap the image icon top-right, I'm taken to Drive to select a file, however only images and videos are selectable.
I cannot choose a PDF or other document file.

### Steps to reproduce the behavior
1. In a post or page, insert a File Block
2. Select "Choose from device" 
3. Within the "Choose from device" file-picker, tap the image icon, right of the search icon.
4. Browse Drive for a PDF, Spreadsheet or other document.
5. Notice it is greyed out and cannot be selected.

##### Tested on Samsung Galaxy S21, Android 11, WPAndroid 17.3-rc-1
Found in beta-testing: p5T066-2eB#comment-8151

**Comment by mchowning** [comment] 2021-05-06 15:19
:wave:  @jd-alexander! What are your thoughts here?

**Comment by jd-alexander** [comment] 2021-05-06 23:25
@mchowning I am going to reproduce this and check to see what could be causing the issue.

**Comment by jd-alexander** [comment] 2021-05-07 06:45
I haven't been able to reproduce this. I will pick it back up tomorrow and see what I discover.

**Comment by jd-alexander** [comment] 2021-05-11 15:13
The documents that can't be selected are Google docs ( i.e docs in a type/representation that doesn't represent a file format). To access these documents our users would have to first download the document to their device and then reupload. If the document exists as a PDF, docx, etc. file type in Google Drive it can be selected. Since this behavior is expected we will be closing this issue.

**Closed as completed by jd-alexander** 2021-05-11 15:13 UTC
