### ISSUE TITLE
Reader: Wrong content on Saved tab

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#12886] opened 2020-09-04 07:42 UTC
### Expected behavior
When I switch to Saved tab, list of saved posts should be rendered.

### Actual behavior
When I switch to Saved tab, list of posts from Automattic tab is displayed.

### Steps to reproduce the behavior
1. Select Automattic tab
2. Restart the app
3. Select "Following" tab
4. Select "Saved" tab
5. Notice the content is a content of the Automattic tab, not saved tab

##### Tested on [device], Android [version], WPAndroid [version]
Emulator API 29

**Comment by malinajirka** [comment] 2020-09-04 08:41
I've investigated this issue and it's quite interesting. ViewPager2 is not correctly handling fragment state restoration and not even fragment's lifecycle. When you follow the steps, none of the fragment is moved to the "resumed" state. Either case, I've not been able to reproduce the issue with `v1.1.0-alpha01` of the viewpager2 library. Since it's still in alpha, I don't want to use it in production. However, I think we should just wait until the library is released.

**Comment by thehenrybyrd** [comment] 2022-08-25 11:36
I was unable to reproduce this in WP Android 20.5-rc-2 on Samsung Galaxy S21. The "Saved" tab displayed the correct data immediately.
Closing, please reopen if we encounter this again.

**Closed as completed by thehenrybyrd** 2022-08-25 11:36 UTC
Labels: [Type] Bug
