### ISSUE TITLE
Orientation isn't correct when uploading photos sometimes

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#5737] opened 2017-04-24 23:58 UTC
> In Aztec, the vertical photo did appear in the media selector sideways, but when I added it to the post it showed up immediately with a vertical orientation. In Visual, the vertical photo appeared vertical in the media selector; when I added it to the post it showed up sideways while it uploaded, but after the upload finished it appeared in the post with a vertical orientation.

A report from @rachelmcr 

Version 7.1, Samsung devices SM-G920F & SM-G903F

@nbradbury/@aforcier any ideas? Which part of the app is likely responsible: the editor or the media picker?

**Comment by rachelmcr** [comment] 2017-04-25 09:15
To clarify, the description above is from my testing on a Nexus 9, Android 7.1.1, WPAndroid alpha-49.

The issue seen on those Samsung devices (using WPAndroid 7.1) resulted in images being uploaded sideways AND appearing sideways in the resulting post. (I couldn't reproduce the image being sideways in the post on my Nexus 9.)

Internal ref: p4a5px-1I6-p2

**Comment by nbradbury** [comment] 2017-04-25 16:57
> @nbradbury/@aforcier any ideas? Which part of the app is likely responsible: the editor or the media picker?

Which "media selector" are we talking about here? If it's the new photo picker, then it's most likely responsible.

**Comment by rachelmcr** [comment] 2017-04-25 17:24
The issue reported by users (and that I tested in the Visual editor) uses the stock Android picker. (The new photo picker isn't released in the visual editor.)

The test I did in Aztec was with the new photo picker.

**Comment by rachelmcr** [comment] 2017-04-28 15:27
We have another report of photos being uploaded sideways. In this it's a Sony device SO-03G, app version 7.1.

Internal ref: 184186-h

**Comment by ChrissiePollock** [comment] 2017-05-03 16:16
Another report from WordPress - 7.1 - SAMSUNG-SM-N900A - android - 5.0 - 

Internal ref: 182427-h

**Comment by rachelmcr** [comment] 2017-05-05 11:06
Another report from a user with a Sony device SO-03G, Android 7.0, app version 7.1.

Internal ref: 185960-h

**Closed** 2017-05-09 08:02 UTC
Labels: Media, [Type] Bug
