### ISSUE TITLE
Notifications don't load after logging in.

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-Android#15995] opened 2022-02-24 21:27 UTC
### Expected behavior
Notifications to load when logging in.

### Actual behavior
Most of the time they don't.

### Steps to reproduce the behavior

- Log into the app.
- Go to Notifications.
- The `No notifications` view is displayed even though there are Notifications.
- Pull to refresh.
- It shows the loading indicator and never completes.
- After a couple of times of force closing the app and pull to refresh it would finally load.

Sometimes the Notifications did load immediately, but most times they not. Other parts of the app loaded fine.

![Screenshot_20220222-143228](https://user-images.githubusercontent.com/1816888/155610522-7341196b-7073-4416-baca-b893c7c7a602.png)

**Comment by thehenrybyrd** [comment] 2022-05-09 10:27
I was able to reproduce this in WP 19.8-rc-2, on Samsung Galaxy S21, Android 12.

Here are the steps I took:
1. Log out, then log in again to the app.
2. Select site, dismiss Quick Start prompt, and tap Notifications tab.
3. See "No notifications...yet" in "All" tab. 
4. Check all other Notifications tabs. In all of them, there are "No [comments/follows/likes] yet", except the Unread tab which states "you're all up to date".
5. Pull to refresh, and note the loading indicator starts and never stops. Notifications do not load.

Restarting the app and then switching to My Site, pull-to-refresh, and then back to Notifications loaded them for me.

**Comment by thehenrybyrd** [comment] 2022-05-10 09:18
While smoke testing login, I logged in with a newer account and was _not_ able to reproduce this issue. This account had only a few (4) notifications from site creation, but they all appeared in both "All" and "Unread".

I then tried again with the account I used in my last report, and no longer had the issue.

A good next step would be to get app logs if we can reproduce this again.

**Comment by thehenrybyrd** [comment] 2022-05-10 09:49
This showed up again after creating a new account and site. I wasn't able to get logs in this case, but I did get a recording:

https://user-images.githubusercontent.com/15107387/167598642-a55dc37a-f008-4f93-a72c-2376dc314fea.mp4

I previously thought this could be due to loading too many sites in the background, or too many notifications, but I think that couldn't be the case with a brand new account and site.

**Comment by antonis** [comment] 2024-03-05 10:49
I've tested with an existing account and a new account signup with the latest version of the app (`24.3`) and wasn't able to reproduce the issue. I'm closing it for now. Feel free to reopen if the issue reoccurs.

**Closed as completed by antonis** 2024-03-05 10:49 UTC
Labels: [Type] Bug, [Pri] Medium, Notifications
