### ISSUE TITLE
Stats Refresh:  Stats graph showing formulas instead of values 

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-Android#10071] opened 2019-06-19 17:44 UTC
### Expected behavior
When you go to the Stats view in any language, on the side of the graph you should see the range of number of views appear

### Actual behavior
If you are in some languages (Swedish is the only one I found like this so far) instead of displaying the quantities in the side bar you see formulas for getting the quantity:
<img src="https://cdn-std.dprcdn.net/files/acc_593859/0ZW7Ia" />

### Steps to reproduce the behavior
1. Switch your WordPress app to Swedish
2. Open the WordPress app and go to a site with some traffic and view it's stats
3. Go to any of the views with a graph (days, weeks, etc)
4. see all the maths appear

WordPress alpha 171
Android 5.1.1

**Comment by frosty** [comment] 2019-06-19 18:12
cc @planarvoid 

I think this must be an issue with the large value formatter – at a guess, strings are being formatted differently in some locales, which means code to replace occurrences of `E[0-9][0-9]` won't do anything.

**Comment by planarvoid** [comment] 2019-06-20 07:18
This is the same issue - https://github.com/wordpress-mobile/WordPress-Android/issues/9308. The information that it's always happening in Swedish is new. I couldn't reproduce the issue before. I think there is a bug in the library (which we could fix by overriding it).

**Comment by frosty** [comment] 2019-06-21 08:20
Fixed by #10075

**Closed by frosty** 2019-06-21 08:20 UTC
