### ISSUE TITLE
Comments: Broken images visible in comments list.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3265] opened 2015-09-28 23:02 UTC
Nexus 4, OS 5.1.1

Title has it. 
The comment list in the screenshot contains three comments each with an image in the comment content.  Notice the broken image glyph in each of the rows.
![screenshot_2015-09-28-17-56-53](https://cloud.githubusercontent.com/assets/1435271/10151208/0726f96c-660b-11e5-9938-27800cfc1ea2.png)

**Comment by rachelmcr** [comment] 2015-12-10 15:06
I reproduced this on my Nexus 9, OS 6.0, app beta 4.8-rc-3.

Tapping on the comment to view the comment detail displays the image as expected. In the list view, it might be nice to display a media icon (or just nothing at all).

**Comment by khaykov** [comment] 2016-11-04 09:35
I tested this on variety of Android versions and looks like this is no longer happens. Closing.

**Closed by khaykov** 2016-11-04 09:35 UTC
Labels: Comments, [Type] Bug
