### ISSUE TITLE
Stats: request to improve the "Data not loaded" screen when stats are loading slowly

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#12828] opened 2020-08-28 22:13 UTC
Steps to reproduce:

1. Use a site that has 1M+ yearly views or 150k+ monthly views.
1. Go to Stats.
1. Browse the Days, Weeks, Months, Years screens and note how long it takes for each one to load.

**Result:** the Days and Weeks screens loaded fairly quickly, and the Months and Years screens took 70+ seconds to load. During the loading time, the first screen displayed says "Data not loaded" and then eventually a placeholder screen displayed saying "There was a problem loading your data, refresh your page to try again."

We could improve this by creating a friendlier message instead of saying "Data not loaded" for this case.

"Data not loaded" after tapping Months on a site with 150k+ monthly views|Placeholder screen appears after a bit and pulses a screen saying there was a problem
---|---
![Screenshot_20200828-152638](https://user-images.githubusercontent.com/1119271/91618404-7ef29b80-e947-11ea-837f-a70f3ae01650.png)|![Screenshot_20200828-152646](https://user-images.githubusercontent.com/1119271/91618402-7e5a0500-e947-11ea-8952-bcbcb5c134ab.png)
<p style="clear:both;"><sup>Tested with WPAndroid 15.6-rc-2 on Pixel 3 Android 10 using `en.blog.wordpress.com` from a connection 23Mpbps with 18-759ms latency. .</sup></p>

Note: it's possible this is an extreme edge case because of the latency on the connection ([screenshot](https://user-images.githubusercontent.com/1119271/91618929-07257080-e949-11ea-9e5f-63bc85ef2ca5.png)). If so, please feel free to close this issue with a note!

**Comment by designsimply** [comment] 2020-09-09 17:30
I noticed this again while testing 15.7. beta—I took a video this time and found that it took over 1m51s to load Months stats (started recording a few seconds in and tapped Retry 23s in though) and about 1m35s to load Years stats for the en.blog site. ([3m37s](https://cloudup.com/cRnhvNadRmV))
<p style="clear:both;"><sup>Tested with WPAndroid 15.7-rc-1 on Pixel 3 Android 11.</sup></p>

Internet connection speed at the time of the test was 120Mbps. ([Screenshot Sep 9, 2020 11_25_37 AM](https://user-images.githubusercontent.com/1119271/92632838-0369e600-f287-11ea-9a03-48c90b7da8f9.png))

**Comment by megsfulton** [comment] 2020-09-21 22:12
We can definitely improve the messaging here. In order to do that, it would be helpful to understand what the underlying cause of the error is? 

Also wondering if there's a technical issue here that might need some developer eyes 👀 on it?

**Comment by designsimply** [comment] 2020-09-30 00:43
I checked on this again during 15.8 beta testing and found the issue where the "Data not loaded" message appears on the Months screen for a site with a lot of followers (70M) and traffic (183k views per month), but the data loaded normally after that when I did a pull-to-refresh. Note that this only happens for me on sites with a very high volume of traffic. In any case, I wonder if we can make it __feel__ faster by caching and loading the previous months (or years) right away and only refreshing the page with the latest month's data with a refresh as soon as it is available to the app.

<img src="https://user-images.githubusercontent.com/1119271/94630533-5120af80-0283-11eb-9ee1-40d9f6700c4e.jpg" width="270" alt="Screenshot_20200929-181929"> <img src="https://user-images.githubusercontent.com/1119271/94630535-53830980-0283-11eb-99fe-00da0d043466.jpg" width="270" alt="Screenshot_20200929-182211">
<p style="clear:both;"><sup>Tested with WPAndroid 15.8-rc-1 on Pixel 4 Android 10.</sup></p>

I've added this issue to Groundskeeping so we can look at it in the next rotation coming up in a few weeks. Thanks @megsfulton!

**Comment by SiobhyB** [comment] 2023-04-18 17:00
I came across this when testing [`22.2-rc-1`](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/22.2-rc-1). I used wordpress.com/blog as the basis for my testing and confirmed that I got a "Data not loaded" screen when scrolling to view the stats in the "Months" and "Years" tabs. After a while, the stats loaded as expected.

**Comment by ravishanker** [comment] 2023-06-21 01:47
Since this seems to occur only on a high volume, and flaky or slow connections, there's anything to fix here.  There's already a retry button as well.  Also, stats are likely to revamped soon.  So closing this for now.

**Closed as completed by ravishanker** 2023-06-21 01:47 UTC
Labels: [Type] Enhancement, Stats, Design Needed
