### ISSUE TITLE
405 error on post upload

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#3456] opened 2015-11-30 21:51 UTC
`46.139.84.148 - - [30/Nov/2015:10:55:50 +0000] "GET /xmlrpc.php HTTP/1.0" 405 42 "-" "wp-android/4.8-rc-1 (Android 5.1.1; en_US; Sony D5803/D5803)"`

Steps to reproduce:
1. Open the app, write a post. It can include images, but doesn’t have to. I can reproduce the issue whether I include images or not.
2. Click “Save” or “Publish” to push your changes to the site.

![2015-11-29-13-47-35](https://cloud.githubusercontent.com/assets/1158819/11485650/5141553a-9769-11e5-99b6-c08ab3521f3c.png)

Reported by @jeherve

Could be the host

**Comment by jeherve** [comment] 2015-11-30 22:02
> Could be the host

If there is anything I can do to confirm that with them, please let me know.

They confirmed that this IP isn't blocked, though.

**Comment by maxme** [comment] 2015-12-01 06:19
> If there is anything I can do to confirm that with them, please let me know.

Do they have any plugins installed? Looks like a plugin or their host is blocking the `metaWeblog.newPost` or `metaWeblog.editPost` xmlrpc call.

**Comment by maxme** [comment] 2015-12-03 10:24
Thanks to @jeherve, we've probably found the source of the issue. The server was serving a http connection, this self hosted site was setup in the App at date D1. Later the server was updated and is now serving a https connection, a 301 redirection has been setup to redirect from `http://jeremy.hu/xmlrpc.php` to `https://jeremy.hu/xmlrpc.php`. Note that traffic is routed to cloudflare before going to the server.

Removing/reinstalling the self hosted site in the App fixed the problem.

I've tested that configuration *without cloudflare* on a private server and the XMLRPC was correctly redirected to the https server. I think the redirection + the traffic redirection to cloudflare is the problem (should be tested).

Note: The `GET` request in the server logs is really weird.

If the problem is the redirect. I'm not sure how we can fix it, replacing server endpoint automatically after a redirection could probably do more harm.

**Comment by mzorz** [comment] 2016-12-01 13:44
Tested adding a self-hosted site, self-hosted jetpack connected site, and wp.com site and posting to all 3 successfully. I assume this problem was specific to this installation and had little to do with the Android app itself. Closing this issue.

**Closed by mzorz** 2016-12-01 13:44 UTC
Labels: [Type] Bug
