### ISSUE TITLE
Gallery is removed after editing post from Jetpack Android app

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-Android#18465] opened 2023-05-18 13:56 UTC
### Expected behavior
I'd expect to be able to edit a post from the app that was created on the web without losing my gallery. 

### Actual behavior
If I edit the post in the app that contains an image gallery, the gallery is removed. 

It sounds related to the issue https://github.com/wordpress-mobile/WordPress-Android/issues/17712 

### Steps to reproduce the behavior
1. Create a post on a Jetpack connected site from the web browser that includes text above and bellow an image gallery
2. Open the post from the Jetpack app
3. Edit the text bellow the image
4. Update the post
5. Refresh the post in the browser, the image gallery is removed. 

##### Tested on Samsung s9+, Android 10, JPAndroid / WPAndroid 22.3

User report: 6237950-zen

**Comment by thomashorta** [comment] 2023-06-13 22:09
Hi @rezzap, I believe you're right and this is related to #17712. 🙇 

The fix for that issue is part of the Android Jetpack version 22.5 release which is currently being rolled out to our users and should be available to all userbase by tomorrow (pbArwn-69x-p2). I just tested 22.3, 22.4, and 22.5 and confirmed the issue is present in the previous versions but is fixed on the latest.

It would be great to get back to that user and let them confirm that the issue no longer happens on Jetpack 22.5 before closing this issue.

Let me know if you need anything, and thank you!

**Comment by rezzap** [comment] 2023-06-14 08:46
@thomashorta  I've let the user know they can expect the fix in 22.5 and we can re-open the issue here if they follow up. We didn't hear back from them after the latest reply, so I wouldn't expect us to wait to close this if we're not reproducing this now.

**Comment by thomashorta** [comment] 2023-06-14 13:06
That makes sense to me, I will close the issue for now, since the fix for #17712, introduced in release 22.5, fixed this issue as well.

**Closed as completed by thomashorta** 2023-06-14 13:06 UTC
Labels: [Type] Bug, [Pri] Medium, Posting/Editing
