### ISSUE TITLE
Remove superfluous periods in Blogging Reminders

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-Android#15403] opened 2021-10-01 15:06 UTC
Reported by @kyleaparker  in version 18.3 internal reference p5T066-2G1

- We should remove the extra period in 'On Monday and Sunday at 10am.'
- We should remove the period after the shortened day names (Mon, Tue, Wed)

![image](https://user-images.githubusercontent.com/50576199/135643277-813c654d-95a9-42f1-802a-6ecd8b6502ed.png)

![image](https://user-images.githubusercontent.com/50576199/135643300-8620d857-c4e8-44be-8636-ba081ec24bfc.png)

**Comment by yashambkr** [comment] 2022-07-10 04:16
@osullivanchris @thehenrybyrd  is the issue resolved?  if not I can work on it.

**Comment by niklasenberg** [comment] 2022-09-06 16:48
@osullivanchris seemingly resolved, was not able to reproduce on **Google Pixel 3a with WP Android 20.6**

<img width="376" alt="Screenshot 2022-09-06 at 18 44 14" src="https://user-images.githubusercontent.com/81677013/188692435-7eed95a4-af54-4b3a-b1e6-4c0698a3d928.png">

<img width="376" alt="Screenshot 2022-09-06 at 18 44 29" src="https://user-images.githubusercontent.com/81677013/188692523-9f387562-3c15-4e19-8c8d-0cd5568eba76.png">

**Comment by thehenrybyrd** [comment] 2022-11-01 09:54
I was also unable to reproduce in WP Android 21.0, agreed that it's resolved. I didn't find a PR specific to this, so suspect someone fixed it along the way in another PR. Closing.

**Closed as completed by thehenrybyrd** 2022-11-01 09:54 UTC
Labels: [Type] Bug, [Pri] Low, Good First Issue, Blogging Reminders
