### ISSUE TITLE
ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#17154] opened 2022-09-12 12:46 UTC
**Sentry Url**: https://sentry.io/share/issue/556f598b913648d39b199ab5c3188bae/
**User Count**: 936
**Count**: 1207
**First Release**: 20.1
**First Seen**: 2022-06-28T10:26:41.803000Z
**Last Seen**: 2022-09-12T11:40:29Z
**24 Hours**: 27
**30 Days**: 555

```
ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
There was 1 root cause:
com.android.volley.NoConnectionError(java.net.ConnectException: Failed to connect to /10.199.212.2:8080)
 call GlideException#logRootCauses(String) for more detail
     at org.wordpress.android.util.image.ImageManager.preload(ImageManager.kt:313)
     at org.wordpress.android.ui.sitecreation.SiteCreationMainVM$preloadThumbnails$1.invokeSuspend(SiteCreationMainVM.kt:141)
```

**Comment by derekblank** [comment] 2022-09-16 05:48
This issue appears to be related to the user attempting to load an image resource while being offline. As it references `Glide`, it's possible that it is related to the introduction of the [react-native-fast-image](https://github.com/DylanVann/react-native-fast-image) library, but FastImage has since been disabled for Android, so I haven't yet confirmed that this is related.

**Comment by SiobhyB** [comment] 2023-09-05 16:43
I outlined a couple of other Sentry issues that I believe are related to this one in the comment at https://github.com/wordpress-mobile/WordPress-Android/issues/18629#issuecomment-1706958560.

I'll keep this one open as it differs more than the other two Sentry reports, but let me know if you think we should close in favour of that other issue.

**Comment by antonis** [comment] 2023-12-05 15:36
This was fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/19474 in `23.7` but two occurrences of a regression in `23.7` and `23.7.1` captured a regression. The stack traces were the following:

```
java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
There was 1 root cause:
com.android.volley.NoConnectionError(java.net.SocketException: Connection reset)
 call GlideException#logRootCauses(String) for more detail
    at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:217)
    at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:130)
    at org.wordpress.android.util.image.ImageManager.preload(ImageManager.kt:315)
    at org.wordpress.android.ui.sitecreation.SiteCreationMainVM$preloadThumbnails$1.invokeSuspend(SiteCreationMainVM.kt:202)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.CoroutineContextKt.withContinuationContext
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:90)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
``` 

and

```
java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
There was 1 root cause:
com.android.volley.NoConnectionError(javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x6fe368d408: I/O error during system call, Connection reset by peer)
 call GlideException#logRootCauses(String) for more detail
    at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:217)
    at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:130)
    at org.wordpress.android.util.image.ImageManager.preload(ImageManager.kt:315)
    at org.wordpress.android.ui.sitecreation.SiteCreationMainVM$preloadThumbnails$1.invokeSuspend(SiteCreationMainVM.kt:202)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.CoroutineContextKt.withContinuationContext
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:90)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by antonis** [comment] 2023-12-05 16:14
> two occurrences of a regression in `23.7` and `23.7.1` captured a regression

A follow up PR was opened to handle this https://github.com/wordpress-mobile/WordPress-Android/pull/19740

**Closed as completed** 2023-12-06 06:07 UTC
Labels: [Pri] Medium, [Type] Crash, Site Creation
