### ISSUE TITLE
Crash when sharing a video with the app

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#10843] opened 2019-11-25 09:06 UTC
The app crashes when you try to share a video with the app on API 29. 

Steps to reproduce: 
- Share a video with the app
- Select the "Add to a new post" option
- The editor crashes

Stacktrace: 
```
java.lang.IllegalArgumentException: Invalid column latitude
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at org.wordpress.android.util.MediaUtils.getFilenameFromURI(MediaUtils.java:173)
        at org.wordpress.android.util.MediaUtils.downloadExternalMedia(MediaUtils.java:214)
        at org.wordpress.android.util.MediaUtilsWrapper.copyFileToAppStorage(MediaUtilsWrapper.kt:39)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase.copyToAppStorage(CopyMediaToAppStorageUseCase.kt:48)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase.access$copyToAppStorage(CopyMediaToAppStorageUseCase.kt:17)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase$copyFilesToAppStorageIfNecessary$2.invokeSuspend(CopyMediaToAppStorageUseCase.kt:31)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase$copyFilesToAppStorageIfNecessary$2.invoke(Unknown Source:10)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:155)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase.copyFilesToAppStorageIfNecessary(CopyMediaToAppStorageUseCase.kt:27)
        at org.wordpress.android.ui.posts.editor.media.AddLocalMediaToPostUseCase.addNewMediaToEditorAsync(AddLocalMediaToPostUseCase.kt:48)
        at org.wordpress.android.ui.posts.editor.media.EditorMedia$addNewMediaItemsToEditorAsync$1.invokeSuspend(EditorMedia.kt:116)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by jd-alexander** [comment] 2019-12-23 19:02
This is being caused because in API 29 `latitude` is depreciated

**Comment by designsimply** [comment] 2020-02-18 20:35
I tested today with WPAndroid 14.2-rc-2 on Pixel 3 Android 10 and I was unable to crash the app when sharing a video in either Aztec or Gutenberg Mobile. ([52s](https://cloudup.com/cyTFtNOmjMY), [1m4s](https://cloudup.com/cJpdv_Taa66))

@jd-alexander I see a few PRs linked to this issue, but I'm not quite sure any are the proper fix. Can you confirm if you fixed this in a different PR and note which one or if this problem is still happening for you by chance?

**Comment by jd-alexander** [comment] 2020-02-18 21:30
Hi @designsimply I did a fix but I was having problems reproducing the issue! So I wasn't confident to merge it unless it occurs again, which would cause me to make someone review the PR to ensure there are no regressions and see if it resolves the issue. Is this a high priority now in terms of impact?

**Comment by designsimply** [comment] 2020-02-18 22:12
Not high priority. I just wanted to check in on it! especially because I couldn't find it in Sentry with a search and I couldn't replicate it on my Pixel 3 with the steps given. I thought we might be able to close it. 🙂 PR review it is. @khaykov might you be able to help review this during your maintenance rotation this week if you have time?

**Closed** 2020-02-22 04:20 UTC
Labels: Posting/Editing, [Type] Crash
