### ISSUE TITLE
Editor: Improve preview (deprecate local preview or at least prioritize remote preview)

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-Android#4243] opened 2016-06-17 09:36 UTC
Right now Preview doesn't render properly in some circumstances (e.g. shortcodes won't render, plugins won't get a stab at the content, etc.). Let's update it so it's more robust and users can better get a sense of what their content will look like without having to leave the app.

Parallel WPiOS Issue - https://github.com/wordpress-mobile/WordPress-iOS/issues/5579

**Comment by maxme** [comment] 2016-06-17 10:09
Could we just drop the local preview and open the editor instead?

**Comment by hoverduck** [comment] 2016-11-15 16:44
Along this note I've run into issues with the Preview where if you tap on an image it opens at full zoomed-in resolution with no way out but returning to the Posts/Page list or opening the Editor

![android-bad-preview](https://cloud.githubusercontent.com/assets/7233112/20314621/cd97e13e-ab28-11e6-965b-c97ec3286883.gif)

**Comment by maxme** [comment] 2017-04-11 06:20
Local changes preview will never be good. With auto-sync, local preview won't be used often. 

I suggest we just drop the preview for local changes and let the user open the editor.

**Comment by oguzkocer** [comment] 2017-04-17 12:36
> Local changes preview will never be good.

I agree with this. I'd rather we don't show a local preview at all rather than showing something that's inaccurate as it can mislead more than it helps.

The only issue I think we need to tackle here is that in the Preview page we have the "This post has local changes which haven't been published" view to publish or revert changes which I don't think the user can do elsewhere. This probably is worth a separate issue though and a higher priority one in my opinion.

What do you think @maxme?

**Comment by oguzkocer** [comment] 2017-04-17 12:46
Actually, I looked at this again and there might be a simple solution to both of these issues, not sure if it'd be a good one.

What if, if there are local changes, we replace the "Preview" button with "Revert". Since we have the publish beside it, they can do all possible actions from the list. "Edit", "Revert", "Publish" and "Trash" the post and we can 🔥 the preview page.

**Comment by oguzkocer** [comment] 2017-04-17 12:50
Just noting here that #4623 is also relevant to these possible changes, so we should keep that in mind.

P.S: Sorry about the multiple comments in quick succession, I just noticed it while going through the `broken-window` issues.

**Comment by elibud** [comment] 2018-03-05 21:30
I think we should keep previews for now, two reasons:

1. We don't know how much users rely on them with more data.
2. Once we implement autosave (hopefully in the next couple of months) the situation should improve a lot.

**Comment by rachelmcr** [comment] 2018-09-28 11:49
This came up again while observing a user with a new site (internal ref: p77Llu-b6J-p2). If you preview a new post that hasn't been saved remotely yet, you get the local preview. You have to know that you need to save the draft first, and then preview, to get a "real" (remote) preview.

I also noticed that I always get a local preview if I open the editor and preview from the ellipsis menu in the editor, even if I get a remote preview when I preview from the posts list.

It feels like we should be trying to save the draft remotely whenever someone wants to preview the post (e.g. selects "Preview" from within the editor) and then try to show them the remote preview, even if we keep the local preview as a fallback.

Current WPiOS issue for reference: https://github.com/wordpress-mobile/WordPress-iOS/issues/9282

**Comment by SiobhyB** [comment] 2019-01-02 16:12
I'm working with a user in 1672232-z who noticed some differences between a post they created in Gutenberg (with the Twenty Nineteen) theme and the preview from the app. I suspect that part of the problem is that we're displaying a "simple" preview from within the app.

@rachelmcr: Do you think that theory sounds correct? Do you think we'll see more of these types of issues with Gutenberg?

**Comment by rachelmcr** [comment] 2019-01-04 16:01
> Do you think that theory sounds correct? Do you think we'll see more of these types of issues with Gutenberg?

As discussed in Slack, this particular user's case was with remote preview — let's track any remote preview issues that are specific to the apps separately from this one. We can also keep an eye out for anything Gutenberg-specific that causes trouble in the app's local preview, especially as it relates to prioritizing work on local v. remote previews. (Internal ref: p1546448856004900-slack-cellular-happiness)

**Comment by designsimply** [comment] 2019-04-18 21:17
Moving up in priority and noting this needs to be re-assessed and we may want to break it up into smaller pieces if that will help make the issue more actionable.

**Comment by diegoreymendez** [comment] 2019-04-23 16:28
Moving this into the "Offline Support" project since it's related.

**Comment by maxme** [comment] 2019-04-26 14:49
I'm closing this ticket, as it's going to be solved by:
- Autosave: https://github.com/wordpress-mobile/WordPress-Android/issues/9728
- Local preview removal: https://github.com/wordpress-mobile/WordPress-Android/issues/9729

**Closed by maxme** 2019-04-26 14:49 UTC
Labels: Offline Support, Posting/Editing, [Pri] High, [Type] Broken Window, [Type] Enhancement
