### ISSUE TITLE
App keeps closing

### ISSUE THREAD

**Issue by thabotswana** [wordpress-mobile/WordPress-Android#16734] opened 2022-06-13 10:22 UTC
A user reported that their app keeps shutting down. 

I found several Sentry reports with `<unknown>` errors on June 11 and the following [error](https://sentry.io/organizations/a8c/discover/wordpress-android:31973b5406fc497382024a10df2f602f/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=1438088&query=user.email%3Avaughn%40the360mag.com&sort=-timestamp&statsPeriod=7d&yAxis=count%28%29) on June 8:

```
OutOfMemoryError: Failed to allocate a 64 byte allocation with 38712 free bytes and 37KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
```

##### User/device details
Ticket link: 5288201-zen
App version: 19.9
Device model: Samsung SM-S908U1
Type of site: Jetpack

**Comment by thehenrybyrd** [comment] 2022-06-16 07:34
@thabotswana thanks for the report! It would be helpful to know under what circumstances the app is closing. For instance, does that happen every time the user opens the app? Only when they try to load posts? 
If this is a crash you're only seeing with one user, and you are having difficulty troubleshooting it with them, it might be more appropriate for a Mobile Request.

@AliSoftware do you think this could be related to one of the other OOM's we're currently tracking? https://github.com/wordpress-mobile/WordPress-Android/issues/15474, https://github.com/wordpress-mobile/WordPress-Android/issues/9997

**Comment by AliSoftware** [comment] 2022-06-16 09:45
If that Sentry report you linked was found by matching it with the user's email, this OutOfMemory error is then indeed likely the culprit.

@thehenrybyrd I'm not sure I'm the best person to analyze if those are related to the two other reports you linked. Probably @ashiagr (as Android groundskeeper this sprint) could help better analyze if those are the same issues or not?

**Comment by ashiagr** [comment] 2022-06-16 12:22
The OOM error linked to the issue seems to be [limited to a single user](https://sentry.io/share/issue/90bc1e36e461472e835cc471b116dd26/) and looks different from the other OOMs. 

> It would be helpful to know under what circumstances the app is closing. For instance, does that happen every time the user opens the app? Only when they try to load posts?
If this is a crash you're only seeing with one user, and you are having difficulty troubleshooting it with them, it might be more appropriate for a Mobile Request.
 
💯 agree with this. If we can have consistent steps to reproduce, that would be super helpful.

**Comment by thabotswana** [comment] 2022-06-20 11:52
When @Chrissie Pollock asked the user for more info, they simply responded with this:

>No error just closes

The ticket has closed so I guess we can close this.

**Closed as completed** 2022-06-21 12:28 UTC
Labels: [Type] Crash
