### ISSUE TITLE
Missing file extension on media upload response causes NPE

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#14193] opened 2021-03-04 22:04 UTC
Sentry issue: https://sentry.io/share/issue/a5716e8df6f54651be218d1682f98dde/
User report: 3784160-zd-woothemes

```
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter extension
    at org.wordpress.android.fluxc.utils.MimeTypes.getMimeTypeForExtension
    at org.wordpress.android.fluxc.utils.MediaUtils.getMimeTypeForExtension(MediaUtils.java:60)
    at org.wordpress.android.fluxc.network.xmlrpc.media.MediaXMLRPCClient.getMediaFromXmlrpcResponse(MediaXMLRPCClient.java:547)
    at org.wordpress.android.fluxc.network.xmlrpc.media.MediaXMLRPCClient.access$500(MediaXMLRPCClient.java:72)
    at org.wordpress.android.fluxc.network.xmlrpc.media.MediaXMLRPCClient$3.onResponse(MediaXMLRPCClient.java:218)
    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
```

Related FluxC issue: https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1910

**Comment by renanferrari** [comment] 2021-03-04 22:11
From what I've seen on Sentry, it seems that this is only caused on XML-RPC responses, so it's probably fair to say this only affects self-hosted sites.

I tried a few things to reproduce this, but ultimately I wasn't able to. That said, simply making the extension parameter nullable on `MimeTypes::getMimeTypeForExtension` should be enough to prevent the crash from happening.

**Comment by renanferrari** [comment] 2021-03-04 22:12
From what I've seen on Sentry, it seems that this only happens on XML-RPC responses, so it's probably fair to say this only affects self-hosted sites.

I tried a few things to reproduce this, but ultimately I wasn't able to. That said, simply making the extension parameter nullable on `MimeTypes::getMimeTypeForExtension` should be enough to prevent the crash from happening.

**Comment by reginabally** [comment] 2021-03-05 05:00
The user wrote back and said that the issue was resolved after fixing a problem on the control panel at their host.

**Comment by designsimply** [comment] 2021-03-05 08:31
@reginabally can you maybe find out what they changed in their control panel? I am quite curious what solved the issue for them!

**Comment by reginabally** [comment] 2021-03-08 09:18
@designsimply I'm curious to know too! I've sent the user a follow-up reply and asked them for more details. Thanks for the nudge!

**Comment by reginabally** [comment] 2021-03-15 06:08
@designsimply This is the reply we received from the user:

> The it guy told me that at the server were a lot of files approximately 15gb of information so he deleted them, and the web now is working. 

It sounds like an out-of-storage issue caused by huge log files on the site. 🤔

**Comment by zwarm** [comment] 2022-02-15 20:04
The Kotlin NPE was addressed in this FluxC [PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1910)

**Closed as completed by zwarm** 2022-02-15 20:04 UTC
Labels: [Pri] Medium, Media, [Type] Crash
