### ISSUE TITLE
Reader occasionally shows 'New Posts' after refresh.

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2367] opened 2015-02-23 17:26 UTC
A few times this weekend I returned to the app in the Reader, and it automatically refreshed the list. But sometimes it wouldn't save my place in the list, instead refreshing the entire list and I was at the top and lost my place. It still showed the 'New Posts ^' button even though I was at the very top of the new posts.

I think it's only doing this if the app was killed and is starting up again. Hard one to reproduce.

**Comment by nbradbury** [comment] 2015-02-23 18:05
Did this happen on "Blogs I Follow?" If so I may know the cause.

**Comment by roundhill** [comment] 2015-02-23 19:16
> Did this happen on "Blogs I Follow?" If so I may know the cause.

Yes sir!

**Comment by nbradbury** [comment] 2015-02-25 22:00
I'm pretty sure what's happening is that there are actually new posts, but their pubDate is older than the post currently at the top of the list so when you tap new posts they don't show up at the top.

**Comment by nbradbury** [comment] 2015-03-27 20:02
Issue was not resolved by PR #2375

**Comment by nbradbury** [comment] 2015-09-02 20:58
Closing, haven't seen the problem in quite a while.

**Closed by nbradbury** 2015-09-02 20:58 UTC
Labels: bug, Reader
