### ISSUE TITLE
Weird redrawing behavior on the Comment list.

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#88] opened 2013-09-19 16:16 UTC
On the nexus 7. You'll need multiple browsers installed to see this probably.
Go to the comment list
On the comment detail, tap the hyperlink for the commenter's website. 
Dismiss the action modal
Watch closely as all the gravatars reload.

**Comment by rachelmcr** [comment] 2015-11-25 19:10
I wasn't able to reproduce this behavior on my Nexus 7 (OS 5.1.1, app beta 4.8-rc-1) or my Nexus 9. @roundhill I am closing this issue because I believe it is resolved, but if you can still reproduce it please reopen.

**Closed by rachelmcr** 2015-11-25 19:10 UTC
Labels: comments, trac, [Type] Bug
