### ISSUE TITLE
Pages Overflow Menu Hidden After Returning to List from Editor

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#8608] opened 2018-11-15 00:51 UTC
### Expected
The overflow menu for each page is shown after returning to the list from the editor and refreshing the list when the device has a network connection.

### Observed
The overflow menu for each page is hidden after returning to the list from the editor and refreshing the list when the device has a network connection.  See the animation below for illustration.

<img src="https://user-images.githubusercontent.com/3827611/48521548-8b713700-e83a-11e8-8e4f-7e5cd5366c1b.gif" width="320">

### Reproduced
1. Go to ***My Site*** tab.
2. Tap ***Site Pages*** item under ***Publish*** section.
3. Notice overflow menu is shown for each page list item.
4. Tap page list item.
5. Notice editor is opened.
6. Tap back arrow.
7. Notice overflow menu is hidden for each page list item.
8. Swipe down to refresh list.
9. Notice overflow menu is hidden for each page list item.

##### Tested
Google Pixel 3 on Android 9.0 with WordPress alpha-136

**Comment by rachelmcr** [comment] 2018-11-16 12:49
It looks like this is a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/8520. I'm closing this and adding relevant details to that issue.

**Closed by rachelmcr** 2018-11-16 12:49 UTC
Labels: Pages List, Properly placed pages, [Type] Bug
