### ISSUE TITLE
Reader: Image Caption/Title Repeated/Duplicated on Another Post

### ISSUE THREAD

**Issue by erricgunawan** [wordpress-mobile/WordPress-Android#12628] opened 2020-08-10 04:46 UTC
### Expected behavior
Image caption (or title) from one post should not be displayed on another post in the Reader.

### Actual behavior
Sometimes the image caption/title for one post shows up on two or three others. This is just on the app Reader, not from the website. It's not always the next post either, sometimes there are 2 or 3 posts between them.

It doesn't happen regularly with the same blogs. They don't even need to be one after the other in Reader, there may be a few posts that are normal between them. User noticed it about a month ago. By July 20 it was often enough. It also may not happen for a day or two and then start up again for a few days in a row.

Screenshot: https://d.pr/i/L0xcDI/oqIHvJzFTO

![Screen Shot 2020-08-08 at 10 14 23](https://user-images.githubusercontent.com/1119271/90038181-5a799c80-dc82-11ea-82ea-0d6ba51d6355.png)

### Steps to reproduce the behavior
1. Open the Reader in the app
2. Start browsing from posts

Note: some of us tried this but couldn't reproduce.

##### Tested on Samsung SM-A705W, Android 10, WPAndroid 15.3

Reported on 3183314-zen

**Comment by ashiagr** [comment] 2020-08-10 10:39
Hey @erricgunawan,

I just noticed this issue and I believe I've some inputs:

> Sometimes the image caption/title for one post shows up on two or three others.

Reader post card was recently refactored and I believe this issue is related to [this one](https://github.com/wordpress-mobile/WordPress-Android/issues/12353) which was introduced because of an [Android bug](https://issuetracker.google.com/issues/73186245). 

> Note: some of us tried this but couldn't reproduce.

It got fixed in release `15.3-rc-1` [here](https://github.com/wordpress-mobile/WordPress-Android/commit/97ae81ebab523ebdf0ec16cdbf5a5019823089fc#diff-bf439452361560d7bdc72fae370fa88aR140-R190). Let me know if you can still reproduce it. I'm assigning this issue to myself and I'll closely monitor it.

**Comment by erricgunawan** [comment] 2020-08-11 07:37
Thanks for looking into this @ashiagr !

Glad to hear it's related to something here.

Actually, some of us aren't able to reproduce this (including me).

It's a report from a user that said they're having this issue. 

They reported they're already in `15.3` (the device info mentioned above is the user's device info). 

I believe `15.3-rc-1` predates `15.3` so the fix should have been included, no?

Do you have any suggestions for it? Should they do a clean/fresh installation to see if it's still an issue?

**Comment by ashiagr** [comment] 2020-08-11 07:52
> I believe 15.3-rc-1 predates 15.3 so the fix should have been included, no?

**Comment by ashiagr** [comment] 2020-08-11 08:01
I tested on `15.2` and `15.3` and captured videos here:

**15.2** https://cloudup.com/iEAWbGGy076. 
**15.3** https://cloudup.com/iEAWbGGy076 

Noticed that an image title appeared on a wrong post at `timestamp: 00.16` on **15.2** but not on **15.3**  at `timestamp: 00.11`.

> I believe 15.3-rc-1 predates 15.3 so the fix should have been included, no?

Yes, it should have been included.

> Do you have any suggestions for it? Should they do a clean/fresh installation to see if it's still an issue?

It would be great if they can fresh install and confirm it.

**Comment by erricgunawan** [comment] 2020-08-16 04:07
Sorry for the delay!

I managed to reply back to the user asking them to update to the latest version (which is on `15.4` now).

If they ever encountered the issue again, I told them to let us know.

Thanks again for looking!

**Comment by ashiagr** [comment] 2021-01-06 05:57
Closing it as not heard of any complaints after this. Please feel to re-open in case you come across it again. Thank you!

**Closed by ashiagr** 2021-01-06 05:57 UTC
Labels: New Reader Android, Reader, [Type] Bug
