### ISSUE TITLE
.org: New Posts are always posted Pending Review

### ISSUE THREAD

**Issue by akirk** [wordpress-mobile/WordPress-Android#6096] opened 2017-06-18 16:14 UTC
### Expected behavior
When I create a new post and submit it, it should be submitted as "Published". Also, when I modify a post status to "Published" this should be reflected.

### Actual behavior
New posts and modified post statuses are published as "Pending Review". The only way to get a post into the "Published" state is to use the "Publish" function on the posts listing screen after tapping on "More".

### Steps to reproduce the behavior
Create a new post, add a headline and use the "Submit" button in the header (note that on WordPress.com and Jetpack blogs this is a "Publish" button).

##### Tested on Xperia X Compact, Android 7.0, WordPress alpha-60

This is on a WordPress 4.8 install without Jetpack.

**Comment by rachelmcr** [comment] 2017-06-20 09:35
I confirmed this issue in alpha-61 on a self-hosted site, regardless of which editor is used.

**Comment by catehstn** [comment] 2017-06-20 10:12
This is pretty annoying - @koke, do you have time to take a quick look at it? Thanks!

**Comment by catehstn** [comment] 2017-06-20 10:16
Oops - Android. @nbradbury could you possibly? 💕

**Comment by nbradbury** [comment] 2017-06-20 10:53
Yes, I can tackle this - will try to get to this later today or tomorrow.

**Comment by nbradbury** [comment] 2017-06-20 12:14
The problem appears to be due to [this](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L961-L965). Looking into it.

**Comment by nbradbury** [comment] 2017-06-21 20:19
Closed via #6113

**Closed by nbradbury** 2017-06-21 20:19 UTC
Labels: Posting/Editing, [Pri] High, [Type] Bug
