### ISSUE TITLE
Pull-to-refresh not working on plugins screen

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#14087] opened 2021-02-16 17:33 UTC
### Expected behavior

Pulling-to-refresh the plugin screen should always result in the plugins shown in their correct state (active/inactive).

### Actual behavior

Despite pulling-to-refresh the plugins screen, it still showed an "old" state (inactive) of a plugin instead of its "new" state (active). It wasn't until I went to the site list screen and pulled-to-refresh there that the plugins screen finally showed the correct state of all plugins (as seen on the web).

### Steps to reproduce the behavior

In my case, I had a site with two plugins and a backup of that state. 
1. I added a plugin and then restored the site to the backup, expecting that the new plugin would be transitioned to inactive (restores can't remove plugins, they inactivate them AFAIK).
2. When I went to the plugins screen to check that the plugin was now inactive, it incorrectly showed up as active
3. I tried pulling-to-refresh the plugins screen, no luck
4. I checked on the web and the plugin showed up as inactive (as I expected)
5. I went back to the site list screen, pulled-to-refresh there and came back to the plugin screen, where the plugin was now showing up as inactive (as I expected)

**Comment by designsimply** [comment] 2021-03-03 09:39
I agree this should be investigated but would like to wait for additional feedback from users before raising this in priority in Groundskeeping, partly because I think Jetpack Plugins are a relatively low-traffic area of the app compared to some other areas where we are focusing work currently. This is always subject to change and open for discussion, so please push back if you feel it should be prioritized higher. Thank you!

**Comment by guarani** [comment] 2021-03-03 12:25
Thanks @designsimply, I agree with the assessment. (I also corrected a few typos I'd made in the issue above 😄).

**Comment by SiobhyB** [comment] 2023-04-18 18:15
I recently tested the Jetpack installation flow as part of [`22.2-rc-1`](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/22.2-rc-1) and confirmed this was an issue for me too. I went through the following steps:

1. Navigated to the /wp-admin area for a self-hosted site on the web, from there I uninstalled the Jetpack plugin.
2. In the app, I was already logged into the self-hosted site, so selected it from the site picker.
3. The Jetpack plugin was listed under the "Installed" section in the Plugins screen.
4. Multiple attempts to refresh the Plugins screen via pull-to-refresh were unsuccessful. 
5. I was eventually able to refresh the screen (by selecting a different site from the picker then returning to the self-hosted site I was working on).
6. After installing the Jetpack plugin via the in-app Plugins section, I was again unable to see the updated plugin details by pulling-to-refresh.

**Comment by mkevins** [comment] 2023-05-22 06:59
I have investigated this issue a bit, and afaict, there is no "pull to refresh" on the main Plugins screen. Instead, what I have found is that after navigating to the screen for the Installed plugins (i.e. tapping the "Manage" button), the individual list of installed plugins can be refreshed via pull-to-refresh. In that case, the data updates normally, as expected.

A reasonable fix for this might be to add swipe-to-refresh behavior at the activity level, but that might be overkill, since that would perform a refresh fetch for every section on that screen (i.e. Installed, Featured, Popular, etc.). Alternatively, a "low tech" solution might be to disable the overscroll animation on the Activity's main list. Perhaps this would dissuade the expectation that swiping down will refresh the visible content. :thinking: 

Implementation-wise, the second option is extremely simple:

<details>
<summary>Patch to disable overscroll animation</summary>

```patch
diff --git a/WordPress/src/main/res/layout/plugin_browser_activity.xml b/WordPress/src/main/res/layout/plugin_browser_activity.xml
index 13aeb76990..fcbaf72248 100644
--- a/WordPress/src/main/res/layout/plugin_browser_activity.xml
+++ b/WordPress/src/main/res/layout/plugin_browser_activity.xml
@@ -24,7 +24,8 @@
         android:layout_width="match_parent"
         android:layout_height="match_parent"
         android:layout_below="@+id/toolbar"
-        app:layout_behavior="@string/appbar_scrolling_view_behavior">
+        app:layout_behavior="@string/appbar_scrolling_view_behavior"
+        android:overScrollMode="never">
 
         <LinearLayout
             android:layout_width="match_parent"
```
</details>

Whereas the first would be slightly more complex (but still, probably not a huge change). But, it means we are refreshing everything again when many of those rows will likely be unchanged.

:wave: :smile: @SiobhyB, @guarani , curious what you think about the above solutions. Would disabling overscroll change the expectation? Or do you think it'd be better to refresh all lists on that screen (i.e. enable swipe-to-refresh at the activity level)?

**Comment by mkevins** [comment] 2023-05-24 06:42
I have toyed with an implementation to refresh all lists on the main screen, but still think that the simpler solution is to just disable the overscroll animation.

<details>
<summary>Patch to refresh all lists</summary>

```patch
diff --git a/WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginBrowserActivity.java b/WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginBrowserActivity.java
index 9100438a7a..94a940e08c 100644
--- a/WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginBrowserActivity.java
+++ b/WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginBrowserActivity.java
@@ -1,5 +1,6 @@
 package org.wordpress.android.ui.plugins;
 
+import kotlinx.coroutines.flow.MutableStateFlow;
 import android.content.Context;
 import android.os.Bundle;
 import android.view.LayoutInflater;
@@ -49,17 +50,21 @@ import org.wordpress.android.util.analytics.AnalyticsUtils;
 import org.wordpress.android.util.extensions.AppBarLayoutExtensionsKt;
 import org.wordpress.android.util.extensions.CompatExtensionsKt;
 import org.wordpress.android.util.extensions.ContextExtensionsKt;
+import org.wordpress.android.util.helpers.SwipeToRefreshHelper;
 import org.wordpress.android.util.image.ImageManager;
 import org.wordpress.android.util.image.ImageType;
 import org.wordpress.android.viewmodel.plugins.PluginBrowserViewModel;
 import org.wordpress.android.viewmodel.plugins.PluginBrowserViewModel.PluginListType;
 
+import java.util.Arrays;
 import java.util.HashMap;
 import java.util.List;
 import java.util.Map;
 
 import javax.inject.Inject;
 
+import static org.wordpress.android.util.WPSwipeToRefreshHelper.buildSwipeToRefreshHelper;
+
 public class PluginBrowserActivity extends LocaleAwareActivity
         implements SearchView.OnQueryTextListener,
         MenuItem.OnActionExpandListener {
@@ -76,6 +81,8 @@ public class PluginBrowserActivity extends LocaleAwareActivity
     private MenuItem mSearchMenuItem;
     private SearchView mSearchView;
 
+    private SwipeToRefreshHelper mSwipeToRefreshHelper;
+
     @Override
     public void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
@@ -148,6 +155,17 @@ public class PluginBrowserActivity extends LocaleAwareActivity
         configureRecycler(mNewPluginsRecycler);
 
         setupObservers();
+
+        mSwipeToRefreshHelper = buildSwipeToRefreshHelper(
+                findViewById(R.id.ptr_layout),
+                () -> {
+                    if (NetworkUtils.checkConnection(this)) {
+                        mViewModel.fetchAll();
+                        mSwipeToRefreshHelper.setRefreshing(false);
+                    } else {
+                        mSwipeToRefreshHelper.setRefreshing(false);
+                    }
+                });
     }
 
     @Override
@@ -197,6 +215,7 @@ public class PluginBrowserActivity extends LocaleAwareActivity
                           reloadPluginAdapterAndVisibility(PluginListType.NEW, listState);
                       }
                   });
+        mViewModel.getInProgress().observe(this, this::showProgress);
     }
 
     private void configureRecycler(@NonNull RecyclerView recycler) {
@@ -285,6 +304,7 @@ public class PluginBrowserActivity extends LocaleAwareActivity
         } else if (newVisibility != View.VISIBLE && oldVisibility == View.VISIBLE) {
             AniUtils.fadeOut(cardView, AniUtils.Duration.MEDIUM);
         }
+
     }
 
     @Override
diff --git a/WordPress/src/main/java/org/wordpress/android/viewmodel/plugins/PluginBrowserViewModel.kt b/WordPress/src/main/java/org/wordpress/android/viewmodel/plugins/PluginBrowserViewModel.kt
index 8290e4ad25..471fbbff4f 100644
--- a/WordPress/src/main/java/org/wordpress/android/viewmodel/plugins/PluginBrowserViewModel.kt
+++ b/WordPress/src/main/java/org/wordpress/android/viewmodel/plugins/PluginBrowserViewModel.kt
@@ -6,6 +6,12 @@ import android.os.Looper
 import androidx.lifecycle.LiveData
 import androidx.lifecycle.MutableLiveData
 import androidx.lifecycle.ViewModel
+import androidx.lifecycle.asFlow
+import androidx.lifecycle.asLiveData
+import androidx.lifecycle.viewModelScope
+import kotlinx.coroutines.flow.SharingStarted
+import kotlinx.coroutines.flow.combineTransform
+import kotlinx.coroutines.flow.stateIn
 import org.greenrobot.eventbus.Subscribe
 import org.greenrobot.eventbus.ThreadMode
 import org.wordpress.android.WordPress
@@ -67,6 +73,15 @@ class PluginBrowserViewModel @Inject constructor(
     private val _sitePluginsLiveData = MutableLiveData<PluginListState>()
     private val _searchResultsLiveData = MutableLiveData<PluginListState>()
 
+    val inProgress = combineTransform(listOf(
+        _sitePluginsLiveData.asFlow(),
+        _featuredPluginsLiveData.asFlow(),
+        _popularPluginsLiveData.asFlow(),
+        _newPluginsLiveData.asFlow(),
+    )) {listStates ->
+        emit(listStates.any { state -> state is ListState.Loading })
+    }.stateIn(viewModelScope, SharingStarted.Lazily, false).asLiveData()
+
     val featuredPluginsLiveData: LiveData<PluginListState>
         get() = _featuredPluginsLiveData
 
@@ -153,12 +168,16 @@ class PluginBrowserViewModel @Inject constructor(
         updateListStateToReady(PluginDirectoryType.POPULAR)
         updateListStateToReady(PluginDirectoryType.SITE)
 
+        fetchAll()
+
+        isStarted = true
+    }
+
+    fun fetchAll() {
         fetchPlugins(SITE, false)
         fetchPlugins(FEATURED, false)
         fetchPlugins(POPULAR, false)
         fetchPlugins(NEW, false)
-
-        isStarted = true
     }
 
     // Actions
diff --git a/WordPress/src/main/res/layout/plugin_browser_activity.xml b/WordPress/src/main/res/layout/plugin_browser_activity.xml
index 13aeb76990..27d69e2338 100644
--- a/WordPress/src/main/res/layout/plugin_browser_activity.xml
+++ b/WordPress/src/main/res/layout/plugin_browser_activity.xml
@@ -132,14 +132,21 @@
             </RelativeLayout>
         </LinearLayout>
 
+
     </androidx.core.widget.NestedScrollView>
 
-    <FrameLayout
-        android:id="@+id/fragment_container"
+    <org.wordpress.android.util.widgets.CustomSwipeRefreshLayout
+        android:id="@+id/ptr_layout"
         android:layout_width="match_parent"
-        android:layout_height="match_parent"
-        app:layout_behavior="@string/appbar_scrolling_view_behavior" />
+        android:layout_height="match_parent">
+
+        <FrameLayout
+            android:id="@+id/fragment_container"
+            android:layout_width="match_parent"
+            android:layout_height="match_parent"
+            app:layout_behavior="@string/appbar_scrolling_view_behavior" />
 
+    </org.wordpress.android.util.widgets.CustomSwipeRefreshLayout>
     <ProgressBar
         android:id="@+id/progress"
         style="?android:attr/progressBarStyle"
```

</details>

The above patch "kind of" works, but has some additional issues (e.g. scrolling is broken), so would need more time and effort to implement properly, and I'm not sure whether the value added would be worth it. Especially considering that the flow where a user might observe the stale data in this screen feels like an edge case:

1. Navigate to the main plugins screen
2. Make a change to the installed plugins on web
3. Notice that the change is not updated on the main screen

Most likely, the user would navigate to this screen _after_ having made a change on web. Or, if the user is making changes via the app, they'd be in the detail view, which _does_ update.

I have opened a PR with the first solution: https://github.com/wordpress-mobile/WordPress-Android/pull/18498

**Closed as completed** 2023-05-24 08:29 UTC
Labels: [Type] Bug, [Pri] Medium, Plugins

**Comment by guarani** [comment] 2023-05-24 23:19
👋 Hey @mkevins, I'm responding super-late, sorry about that! 
Reading this now:

> Instead, what I have found is that after navigating to the screen for the Installed plugins (i.e. tapping the "Manage" button), the individual list of installed plugins can be refreshed via pull-to-refresh. In that case, the data updates normally, as expected.

I tested again today and this screen is still not working for me. In this screen recording, the bbPress plugin is installed and active, then I deleted it on the web and the app's **Installed** screen keeps showing it as installed & active:

https://github.com/wordpress-mobile/WordPress-Android/assets/1898325/741eb1e4-0830-4a15-97c9-899c1557d853

As I re-read the original issue I wrote above, I realized that it wasn't clear (and lacked screenshots or screen recordings). It's this "Installed" screen where I had the issue, not the main "Plugins" screen.

I'm curious if your able to reproduce or if the "Installed" screen is working for you.

**Comment by mkevins** [comment] 2023-05-24 23:41
> wave Hey @mkevins, I'm responding super-late, sorry about that! Reading this now:

No worries @guarani, thanks for circling back to it anyway :+1: 

> I tested again today and this screen is still not working for me. In this screen recording, the bbPress plugin is installed and active, then I deleted it on the web and the app's **Installed** screen keeps showing it as installed & active:

I wonder, after watching the video, did you mean the Hello Dolly plugin? I didn't see the bbPress plugin on that screen :thinking: 

> As I re-read the original issue I wrote above, I realized that it wasn't clear (and lacked screenshots or screen recordings). It's this "Installed" screen where I had the issue, not the main "Plugins" screen.
> 
> I'm curious if your able to reproduce or if the "Installed" screen is working for you.

Hm.. this is interesting. In my case, I did not reproduce the stale data on the Installed screen. What I tried was, on web (on the computer, not the phone - though I don't think it should make a difference), I activated / deactivated a plugin. Then, in the app, on the "Manage Plugins" screen, I refreshed by pulling down, and the the state was properly updated. I have not tried by deleting the plugin, nor have I tried on mobile web (though I guess that shouldn't matter). I can try again to reproduce this on the detail screen. If not, I wonder what could be different which would lead to different results :thinking:

**Comment by mkevins** [comment] 2023-05-25 00:09
I tried reproducing by installing and deleting (EidoGo) via web, and refreshing that screen in the app, but it still works as expected for me:

| Installing | Deleting |
|-|-|
|<video src="https://github.com/wordpress-mobile/WordPress-Android/assets/8507675/06dbea4b-6587-4b93-ab63-aeb82d957ea7">|<video src="https://github.com/wordpress-mobile/WordPress-Android/assets/8507675/b2a34db6-3182-46b9-8f67-5dfce4757a50">|

I wonder whether this is somehow triggered by leaving the app and coming back (since you are using mobile web instead of the desktop or laptop) :thinking:

**Comment by mkevins** [comment] 2023-05-25 00:40
I also tried deleting a plugin from mobile web, and returning to the app to refresh the screen, but I get the same result, a successful refresh:

https://github.com/wordpress-mobile/WordPress-Android/assets/8507675/073fe440-8383-478d-8182-25ec08e823d5

@guarani , I couldn't tell from your video, but is there any chance that the selected site in the app is different from the one on web where you are making the changes?
