### ISSUE TITLE
Scheduling a private post/page moves them into Published tab instead of scheduled

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#11393] opened 2020-02-27 10:14 UTC
### Expected behavior
When I select a post/page as private and I also set schedule date into the future, I expect to see "Schedule" action in the editor. When I click on the action I expect the post/page will be in "Scheduled" tab.

### Actual behavior
When I select a post/page as private and I also set schedule date into the future, the editor displays only "update" action. When I click on the action the post/page is moved to "Published" tab.

### Steps to reproduce the behavior
1. Create a new draft
2. Enter a title
3. Go to Post Settings
4. Set status to "Private"
5. Select publish date in the future
6. Notice the only available action in the editor is "Update" (instead of "Schedule")
7. Click on the action and notice the post/page is moved into "Published" tab

<img src="https://user-images.githubusercontent.com/2261188/75434901-8b734880-5952-11ea-9eed-97b8d022e5ce.gif" width="300px" />

##### Tested on [device], Android [version], WPAndroid [version]
Emulator, API 29

**Comment by jd-alexander** [comment] 2020-03-11 02:38
Hi @malinajirka I looked into this and I am seeing where the `PostStatus` is being used to set the `PrimaryAction` of the editor. Within the `PostStatus` class in FluxC I saw where the `SCHEDULED` status is being set when a post is marked as published but it's created date is in the future so I am now thinking how this could be adapted in some way without breaking existing `SCHEDULED` functionality since the definition of `SCHEDULED` is a post marked as `PUBLISHED` with a future date. 

We could modify the `FluxC` layer to return a private post as `Scheduled` once it has a future date and but then we would need a way to differentiate between it being public or not which is the tricky part. I am going to spend some more time thinking about this.

**Comment by jhnstn** [comment] 2021-04-05 21:43
I'm unable to reproduce this due to #12344

Once the post is set to private the publish date option is disabled.
I tried setting a future date before changing the status but once the post is private the publish date reverts back to immediately

**Comment by zwarm** [comment] 2022-02-15 19:19
Tested using WP app 19.1.1, pixel 5, running OS 12 and unable to reproduce.

Once the post status is set to private, the publish date is set back to now or immediate and greyed out. If you don't tap the publish/update button, but back out of the editor, the post is saved as a draft and is visible in the drafts list. 

If you edit a post on the web and try to change the status from public to private, a dialog is shown confirming that you want to publish the private post now. This is even the case if you had already scheduled the post with a future publish date. 

<img width="550" height="300" alt="Alt desc" src="https://user-images.githubusercontent.com/506707/154131958-e73decae-6561-4ba7-9ff3-2f5da5c81891.png">


 FYI @thehenrybyrd - closing this ticket

**Closed by zwarm** 2022-02-15 19:19 UTC
Labels: [Type] Bug, Posting/Editing
