### ISSUE TITLE
PIN Lock can cause posts to disappear

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4846] opened 2016-11-29 16:37 UTC
### Steps to reproduce the behavior
0) Ensure you have a PIN set in the WordPress app
1) Open an existing post for editing
2) Tap the Home button
3) Open ~20 different apps to force WordPress to be booted out of memory.
4) Re-open WP and input your PIN

### What I expected
To be able to resume editing my post

### What happened instead
The post body and title were both erased, but anything set in the options pane (Featured Image, etc) remain.

I can repeat this every time on my 6P, but I haven't been able to reproduce it on the emulator or my old OnePlus One

**Comment by rachelmcr** [comment] 2016-11-29 16:52
I reproduced the issue (post body and title were erased) with the steps above on my Nexus 9, Android 7.0, WPAndroid alpha-28.

**Comment by daniloercoli** [comment] 2016-11-29 16:56
I think you can repro the issue even without setting the PIN Lock in the app:
- Open an existing post for editing.
- Tap the Home button.
- Open ~20 different apps (or more) to force WordPress to be booted out of memory.
- Re-open WP.

This is related to https://github.com/wordpress-mobile/WordPress-Android/issues/4765

**Comment by hoverduck** [comment] 2016-11-29 16:58
Weird, I could only reproduce it with the PIN enabled...but maybe I wasn't opening enough apps in the meantime.  Thanks

**Comment by daniloercoli** [comment] 2016-11-29 17:57
Yes, probably with the PIN Lock library enabled the app eats more memory.

Anyway, I was able to reproduce the issue when the PIN Lock is ON. The app was killed by the system, and tapping on the app icon is like a clean start. `deferredInit` was called....and so on.

**Comment by daniloercoli** [comment] 2016-11-30 14:42
Having hard time to replicate the issue on my Nexus 5X.
There is something wrong in the way the Editor is initialized when the system starts killing things due to low memory condition.

**Note:** If you try to replicate the issue under severe memory usage you will not get it, since the system will kill the whole app. You will see the posts list on re-start.

This is the log I got from AS the rare times I was able to replicate it:

```
11-30 15:35:19.636 8754-8754/org.wordpress.android I/WordPress-NOTIFS: notifications service > destroyed
11-30 15:35:19.654 8754-9584/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=kòj kò
                                                                       
                                                                       https://eritreocazzulati.wordpress.com/2016/11/23/test-trackback-and-pingback/
                                                                       
                                                                       ojoj
                                                                       
                                                                       &nbsp;
11-30 15:35:24.187 10375-10463/org.wordpress.android I/OpenGLRenderer: Initialized EGL, version 1.4
11-30 15:35:24.187 10375-10463/org.wordpress.android D/OpenGLRenderer: Swap behavior 1
11-30 15:35:24.216 10375-10375/org.wordpress.android W/ViewRootImpl[PasscodeUnlockActivity]: Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=23961414, downTime=23961414, deviceId=-1, source=0x101 }
11-30 15:35:24.216 10375-10375/org.wordpress.android W/ViewRootImpl[PasscodeUnlockActivity]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x68, repeatCount=0, eventTime=23961497, downTime=23961414, deviceId=-1, source=0x101 }
11-30 15:35:24.216 10375-10375/org.wordpress.android W/ViewRootImpl[PasscodeUnlockActivity]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x68, repeatCount=0, eventTime=23961497, downTime=23961414, deviceId=-1, source=0x101 }
11-30 15:35:24.216 10375-10375/org.wordpress.android W/ViewRootImpl[PasscodeUnlockActivity]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x68, repeatCount=0, eventTime=23961497, downTime=23961414, deviceId=-1, source=0x101 }
11-30 15:35:24.216 10375-10375/org.wordpress.android W/ViewRootImpl[PasscodeUnlockActivity]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x68, repeatCount=0, eventTime=23961497, downTime=23961414, deviceId=-1, source=0x101 }
11-30 15:35:24.216 10375-10375/org.wordpress.android W/ViewRootImpl[PasscodeUnlockActivity]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x68, repeatCount=0, eventTime=23961497, downTime=23961414, deviceId=-1, source=0x101 }
11-30 15:35:24.216 10375-10375/org.wordpress.android W/ViewRootImpl[PasscodeUnlockActivity]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x68, repeatCount=0, eventTime=23961497, downTime=23961414, deviceId=-1, source=0x101 }
11-30 15:35:24.216 10375-10375/org.wordpress.android W/ViewRootImpl[PasscodeUnlockActivity]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x68, repeatCount=0, eventTime=23961497, downTime=23961414, deviceId=-1, source=0x101 }
11-30 15:35:24.217 10375-10375/org.wordpress.android W/ViewRootImpl[PasscodeUnlockActivity]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x68, repeatCount=0, eventTime=23961497, downTime=23961414, deviceId=-1, source=0x101 }
11-30 15:35:24.217 10375-10375/org.wordpress.android W/ViewRootImpl[PasscodeUnlockActivity]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x68, repeatCount=0, eventTime=23961497, downTime=23961414, deviceId=-1, source=0x101 }
11-30 15:35:24.258 10375-10375/org.wordpress.android D/WordPress-EDITOR: getTitle() called from UI thread
11-30 15:35:24.785 10375-10505/org.wordpress.android D/WordPress-EDITOR: New field created, id=zss_field_title
11-30 15:35:24.788 10375-10505/org.wordpress.android D/WordPress-EDITOR: New field created, id=zss_field_content
11-30 15:35:24.807 10375-10505/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
                                                                               
11-30 15:35:24.808 10375-10375/org.wordpress.android D/WordPress-EDITOR: getContent() called from UI thread
11-30 15:35:24.829 10375-10505/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=
11-30 15:35:24.832 10375-10375/org.wordpress.android I/Choreographer: Skipped 34 frames!  The application may be doing too much work on its main thread.
11-30 15:35:24.850 10375-10375/org.wordpress.android D/WordPress-NOTIFS: Register token action succeeded
11-30 15:35:24.850 10375-10375/org.wordpress.android D/WordPress-NOTIFS: Server response OK. The device_id: 17110528
11-30 15:35:24.851 10375-10375/org.wordpress.android D/WordPress-PROFILING: Visual Editor Startup: begin
11-30 15:35:24.851 10375-10375/org.wordpress.android D/WordPress-PROFILING: Visual Editor Startup:      1 ms, EditorFragment.onCreate
11-30 15:35:24.851 10375-10375/org.wordpress.android D/WordPress-PROFILING: Visual Editor Startup:      160 ms, EditorFragment.initJsEditor
11-30 15:35:24.851 10375-10375/org.wordpress.android D/WordPress-PROFILING: Visual Editor Startup:      1017 ms, EditorFragment.onDomLoaded
11-30 15:35:24.851 10375-10375/org.wordpress.android D/WordPress-PROFILING: Visual Editor Startup:      61 ms, EditorFragment.onDomLoaded completed
11-30 15:35:24.852 10375-10375/org.wordpress.android D/WordPress-PROFILING: Visual Editor Startup: end, 1239 ms
11-30 15:35:24.852 10375-10375/org.wordpress.android E/chromium: [ERROR:interface_registry.cc(99)] Failed to locate a binder for interface: autofill::mojom::AutofillDriver
11-30 15:35:24.859 10375-10380/org.wordpress.android I/art: Do partial code cache collection, code=27KB, data=29KB
11-30 15:35:24.860 10375-10380/org.wordpress.android I/art: After code cache collection, code=23KB, data=28KB
11-30 15:35:24.860 10375-10380/org.wordpress.android I/art: Increasing code cache capacity to 128KB
11-30 15:35:24.862 10375-10505/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getFailedMedia~ids=
11-30 15:35:24.879 10375-10505/org.wordpress.android D/WordPress-EDITOR: Focus in callback received
11-30 15:35:24.881 10375-10505/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
```

It seems clear from the log that the Editor is "re-started" without setting its content again, and immediately after, the "empty" content is read from `EditPostActivity` and saved to the post object. Resulting in saving an empty post.

**Comment by hoverduck** [comment] 2016-11-30 15:06
Yeah, I can 100% replicate it on my 6P, but haven't been able to do it at all on other devices.  If there's any additional logging I can capture for you let me know.  It could easily be some other app on my phone that's helping put me into this situation more reliably.

**Comment by catehstn** [comment] 2017-01-21 01:34
@hoverduck can you try and repro again? This was hopefully resolved in #4927.

**Comment by hoverduck** [comment] 2017-01-23 17:27
@catehstn - Yep, I was able to reproduce it before I added the priority labels.

**Comment by tonyr59h** [comment] 2017-04-24 17:43
As with #3771: We're not going to continue to support the PIN lock feature so I'm going to close this issue out.

**Closed by tonyr59h** 2017-04-24 17:43 UTC
Labels: Posting/Editing, [Pri] Medium, [Type] Broken Window, [Type] Bug
