### ISSUE TITLE
Editor preference switch stuck

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#14782] opened 2021-06-04 18:10 UTC
### Expected behavior

The editor preference switch should easily toggle between ON and OFF when tapped.

### Actual behavior

The switch gets stuck sometimes and only changes positions when tapped repeatedly in quick succession.

### Steps to reproduce the behavior

1. Log in to a WP.com account that has access to an Atomic site or Jetpack site (Simple sites no longer display this switch)
2. Go to My Site →  Settings → Use Block Editor
3. Toggle the switch between ON and OFF repeatedly and notice that the switch often gets stuck

Video courtesy of @thehenrybyrd, taken from https://github.com/wordpress-mobile/WordPress-Android/issues/14728#issuecomment-849604956:

https://user-images.githubusercontent.com/15107387/119827962-63cab180-bf02-11eb-971c-6cfafa098dee.mp4

Note that this looks different (but possibly related) to https://github.com/wordpress-mobile/gutenberg-mobile/issues/1632, where the switch "toggles on its own" or gets out of sync with the backend.

**Comment by guarani** [comment] 2021-06-07 13:25
Added myself as assignee to indicate that I'm going to check when this issue became present, in order to help us triage/prioritize it.

**Comment by jostnes** [comment] 2021-11-24 05:55
This is still reproducible on WPAndroid 18.7. Though one difference is that I did not have to tap the toggle in quick succession to see the issue, it happened on the first tap:


https://user-images.githubusercontent.com/17252150/143182584-5a9a13d7-7652-4096-a5b6-6a67f8a08f15.mp4



Tested on OPPO Reno6 Z, Android 11.

**Comment by guarani** [comment] 2021-11-24 14:33
Thanks for sharing, @jostnes!

I'd left a comment earlier saying I'd check older versions of the app to see when this issue first started. Unfortunately I didn't follow up on that and six months has passed. On the plus side, we now know the bug has been around for at least six months, so we should have enough info to triage/prioritize it.

@mchowning, I see this already has the Medium priority label. Is there anything left to do here with regard to issue triage/prioritization? 

In the meantime, I've unassigned myself as a fix for this will likely need an Android developer.

**Comment by mchowning** [comment] 2021-11-30 15:06
> @mchowning, I see this already has the Medium priority label. Is there anything left to do here with regard to issue triage/prioritization?

I don't think there's anything left to do wrt triage/prioritization. Medium still feels right to me since this is a pretty big issue, but it's a bit of an edge case since we've deprecated the classic editor for the vast majority of our users. 

Thanks for updating this @guarani .

**Comment by ParaskP7** [comment] 2022-04-04 09:08
👋 @guarani !

Thank you for opening this issue, I too have noticed this since day one, when I first started working with the app during my trial. I am sure I also opened another such issue when I was doing the trial. Actually, here it is, see #12529, I am also seeing @hypest closing this issue about a month ago, see [closing comment](https://github.com/wordpress-mobile/WordPress-Android/issues/12529#issuecomment-1063131870).Based on the above and after looking at this issue briefly to figure out the root cause, I came-up with the following conclusion that I would like to discuss with you:

**Comment by ParaskP7** [comment] 2022-04-04 09:42
👋 @guarani !

Thank you for opening this issue, I too have noticed this since day one, when I first started working with the app during my trial. I am sure I also opened another such issue during that period. Actually, here it is, see #12529. I am also seeing @hypest closing this issue I opened about a month ago, see [closing comment](https://github.com/wordpress-mobile/WordPress-Android/issues/12529#issuecomment-1063131870). Maybe this was supposed to be close as part of this clean-up work as well? 🤔 

Based on the above and after looking at this issue briefly to figure out the root cause, I came-up with the following conclusion that I would like to discuss with you:
1. `A Step Forward`: It seems that when the switch gets enabled/disabled (see [SiteSettingsFragment.onPreferenceChange(...)](https://github.com/wordpress-mobile/WordPress-Android/blob/082b8f039aef4abf647e9b927bd3d3834137f25e/WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java#L799-L803)) this fires a chain of reactions that ends up cycling back to the settings itself again (see [SiteSettingsInterface.onSiteEditorsChanged(...)](https://github.com/wordpress-mobile/WordPress-Android/blob/a2218f0ea74ff4ee996b6266f09b290c43bc6aa1/WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java#L1173-L1181)). This mean that this switch is not a fire and forget event but rather chained in such a way that updates the settings UI again both, instantly and on network request response. Then, these events that flow through `Event Bus`, are event got picked up by the main activity (see [WPMainActivity.refreshCurrentSelectedSiteAfterEditorChanges(...)](https://github.com/wordpress-mobile/WordPress-Android/blob/b219a60d014b90448b6b583070d19bc1607e8869/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L1521-L1546)), which might also trigger another set of events. Although, I don't see this affecting it much.
 
    Thus, we are seeing these kind of weird issues with the switch. Below are the code path that I am seeing being triggered as part of enabling/disabling block editor:
    - `SiteSettingsFragment.onPreferenceChange(...)`
    - `SiteUtils.enable/disableBlockEditor(...)`
    - `SiteActionBuilder.newDesignateMobileEditorAction(...)`
    - `SiteStore.onAction(...)`
    - `SiteStore.designateMobileEditor(...)`
        - `SiteRestClient.designateMobileEditor(...)`
        - `SiteActionBuilder.newFetchedSiteEditorsAction(...)`
        - `SiteStore.onAction(...)`
        - 2nd ⚠️ `emitChange(...)` -> `OnSiteEditorsChanged(...)`
    - 1st ⚠️ `emitChange(...)` -> `OnSiteEditorsChanged(...)`
    
   As such, and to fix the issue one would need to change all this chaining and firing of events in such a way that it doesn't cycle back to update the settings UI or any UI for that matter. However, this change feels a bit tricky and needs some refactoring, ideally replacing `Event Bus` with `Coroutines` in order to reduce complexity and unwanted side-effects.

2. `A Step Back`: Because this change can end up being a bit too complex, considering the benefit it will provide ultimately, or new bugs it will introduce if done quickly, especially due to the fact that we have deprecated the classic editor for the vast majority of our users (see [disabled - track trends - last 12 months](https://mc.a8c.com/tracks/trends/?eventname=wpandroid_gutenberg_disabled&interval=day&startdate=20210404&stat=uniques) with an average of 50 hits a day), it might be better to just ignore this until it is completely removed in the future. Wdyt?
 
PS: The [enabled - track trends - last 12 months](https://mc.a8c.com/tracks/trends/?eventname=wpandroid_gutenberg_enabled&interval=day&startdate=20220302&stat=uniques) is not shared because this track event gets triggered from multiple other flows as well, thus cannot be compared side-by-side with it equivalent disabled track event.

**Comment by hypest** [comment] 2022-04-04 13:04
👋 @ParaskP7 , are you perhaps experiencing a flow where the switch is available to the user?

**Comment by ParaskP7** [comment] 2022-04-04 13:14
👋 @hypest !

I am not exactly sure what you mean... 😊 I am indeed experiencing a flow where the switch is available to me. The site I am testing it on is an `Atomic` site of mine.

> Log in to a WP.com account that has access to an Atomic site or Jetpack site (Simple sites no longer display this switch)

As per this issue's description, `Simple` sites no longer display this switch, was this changed since?

**Comment by hypest** [comment] 2022-04-04 14:18
ah, gotcha, thanks for elaborating @ParaskP7! I was a bit confused about which case we are talking about. Indeed, it's only the Simple sites (which are the majority at that anyway) that had the switch retired.

> As per this issue's description, Simple sites no longer display this switch, was this changed since?

Nope, hasn't changed.

**Comment by antonis** [comment] 2022-04-27 13:19
I investigated this and noticed the following:
1. I confirmed the code path @ParaskP7 [highlighted above](https://github.com/wordpress-mobile/WordPress-Android/issues/14782#issuecomment-1087338495)
2. The `SiteModel.mobileEditor` seems to always be empty in my tests [resulting in a default `true` value](https://github.com/wordpress-mobile/WordPress-Android/blob/e8816fe2aee230cd42fc1362a71b7eb21ce889c0/WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java#L217)
3. The option is available even if the site (e.g. a JN self-hosted site) does not have the classic editor installed
4. Note that the issue still occurs even when the editor is available on the site
5. Setting the default editor to classic from the site is not reflected on the setting which is always switched on (actually empty as per 2 above)

**Closed as completed** 2022-05-11 12:19 UTC
Labels: [Type] Bug, [Pri] Medium, Posting/Editing
