### ISSUE TITLE
Unable to view wpcom post when loading a comments link

### ISSUE THREAD

**Issue by akirk** [wordpress-mobile/WordPress-Android#4797] opened 2016-11-17 12:04 UTC
### Expected behavior
I enter the app via a comments link on a wpcom notification e-mail. The comments section opens up. The arrow button on the top left or tapping on the title brings me to the post. 

### Actual behavior
The post title is not clickable and the arrow button takes me back to the e-mail app. 

### Steps to reproduce the behavior
see above 

##### Tested on [device], Android [version]
6.2 alpha-28

**Comment by rachelmcr** [comment] 2016-11-17 15:00
I also noticed this behavior when clicking the "See all comments" link from an email and then trying to view the post that the comments were on.

cc @hypest

**Comment by hypest** [comment] 2016-11-17 16:27
That's actually expected behaviour. We've have made the top "back" button perform like the bottom (system) back button and return to where you came from. See here for the relevant discussion: https://github.com/wordpress-mobile/WordPress-Android/pull/4606#issuecomment-252110991

That said, we might reconsider in the future. I will close this ticket as "wontfix" and we can open it in the future if we think so. Feel free to comment here though and explore the reasons why we should consider it an issue, even if closed. Thanks!

**Closed by hypest** 2016-11-17 16:27 UTC
Labels: Reader, [Type] Bug

**Comment by rachelmcr** [comment] 2016-11-17 16:45
The problem I see is that there's no way to get from that comments view to the full post. The title appears at the top of the screen, but you can't tap on it to view the post. That means if I open the comments link, it's a total dead end and I have to leave the app and either open a link to the post itself or reopen the app and dig through the Reader to find the post to view it.

It's ok if the back button doesn't take me to the post, but is there another way we could implement a link between that comments screen and the full post?

**Comment by hypest** [comment] 2016-11-17 17:00
> It's ok if the back button doesn't take me to the post, but is there another way we could implement a link between that comments screen and the full post?

This is a fair point to raise. The current GitHub issue description focuses more on the "back arrow" side of the feature but we probably can raise this as a new issue: "can't easily reach the post the comments are about" and label it a `[Type] enhancement`. We can then work on solutions for it.

To add some context, a "quick" solution would be to make the post title section at the top be tappable and taking you to the post body but there will be some gotchas regarding navigation that are not obvious (like, tapping the top back button while in the post might make you think you would go "up", not the comments, adding confusion about the expectations there). We'll need to put some thought to that.

**Comment by akirk** [comment] 2016-11-17 18:45
> The current GitHub issue description focuses more on the "back arrow" side of the feature but we probably can raise this as a new issue: "can't easily reach the post the comments are about" [...]

Excuse me but the title of the ticket is "Unable to view wpcom post when loading a comments link", it's not about the back button.

> That means if I open the comments link, it's a total dead end and I have to leave the app and either open a link to the post itself or reopen the app and dig through the Reader to find the post to view it.

Rachel hits the nail on the head here, thank you! So I'd like to ask you to re-open the ticket, please don't just quickly dismiss it, focusing on one possible resolution I mentioned in the description.

Thank you!

**Comment by hypest** [comment] 2016-11-21 12:10
Hey @akirk !

> Excuse me but the title of the ticket is "Unable to view wpcom post when loading a comments link", it's not about the back button.

I should not have framed the Back button mention as "focused", sorry for that. I understand you mentioned it in order to complete the picture that there is no way to view the post itself.

Let's separate the two though: the back button behaviour is one thing and the post title not being clickable is another. Even though the current behaviour for both is normal, as indented and not a bug, I'd like us to think of them as separate features we'd like to consider implementing (feature-requests). I closed this ticket to denote that the behaviour observed is indented and there is no work to be done to "fix" this ticket.

I would encourage us to open two new tickets: the first about requesting the feature of altering the top back button (maybe even the bottom one as well, note that these two have different meanings within Android) and a second ticket about making the title a shortcut to the post. Discussion can then take place in those respective places if needed.

BTW, I think the second of those tickets would be less controversial and thus easier to tackle.

**Comment by hypest** [comment] 2016-11-25 09:59
Headsup, I've changed the header behaviour to match the one we have when opening the app from a push notification. That is, the header is now tappable and navigates to the parent post.

This basically fixes this ticket since the basic premise of this ticket is to have a way to go to the parent post. The fix will be available in the next alpha/beta release.

Note, the current behaviour of the header_not being tappable_ when you navigate into the comments list from the parent post itself is unaltered.

**Comment by akirk** [comment] 2016-11-25 10:36
Great, that sounds like a good solution, happy about that. Thank you!
