### ISSUE TITLE
Hide or deactivate moderate buttons in comment detail when multiple comments are selected

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1158] opened 2014-03-26 20:29 UTC
That works correctly but can be confusing: 
https://cloudup.com/crSdJOaxq6A

**Comment by rachelmcr** [comment] 2015-12-02 16:06
Since the app no longer shows the comment detail while moderating comments in bulk, this is no longer an issue. Only the bulk moderation buttons are available. (Tested and confirmed in 4.8-rc-3.) Closing as resolved.

**Closed by rachelmcr** 2015-12-02 16:06 UTC
Labels: comments, [Type] Bug
