### ISSUE TITLE
Remove excessive extra space from below Kickstarter embeds

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#5011] opened 2017-01-09 22:55 UTC
### Expected behavior

I expected embedded Kickstarter videos to look fabulous on mobile.

### Actual behavior

There's a funny extra space below embedded Kickstarter videos.

<img alt="screenshot_2017-01-09-15-06-06" src="https://cloud.githubusercontent.com/assets/1119271/21786829/3f43b7ce-d683-11e6-85c9-ef979c956129.png" width="300" /> <img alt="screenshot_20170109-154206" src="https://cloud.githubusercontent.com/assets/1119271/21786831/42b1e070-d683-11e6-828c-a01aa8513046.png" width="200" />

### Steps to reproduce the behavior

1. Install WPAndroid 6.5-rc-1.
1. Create and publish a post with a Kickstarter URL on it's own line with a line of text above.
1. Open a web browser on any mobile device and check to see if there's excessive extra space below the embedded video.

**Comment by maxme** [comment] 2017-01-10 05:54
I'm not sure where that extra come from. It's probably a theme bug or another bug in WordPress (might be when the oEmbed is pulled there), but that's not a bug in the app.

**Comment by hoverduck** [comment] 2017-01-19 23:52
It looks like an issue with the iframe src from Kickstarter when displayed at mobile width, out of our control.  Closing.

**Closed by hoverduck** 2017-01-19 23:52 UTC
Labels: Posting/Editing, [Type] Enhancement
