### ISSUE TITLE
Theme details button links to Reader

### ISSUE THREAD

**Issue by bryceadams** [wordpress-mobile/WordPress-Android#3414] opened 2015-11-18 00:46 UTC
**Device:** Nexus 6P

Running the beta. When i click on the details button for a theme, it looks like it's taking me to a page with info on it but then redirects to the reader.

Here's a video: https://drive.google.com/file/d/0BwIjGsCqLwjoTldkMHVsVktyZk0/view?usp=sharing

**Comment by rachelmcr** [comment] 2015-11-24 17:09
I tested this on my devices, with the same theme (Boardwalk) activated on my blog, and couldn't reproduce the issue. After I tap on "Details" at the top of the screen I am taken to the theme description page for the active theme on my site.

Not sure why it'd be different, but I noticed in your video that the first thing to start loading was the [theme showcase](https://wordpress.com/themes) before the reader came up.

Device: Nexus 9 & Nexus 7
Version: 4.8-rc-1

**Comment by rachelmcr** [comment] 2016-02-02 16:55
I just tested this theme details issue again on a Nexus 6P emulator and couldn't reproduce it there, either. @bryceadams if you get a chance, can you test this again and see if it's still an issue for you on the latest beta?

**Comment by bryceadams** [comment] 2016-02-04 02:42
@rachelmcr just tried again and same issue - takes me to the reader.

**Comment by bryceadams** [comment] 2016-02-04 02:43
Note that the exact same thing happens if I click the ellipsis next to other themes and then details.

**Comment by hoverduck** [comment] 2016-05-02 21:25
I've seen this bug on both my Nexus 6P and OnePlus One.  But only with my primary site on my personal account...I can't recreate it on any other site or with a test account.  Like the most recent comment above, if I click the ellipsis->Details next to other themes I also get the reader, but if I switch my site's theme then the Details button at the top starts working fine.

Using alpha-7.

I looked at the Application Log and don't see anything useful, but I'd be happy to compile and test a debug version.  I looked a little bit at the logcat logs and don't see anything definitive, but it does say
`WordPress-READER: reader post list > saving instance state` when it's done loading the Themes page.  But it says that whether I'm on a site that works or doesn't, so by itself that doesn't point to the problem.

**Comment by maxme** [comment] 2017-01-02 15:31
I couldn't reproduce. This is probably a bug in Calypso, a redirect or a JS function that detects "something" (User agent?) from the request and redirect (in that case, results could vary from Android version to another and from Webview version to another).

**Comment by hoverduck** [comment] 2017-01-18 22:05
I can no longer reproduce it either...closing.

**Closed by hoverduck** 2017-01-18 22:05 UTC
Labels: Themes, [Type] Bug
