### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11791] opened 2020-04-30 12:32 UTC
**Sentry Url**: https://sentry.io/share/issue/7f9c48c8dba04519a745cc00768bdd85/
**User Count**: 3
**Count**: 18
**First Release**: org.wordpress.android-14.6.1
**First Seen**: 2020-04-25T02:22:32Z
**Last Seen**: 2020-04-28T23:40:07Z
**24 Hours**: 0
**30 Days**: 18

```
NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
     at com.android.webview.chromium.WebViewContentsClientAdapter.getDefaultVideoPoster(WebViewContentsClientAdapter.java:1164)
     at org.chromium.android_webview.DefaultVideoPosterRequestHandler$1.run(DefaultVideoPosterRequestHandler.java:39)
     at android.os.Handler.handleCallback(Handler.java:815)
     at android.os.Handler.dispatchMessage(Handler.java:104)
     at android.os.Looper.loop(Looper.java:207)
     at android.app.ActivityThread.main(ActivityThread.java:5765)
     at java.lang.reflect.Method.invoke(Method.java:null)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

Update: See https://github.com/wordpress-mobile/WordPress-Android/issues/13070 for repro steps

**Comment by bummytime** [comment] 2020-04-30 20:07
User count is currently at 4. Looking through the events and related breadcrumbs in Sentry, this _may_ be related to the reader webview. I'm seeing a lot of this:

```
i/WordPress-STATS: 🔵 Tracked: reader_article_rendered, Properties: {"post_id":XXX"blog_id":XXX,"feed_id":XXXX,"feed_item_id":0,"is_jetpack":false}

d/WordPress-READER: reader post list > saving instance state

d/WordPress-READER: bump page view succeeded

NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
```

**Comment by designsimply** [comment] 2020-05-19 19:58
**Events:** 172
**Users affected:** 46
**Note:** 95% Android 6.x so far
**Also see:** [this graph]()
<sub>https://sentry.io/share/issue/7f9c48c8dba04519a745cc00768bdd85/</sub>

**Comment by designsimply** [comment] 2020-06-27 00:40
**Events:** 590
**Users affected:** 98
**Note:** 91.52% Android 6.x
**Culprit:** `com.android.webview.chromium.WebViewContentsClientAdapter in getDefaultVideoPoster`
<sub>WORDPRESS-ANDROID-AWF: https://sentry.io/share/issue/7f9c48c8dba04519a745cc00768bdd85/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1629979327&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85910480-5bdb2c80-b7dc-11ea-9c60-4bba648b8b1b.png)</a>

**Comment by designsimply** [comment] 2020-08-20 17:12
**Events:** 1,000
**Users affected:** 142
**Note:** 76% Android 6.0 + 16% Android 6.0.1 = 92% Android 6.x total
**Note:** Lots of HUAWEI devices
**Culprit:** `com.android.webview.chromium.WebViewContentsClientAdapter in getDefaultVideoPoster`
<sub>WORDPRESS-ANDROID-AWF: https://sentry.io/share/issue/7f9c48c8dba04519a745cc00768bdd85/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1629979327&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/90803396-e8363700-e2d5-11ea-9536-10aa553f71a5.png)</a>

**Comment by bummytime** [comment] 2020-10-09 13:38
@malinajirka and I chatted about this in Slack some more. Apparently this is a known bug in Chrome - but there are workarounds. Based the number of affected users we are seeing here https://github.com/wordpress-mobile/WordPress-Android/issues/13070#issuecomment-705831797 (about 150 in aggregate), this would put the issue at "Normal" priority. Moving to groundskeeping project. 

For future reference, check out #13070 for @malinajirka's repro steps.

**Comment by malinajirka** [comment] 2020-10-09 13:43
I've done a quick investigation of this crash and it seems it's an issue with Webview/Chrome.

This is a javadoc of the `getDefaultVideoPoster ` method which is the root cause of the NPE. 

"When not playing, video elements are represented by a 'poster' image. The image to use can be specified by the poster attribute of the video tag in HTML. If the attribute is absent, then a default poster will be used. This method allows the ChromeClient to provide that default image."

I think we could override this method in provide our own default "poster".

**Comment by designsimply** [comment] 2020-10-16 20:23
**Events:** 1,400
**Users affected:** 141
**Majority of cases are:** Android 6.0
<sub>WORDPRESS-ANDROID-AWF: https://sentry.io/share/issue/7f9c48c8dba04519a745cc00768bdd85/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1629979327&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96305301-ebd6f900-0fba-11eb-9a34-38ac62534e45.png)</a>

**Comment by designsimply** [comment] 2020-11-26 03:16
**Events:** 1,600
**Users affected:** 120
**Majority of cases are:** Android 6.0
<sub>WORDPRESS-ANDROID-AWF: https://sentry.io/share/issue/7f9c48c8dba04519a745cc00768bdd85/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1629979327&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/100303929-e6c27d80-2f5a-11eb-86da-4921c32abe45.png)</a>

**Closed** 2020-12-14 10:07 UTC
Labels: Reader, [Type] Crash
