### ISSUE TITLE
Internal inconsistency error! mSmartLockHelper found null!

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-Android#8829] opened 2018-12-19 19:28 UTC
This isn't a crashing exception, but it's being manually reported in the code here:

https://github.com/wordpress-mobile/WordPress-Android/blob/34d489488d54ec5fb796c239595562e856ecad0d/WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java#L658-L661

It looks like it's only triggered by `LoginMode: FULL`, which makes sense, as `mSmartLockHelper` isn't initialized on that code path:

https://github.com/wordpress-mobile/WordPress-Android/blob/34d489488d54ec5fb796c239595562e856ecad0d/WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java#L136-L150

Hopefully that information is helpful for arriving at a fix. 

**reference:** 5be1a16bf8b88c2963c8c8f1-fabric
**90-day impact:** ~15 times/day, ~1300 affected users
**UX impact:** Users who end up in this state can't use their stored credentials to log in

**Comment by designsimply** [comment] 2019-03-15 21:35
90-day impact: ~23 times/day, ~2008 affected users.
<sub>(5be1a16bf8b88c2963c8c8f1-fabric)</sub>

Occurrences dropped significantly on Feb 14 when 11.7 was released.

**Comment by malinajirka** [comment] 2019-03-18 09:32
I've checked Fabric and it seems the issue was fixed in 11.7 -> there aren't any occurrences in 11.7/11.8/11.9. 

Closing

**Comment by malinajirka** [comment] 2019-03-18 09:37
Sorry, I just noticed it's just being logged under a different crash

5c5f01e0f8b88c29633e0da2-fabric

**Comment by malinajirka** [comment] 2019-03-18 10:27
>It looks like it's only triggered by LoginMode: FULL, which makes sense, as mSmartLockHelper isn't initialized on that code path:

I've checked and it's being initilized from `LoginActivity.showEmailLoginScreen()`. I wasn't able to reproduce the issue.

Since most users log in just once in a while and this issue affects only very few users I don't think it's worth trying to fix it, unless we have more information how to reproduce the issue. cc @designsimply

**Comment by designsimply** [comment] 2019-03-18 18:37
> I just noticed it's just being logged under a different crash
> 5c5f01e0f8b88c29633e0da2-fabric

Good catch! I will watch out for things like this when checking the numbers in Fabric in the future!

I re-checked the numbers:

30-day impact: ~33 times/day, 949 affected users from Feb 17 - Mar 18, 2019.
<sup>(5c5f01e0f8b88c29633e0da2-fabric)</sup>

Even if most users log in just once in a while, being frustrated at that point (especially if it's an early experience with the app) would make this issue important in terms of severity because you would feel blocked/annoyed/frustrated at the start of the experience. I think it would be okay to leave this open but de-prioritize it with a note that we should try again at a later time to reproduce the issue if the crash numbers stay the same or increase.

**Comment by malinajirka** [comment] 2019-03-19 08:26
Just to clarify my thoughts - I might be missing something.

This is not a crash - the users have no way to find out (unless they check the logs) that something went wrong. The only result of this issue is, the user needs to enter their password again when they sign in next time.

So I think it affects only a very few people - only those who encounter this error and they log out and want to sign-in again or they want to sign in on another device (=> far less than ~33 per day). Moreover, the only result of this error is they need to enter their password.

cc @designsimply

**Comment by rachelmcr** [comment] 2019-03-21 17:23
I reproduced the issue with these steps:

1. Start logged out of the app.
2. Select "Sign up for WordPress.com."
3. Select "Sign up with email."
4. On the signup screen, enter an email that's already linked to an existing WordPress.com account with saved credentials.
5. When you tap the "Next" button, you're taken to the magic link screen (bypassing the email login screen).
6. Select "Enter your password instead."
7. Enter your WordPress.com account password.
8. Tap "Continue" to finish logging in.
9. Go to Me > Help & Support > Application log and confirm you see the internal consistency error in the logs.

This isn't a big deal if the user can use the magic link or password to log in. However, any fixes/improvements to make login easier are worth doing if we can, given that we know that users can struggle with the login process (including trouble remembering their password and sometimes having to reset the password before successfully logging in).

**Comment by malinajirka** [comment] 2019-03-23 06:47
Awesome, great job @rachelmcr! I'll fix it either today or on Monday.

**Comment by koke** [comment] 2019-04-10 11:01
😬 Sorry, I was looking at this issue in the project, I meant to close the sidebar, and I closed the issue instead 🤦‍♂️

**Closed** 2019-05-07 11:53 UTC
Labels: Login, [Type] Bug
