### ISSUE TITLE
Draft on mobile app overwrite a newer version of draft post on blog

### ISSUE THREAD

**Issue by rainbowbreeze** [wordpress-mobile/WordPress-Android#3381] opened 2015-11-06 23:21 UTC
Step to reproduce the issue:
- Create a draft post on the website
- Open the Android app
- Open the draft post with the mobile app
- Save it in the Android app
- Go back to the site and start editing the draft post
- Save it
- Go back to Android app and start editing the draft post

Expected result: Android app tells you that the local post is old and need to be updated with the newer version on the website, or automatically loads the new post without any user notification.

Result: the Android app doesn't load the newer version of the post and when I edit it or save, the old version overwrite the one newer one on the website

Rate: 100% of the time with the post I edited both on web and Android, and lost two times the changes because Android ovewrote the never version on the site.

**Comment by rachelmcr** [comment] 2015-11-11 15:43
I tested using the steps above and reproduced the issue as described.

However, it was only an issue when I left the app open to the Blog Posts screen (either with my device's screen on or with the screen locked). If I navigated to another part of the app first, or left the app and came back, when I started editing the post it was the newer, updated draft as saved in my web browser.

**Comment by rachelmcr** [comment] 2016-01-18 12:57
I tested again and confirmed that if I pull down to refresh the blog posts screen before opening the draft in the app again, the draft is updated as expected. It could be useful to check for updates when opening a specific post in the editor, but I'm going to mark this as low priority since it's only an issue if that screen hasn't been refreshed since the change was made.

**Comment by boscoppa** [comment] 2018-02-14 22:10
I'm experiencing this exact issue, so I guess it hasn't been fixed in the past two years. I finished a first draft of a post in a web browser, and showed a friend on the mobile app. The app opened to the blog post page and I clicked onto the blog post. At this point I can only assume it loaded the version of the post that was most recently cached in the app, rather than fetching the latest online version. My friend corrected a few typos in the blog, and then reached a point where the post was unfinished. I realised what had happened as I have experienced this issue before, so I went back to the browser on my desktop and checked the history to see if I could recover the full post (which I've managed to do before), but it wasn't listed in the history, even though I made sure it was saved in the browser.

This seems like a pretty serious bug if it can result in almost entire post being overwritten and replaced in the history, and something that should have a very easy fix.

**Comment by rachelmcr** [comment] 2018-02-15 10:42
Thanks for bringing this up, @boscoppa! It sounds like this might be aggravated by an issue with revisions not all being saved on the web side, possibly due to https://github.com/Automattic/wp-calypso/issues/20265. The negative impact is much higher than when this issue was first raised since there may not be a saved revision to revert to, which leads to permanent content loss.

@elibud does this fit into the work being done on #nodeadends?

**Comment by elibud** [comment] 2018-02-15 13:01
@rachelmcr Yes this is something that we can address, or at least try to alleviate, since the bottom line is that our systems are not well thought for multi-device edition. Let me know if you would like to propose a project and we can work together on determining the priority and impact. Thank you.

**Comment by SiobhyB** [comment] 2018-03-07 11:43
I see this come up fairly often in app support too. We're usually able to help people restore the "lost" version of the post from revisions, but it's still a stressful experience for people who think they've lost their content.

Recent tickets:

261889-h, 262963-h, 264047-h, 264064-h

Related: #5984

**Comment by AtrumGeost** [comment] 2018-03-27 20:42
Hey folks!

I got another report of that issue here #1038487-zen

**Comment by oguzkocer** [comment] 2019-02-14 21:05
I believe this is fixed (improved) in #8989.

**Closed by oguzkocer** 2019-02-14 21:05 UTC
Labels: Posting/Editing, [Type] Bug
