### ISSUE TITLE
Some announcement badges contain text that looks like they are links but that aren't active

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#13113] opened 2020-10-12 22:09 UTC
### Expected behavior

I expect that any text that looks like a link in the announcement badges will work like a link.

### Actual behavior

Some text, usually numbers, look like they are links but nothing happens when you tap on them.

### Steps to reproduce the behavior

Trigger any announcement badge that contains links and try to tap on them. ([56s](https://cloudup.com/c2GMVrCiSA2))

Some example announcement badges I tested were: 

20 Likes|Boom!
---|---
<img src="https://user-images.githubusercontent.com/1119271/95794429-1d8f4d80-0ca5-11eb-997a-3770004c7c16.png" width="270" alt="Screen Shot 2020-10-12 at Oct 12 4 05 22 PM">|<img src="https://user-images.githubusercontent.com/1119271/95794427-1c5e2080-0ca5-11eb-921d-6fa68f369287.png" width="270" alt="Screen Shot 2020-10-12 at Oct 12 4 06 20 PM">

**Comment by designsimply** [comment] 2020-11-06 22:11
I saw this again while testing with WPAndroid 16.1-rc-1 on the finishing Next Steps notification: [1m31s](https://cloudup.com/cXYUMsu02uy).

**Comment by develric** [comment] 2021-04-19 22:36
If I'm not wrong this seems to be not more an issue in current develop (at this point in [history](https://github.com/wordpress-mobile/WordPress-Android/tree/a860d8b29eb097aed016d28092021c4fa756a2c4)).

| Version 15.9 | Current develop |
|---|---|
| ![image](https://user-images.githubusercontent.com/47797566/115311451-f774c980-a16f-11eb-859c-43291e119284.png) | ![image](https://user-images.githubusercontent.com/47797566/115311504-0bb8c680-a170-11eb-8f75-c18c70ec0d14.png) |

Hey @designsimply 👋 , just to be sure I'm not misunderstanding things, would be great if you could double check current develop against this original issue so that we can decide if it's possible to close this ticket, thanks 🙇

**Comment by antonis** [comment] 2024-03-05 16:23
> If I'm not wrong this seems to be not more an issue in current develop 

I checked with the latest version of the app (`24.3`) and the issue is not reproducible. I'm closing for now. Feel free to reopen if the issue reoccurs.


https://github.com/wordpress-mobile/WordPress-Android/assets/304044/7e9579a1-5571-4271-a698-bb09e3f2754f

**Comment by mkevins** [comment] 2024-03-06 04:51
I was unfortunately able to reproduce this. Steps:

* Uninstall the app
* Install a fresh copy (e.g. from `trunk`)
* Log into an account with a site
* Tap notifications tab
* Scroll to the first notification (usually something like "Welcome to WordPress.com!" "We're here to help.")
* Tap the "Welcome to WordPress.com!" notification
* 💥 Links are displayed which do not open

Screenshot:

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/8507675/355a0f7e-6234-43e4-90c4-1c9c50dbf4e3" width="360">

**Comment by dangermattic** [comment] 2024-03-06 04:51
Thanks for reporting! 👍

**Comment by antonis** [comment] 2024-03-06 07:42
> Scroll to the first notification (usually something like "Welcome to WordPress.com!" "We're here to help.")

Good catch @mkevins 👍 Let's keep this open and revisit it.

**Closed as completed** 2024-03-07 07:38 UTC
Labels: [Type] Bug, [Pri] Low, Notifications
