### ISSUE TITLE
Error: java.io.IOException: write failed: ENOSPC (No space left on device)

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13461] opened 2020-11-24 08:46 UTC
**Sentry Url**: https://sentry.io/share/issue/96272d47bbf84f3cb0f92ec7e2f322fe/
**User Count**: 499
**Count**: 2283
**First Release**: org.wordpress.android-14.6.1
**First Seen**: 2020-04-28T12:22:54Z
**Last Seen**: 2020-11-24T07:43:28Z
**24 Hours**: 15
**30 Days**: 572

```
Error: java.io.IOException: write failed: ENOSPC (No space left on device)
     at org.wordpress.android.util.helpers.logfile.LogFileWriter$write$1.run(LogFileWriter.kt:42)
...
(4 additional frame(s) were not displayed)
```

**Comment by leandroalonso** [comment] 2020-11-24 13:04
Duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/13271

**Closed as completed by leandroalonso** 2020-11-24 13:04 UTC
Labels: [Type] Crash
