### ISSUE TITLE
App freeze when sharing from another app to WP mobile

### ISSUE THREAD

**Issue by adamjohndaly** [wordpress-mobile/WordPress-Android#15023] opened 2021-07-13 18:55 UTC
### Expected behavior
Sharing to WP mobile does not freeze and save a draft

### Actual behavior
Sharing from Google > WP on Android will cause WP to freeze. 

### Steps to reproduce the behavior
I just shared a link from the Google app, (not chrome,) it worked well, exited the share extension entirely then tried to share again, and it never showed the text on screen and just showed a spinner indefinitely. It did save to my drafts though.

### Zendesk
4136481-zen

### Slack
p1626195102469900-slack-C03URUK5C

**Comment by mchowning** [comment] 2021-07-15 15:21
:wave: @antonis ! Does https://github.com/wordpress-mobile/WordPress-Android/issues/15025 resolve this issue?

**Comment by antonis** [comment] 2021-07-16 04:37
@mchowning Unfortunately not. The applied fix only handles the page creation with template.
The [root cause seems to be the same](https://github.com/wordpress-mobile/WordPress-Android/issues/15025#issuecomment-879862548) but we need to handle this separately or find another solution that would cover all cases.

**Comment by chipsnyder** [comment] 2021-07-16 13:39
I'm focused on groundskeeping next week so I can add this and https://github.com/wordpress-mobile/WordPress-Android/issues/14972 to my task list on Monday morning. 

cc @startuptester

**Comment by mchowning** [comment] 2021-07-27 14:48
👋  @chipsnyder ! Just wanted to check in and see if you had a chance to look this?

**Comment by chipsnyder** [comment] 2021-07-27 14:51
Hey @mchowning No I wasn't able to get to this one during my Groundskeeping tasks. So feel free to hand it off if needed and I'll be happy to review it.

**Comment by mchowning** [comment] 2021-07-27 14:58
I moved this from the `Mobile Gutenpages` board to the `Mobile Gutenberg` board since this doesn't seem limited to pages. Feel free to move it back if you disagree @chipsnyder .

**Comment by antonis** [comment] 2021-07-28 13:56
We have another user report on this (`4179971-zen`).

**Comment by AliSoftware** [comment] 2021-09-29 16:09
Yet another report about it in4335599-zen, which is a follow-up of 4138354-zen

@mchowning can we escalate this somehow?

**Comment by renanferrari** [comment] 2021-09-30 22:13
I spent some time investigating this as part of my groundskeeping and I think I was able to figure out the cause of the issue, but the only fix I could think of didn't seem good enough to me. I'm sharing some of my findings below so that someone with more experience in this part of the codebase can follow up on this in the future.

Long story short, this issue seems to be caused by a racing condition involving the `EditPostRepository::updateAsync` method. When a post is created from the share action, this method ends up being called from two different places:
- [`EditPostActivity::setPostContentFromShareAction`](https://github.com/wordpress-mobile/WordPress-Android/blob/473573852f9ad0416c7ba80817480d077e1f5a6d/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L2507)
    - Called from `onEditorFragmentInitialized` → `onEditorFinalTouchesBeforeShowing` → `refreshEditorContent` → `fillContentEditorFields`
- [`EditPostSettingsFragment::updatePostFormat`](https://github.com/wordpress-mobile/WordPress-Android/blob/c1278d6a6262c401d72501be991b9d2d13ea7408/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java#L786)
    - Called from `onActivityCreated` → `fetchSiteSettingsAndUpdateDefaultPostFormatIfNecessary` → `SiteSettingsListener::onSettingsUpdated`

When this happens, we log the following error:

```
EditPostRepository: Transaction is writing on a locked thread [dalvik.system.VMStack.getThreadStackTrace(Native Method), java.lang.Thread.getStackTrace(Thread.java:1720), org.wordpress.android.ui.posts.EditPostRepository.reportTransactionState(EditPostRepository.kt:151), org.wordpress.android.ui.posts.EditPostRepository.access$reportTransactionState(EditPostRepository.kt:35), org.wordpress.android.ui.posts.EditPostRepository$updateAsync$1.invokeSuspend(EditPostRepository.kt:120), kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33), kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106), android.os.Handler.handleCallback(Handler.java:883), android.os.Handler.dispatchMessage(Handler.java:100), android.os.Looper.loop(Looper.java:241), android.app.ActivityThread.main(ActivityThread.java:7617), java.lang.reflect.Method.invoke(Native Method), com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)]
```

Replacing the `EditPostRepository::updateAsync` call inside `EditPostActivity::setPostContentFromShareAction` with `EditPostRepository::update` seems to fix the issue, but I don't think we want to call a blocking method there. 

I also tried to figure out if we always need to fetch and update the post format, but didn't get too far.

Anyway, I hope this is helpful for anyone willing to give this another shot!

**Comment by mchowning** [comment] 2021-10-01 14:47
It sounds like this is a regression that started around the beginning of July (4138354-zen). Did your investigation gave any indication about what change might have caused this to start occurring @renanferrari ?

**Comment by renanferrari** [comment] 2021-10-01 18:59
@mchowning The classes I looked into during my investigation didn't have any relevant changes recently. I also looked into the `EditPostActivity` just now and still couldn't find anything that caught my attention.

That said, your comment above helped me confirm that this bug was introduced on `17.7`, since I could reproduce it there but not on `17.6`:

### 17.6

https://user-images.githubusercontent.com/830056/135672517-ec4a3cdf-5ab3-4af6-a858-d4d8ad06c614.mp4

### 17.7

https://user-images.githubusercontent.com/830056/135672538-19e12b82-5bb5-4d86-b5dc-dcdccad52301.mp4

I was in the process of comparing [the changes between the two releases](https://github.com/wordpress-mobile/WordPress-Android/compare/17.6...17.7) to see if anything stands out, but I ran out of time.

**Comment by antonis** [comment] 2021-10-04 05:46
@mchowning, @renanferrari Thank you for investigating this 🙇 
>I was in the process of comparing the changes between the two releases to see if anything stands out

My understanding is that the change that triggered the issue is [the upgrade of the RN version](https://github.com/wordpress-mobile/WordPress-Android/issues/15025#issuecomment-879672695).
> this issue seems to be caused by a racing condition

This is just a guess but probably the racing condition became more common due to performance difference of the two versions. I'm not sure if a fix similar to the [fix in the page with template](https://github.com/wordpress-mobile/WordPress-Android/pull/15027/files) (that seems to have the same root with [this issue](https://github.com/wordpress-mobile/WordPress-Android/issues/15025#issuecomment-879862548)) is possible. This involved changing the way we passed the template content to the `EditPostActivity`. Instead of passing it in the activity's bundle we retrieve the content from `EditPostActivity` since it was already in the cache.

**Comment by antonis** [comment] 2022-01-14 09:27
This should be already fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/15697

**Closed as completed by antonis** 2022-01-14 09:27 UTC
Labels: [Pri] High
