### ISSUE TITLE
Stats not accessible after self-hosted login

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-Android#17412] opened 2022-11-02 13:31 UTC
Reproducible on both WPAndroid and JPAndroid.

### Expected behavior
After logging in via site address, I expected to see a “Log in with your WP.com credentials” like on iOS. 

### Actual behavior
After logging in via site address, navigating to the stats screen shows a blank screen. 

### Steps to reproduce the behavior
1. Create a Jurassic Ninja site
2. Log in via site address
3. Go to Stats
4. A blank screen is shown

**Comment by ovitrif** [comment] 2022-11-02 13:49
I'll investigate this issue for a start, and if feasible coordinate with someone else if it's related to other work.

**Comment by ovitrif** [comment] 2022-11-02 15:02
> I'll investigate this issue for a start, and if feasible coordinate with someone else if it's related to other work.

I wasn't able to reproduce the issue on the WordPress app, tested on the beta version with an Android 9 physical device and on the `release/21.1` branch version with an Android 13 emulator.

I asked for this to be tested internally by other contributors that worked on the redesign of the landing screens (ref p5T066-3HF-p2#comment-13902)

I tested both with smart lock enabled and disabled (preview is from WordPress app, the same was in the Jetpack app during my testing):

https://user-images.githubusercontent.com/4588074/199566705-0a052e7a-ecbc-444b-a3f6-e30c9808ad8b.mp4

**Comment by antonis** [comment] 2022-11-02 16:21
I've tested this with a Pixel 5 (Android 13) and wasn't able to reproduce the issue 🤷 
I was guide to the install jetpack screen and after I logged in with my WP.com account and completed the setup I was able to see the stats.

https://user-images.githubusercontent.com/304044/199543620-fdd2ca1c-82ef-4940-8694-edbdc81120b3.mp4

@momo-ozawa Since we have the same device I was wondering if there is a special configuration for the JN site? I used the default options and just pressed the Create button.

**Comment by momo-ozawa** [comment] 2022-11-02 16:41
@antonis Thank you for testing! I'm not using a special config for the JN site - just the default option via the "Create" button.

As @ovitrif mentioned in a p2 comment (p5T066-3HF-p2#comment-13906), after creating the JN site I did the following:
- Set up Jetpack on wp-admin
- Connected it to my account

**Comment by thehenrybyrd** [comment] 2022-11-08 08:00
Seems this issue is likely related to https://github.com/wordpress-mobile/WordPress-Android/issues/17413. Both issues have proven difficult to reproduce, and in both cases reinstalling the app fixes the issue. 
I'll prioritize these as medium (high severity, low impact) for now, but this deserves more investigation if we run into it in betas again.

**Comment by irfano** [comment] 2024-03-20 12:22
I tried to reproduce by testing different cases, but I was unable to do so. I am closing this since there have been no further reports following Momo's case.

**Closed as not planned by irfano** 2024-03-20 12:22 UTC
Labels: [Type] Bug, [Pri] Medium, Stats, Self-hosted
