### ISSUE TITLE
QuickPress shortcut is not working

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#20912] opened 2024-05-30 07:16 UTC
### Expected behavior
QuickPress widget should open posting screen.

### Actual behavior
QuickPress widget is showing an error, `An error occurred when accessing this blog`, and not opening the posting screen.

[bug.webm](https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/41769f48-d07d-4df5-b4d3-f192b498b143)

### Steps to reproduce the behavior
1. Log in.
2. Go back to the device's home screen and long tap on the app icon.
3. Select Widgets.
4. Add the QuickPress shortcut to the home screen.
5. Tap on the shortcut.

**Comment by dangermattic** [comment] 2024-05-30 07:16
Thanks for reporting! 👍

**Comment by guarani** [comment] 2024-06-03 20:21
I could reproduce this on 24.9 but I couldn't see anything in the logs. It works on 24.5 though, so it might be a recent regression.

**Comment by guarani** [comment] 2024-06-03 21:03
It looks like this regression was introduced in 24.7. I checked the release notes and noticed https://github.com/wordpress-mobile/WordPress-Android/pull/20521, which touches the site picker. The error message in this bug says, "An error occurred when accessing this blog.", so I wonder if they're related.

@jarvislin, do you think the above site picker PR could be related to this regression?

**Comment by jarvislin** [comment] 2024-06-04 12:41
Hi @guarani, thanks for pinging.

I just compared the commits before and after I merged #20521 and tested the shortcut flow. This issue occurred before #20521 was merged. The SHA-1 of the commit I tested is a6edf15, which is version 24.6. 

I found that the toast message is coming from `EditPostActivity`.

https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt#L516

cc @zwarm, who might be more familiar with this file.

**Comment by guarani** [comment] 2024-06-04 14:28
Thanks for checking @jarvislin!

**Comment by zwarm** [comment] 2024-06-11 17:47
Hi - I took a quick, very quick, look and it seems that when EditPostAcitivity can't verify the site, that message is shown. I have to dig deeper, I'll put this on my to-do list. 

Update: Posted a PR with the fix #20974

**Closed as completed** 2024-06-12 14:37 UTC
Labels: [Type] Bug, Posting/Editing
