### ISSUE TITLE
[GlobalStep] VideoPress error is seen partially off screen

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11209] opened 2020-01-31 11:26 UTC
### Description
VideoPress error saying “This video doesn’t exist” when an invalid video is used, clips past the page’s borders and extends off screen.
This issue was also tested on the Samsung Galaxy Tab S2 9.7” (7.0) but not seen to occur on that device.

### Reproduction Rate
4/4 100%

### Expected behavior
The VideoPress error message should be displayed without graphical issues.

### Actual behavior
The VideoPress error message  is displayed partially off screen.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Press the “Add new” button.
4. Select the blog post option.
5. Type a title.
6. In the post contents add the shortcode for a VideoPress with an invalid video link, the following example can be used:
```
[wpvideo 0cobLTqC] 
```
##### Tested on the following
Huawei P30 Pro (9.0)

#### Please see the attached screenshots for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/73535853-7e7b3c00-441c-11ea-9ee6-d1d17706d6c4.jpg" />

### Submitted by:
Luis Pimenta

**Comment by wptester9845** [comment] 2020-02-13 10:45
This issue was seen to still occur on WordPress 4.2

Luis Pimenta

**Comment by chipsnyder** [comment] 2021-04-08 13:51
This seems to be a duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/13337#issuecomment-809632660

**Closed by chipsnyder** 2021-04-08 13:51 UTC
Labels: Previews, [Pri] Low, [Type] Bug
