### ISSUE TITLE
Reader: Some iframe embeds can appear mis-styled after stripping inline css.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4597] opened 2016-10-03 20:49 UTC
We're stripping the inline css from iframe embeds.  This can causes some layout/styling issues for certain iframes, case in point: Mesh.  Original report from Joen:

> Here’s the oembed code for a Mesh:
> 
> ```
> <div class="embed-mesh">
> <div style="width: 100%; position: relative; max-width: 500px" class="mesh-embed">
> <div style="padding-top: 100%"></div>
> <p><iframe src="https://me.sh/17qr8mvt/1qn?oembed=500" style="position: absolute; top: 0px; min-width: 320px; min-height: 320px; display: block; margin: 0px; width: 100%; height: 100%;" frameborder="0" allowfullscreen="true"></iframe></p></div>
> </div>
> ```
> 
> Here’s what the code looks like inside a webview inside the WP Android reader:
> 
> ```
> <div class="embed-mesh">
> <div style="width: 100%; position: relative; max-width: 500px" class="mesh-embed">
> <div style="padding-top: 100%"></div>
> <p><iframe src="https://me.sh/17qr8mvt/1qn?oembed=500" frameborder="0" allowfullscreen="true" allowtransparency="true" width="456" height="257"></iframe></p></div>
> </div>
> ```
> 
> Notice how it’s almost arbitrarily different. A width and height is added to the iframe, and all inline styles are removed. This results in the following display of a Mesh:

![screenshot_2015-05-13-13-34-49](https://cloud.githubusercontent.com/assets/1435271/19053504/d989b3b0-8980-11e6-9c66-2752a962f43c.png)

**Comment by maxme** [comment] 2017-03-09 17:47
@nbradbury are we stripping the `style` element in all tags? Should we keep it in `iframe`s? Does this problem actually have a solution ;)?

**Comment by oguzkocer** [comment] 2017-04-18 13:04
I am unable to reproduce this issue. Here is how the mesh shows up right now:

![screenshot_1492520570](https://cloud.githubusercontent.com/assets/662023/25131989/96db710a-2450-11e7-83f8-f0b63d4898ee.png)

@jasmussen Do you mind testing it to verify that it's working as expected now? Thanks!

**Comment by jasmussen** [comment] 2017-04-19 07:35
@oguzkocer 

> Do you mind testing it to verify that it's working as expected now? Thanks!

I couldn't easily find any good embeds in my feed to test. But if it looks like your screenshot, then that means it works perfectly! 🌟  Thank you for working on this!

**Comment by oguzkocer** [comment] 2017-04-19 12:41
@jasmussen Thanks a lot!

I did run another test, with a bigger mesh just to make sure and it seems to be working well. The embeds don't show up in the list page, which I guess is expected. But the detail page is working well, so I am closing the issue.

![screenshot_1492605633](https://cloud.githubusercontent.com/assets/662023/25180438/a7ebf6e2-2516-11e7-82c1-8cda3f2dd7b5.png)

**Closed by oguzkocer** 2017-04-19 12:41 UTC
Labels: Mobile Request, Reader, [Pri] Medium, [Type] Broken Window, [Type] Bug
