### ISSUE TITLE
Posts: Unauthenticated webview when viewing a post from the posts list

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#5326] opened 2017-03-03 11:14 UTC
### Expected behavior

I expect to get an authenticated webview when I select "View" on a published or draft post in the posts list.

### Actual behavior

The webview is not authenticated, so viewing a published post bumps the stats and viewing a draft leads to a 404 error.

h/t Davor for reporting this issue in the alpha version.

cc @maxme — possibly due to FluxC changes?

### Steps to reproduce the behavior

1. Open the Blog Posts section for a site.
2. Find a draft (marked "Draft" - not a local draft) in the posts list.
3. Tap "View" on the post's card. Result: 404 error.
4. Find a published post in the posts list.
5. Tap "View" on the post's card. Result: The post loads but with a logged-out view, so the view is counted in the site's stats.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-38

**Comment by oguzkocer** [comment] 2017-03-13 10:21
@rachelmcr I assume this is happening for .com sites since you mentioned the stats. Do you mind trying to reproduce it on current `develop`, I just tried on a fresh installation and everything works as expected. I actually updated the title of the draft while on webview, re-fetched blog posts and verified that it's actually updated.

I made sure I logged-out from Chrome before testing all this.

**Comment by maxme** [comment] 2017-03-13 10:39
@oguzkocer there is at least a problem with Jetpack sites (I tried one when I tagged this issue and there was something wrong).

**Comment by oguzkocer** [comment] 2017-03-13 12:08
@maxme That's right, we currently show incorrect username/password error for Jetpack sites:

![screenshot_1489406858](https://cloud.githubusercontent.com/assets/662023/23853713/e2c9fec4-07fe-11e7-8009-9412f11d0c67.png)

**Comment by rachelmcr** [comment] 2017-03-14 12:15
This was happening on WordPress.com sites. I retested in alpha-39 and it's resolved there. I also checked a self-hosted site without Jetpack and it's working there as well.

I do still see the Jetpack issue (Incorrect username or password) but it's working as expected on other sites now.

**Comment by oguzkocer** [comment] 2017-03-14 12:19
Thanks for confirming it @rachelmcr, I am currently working on the Jetpack issue.

**Comment by rachelmcr** [comment] 2017-04-07 11:31
@oguzkocer I am seeing this issue again in alpha-46. It specifically happens on WordPress.com sites with custom domains — on those sites, the webview is unauthenticated, although it works as expected on WordPress.com sites with a *.wordpress.com subdomain.

**Comment by oguzkocer** [comment] 2017-04-10 13:49
@rachelmcr This is caused by Calypso, or wherever we handle the login post request as the request for custom domains and `.wordpress.com` are the same. I did verify it through making a `POST` request outside of the map and you're right, the custom domains do not get authenticated.

We can either try to get this fixed in server-side or we can maybe use the `unmapped_url` option to replace the custom domain, which I don't really like.

**Comment by rachelmcr** [comment] 2017-04-10 14:45
> Edit: This will probably fail for iOS as well.

Preview works as expected for me on iOS. When I view or preview a post on a WordPress.com site with a custom domain, I get an authenticated webview as expected.

**Comment by danielwrobert** [comment] 2017-04-10 15:47
I was about to file a bug for this, before seeing this ticket. I've experienced the same issue.

I have confirmed it works on iOS. It fails, as noted above, in alpha-46 on both a Nexux 6 (running Android 7.0) and a Google Pixel (running Android 7.1.1).

**Closed** 2017-04-24 16:49 UTC
Labels: Low Hanging Fruit, Post List, [Pri] High, [Type] Broken Window, [Type] Bug
