### ISSUE TITLE
OutOfMemoryError org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest in parseNetworkResponse

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/WordPress-Android#15474] opened 2021-10-15 18:55 UTC
A user reported that the WPAndroid app crashed frequently and they say image tags/alt text disappear. They say this happens with any post whether large or small. 

**Sentry Url**: https://sentry.io/share/issue/52c6e1fa24fa47e68af7edb93574666e/
**User Count**: 4
**Count**: 962
**First Release**: 12.3.2
**First Seen**: 2021-07-19T08:43:37.162Z
**Last Seen**: 2021-10-15T17:10:33.409Z
**24 Hours**: 27
**30 Days**: 165

```
java.lang.OutOfMemoryError: Failed to allocate a 41431560 byte allocation with 19100920 free bytes and 18MB until OOM, target footprint 536870912, growth limit 536870912
    at libcore.util.CharsetUtils.toUtf8Bytes(CharsetUtils.java)
    at java.lang.String.getBytes(String.java:946)
    at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.parseNetworkResponse(XMLRPCRequest.java:62)
    at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:143)
    at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
    at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```

Internal ref: p4a5px-2Mz-p2

**Comment by jhnstn** [comment] 2021-10-19 15:46
The disappearing image tags/alt text seems related to #8393 since the site in question is self hosted and the user confirmed they are logging in by url. (h/tip @designsimply )

We are yet to uncover what is causing the crashes. It could be an authentication or plugin issue. We did review the list of plugins installed on the site and nothing jumped out as problematic. 

Since this is only being reported by one user and the crashes don't seem wide spread I'm setting the priority as Medium.

**Comment by jd-alexander** [comment] 2021-11-01 19:10
This issue is related to this [FluxC line](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/5f2fb2f652ec711d17c5b7392c54491b1259f370/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/XMLRPCRequest.java#L62).

It seems this error occurs when the app is somehow running out of memory when trying to parse the network response. For several users, I saw 

```
Low memory
{
action: LOW_MEMORY, 
level: 10
}
```

This indicates that the device was not able to allocate enough memory for the content in question. Reviewing the stacktraces, the request memory amounts range from 113MB to 214MB. That's quite sizeable. So it seems this crash is related to content size.

-----
This issue is currently only impacting 5 users. If the user impact increases then we can look into handling this error more gracefully.

**Comment by designsimply** [comment] 2021-11-01 20:34
@jd-alexander I just wanted to chime in and say that I agree with the medium prioritization but also that I think it's likely affecting more than 5 users since most cases in that Sentry issue are being recorded as `id:0` (I'm guessing because it's a problem that happens for non-WP.com users logging in via the site credentials only option). 

If you look at the user tag for the `1038272760` issue in Sentry right now, you'll see that Sentry recorded 400+ cases:

<a href="https://sentry.io/organizations/a8c/issues/1038272760/tags/?project=1438088"><img src="https://user-images.githubusercontent.com/1119271/139737896-70742ad5-a36d-40be-9a7c-044c4483acfd.png" width="270" alt="image"></a>

And if you look at the 90-day graph for the `1038272760` issue in Sentry, you can see that the number of occurrences is rising over time but not toooo much: 

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1038272760&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=122&widths=-1&yAxis=count%28%29"><img src="https://user-images.githubusercontent.com/1119271/139737774-fa4cd5d3-4314-479c-b97b-df6ed2e209a6.png" alt="image"></a>

**Comment by jd-alexander** [comment] 2021-11-01 21:42
> @jd-alexander I just wanted to chime in and say that I agree with the medium prioritization but also that I think it's likely affecting more than 5 users since most cases in that Sentry issue are being recorded as `id:0` (I'm guessing because it's a problem that happens for non-WP.com users logging in via the site credentials only option).
> 
> If you look at the user tag for the `1038272760` issue in Sentry right now, you'll see that Sentry recorded 400+ cases:
> 
> [<img alt="image" width="270" src="https://user-images.githubusercontent.com/1119271/139737896-70742ad5-a36d-40be-9a7c-044c4483acfd.png">](https://sentry.io/organizations/a8c/issues/1038272760/tags/?project=1438088)
> 
> And if you look at the 90-day graph for the `1038272760` issue in Sentry, you can see that the number of occurrences is rising over time but not toooo much:
> 
> [![image](https://user-images.githubusercontent.com/1119271/139737774-fa4cd5d3-4314-479c-b97b-df6ed2e209a6.png)](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1038272760&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=122&widths=-1&yAxis=count%28%29)

Understandable @designsimply thanks for sharing. These memory issues aren't normally the easiest to recover from once the app gets into that state. Being that most of the devices that this error is occurring on is stating that the device itself has low memory, then that would be a bit out of our control since we aren't able to lessen the memory requirements of the data from the network response. 

Just to check, have you been able to reproduce this crash?

**Comment by designsimply** [comment] 2021-11-02 21:24
I agree, and I think the numbers of occurrences are still pretty low overall too. The graphs are nice to have though because they can help show trends or spikes, which can help a lot if it ends up that we need to loop back later to review the same issue again.

> Just to check, have you been able to reproduce this crash?

I haven't! We have been working with a user who reported the problem to support though, and I can tell you some general information about that account and what additional details the user has reported in case it's helpful—including quotes about the problem as described by the user:

> app closes frequently and unexpectedly
> <sup>Oct 12 22:57</sup>

They tried deleting and re-installing the app and it didn't help.

> it just started happening for all posts large or small
> <sup>Oct 13 22:04</sup>

> this happens when I'm logged in to app via url
> <sup>Oct 18 17:10</sup>

It may be noteworthy that the problem happens when they log in to the app using the site credentials login flow.

If you look at the internal reference 4372569-zen, it contains a set of app logs from the user which contain several volley errors including "AuthFailureError" but I am not sure if that's related to the problem.

At the time of the original report, the user site in this case contained 12074 posts and 44 pages by 21 authors. The site also has 36 active plugins, which you can see a list of at internal reference p4a5px-2Mz-p2#comment-12480.

> having issues editing posts via app never happened before until last 24 hours
> <sup></sup>

This user may be facing multiple separate issues. In their latest communication from Oct 26th, they included another set of app logs which contain several lines that start something like this:

```
[Oct-26 23:49 POSTS] StackTrace: org.json.JSONException: Unterminated object at character 20 of {id=
[Oct-26 23:49 POSTS] Unterminated object at character 20 of {id=
[Oct-26 23:49 POSTS] StackTrace: org.json.JSONException: Expected literal value at character 18 of {id=
```
<sup>Go to internal ref 4372569-zen and scroll to "Oct 26 18:51" to see the full set of logs.</sup>

Based on that latest information, do you think the error about the unterminated object at character xx could be related to the memory errors? Could the problem be related to some kind of strangely encoded content on the site itself that the app is unable to handle or do you think this user may be facing more than one bug simultaneously? 

Device and app details: 
WordPress - 18.4 - Version code: 1125
Android device name: Samsung SM-N975U
Free Space: 465,543MB

> Being that most of the devices that this error is occurring on is stating that the device itself has low memory, then that would be a bit out of our control since we aren't able to lessen the memory requirements of the data from the network response.

I see. Could something in our app be causing the memory on their device to become low though? The device in this user's case is a Samsung SM-N975U which looks not too terribly old and it appears to have plenty of free space and my gut tells me to try to check for something on our side that might be causing the low memory errors (I may be wrong about this! my main goal at this point is to try to provide you with the best information possible about the problem report and to try to help by asking good questions).

**Comment by jd-alexander** [comment] 2021-11-03 00:14
> I agree, and I think the numbers of occurrences are still pretty low overall too. The graphs are nice to have though because they can help show trends or spikes, which can help a lot if it ends up that we need to loop back later to review the same issue again.

Thanks for sharing this! I will always keep an eye on these graphs to spot any trends because these trends can allow us to spot any generalizations in the reports we are getting to determine the actual cause for a crash.

> I haven't! We have been working with a user who reported the problem to support though, and I can tell you some general information about that account and what additional details the user has reported in case it's helpful—including quotes about the problem as described by the user:

The quotes were helpful in recreating the user flow that would have originated in the crash taking place. 

> If you look at the internal reference 4372569-zen, it contains a set of app logs from the user which contain several volley errors including "AuthFailureError" but I am not sure if that's related to the problem.

I don't think the `AuthFailureError` is related here, nonetheless, it's good to be aware of it in case it's needed to replicate the environment of the user as closely as possible. 

> At the time of the original report, the user site in this case contained 12074 posts and 44 pages by 21 authors. The site also has 36 active plugins, which you can see a list of at internal reference p4a5px-2Mz-p2#comment-12480.

This piece of information is quite helpful. "12074 posts" is a lot. The crash that took place for this user occurred within the `PostsListActivity`, the screen in the app that shows all Posts. Therefore, it could be that the functionality there that triggers the fetching of posts from the server is not able to allocate enough application memory to store the response from the server. 

> Based on that latest information, do you think the error about the unterminated object at character xx could be related to the memory errors? Could the problem be related to some kind of strangely encoded content on the site itself that the app is unable to handle or do you think this user may be facing more than one bug simultaneously?

I doubt this is related to memory. You are spot on with it being related to parsing errors of the site's contents.

> I see. Could something in our app be causing the memory on their device to become low though? The device in this user's case is a Samsung SM-N975U which looks not too terribly old and it appears to have plenty of free space and my gut tells me to try to check for something on our side that might be causing the low memory errors (I may be wrong about this! my main goal at this point is to try to provide you with the best information possible about the problem report and to try to help by asking good questions).

Thanks for sharing. These thoughts and questions have been really helpful. One of the differentiating factors here from a memory standpoint is RAM and Storage. The RAM/Memory fluctuates as all running app and OS processes make use of it. There are systems that regulate how much memory a single app, like WordPress has access to, hence we have to facilitate scenarios like these where we aren't able to access enough RAM for resource-intensive memory events. So even a high-end device like this, can have low memory scenarios because Android won't allocate too much memory to our app as that would cause instability elsewhere as there are critical system processes that cannot be garbage collected therefore enough memory has to be available for efficiency.

**Comment by jd-alexander** [comment] 2021-11-03 00:19
Based on the information here, a scenario that we could recreate for testing purposes is to create a self hosted site with >10,000 posts and see if we run into a low memory scenario. 
If we are able to recreate this then we can possibly leverage some form of mechanism in the near future for optimization. 

I know there have been talks about improving how posts are fetched and that the utilization of chunks when processing the data stream could help us prevent such issues as it would involve us getting an idea of the size of the content being fetched and comparing that with the device's memory constraints.

**Comment by ashiagr** [comment] 2021-12-29 13:10
Sharing a few findings:

> it's likely affecting more than 5 users since most cases in that Sentry issue are being recorded as id:0 (I'm guessing because it's a problem that happens for non-WP.com users logging in via the site credentials only option).

As of today, out of `637` events in the past 3 months, `596` events (`93%`) are from two users only. Both accessed sites with a large number of posts. 

User  |Event Count | Device Family | Device Name | Site Id  | Post Count |  Timezone
-------------|-------------|------------|------------|-----------|-------------|----------
`User1` | 464 | SM-N975U (Samsung Note)| 360 MAGAZINE |  129573295 | 12485 | America/New York
`User2`| 97 + 35 | SM-A505F, SM-A515F (Samsung Galaxy A5) | A50 ของ วราภรณ์ , Virus~iDA |  166702177 | 14183 | Asia/Bangkok

Event count can be checked in `Sentry - Discover` section by selecting the issue id and device name. 

<img width="1580" alt="Screenshot 2021-12-29 at 6 18 51 PM" src="https://user-images.githubusercontent.com/1405144/147664015-ce74cb2d-9fc6-48fc-a800-be5f68eaa4de.png">

The [next user](https://sentry.io/share/issue/52c6e1fa24fa47e68af7edb93574666e/) with the most number of events count (<10) has also accessed a site (116658753) with large num of posts (41561).

Also note that `User2` is using `Galaxy A5` devices that might not be best-optimized for memory, also reported in the SO thread [here](https://stackoverflow.com/a/45611316/193545) for a similar issue.

While the OOM occurs when converting a string to a byte array:
```
java.lang.OutOfMemoryError:
    at libcore.util.CharsetUtils.toUtf8Bytes(CharsetUtils.java)
    at java.lang.String.getBytes(String.java:946)
    at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.parseNetworkResponse(XMLRPCRequest.java:62)
```
it is likely that the device is already in a state of low memory when this happens due to quick memory-intensive operations by the user before it. This is just a guess and might not entirely explain the issue for `User1`.

**Closed as completed** 2024-08-28 03:17 UTC
Labels: [Pri] Medium, [Type] Crash
