### ISSUE TITLE
Galleries don't work

### ISSUE THREAD

**Issue by wlanowski** [wordpress-mobile/WordPress-Android#15819] opened 2022-01-14 08:35 UTC
### Expected behavior
When I create a gallery via mobile app, the gallery does not appear in the post and the gallery block is broken. If I want to edit this block online via browser, the clock does not appear in the editor and shows the message: _this block has unexpected or invalid content._

### Actual behavior
the gallery block should work

### Steps to reproduce the behavior

1. use wordpress App 18.9 or 19.0 (18.8 is working!)
2. create a post
3. create a gallery block

##### Tested on [device], Android [version], WPAndroid [version]

The Error is reproduceable on this versions:

- Android app version 18.9
- Android app version 19.0
- iOS app version 18.9

The error occurs, on two of my websites. Everything is up to date. I have wordpress reports available for you:

- wlanowski.de [https://gist.github.com/wlanowski/71e4e9452dda53efa9ef2f245475307a](https://gist.github.com/wlanowski/71e4e9452dda53efa9ef2f245475307a)
- superbitch380.de [https://gist.github.com/wlanowski/becbb58449a690223b482041f3520a6b](https://gist.github.com/wlanowski/becbb58449a690223b482041f3520a6b)

The error does **_not_** occur, when using this:

- Android app version 18.8
- create gallery block via browser editor (does not matter, which editor)

**Comment by wlanowski** [comment] 2022-01-15 01:55
The error does not occur with wordpress beta 5.9. 5.8.3 occurs

**Comment by thehenrybyrd** [comment] 2022-01-28 08:16
@wlanowski thanks for the details regarding app and WordPress versions that are working or not working!

@hypest this looks like a regression in the gallery block, effecting only blocks created from the app.

**Comment by hypest** [comment] 2022-01-31 14:56
👋 all. @antonis , does this one ring a bell perhaps? My impression is that there was a similar gallery issue wrangled recently 🤔

**Comment by antonis** [comment] 2022-01-31 15:29
Thank you for the ping @hypest 🙇 
I don't recall a similar issue 🤔 . The [auto-migration of v1 Gallery blocks to v2 format was included in Gutenberg 12.1](https://github.com/WordPress/gutenberg/pull/36191)([mobile version 18.9](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4315)). Since the issue does not occur in `5.9` I wonder if the site (5.8.3) is set to use the old gallery block by default. @glendaviesnz, @mkevins do you have any insights on this?

**Comment by wlanowski** [comment] 2022-01-31 15:36
Hi there!

As the issue does not occure anymore with current Versions of WP core and WP mobile this issue is Not present for me anymore. Close?

**Comment by hypest** [comment] 2022-01-31 18:10
Thanks for your input everyone!

Let's close this one as not occurring anymore and, we can reopen if needed 👍

**Closed as completed by hypest** 2022-01-31 18:10 UTC
Labels: [Type] Bug

**Comment by fluiddot** [comment] 2022-06-02 16:04
Looks like this issue was related to a bug about using a WordPress version (not the app but the core) that doesn't support the new Gallery block version (i.e. `v2`). As described in [this ticket](https://github.com/WordPress/gutenberg/issues/41465) due to a PR merged in [Dec 2021](https://github.com/WordPress/gutenberg/pull/37134) the `v2` was being used in the native version, independently on if that version was supported or not by the WordPress version.
