### ISSUE TITLE
Jetpack: Stats prompt leads to error if Jetpack is installed but deactivated

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4953] opened 2016-12-22 10:48 UTC
### Expected behavior

If Jetpack is installed on my site but deactivated, and I visit the Stats section for that site, I expect to see a message about installing/activating Jetpack.

### Actual behavior

When I visit the Stats section, I see a message that Jetpack is installed but not connected to WordPress.com. When I tap "Yes" to connect Jetpack, I get the error "Sorry, you are not allowed to access this page" (because Jetpack is installed but not activated):

![2016-12-22 10 41 01](https://cloud.githubusercontent.com/assets/8658164/21423121/40760808-c833-11e6-93d2-b07439118d01.png)
![2016-12-22 10 41 06](https://cloud.githubusercontent.com/assets/8658164/21423123/42623f9c-c833-11e6-9460-d034729dbf94.png)

If I activate the Jetpack plugin, it works as expected — I am taken to the Jetpack section of my site's dashboard where I can connect Jetpack to WordPress.com:

![2016-12-22 10 42 43](https://cloud.githubusercontent.com/assets/8658164/21423169/6ae13e1e-c833-11e6-9b86-9d99c04a503d.png)

### Steps to reproduce the behavior

1. On a self-hosted site, install the Jetpack plugin but do not activate it.
2. In the app, log in to that self-hosted site.
3. Open the Stats section.
4. When the prompt appears, tap "Yes" to connect Jetpack to WordPress.com. Result: Error message.
5. In your site's dashboard, activate the Jetpack plugin.
6. Open the Stats section again.
7. When the prompt appears, tap "Yes" again to connect Jetpack to WordPress.com. Result: You are taken to your site's dashboard to connect Jetpack.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-31

**Comment by hoverduck** [comment] 2017-01-19 23:35
Related:

https://github.com/wordpress-mobile/WordPress-Android/issues/2646
https://github.com/wordpress-mobile/WordPress-Android/issues/3275

**Comment by catehstn** [comment] 2017-01-21 01:30
@maxme is this handled by FluxC?

**Comment by maxme** [comment] 2017-01-23 05:56
Not yet handled by FluxC, we're working on better Jetpack support, there is also some UI stuff to work on in wpandroid to handle that perfectly.

**Comment by aforcier** [comment] 2017-03-21 19:54
Still applies in `alpha-41` - with the difference from pre-FluxC that if you're not signed into WordPress.com in the app already, you get sent to the 'Sign in to your WordPress.com account' screen instead.

**Comment by tonyr59h** [comment] 2017-05-25 22:23
Unable to reproduce this in `alpha-58`, activating then returning to the Stats screen works as expected. Tested via Genymotion API 23. @rachelmcr would you mind confirming?

**Comment by tonyr59h** [comment] 2017-05-26 19:56
Tested again on Genymotion API 16 and this issue seems to be resolved. Going to close it now, if someone else can reproduce please re-open with App/OS details.

**Closed by tonyr59h** 2017-05-26 19:56 UTC
Labels: Jetpack, Stats, [Pri] Medium, [Type] Broken Window, [Type] Bug
