### ISSUE TITLE
Tapping the "Edit" button on an inserted video should open a specific dialog, not the image editing one

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2613] opened 2015-05-01 12:16 UTC
![wpid-screenshot_2015-04-27-22-37-14](https://cloud.githubusercontent.com/assets/40213/7430004/79751208-f00c-11e4-8673-1a2caa1a5902.png)

**Comment by maxme** [comment] 2015-05-01 12:22
Note: title styling is on `Horizontal alignment` and `Width`

**Comment by rachelmcr** [comment] 2015-12-07 18:19
I checked on 4.8-rc-3 and confirmed that we're still showing the image settings dialog for inserted videos. I will keep an eye on this in the new editor to see how we handle the edit dialog for videos there.

**Comment by rachelmcr** [comment] 2016-03-22 17:58
In the new editor, videos don't have an edit button so there's no edit dialog to bring up there. This is the same as the iOS editor. In the web interface (Calypso and wp-admin), videos are added with a shortcode so there's also no edit dialog for videos there.

I'm closing this issue since it's resolved in the new editor by not using any edit dialog for videos.

**Closed by rachelmcr** 2016-03-22 17:58 UTC
Labels: Media, posting/editing, [Type] Bug
