### ISSUE TITLE
Style issue when sharing media to the app

### ISSUE THREAD

**Issue by sarahfg** [wordpress-mobile/WordPress-Android#11182] opened 2020-01-28 20:48 UTC
### Steps before issue
1.  Select an image in the gallery of the phone
2.  Press the share button,
3. Select the WP app

#### Issue
When the the screen to select a site and share pops up there is a white button has no text in it. It should be labelled 'upload to media library'.

![](https://d.pr/i/rwhPRP+)

(Image link: https://d.pr/i/rwhPRP )

Samsung Galaxy S4. Android 5.0.1 WordPress - 13.9 -

Unable to reproduce on 
Pixel 3 Android 10 WordPress 13.9

#2666264-zen

**Comment by malinajirka** [comment] 2020-01-29 10:02
Seems like a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/11173. Closing

**Closed by malinajirka** 2020-01-29 10:02 UTC
