### ISSUE TITLE
Email notification link not opening in the App 

### ISSUE THREAD

**Issue by rossanafmenezes** [wordpress-mobile/WordPress-Android#13337] opened 2020-11-10 14:12 UTC
### Expected behavior

When you receive an email notifying you about a new post and you click on the link the post should open in the mobile app or in the browser according to your settings. 

<img src="https://user-images.githubusercontent.com/30724184/98681779-1fded900-2331-11eb-99a1-5fee3680bb7a.jpg" width="270" alt="IMG_20201110_084530_105">

### Actual behavior

The link opens in a browser regardless if you have your settings to open links the app can handle in the app. It happens to custom domains and wordpress.com subdomains the same way. 

Worth noting that trying to open a link from Facebook for example prompts the option to open it with the app or the browser and you can select the option if you have the option set to ask every time. So it's not an issue with Android.

### Steps to reproduce the behavior

- Open the WordPress app
- Go to your Profile > App Settings > Open your device settings > Advanced > Open by default > Open supported Links
- Select either the "Ask every time" or "Allow app to open supported links"
- Go to your email and open any email notification from WordPress sites you follow 
- click on the post link

The post should open in the app/reader but opens in the browser

Also worth noting, @sarahfg was able to have the link open in the App at some point, but not anymore. 

##### Tested on [device], Android [version], WPAndroid [version]

Pixel, 2 and 3 with Android 11
Samsung Galaxy A20, model # SM-A205U1.
Android, version 10.
OPPO Reno 4 on Android 10

All using WordPress app 16

(internal reference: 3<span></span>470196-zen)

**Comment by designsimply** [comment] 2020-11-12 00:17
I checked the My Site > Profile > App Settings > Open device settings > Advanced > Open by default screen and then I tapped on the "Open supported links" option and I saw the following note at the bottom of the screen:

<blockquote>App claims to handle following links:
 
wordpress.com
*.wordpress.com
public-api.wordpress.com</blockquote>

<img src="https://user-images.githubusercontent.com/1119271/98878751-fca34f00-2440-11eb-989f-d62050a9ec4e.png" width="270" alt="Screenshot_20201111-164230">

I selected the "Allow app to open supported links" option and then tested opening various links from my email and I found that  if I tap on a public-api.wordpress.com post link from an email it does open in the WPAndroid app but since I have two separate browsers installed it prompts to ask me which browser I want to use first. I found that the redirects worked properly for me when using Chrome but not when using Firefox. ([5m19s](https://cloudup.com/cHnKy_j5bMr))

<sup>Tested with WPAndroid 16.1-rc-3 on Pixel 3 Android 11.</sup>

To re-cap, I was able to get the links to open in the app for the following conditions:

* App Settings is set to "Allow app to open supported links".
* The link tapped is a post not a home page.
* The link tapped is a wordpress.com, *.wordpress.com, or public-api.wordpress.com link.
* Chrome is my default browser or I select it when prompted.

I will need to do some extra research to verify what the expected behavior for this one is exactly. 

Aside: if I were to ask for a small change, I would suggest adding wp.me to the list of supported link types and then at least we could let users know that the short links at the bottom of their new post email notices should work a bit more consistently.

**Comment by designsimply** [comment] 2020-11-12 18:22
The following PRs have some extra info about which types of deep links from emails are supported: https://github.com/wordpress-mobile/WordPress-Android/pull/4669, https://github.com/wordpress-mobile/WordPress-Android/pull/9957, https://github.com/wordpress-mobile/WordPress-Android/pull/11996, https://github.com/wordpress-mobile/WordPress-Android/pull/12004.

> The link opens in a browser regardless if you have your settings to open links the app can handle in the app. It happens to custom domains and wordpress.com subdomains the same way.

In testing, I found that the browser must be selected first and then the app is automatically opened from there but only if it is a supported link such as a post link and the link must be a *.wordpress.com domain. It may also matter which browser is your default. For example, the redirect worked for me in Chrome but not Firefox.

@rossanafmenezes can you please confirm that you are tapping on a supported type of link such as a post link on a *.wordpress.com domain? You should be able to find the full link in your email by long-pressing on it and then selecting Copy. When you are prompted to select a browser, which browser do you select? Does the link open in the app if you tap a *.wordpress.com domain and you select Chrome when prompted?

**Comment by rossanafmenezes** [comment] 2020-12-04 18:31
Hi @designsimply  all the links I used to do the testing were WordPress.com links since they were all from my own WP.com testing sites. 

That's the whole issue. I'm not prompted to select a browser or any app for that matter. I only have Chrome on my phone and it opens directly on Chrome. It does not even  ask if I want to open in the WordPress app or on the browser. It simply ignores the app option and opens on Chrome.

**Comment by designsimply** [comment] 2020-12-07 21:33
We re-tested this today and @rossanafmenezes was able to get it working. 👍 

<img src="https://user-images.githubusercontent.com/1119271/101407016-7b9c7380-3897-11eb-9707-554f22b10e92.jpg" width="270" alt="IMG_20201207_153558_110">
<sup>Screenshot from rossanafmenezes - shared with permission.</sup>

I'm following up here to note that we tested and confirmed these settings are working as expected and to add some troubleshooting notes and close the issue with an ask to please re-open (or make a new one) if this comes up again.

Troubleshooting

1. In the WPAndroid app, go to My Site > user icon (top right) > App Settings > Open device settings > Advanced > Open by default and double check the "Open supported links" section—verify it is set to either "Ask every time" or "Allow app to open supported links".
1. In your default browser app, verify that any setting for "Open links in apps" is enabled.
1. In your email app, verify that you are clicking on a supported link (currently, the supported links are wordpress.com, *.wordpress.com, and public-api.wordpress.com).

Gotchas

* Depending on what email app you are using and your settings for that app, it may look like some links are opening in Chrome when they are actually opening in an in-app browser first and you may need to do one more action such as tap the three dots at top right (or a similar button) before you see the prompt to ask where you want to open the link.
* Your browser may also have a setting that overrides how/where links are opened. For example, in the Firefox browser I had to enable the "Open links in apps" settings in the browser itself ([screenshot](https://user-images.githubusercontent.com/1119271/101408067-15185500-3899-11eb-82d0-ce404122168f.png)) before opening *.wordpress.com links from my Gmail app would work to open supported links directly in my WordPress app.

If someone reports they are still having trouble after double checking their settings and the types of links they are tapping on, have them go to the email and long-press then "Copy URL" and send that URL in to support and we can try testing using the same blog they are using.

Aside: I also wanted to mention that I tested this several times today and it always worked as expected in my tests. I tested using WPAndroid 16.3-rc-2 on Pixel 3 Android 11 with Chrome then Firefox set as the default browser.

**Closed as completed by designsimply** 2020-12-07 21:33 UTC
Labels: [Type] Bug, App Settings
