### ISSUE TITLE
Android 12 Forces Editor to Close

### ISSUE THREAD

**Issue by thabotswana** [wordpress-mobile/WordPress-Android#15811] opened 2022-01-10 11:23 UTC
We got a user report that the app has started forcing the editor to close seconds after opening it since updating to Android 12.

I don't have Android 12 so unable to test this.

>I open the wp editor and start writing for about 5 seconds and then the editor closes down by itself and just takes me back to the list of posts. The post I'm working on still auto-saves though, but it's doing this everytime

4667763-zen

##### Samsung SM-G980F, Android 12, WPAndroid 18.8

**Comment by hypest** [comment] 2022-01-11 14:53
Can't reproduce on an Android 12 _emulator_ from my side.

**Comment by antonis** [comment] 2022-01-11 15:08
I tested on a Pixel 5 (Android 12) and I wasn't able to reproduce the crash (tried `18.8`, `18.9` and `19.0-beta`).

**Comment by mchowning** [comment] 2022-01-20 15:20
I also can't reproduce this on a Pixel 3 running Android 12. I'll go ahead and close this since we can't reproduce it, but feel free to reopen it if you disagree or if we get more information about this.

**Closed as completed by mchowning** 2022-01-20 15:20 UTC
Labels: Posting/Editing, [Type] Crash
