### ISSUE TITLE
Publish option is enabled for account that hasn't confirmed email yet

### ISSUE THREAD

**Issue by chenchaoyi** [wordpress-mobile/WordPress-Android#5405] opened 2017-03-15 06:01 UTC
### Expected behavior
Publish is disabled before a newly created account from desktop browser confirms its email address

### Actual behavior
Publish is enabled as usual, and all "published" posts go to draft instead.

### Steps to reproduce the behavior

Sign up a new user **from desktop browser** (Note this has to be from desktop, Sign up from mobile devices doesn't seem to require email confirmation). Do **NOT** confirm the email address from your email inbox.

Notice the Publish is disabled from desktop browser and there is a hint to ask for email confirmation first:
<img width="778" alt="screen shot 2017-03-12 at 11 11 12 pm" src="https://cloud.githubusercontent.com/assets/1484624/23935612/f9cd9ea8-0909-11e7-93f8-1610b99db12b.png">

Log in from **Android app**, create a new post, and notice the **Publish** button is enabled contrary to the desktop behavior. After click on it, the post will be only saved to draft, instead of published.

This is very misleading. It might take a while for the user to find out that all the "published" posts were still sitting as draft. The user has to log in from desktop browser to find out what was the reason that the "published" posts are all just saved to draft.

##### Tested on [device], Android [version]
- WorePress Android App **Version 6.9** 
- **Samsung Galaxy S5**, 
- **Android version 6.0.1**

**Comment by daniloercoli** [comment] 2017-03-15 09:53
Duplicate of #4600 

@tonyr59h - What do you think if we escalate this issue? I've seen a lot of our users during my HS rotation having problem publishing from the app since the email was not confirmed.

**Closed by daniloercoli** 2017-03-15 09:53 UTC
Labels: [Pri] High, [Type] Broken Window

**Comment by tonyr59h** [comment] 2017-03-17 19:43
> What do you think if we escalate this issue?

I'm tackling this issue (#4600) today, I'll cc you for the review 😉
