### ISSUE TITLE
Can approve or reply comments from notifications screen

### ISSUE THREAD

**Issue by thejeshgn** [wordpress-mobile/WordPress-Android#2627] opened 2015-05-05 10:28 UTC
- Self hosted blog
- Version 3.9.1

- Get a notification for a comment
- Go to notifications screen
- Click on comment & app moves to single comment screen
- Click on approve tick mark
- Tick turns pink, goes back to notifications page, refreshes
- displays "An error occurred while moderating"

**Comment by rachelmcr** [comment] 2015-11-25 12:31
Hi @thejeshgn! I tested this issue on a self-hosted blog running WordPress 4.3.1 and couldn't reproduce the behavior you described. Is this still an issue for you? (If so, I can continue testing it.)

**Comment by rachelmcr** [comment] 2016-02-01 18:15
I'm going to go ahead and close this issue, since I can no longer reproduce it. If you still have trouble with this, please comment here and we can reopen and investigate it!

**Closed by rachelmcr** 2016-02-01 18:15 UTC
Labels: comments, Notifications, [Type] Bug
