### ISSUE TITLE
Stats page not updating past day of installation

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-Android#10992] opened 2019-12-19 14:42 UTC
### Expected behavior

When navigating to the stats page, it would show the most recent days stats or pulling down to refresh would update to the most current day. 

### Actual behavior

Two user's have reported that when going to the stats page, they are not seeing any stats past Dec. 5th and pulling down to refresh did not fix it.

One user mentioned "If you uninstall and reinstall the app, the data will be displayed on the day of the reinstallation, but after that date, it will remain fixed (the next day, the date will be displayed as yesterday's date)."

### Steps to reproduce the behavior

1. Open a Jetpack connected site in the app. 
2. Navigate to Stats > Days.
3. Latest day refelected will be Dec. 5th (or the day of the most recent app re-installation since)
4. Pull down to refresh, nothing changes.

##### Tested on Galaxy Note 10+, Android 9, WPAndroid 13.7

The same user confirmed the same site doesn't replicate the issue when on their Galaxy Note 5 with Android 7.

User report with logs and details at 2542198-zen
Second report (but no follow up from user) 2544201-zen

Pinging @ScoutHarris

**Comment by planarvoid** [comment] 2019-12-20 10:41
thanks for the report @rezzap 👍 
I don't think this bug is related to the app since it's not happening to more users (and also not happening to the same user on both devices). I checked the app and couldn't reproduce it, I don't think there is anything in the app that could cause this issue. Especially on pull to refresh we just skip all the caching and directly hit the API. Is it possible there is some server-side Jetpack caching per device that's broken? It's suspicious that both the reports stopped working on December 5 so they could be related to a server change. The functionality in the app hasn't been touched since February. I also checked the logs and there is nothing broken there. 
I don't think there is much we can do on the app side if there isn't more user reports or if we can't reliably reproduce it.

**Comment by sarahfg** [comment] 2019-12-23 14:02
The user has let us know there were no server changes or plugin changes around that time. They also let us know another detail.

> When I firstly installed the app, then the date the app shows was the date it was installed. However, the next day I found the date was not changed

The user is convinced it has to do specifically with Galaxy Note 10+ . Do we have any way of testing on that particular device? Or would there be any device settings a user could enable that would break things in this way?

**Comment by designsimply** [comment] 2020-01-14 11:07
Summary of troubleshooting steps that were taken in the support request, for reference:

* Galaxy Note 10+ - stats do not update past the app install date.
* Galaxy Note 5 - stats work normally.

1. Double check that pull-to-refresh doesn't help. It doesn't.
1. Started a new Jetpack sync.
1. Update Jetpack from 7.5.3 to 8.0.
1. Delete and re-install the app.
1. Checked that both devices are using the same time and date settings.
1. Checked that the site was added to the WordPress app via the same way on both devices.
1. Confirmed there have been no new changes to the server or plugins.

@rezzap the only other troubleshooting step that comes to mind for this case, that I don't think was already tried, would be for the user to check whether the same problem happens if they switch from network to cellular data (or vice versa) or if they can check from a completely different network connection.

Aside: I noticed several lines like this in the app logs the Galaxy Note 10+ user sent in:

```
16 - [Dec-12 03:26 UTILS] ScaleType FIT_START is not supported.
17 - [Dec-12 03:26 UTILS] ScaleType FIT_START is not supported.
18 - [Dec-12 03:26 UTILS] ScaleType FIT_START is not supported.
19 - [Dec-12 03:26 UTILS] ScaleType FIT_START is not supported.
```

@planarvoid could those lines be relevant to this case? What do those lines mean?

I can't think of any device settings that would cause stats not to update. I asked in #android-dev on Slack to see if anyone has a Galaxy Note 10+ they could use to help test this case.

**Comment by designsimply** [comment] 2020-01-24 00:32
My apologies for the errant ping, planarvoid is offline for a bit! @develric can you help us understand the logs noted in the previous comment and also suggest next steps for troubleshooting this case if you can think of any?

**Comment by develric** [comment] 2020-01-27 10:15
Hi @designsimply , i tried to look a bit into this and I was not able to reproduce either. I also think the best would be to try to reproduce the issue on the same device of course, I guess we do not have any update on the Note 10+ availability on our end (right?).

Looking into the code currently I do not have any major suggestion tbh, but this said, related to the `ScaleType FIT_START is not supported.` log, that one is created in `ImageManager.applyScaleType`. 

Even if I could not find a possible direct correlation with the issue, one place we use the `FIT_START` is in `WidgetUtils.setSiteIcon` that is used in the Stats Widget. 

It seems from the logs that (at least once 😊 ) they are using the stats widget to access the stats (see `Tracked: stats_widget_tapped`). 

If not already done, I would try to suggest to uninstall and reinstall the app without enabling the stats widget and check again. I would not expect big improvements in understanding the issue but waiting to reproduce the issue on a Note 10+ device maybe it's worth a try.

**Comment by rezzap** [comment] 2020-02-07 21:53
We haven't heard back from this user since Dec. 7th 2019. I have sent a follow up to them in 2699323-zen to see if this is still an issue for them and if the suggestion to uninstall and reinstall the app without enabling the stats widget and check again helps.

Thanks both for checking on this!!

**Comment by erricgunawan** [comment] 2020-02-27 02:20
Got another similar report on 2726744-zen (translated):

> Hello, Following your email, I uninstalled the application and reinstalled ... the date is updated but since February 21, the day of this manipulation, the date is frozen at 21 ... I also found that by restarting my phone, the date in the application was updated. Please note that I have no problem with the date on my phone or any other application. 

Device Info:
WordPress - 14.1 - Version code:  826
Android device name: Samsung SM-A705FN
Site: Personal/Simple site

**Comment by erricgunawan** [comment] 2020-03-09 07:04
Another report on 2761834-zen:

> It's not that data is missing, it's that when you already have the app open it doesn't automatically refresh to the current day. You must close the app and reopen it in order for it to show the current day's site stats. Once you have reopened it, it does refresh the stats during the course of the day but will not automatically advance on the next day unless you close and reopen the app.

> I am looking at Site Stats - Daily view. No, If I drag my finger downwards to update it does not go to the current date. It only shows me the dates up to the yesterday's date. I have to close the app and reopen it to get today's stats.

> I have already reinstalled. When I switch screens and switch back it still does not show the current days information. Only when I exit the app and reload do I get the current days info. I am running the latest app, 14.2 but had the same issue with the release earlier in Feb.

Device Info:
WordPress - 14.2 - Version code: 831
Android device name: Samsung SM-N960U
Site Type: Jetpack Free Plan

**Comment by designsimply** [comment] 2020-05-02 02:00
Closing because the issue has been reviewed twice and it doesn't appear there's much we can do from our site, and asking if you would please comment and ask to re-open this issue if any more user reports come in. Thanks!

Noting the potential troubleshooting steps for this case:

* Note the type of site, app version, and device info.
* Confirm that deleting and reinstalling the app resets the latest date avail in Stats.
* If the problem persists, try restarting the device to see if that helps.
* Ask if any server-side changes have been made recently.

**Closed by designsimply** 2020-05-02 02:00 UTC
Labels: Stats, [Type] Bug
