### ISSUE TITLE
WordPress.com logins via WPAndroid not working consistently

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#15967] opened 2022-02-16 14:34 UTC
### Expected behavior

When logging into WordPress.com via the browser (e.g. on a desktop), the notification sent to the app should allow the user to log in to Calypso.

### Actual behavior

The app receives the notification, but after approving the log in, Calypso isn't logged in.

| <img src="https://user-images.githubusercontent.com/1898325/154286763-67fcc83d-02ba-49de-bc9d-f056e37c1eea.gif" alt="" width="600">  |
| - |

### Steps to reproduce the behavior

1. Go to WordPress.com
2. Log in to an account that has 2FA set up (SMS or app based)
3. The webpage will prompt the user to approve the login from the app (note: app must be previously logged into same account)
4. Open the notification received on the device
5. Tap "Approve" and expect the WordPress.com webpage to automatically log the user in

Repeat Steps 2 → 5 and about 25% of the time, the user isn't automatically logged in (the webpage doesn't respond to the approval).

This could be a Calypso issue, but it could also be an issue with the app sending the approval to the backend.

**Comment by thehenrybyrd** [comment] 2022-04-11 11:52
I tested this in 19.6, and wasn't successfully logged in 2 out of 5 times.

**Comment by guarani** [comment] 2022-04-11 20:32
Thanks for checking this, @thehenrybyrd – I appreciate it!

Sounds like it's failing 40% of the time for you, which roughly matches what I saw (failure 25% of the time).

The severity of this seems medium, since there is a semi-reliable workaround (log in again). The impact (how many users are affected) is harder to estimate. Only @thehenrybyrd and I reported the issue, so with two user reports, that might be a medium impact.
Overall, this gives a medium priority.
👋 @antonis, could I please ask you for a second opinion on the priority of this?

**Comment by antonis** [comment] 2022-04-12 08:51
Thank you for the ping @guarani 🙇 
I would agree with the Medium impact assessment 👍

**Comment by guarani** [comment] 2022-04-12 17:19
Thanks @antonis!

**Comment by ovitrif** [comment] 2022-04-22 18:41
I tried to reproduce this issue in `19.7 PreAlpha (local build from trunk)` but I couldn't manage to reproduce it during 15 attempts to login.\* 
For me it worked every time 🤷 .

During my tests I tried both possible ways to approve the:
- Tapping the `Approve` button in the push notification.
- Tapping on the notification and pressing `Approve` in the dialog that appears in the app.

I also tracked down the code call paths and found the place where the actual call to send the 2FA code to the WP.COM REST API is done:

https://github.com/wordpress-mobile/WordPress-Android/blob/23e0049b2fb31abf6614342ec966ed1b1316d138/WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java#L463-L478

During my debugging session it always reached this point... but it also always worked 🤷.

In order to avoid false positives, I also tested 5 times without breakpoints to make sure this is not working correctly because of the different timing when stepping through breakpoints.

Then I proceeded to test in `19.6 (1199)`, downloaded from the Play Store beta program, and repeated the testing steps 5 times but it also always ended up logging me in on the Web.

I'll try this again next week a few more times.

@guarani and @thehenrybyrd If you could please tests this again and copy the Application logs after it reproduces that would help us figure out if it's a problem in the app or on the server side.

To copy & share the app logs:
From `My Site` → `Me` (tap profile picture) → `Help & Support` → `Application log` → Share & email it to my `@automattic` account.

---
\* Testing Device: Samsung Galaxy S8+ (Android 9), EN, GMT+2

**Comment by guarani** [comment] 2022-04-22 19:09
> I couldn't manage to reproduce it during 15 attempts to login.*

I appreciate you checking this so thoroughly, @ovitrif! 

I tried 5 times and was unable to reproduce it. I'm not sure if there was an issue, but it's now fixed somehow, or perhaps it's some detail in the steps to reproduce that we're no longer doing.

My setup was as follows:
1. Sign up for new account in WPAndroid (I didn't set a password)
2. I logged into the account via WP.com and used the magic link in the email to authenticate 
3. I set a password and set SMS-based 2FA
4. I logged out and logged in again
5. I was asked to click the link in the sign-up email and then approve via the app each time I logged in
6. It worked 5/5 times, so I was unable to reproduce this issue

**Comment by ovitrif** [comment] 2022-04-25 08:28
> I tried 5 times and was unable to reproduce it. I'm not sure if there was an issue, but it's now fixed somehow, or perhaps it's some detail in the steps to reproduce that we're no longer doing.

Thank you @guarani for checking this again!

I'll try 5 more times today and then park it if I can't manage to repro the bug today.

@thehenrybyrd Seeing that we're struggling with reproducing this may I kindly ask you to give it a try again since you also saw the issue happening.
5 attempts should be enough to get an idea how to move forward.

If you could try to reproduces the bug during 5 tries I'd be very grateful, and if it does happen please share the app logs 🙏 !

**Comment by ovitrif** [comment] 2022-04-25 10:26
I tried 10 more times to repro this: 4 times with my a8c account, 6 times with a brand new account set-up by following the exact steps [here](https://github.com/wordpress-mobile/WordPress-Android/issues/15967#issuecomment-1106785558).

Since I still couldn't repro it I'm going to plan unassigning myself from this issue, but for now I'm waiting for feedback from @thehenrybyrd, hopefully we can get some more clear info backed by app logs for this issue 🤞🏽

**Comment by guarani** [comment] 2022-04-27 15:34
Thanks for the exhaustive testing, @ovitrif! ❤️

**Comment by thehenrybyrd** [comment] 2022-05-03 13:59
@ovitrif I was also unable to repro in 19.8-rc-1, after 8 tries on 2 different accounts! So I guess the issue has been fixed somewhere :D 
Thanks for taking a look at this! I'll close the issue for now.

**Closed as completed by thehenrybyrd** 2022-05-03 13:59 UTC
Labels: [Type] Bug, [Pri] Medium, Login

**Comment by ovitrif** [comment] 2022-05-03 14:01
Thank you @thehenrybyrd for following up on this 🙇‍♂️

**Comment by guarani** [comment] 2022-05-04 14:52
Thank you folks for all the effort on this!
