### ISSUE TITLE
Crash report - Sharing to WP- IllegalStateException: Can't compress a recycled bitmap

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5823] opened 2017-05-02 16:13 UTC
```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:318)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
Caused by java.lang.IllegalStateException: Can't compress a recycled bitmap
       at android.os.Parcel.readException(Parcel.java:1701)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
       at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
       at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1151)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:988)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:708)
       at org.wordpress.android.util.MediaUtils.downloadExternalMedia(MediaUtils.java:228)
       at org.wordpress.android.ui.media.MediaBrowserActivity$6.doInBackground(MediaBrowserActivity.java:811)
       at org.wordpress.android.ui.media.MediaBrowserActivity$6.doInBackground(MediaBrowserActivity.java:807)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by daniloercoli** [comment] 2017-05-02 16:30
Do we have more info on the issue? Android version, device?

**Comment by daniloercoli** [comment] 2017-05-03 07:57
Unfortunately it seems that i'm not able to reproduce this issue.
The crash in `MediaUtils.downloadExternalMedia` happens when it's called from `MediaBrowserActivity.fetchMedia`, that in order is called when a media is shared to WordPress->Media Library, and when a media is added to the library.

I tried by sharing pictures to WordPress from:
- Google Drive (reached the line `228` and picture is loaded fine)
- Telegram (Not stored in gallery, but didn't reach line `228`)
- FB didn't reach line `228`

Tried by adding pictures to the WP Media Library, and didn't find any problem. 

I can add a catch `IllegalStateException` statement at ` org.wordpress.android.util.MediaUtils.downloadExternalMedia(MediaUtils.java:228) ` and also keep tracking of the error in Crashlytics.

**Comment by mzorz** [comment] 2017-05-04 21:41
Leaving this open as we still need more information - hoping to get that from your PR @daniloercoli ! thank you

**Comment by hypest** [comment] 2018-01-09 11:28
Here's an instance of the caught exception with the specific error ("can't compress recycled image") https://fabric.io/automattic/android/apps/org.wordpress.android/issues/597e839cbe077a4dcc5d0076/sessions/5A3422B0004A00015D84CA53334ABFEE_294e790ae2eb11e7b23c56847afe9799_0_v2

**Comment by daniloercoli** [comment] 2018-01-10 09:30
Uhh, it seems that the logging we added is reporting back some interesting info:
https://fabric.io/automattic/android/apps/org.wordpress.android/issues/597e839cbe077a4dcc5d0076/sessions/latest

Also `EditPostActivity` has some problem when sharing media to a new Post....

**Comment by daniloercoli** [comment] 2018-01-10 19:30
I've tried to replicate this issue in so many different scenarios with no luck. (Tried with Android 5 and 7 with sharing to WP from G+, Google photos, and other apps).
I'm going to remove me from the list of assignees.

**Comment by rachelmcr** [comment] 2019-01-03 13:01
Closing as we haven't seen this crash at all in the past 90 days.

**Closed by rachelmcr** 2019-01-03 13:01 UTC
Labels: [Pri] High, [Type] Crash
