### ISSUE TITLE
Suggestion: Retain the chat screen when one clicks "Contact us"

### ISSUE THREAD

**Issue by arunsathiya** [wordpress-mobile/WordPress-Android#7036] opened 2017-12-24 11:50 UTC
The newly introduced in-app support, [as mentioned on this WordPress.com blog post](https://en.blog.wordpress.com/2017/12/13/manage-your-blog-on-mobile/), does not retain the chat screen if one closes it.

**Steps to reproduce**: Create a live chat ticket by using the **_Contact Us_** button. Close it, and click on **_Contact Us_** button again, it creates a whole new live chat ticket, asking one to enter the message, name and email ID afresh. **The previous discussion is completely gone, and the user cannot see it again.**

**Expectation**: The app shows the live chat screen immediately when one clicks on Contact Us button.

**Comment by arunsathiya** [comment] 2017-12-24 11:55
The user has the worst experience when they clear the WordPress Android app's data/re-install the WordPress Android app, and open the **Contact Us** section. The user would see that the whole previous chat is gone, and has to create a new live chat ticket again.

My suggestion is that, it would be cool to have a WordPress.com-like live chat workflow (retain the previous chat messages, whatsoever)

**Comment by rachelmcr** [comment] 2018-01-23 17:22
Could you share the exact steps you used (exactly what you selected at each stage to submit and close the ticket)? I couldn't reproduce the original issue — these are the steps I tried:

1. Open the Me tab in the app and select "Help & Support."
2. Select "Contact us."
3. Enter a brief message in the first field ("How can we help?") and my name and email address in the other fields.
4. Tap the "Send" button (the paper airplane icon) in the top right.
5. On the "Suggestions" screen, select "Send anyway."
6. Wait for the message to finish sending and the success toast message to appear on screen.
7. Select "Contact us."

Result: I saw the open ticket in the app with my original message and a reply from support.

(Note that once the conversation ends and the issue's resolution is accepted, a new, separate ticket is created. This is how the support tool used in the app works and a true live chat experience would require using a different support tool altogether — something that may happen in the long term but isn't on the roadmap for now.)

I'll close the issue as it seems everything is working as intended, but we can reopen if there's a bug here.

**Closed by rachelmcr** 2018-01-23 17:22 UTC
