### ISSUE TITLE
Audio files in Reader not playing

### ISSUE THREAD

**Issue by RealCarFax** [wordpress-mobile/WordPress-Android#9616] opened 2019-04-13 18:08 UTC
### Expected behavior
When you tap on play on an audio file in a post in the Reader, the audio file should begin to play (as it does via the iOS app).

### Actual behavior
When you tap play, there's no response. The audio looks like it has loaded but it doesn't start to play.

### Steps to reproduce the behavior
Open Reader
Search for ziyou.life
Tap on Sites
Tap on the ziyou.life site titled "sports health on the go"
Tap on the post titled "Audio Post" published 2019/04/13
Tap on the play button for the audio file within this post

##### Tested on [device], Android [version]
Galaxy S10+, Android Pie (9)

**Comment by designsimply** [comment] 2019-04-19 02:27
Tested and confirmed using WPAndroid alpha-165 (12.2 alpha) on Pixel 3 Android 9 that I cannot play audio in a post in the Reader.

<img src="https://user-images.githubusercontent.com/1119271/56401886-50739500-6218-11e9-8638-32e945c92902.png" width="270" alt="Screenshot_20190418-201336">

**Comment by designsimply** [comment] 2019-04-25 19:03
Raised this in priority because it's limiting people from listening to audio via the Reader in the app.

**Comment by nbradbury** [comment] 2019-04-25 19:33
@designsimply I just took a look at this but the site mentioned above (ziyou.life) doesn't show any posts. So I tried with an audio post on my site and it works fine. In my case the format is MP3 - what format is the audio in your test post?

**Comment by suyogyashukla** [comment] 2019-04-25 20:02
Just letting folks know that I talked to @elibud about this and she told that folks are looking into this and this should be fixed soon. However, because we have code freezes it won’t get to the users until approximately one month if we manage to figure it out so we'd need to set our user's expectations accordingly.

**Comment by designsimply** [comment] 2019-04-25 20:15
@nbradbury yep, mp3, which you noted in your update above. 👍

@suyogyashukla sounds good! Please also note that when you hear an approx. timeline like that you should not make promises for any specific ETA and what you can say is that we are aware of the problem and that it's likely it would be a month minimum before the fix could show up in a future release. This is because you never know what might interrupt or if an issue will be harder to fix than it first appears. 🙂

**Closed** 2019-04-25 21:38 UTC
Labels: Reader, [Type] Bug
