### ISSUE TITLE
[GlobalStep] [Android] Incorrect button format is displayed on readers tab when viewed on devices.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-Android#12002] opened 2020-05-21 14:43 UTC
**Environment:**
Android: Samsung Galaxy s9 (v10), Samsung Galaxy S7 (v8), Samsung Galaxy Tab A (v9).
Build WPAndroid [version]: v14.9

**Steps To Reproduce:**
 1. Install and launch the application.
 2. Tap on "Log In".
 3. Log in to the app using valid credentials.
 4. Go to My site and go to Blog Posts section
 5. Go to Published tab and open a post with coloured buttons format.
 6. Note that in View it displays the formatted coloured buttons.
 7. Now go to Reader tab, (Assuming your site is in "followed sites" or else Followed Sites> Manage> Enter URL)
 8. Observe that it fails to display the post with proper coloured buttons format.

 **Actual Result:**
Incorrect button format is displayed on readers tab when viewed on devices.

 **Expected Result:**
On readers tab, button format should be displayed properly on readers tab when viewed on devices.

**Attachment:**
[#2290.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4663054/2290.zip)

**Comment by designsimply** [comment] 2020-05-22 19:07
Duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/11679.

**Closed by designsimply** 2020-05-22 19:07 UTC
Labels: Reader, [Status] Duplicate, [Type] Bug
