### ISSUE TITLE
Resources$NotFoundException: Resource ID #0x7f080221

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13304] opened 2020-11-06 08:25 UTC
**Sentry Url**: https://sentry.io/share/issue/4699576189b8491ebaee24020cf64987/
**User Count**: 1
**Count**: 1055
**First Release**: org.wordpress.android@15.4-rc-1+897
**First Seen**: 2020-07-29T09:13:23.676000Z
**Last Seen**: 2020-11-06T01:52:39Z
**24 Hours**: 10
**30 Days**: 513

```
Resources$NotFoundException: Resource ID #0x7f080221
     at org.wordpress.android.ui.accounts.login.LoginProloguePageFragment.onViewCreated(LoginProloguePageFragment.kt:56)
...
(60 additional frame(s) were not displayed)
```

**Comment by loremattei** [comment] 2020-11-06 08:28
Sentry reports this happens to only 1 user, but this is misleading. It happens to users who are not logged in, so they have user ID == 0 and Sentry counts them as a single user. 
Given the number of occurrences, I think it's worth more investigation.

**Comment by diegoreymendez** [comment] 2020-11-06 14:21
Can I ask you to look into this @renanferrari ?  I noticed you edited some of the code around the area this crash that's coming up in the crash log, so you may be better positioned to evaluate this issue.

I'm marking this as high priority ([high-severity, medium-impact](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/docs/issue-triage.md#prioritization)).  Feel free to change the priority if it feels off.

**Comment by renanferrari** [comment] 2020-11-06 20:21
@diegoreymendez Thanks for the ping! I'll try to look into this sometime next week.

**Comment by renanferrari** [comment] 2020-11-11 22:03
I spent some time looking into this and while I couldn't reproduce the issue, I'm pretty sure this bug should not occur in version 16.1, since [the code in which this crash used to happen](https://github.com/wordpress-mobile/WordPress-Android/blob/fea2192672de31cac633a7c840abfdde7d836cca/WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginProloguePageFragment.kt#L56) has been updated for [the new Prologue screen](https://github.com/wordpress-mobile/WordPress-Android/pull/13094). So we should probably wait and see if similar issues happen in the new version.

**Comment by designsimply** [comment] 2020-11-29 21:31
I checked the Tags view for this crash in Sentry and also searched for the issue ID in Sentry Discover found this crash is no longer happening in 16.1 as you mentioned @renanferrari—thank you for the tip! Closing.

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1813036460+version%3A16.1%2A&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/100554041-60a28180-324f-11eb-93e4-36083a8ab5dc.png)</a>

**Closed as completed by designsimply** 2020-11-29 21:31 UTC
Labels: [Pri] High, [Type] Crash, Login
