### ISSUE TITLE
Featured images can't be added or updated in the post settings

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5320] opened 2017-03-02 20:41 UTC
I'm pretty sure this is a regression.

* Start a new post.
* Go to post settings.
* Select a featured image: nothing happens in the post settings when the media picker comes back.

**Comment by davoraltman** [comment] 2017-03-02 21:01
Just reproduced this on Assus Zenfone 3 running the alpha-37 version.

**Comment by aforcier** [comment] 2017-03-02 22:05
Definitely a regression, it was caused by the media refactor in https://github.com/wordpress-mobile/WordPress-Android/pull/5283.

**Comment by oguzkocer** [comment] 2017-03-03 09:02
Fixed in #5321

**Closed by oguzkocer** 2017-03-03 09:02 UTC
Labels: fluxc-integration, Posting/Editing
