### ISSUE TITLE
Editor content is cleared on device rotation

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#8399] opened 2018-10-05 15:30 UTC
### Expected behavior
The content of the editor is persisted across configuration changes.

### Actual behavior
The content of the editor is sometimes lost during a configuration change (and the empty content is autosaved).

### Steps to reproduce the behavior
1. Open a post in the editor
2. Keep rotating the device until the content disappears

##### Tested on [device], Android [version]
Pixel 2, Android 9

**Comment by elibud** [comment] 2019-02-18 17:04
@mzorz can you check that this does not happen in Gutenberg mobile please?

**Comment by mzorz** [comment] 2019-02-18 17:52
I have tried this with a simple post with title and content set, on both Aztec and Gutenberg on latest `develop` and can't reproduce anymore. Closing.

**Closed by mzorz** 2019-02-18 17:52 UTC
Labels: Aztec, [Pri] High, [Type] Bug
