### ISSUE TITLE
Change site icon for Self hosted sites

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-Android#9179] opened 2019-02-05 18:35 UTC
I received a request in 1740092-zen from a user who was trying to change the site icon for their self hosted site.  Right now you can change the site icon for WordPress.com sites and jetpack sites, but self hosted sites can not be changed.  In Android if you click on the site icon for a self hosted site you get an error that says you don't have the permissions to change the site icon.
Can we either make it so that the site icon can not be tapped on if the site is self hosted (which is how iOS does this currently) or make it so that the site icon can be changed for self hosted sites?

To see the error, go to My Sites for a self hosted non jetpack site and tap on the site icon, you should see this:
<img src="https://charlietestsiteblog.files.wordpress.com/2019/02/screenshot_2019-02-05-11-32-41.png" />

**Comment by rachelmcr** [comment] 2019-02-05 18:43
Thanks for the report! That message is expected if the user doesn't have permissions to edit the site icon, but it doesn't make sense in this context. @0nko I see you added the site icon editing in https://github.com/wordpress-mobile/WordPress-Android/pull/7722 — was it expected to work on self-hosted sites at that point? (Just want to know if this is a regression from the original behavior.)

**Comment by 0nko** [comment] 2019-02-06 22:41
Thanks looking into this @charliescheer and @rachelmcr. I've checked and we're only testing for the capabilities required to upload and change the icon. I didn't know the self-hosted sites were unsupported. We can simple add another condition for self-hosted sites without Jetpack and show a different message.

**Comment by designsimply** [comment] 2019-04-09 16:30
Tested and confirmed it's still not possible to set a site icon for a self-hosted site in WPAndroid alpha-162 (12.2 alpha) on Pixel 3 Android 9.

<img src="https://user-images.githubusercontent.com/1119271/55817566-079e3c80-5ab2-11e9-986a-6436e7cf0f72.png" width="270" alt="Screenshot_20190409-102517">
<p style="clear:both;"><sub>Tested with `tasteless-petrel.jurassic.ninja` running WordPress 5.1.1. Found while beta testing WPAndroid 12.2.</sub></p>

**Comment by rezzap** [comment] 2020-05-05 19:55
Another user in #2893189-zen reported this and was quite confused by the error messaging present. It should at least be clear that this isn't possible on the type of site and not that they don't have permission to do so.

**Comment by develric** [comment] 2020-07-27 13:40
I'm looking into this one, didn't fully go into the path for what is would be needed to support the setting of an icon in pure self-hosted but that seems to require adding some capability at API/DB level. This said I agree we should align both Android/iOS versions but I would be more keen toward giving a message to the user (like "Setting an icon is not currently supported for pure self-hosted site without JetPack"...or something better 😊!) than disabling the tap on site icon as is currently in iOS.

@frosty , @osullivanchris wdyt?

**Comment by osullivanchris** [comment] 2020-07-27 15:11
@develric @rezzap I agree, it makes more sense to tell the user the specific reason that they cannot take the action. 

On iOS we actually went through this process with 'site title' for non admins recently. We allowed non admins to see the same UI, but without input, and a message telling them they cannot make the change.

Here I think it would be fine to keep the dialog, but change the messaging to make it specific to the error. 

One last question, just to test the assumption...is it definitely not possible for self-hosted sites to set an icon? Like this behaviour is a technical limitation / deliberate choice by us? Just want to check that it is a necessary error message :)

**Comment by develric** [comment] 2020-07-27 16:07
Hey @osullivanchris , thanks for replying 🙇‍♂️!

> Here I think it would be fine to keep the dialog, but change the messaging to make it specific to the error.

Agree 👍! Could something like "Setting an icon is not currently supported without JetPack." work for you?

> is it definitely not possible for self-hosted sites to set an icon?

I'm not an expert here and didn't go deep the full path but for what I get from the [XML-RPC documentation](https://codex.wordpress.org/XML-RPC_WordPress_API) (the API we use for pure self-hosted site) we currently do not natively support methods to allow the site icon to be set (also maybe we should extend the `wp.getUsersBlogs` method to include a site icon url; something similar overall to the `sites/*/settings`REST API we use for .COM and JP). 

Something doable but not sure about the effort. But at least giving meaningful message among the platforms seems reasonable step here, wdyt?

**Comment by osullivanchris** [comment] 2020-07-29 11:52
> But at least giving meaningful message among the platforms seems reasonable step here, wdyt?

Yeah of course, sounds good. I just wanted to check that these constraints were definite and not just ones we were assuming. But it makes sense.

> Agree 👍! Could something like "Setting an icon is not currently supported without JetPack." work for you?

That sounds roughly correct. I don't know the perfect way to word it so I'm tagging editorial for a review here :)

**Comment by michelleweber** [comment] 2020-07-29 14:42
I'm wondering if we spin it, so it's more like an instruction for how to solve this problem: "Editing site icons on self-hosted WordPress sites requires the Jetpack plugin."

**Comment by osullivanchris** [comment] 2020-07-29 14:52
thanks @michelleweber that sounds good to me!

**Comment by thehenrybyrd** [comment] 2021-06-02 10:29
Looks like this is resolved by https://github.com/wordpress-mobile/WordPress-Android/pull/12555 above, I'll close the issue for now.

**Closed by thehenrybyrd** 2021-06-02 10:29 UTC
Labels: Site Settings, [Pri] Low, [Status] Needs Copy Review, [Type] Broken Window, [Type] Enhancement
