### ISSUE TITLE
ApplicationNotResponding: PostSqlUtils.insertOrUpdateLocalRevision

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#16453] opened 2022-05-02 09:31 UTC
**Sentry Url**: https://sentry.io/share/issue/27062676325348d884532ed0f2c619c4/
**User Count**: 674
**Count**: 1895
**First Release**: 19.5-rc-1
**First Seen**: 2022-03-23T18:05:06.486000Z
**Last Seen**: 2022-05-02T09:25:45Z
**24 Hours**: 85
**30 Days**: 1888

```
ApplicationNotResponding: Application Not Responding for at least 5000 ms.
     at org.wordpress.android.fluxc.persistence.PostSqlUtils.insertOrUpdateLocalRevision(PostSqlUtils.java:332)
     at org.wordpress.android.fluxc.store.PostStore.setLocalRevision(PostStore.java:1223)
     at org.wordpress.android.viewmodel.history.HistoryViewModel.saveRevisionsToLocalDB(HistoryViewModel.kt:228)
     at org.wordpress.android.viewmodel.history.HistoryViewModel.onRevisionsFetched(HistoryViewModel.kt:252)
...
(11 additional frame(s) were not displayed)
```

**Comment by mchowning** [comment] 2022-05-04 19:38
Looking at Sentry, this crash appears to only be occurring with older, lower-powered phones. In fact, there is not a single report of the crash on a phone running Android 12. 

Unfortuanately, there also is not a single report of this issue before the 19.5 release, which points to there being a regression. FWIW, I spent a bit of time searching around to see if maybe Sentry had just grouped crashes from earlier releases under a different issue, but I didn't find any other matches. 

The version of FluxC in the app was [bumped](https://github.com/wordpress-mobile/WordPress-Android/commit/a48da3bdee365955946096e41859f698c665cabc) from 1.37 to [1.38](https://github.com/wordpress-mobile/WordPress-FluxC-Android/releases/tag/1.38.0) in the 19.5 release, and the only change that looks even remotely related to the code in this crash was in a change where @renanferrari  added a method to that class. It doesn't look to me like those changes could cause the ANR, but since this is the most recent change to the class, and the timing is right, let me ask if you'd take a look at this Sentry report and see if you see any possible culprits @renanferrari . 🙇

**Comment by mchowning** [comment] 2022-05-04 19:46
### Issue Priority

The number of affected users is low and it is confined to older devices, so I feel **the impact is low**. Although there is technically a workaround for an issue like this (just wait long enough and the app should eventually respond), I feel like a **high severity** is fitting since many users may give up when the OS pops up the dialog saying the app has stopped responding and asks the user if they want to wait or kill the app. 

For those reasons, a **medium priority** looks right to me. Feel free to adjust that if you disagree though.

**Comment by ravishanker** [comment] 2022-09-27 06:25
This seems to be happening on older versions (20.7 and below) and low power devices.  The last 24 hours count is on the decline (85 in May and 64 now) while the last 30 days count is consistent (1.9K).  

Should we close this for now?

**Comment by ravishanker** [comment] 2022-09-30 01:41
I'm closing this for now.  We can always open another issue if this resurface on newer versions

**Closed as completed by ravishanker** 2022-09-30 01:41 UTC
Labels: [Pri] Medium, Posting/Editing, [Type] Crash, [Type] ANR
