### ISSUE TITLE
Crash report 9.7, 9.8, 9.9, and 10.0: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#7790] opened 2018-05-22 13:38 UTC
```
Fatal Exception: java.lang.IndexOutOfBoundsException: 476, -472
       at android.text.PackedIntVector.deleteAt(PackedIntVector.java:218)
       at android.text.DynamicLayout.reflow(DynamicLayout.java:311)
       at android.text.DynamicLayout.-wrap0(DynamicLayout.java)
       at android.text.DynamicLayout$ChangeWatcher.reflow(DynamicLayout.java:662)
       at android.text.DynamicLayout$ChangeWatcher.onSpanChanged(DynamicLayout.java:691)
       at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1252)
       at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:656)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:586)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:849)
       at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:198)
       at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:348)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:91)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6577)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

internal ref. `59878536be077a4dccb3fce8`

**Comment by khaykov** [comment] 2018-10-02 07:29
I did a lot of testing with this issue, and I can't find anything specific that triggers it.
What we know:

- The crash happens in Aztec Editor.
- Post content before crash and spans in it are quite random.
- The crash happens along the UPDATE POST action.
- The crash ONLY happens on Samsung and Huawei devices running Android 8 and 7.

The closest thing to Samsung or Huawei device that I have is Genymotion, and I can't reproduce the issue there. Maybe someone with affected device can take on this one?

**Comment by planarvoid** [comment] 2018-10-10 09:43
This might be related - https://github.com/wordpress-mobile/AztecEditor-Android/issues/651

**Comment by marecar3** [comment] 2019-01-10 16:48
Closing this one in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/8827

**Closed by marecar3** 2019-01-10 16:48 UTC
Labels: [Pri] High, [Type] Crash
