### ISSUE TITLE
Crash while selecting Video from downloads folder

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#12527] opened 2020-07-27 09:04 UTC
I don't think this crash is critical, it's something I've noticed while testing another PR. It might be specific to the folder or to the file type. The content ID for this file was `content://com.android.providers.downloads.documents/document/107` which doesn't point to a video but to a document. However, I think it's worth it to catch this exception. The `downloadExternalMedia` method can return null and we're calling directly `downloadExternalMedia(context, uri).getPath()` so it will always crash if the value is `null`

Steps to reproduce: 
- Go to Media library
- Select "Choose video from device"
- Select an mp4 downloaded video from your downloads folder
- See that the app crashes with the following exception

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
        at org.wordpress.android.util.MediaUtils.getDocumentProviderPathKitkatOrHigher(MediaUtils.java:469)
        at org.wordpress.android.util.MediaUtils.getPath(MediaUtils.java:412)
        at org.wordpress.android.util.MediaUtils.getRealPathFromURI(MediaUtils.java:391)
        at org.wordpress.android.util.analytics.AnalyticsUtils.getMediaProperties(AnalyticsUtils.java:486)
        at org.wordpress.android.ui.media.MediaBrowserActivity.trackAddMediaFromDeviceEvents(MediaBrowserActivity.java:537)
        at org.wordpress.android.ui.media.MediaBrowserActivity.getMediaFromDeviceAndTrack(MediaBrowserActivity.java:455)
        at org.wordpress.android.ui.media.MediaBrowserActivity.onActivityResult(MediaBrowserActivity.java:477)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by designsimply** [comment] 2021-01-22 17:40
Is this the correct matching crash report from Sentry? https://sentry.io/share/issue/d154dcf5a9b3459a9d3051e4a3effb3d/

**Comment by mkevins** [comment] 2022-03-04 08:54
I tried to reproduce this by choosing a video from the Downloads folder (on a Pixel 3a w/ Android 12), but the video uploaded as expected. Is there a set of preconditions that are necessary for reproducing this, or is it perhaps something that doesn't happen frequently? I tried a few different times, but each time it uploaded without issue. :man_shrugging:

**Comment by ravishanker** [comment] 2022-03-18 00:23
I've tried this but couldn't reproduce this issue.  It seems like, it was specific instance.  Probably, no longer an issue given recent upgrade to SDK 11.  I'm going to close this issue.

**Closed by ravishanker** 2022-03-18 00:23 UTC
Labels: [Pri] Low, Media, [Type] Crash
