### ISSUE TITLE
Notify the user clearly when they are out of storage to upload media

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#7103] opened 2018-01-15 23:49 UTC
Currently when the user has run out of storage in their plan, we simply show an error message.

Suggestion from @sarahblackstock:

> The error does not directly tell them they’re out of space. Would it be possible to make it do that? Something that tells them they’re at 3 out of 3GB or directs them to buy a plan to add more could help them understand what the problem is right away.

cc @elibud

**Comment by kwonye** [comment] 2018-01-15 23:49
iOS issue here: https://github.com/wordpress-mobile/WordPress-iOS/issues/8450

**Comment by elibud** [comment] 2019-09-04 20:36
@yaelirub what do you think about adding this issue across both platforms to the upcoming media improvements?

**Comment by yaelirub** [comment] 2019-09-05 23:30
@elibud, I think thats a great idea! I will add this to the board once created.

**Comment by designsimply** [comment] 2020-09-08 02:54
Tested and confirmed this is still an issue in WPAndroid 15.6 beta. ([1m14s](https://cloudup.com/cNkpDhGWPHh))

When I try to upload media on a site without enough remaining storage space from the Media screen, I see the following notice but it is small and could be easy to miss especially on a screen with a lot going on ("Upload Failed" on the image itself is more prominent and a full screen of images could be distracting in and of itself).

> 1 file not uploaded
> Storage quota exceeded

<img src="https://user-images.githubusercontent.com/1119271/92428258-7407ea00-f143-11ea-8a9d-d825c1fc163d.png" width="270" alt="Screenshot_20200907-204343">
<p style="clear:both;"><sup>Tested with WPAndroid 15.6-rc-1 on Pixel 3 Android 10.</sup></p>

When I try to upload media on a site without enough remaining storage space from the editor, I see a different message that doesn't mention storage at all.

> Failed to insert media.
> Please tap for options.

<img src="https://user-images.githubusercontent.com/1119271/92428247-6fdbcc80-f143-11ea-9d12-10e29756da0d.png" width="270" alt="Screenshot_20200907-204409">
<p style="clear:both;"><sup>Tested with WPAndroid 15.6-rc-1 on Pixel 3 Android 10.</sup></p>

@mattmiklic can you assign someone from the design team to help us improve these error screens, including the copy by reaching out to the Editorial team if needed?

**Comment by elibud** [comment] 2020-09-08 13:16
@frosty @planarvoid can we roll this one into the Media Picker improvements?

**Comment by planarvoid** [comment] 2020-09-08 14:53
hey @develric 👋 , I'm pinging you since you worked on the improved error codes in the dialogs. Could we change the message in the failed block or does this work need to be done in the Gutenberg repo? 

For the other issue (the snackbar not being too clear) - this could definitely be fixed but we'd need a designer input (let's see what @mattmiklic says)

**Comment by develric** [comment] 2020-09-08 15:28
Hi there 👋!
I understand there are 2 issues:
1. In the Media Library the snackbar is not clear enough: I agree with @planarvoid we better get a design input here.
2. In the GB blocks we want to change the message in the media overlay to be more clear for the user: there is still some magic for me in the glue code between the app and GB but AFAIU we cannot currently change runtime that message directly in the WP app. For completeness on the current status, in #12672  we added the error message in the dialog shown when the user taps for options (as guided by the `Please tap for options` CTA in the image overlay)

<p align="center">
  <img width="300" src=https://user-images.githubusercontent.com/47797566/92495442-319fe500-f1f7-11ea-9bac-71a4654a6b52.png>
</p>

but changing the overlay message directly can probably be more crystal clear (pinging @maxme in case I'm missing something on how to change that overlay message).

**Comment by mattmiklic** [comment] 2020-09-08 22:56
> @mattmiklic can you assign someone from the design team to help us improve these error screens

I've pinged @SylvesterWilmott to see if he can take a look at this.

**Comment by maxme** [comment] 2020-09-09 16:30
> there is still some magic for me in the glue code between the app and GB but AFAIU we cannot currently change runtime that message directly in the WP app.

What is the blocker here? Could we send the error message (or error code) from the app in the event that signals the block editor the upload failed?

**Comment by maxme** [comment] 2020-09-09 17:02
I just checked in the glue code, we would need to update a callback (and its callers) and add something like `String causeOfFailure` to the parameters:

https://github.com/WordPress/gutenberg/blob/master/packages/react-native-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/DeferredEventEmitter.java#L121-L123

Then we could get that `causeOfFailure` in the JS code here:

https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/media-upload-progress/index.native.js#L86-L91

And replace `retryMessage` in the render function with that `causeOfFailure`.

**Comment by develric** [comment] 2020-09-09 17:21
Thanks for checking this and the details @maxme  , AFAIU it doesn't seem too much GB work (at least for a GB pro dev 😄 ) so I would say that seems the way to go in case this is the direction the design will confirm 🙇

**Comment by SylvesterWilmott** [comment] 2020-09-10 15:08
>When I try to upload media on a site without enough remaining storage space from the Media screen, I see the following notice but it is small and could be easy to miss especially on a screen with a lot going on

I believe for dark themes, snackbars are intended to be a light colour for this reason [[From Material Guidelines](https://lh3.googleusercontent.com/Ey82bBeAAmuo-9NgcGIYqM9KyuXd37MHU1RruzbatBbe8oqVEjFyiNBM7WA6XDNg08QavD5DSalm8Kl28bsDwN9PNUcynDIO4XUOSg=w1064-v0)]. I think a snackbar is a good enough component to communicate that storage is full. The error in the editor may benefit from a copy change or we can simply display the snackbar in the editor as well.

We might also consider messaging more along the lines of "Not enough available site storage". Saying that storage is full is inaccurate in this scenario since I may be trying to upload a 1GB file with 0.9GB of storage remaining.

**Comment by designsimply** [comment] 2021-01-04 23:34
@develric would it be possible to show the "Not enough available site storage" error immediately after you attempt to add an image in the editor that exceeds the storage quota? Currently, the error is only shown if you tap the image after an image preview appears with a generic error "Failed to insert media" overlaid on top of it. ([2m27s](https://cloudup.com/cxNTv8TRiyc))

<img src="https://user-images.githubusercontent.com/1119271/103589803-7e47b400-4ea9-11eb-904a-c74be81a2657.png" width="270" alt="image">
<sup>Tested with WPAndroid 16.4-rc-3 on Pixel 3 Android 11 using gotravelrewards.blog logged in as testuser0313.</sup>

Note: it's extra confusing that the image appears in the block below the error as if it uploaded even though it wasn't technically uploaded. This must have been done for speed (which is good) but it's confusing in this case unfortunately.

**Comment by develric** [comment] 2021-01-06 23:09
Hey @designsimply 👋 . I think this and [this other one](https://github.com/wordpress-mobile/WordPress-Android/issues/13353#issuecomment-749823699) are pretty related. 

Re making more readily clear to the user what happened, there was this comment [here](https://github.com/wordpress-mobile/WordPress-Android/issues/7103#issuecomment-689695617) about changes needed in order to show the error message directly into the image overlay. AFAIU from [here](https://github.com/wordpress-mobile/WordPress-Android/issues/7103#issuecomment-690354399) the current direction would be to not touch the overlay but add a snackbar in the Editor showing the message that currently is in the dialog after tapping (where it was hidden one more step from the user). I'm not particularly in favor to one direction or the other (or doing both things 😄  ) anyway I was thinking to look into it more next week (also @planarvoid is coming back from AFK so maybe can add his contribution).

Re the fact that image appears in the block even if the upload failed, I do not have the full picture (play on words unintentional 😄  ), but I can imagine the rationale could have been that you actually have inserted the image in the local draft of the post (since the image was from your device) but the app failed to upload (sync) it to the server. This said, this doesn't mean much since we know that often what it can make sense from a tech point of view is not great for a user point of view 😬 . Maybe we can consider to review the overlay message from `Failed to insert media` to something like `Failed to upload media`? wdyt? (I still think that maybe changing the overlay to reflect the actual error that happened could make sense though 🤔  )

**Comment by designsimply** [comment] 2021-01-13 23:03
> rationale could have been that you actually have inserted the image in the local draft of the post (since the image was from your device) but the app failed to upload (sync) it to the server

This makes sense to me. It's less important than a clear/understandable communication of the error to the user.

+1 for a better overlay message for this specific case!

**Closed** 2021-01-19 14:40 UTC
Labels: Media, Needs Design, [Type] Enhancement
