### ISSUE TITLE
Legacy editor doesn't go out of full screen when hardware back button is pressed

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#2528] opened 2015-04-14 14:52 UTC
When you're writing a post and press the *hardware back button* to get out of full screen mode, it brings you back to the previous page. If you have "Use virtual keyboard for text input" in the emulator, it works as expected: https://cloudup.com/ixIdTcFUPQ7

**Comment by rachelmcr** [comment] 2015-12-10 14:01
I haven't been able to re-test this issue yet, but it would be helpful to know how many users it potentially affects. Related: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/180

**Comment by oguzkocer** [comment] 2015-12-10 16:21
@rachelmcr I think this was only happening in the emulators and not in the actual devices. I just tested it in my S6 and I couldn't replicate it. Could you test it as well and if you can't reproduce it we can just close it. Thanks!

**Comment by rachelmcr** [comment] 2015-12-10 16:26
Ah ok, I knew the original issue was in the emulator but I misunderstood and thought it could also affect some actual devices. I can't reproduce it with my Nexus 9 either so I'm closing the issue. Thanks for your help!

**Closed by rachelmcr** 2015-12-10 16:26 UTC
Labels: posting/editing, [Type] Bug
