### ISSUE TITLE
Back button doesn't work on MediaGalleryActivity

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1853] opened 2014-09-11 15:57 UTC
... when "Don't keep activities" is enabled (When EditPostContentFragment is recreated, MediaGalleryActivity is re-launched).

**Comment by rachelmcr** [comment] 2015-12-03 16:01
I couldn't reproduce any issues with the back button on MediaGalleryActivity, likely due to other changes (i.e. removing EditPostContentFragment). Tested in beta 4.8-rc-3 with "Don't keep activities" enabled.

Closing as resolved, but please reopen if I missed something in my testing.

**Closed by rachelmcr** 2015-12-03 16:01 UTC
Labels: Media, [Type] Bug
