### ISSUE TITLE
Stats: 'Enable Site Stats' displays when logged into non-connected account

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#18485] opened 2023-05-22 16:23 UTC
### Expected behavior

When a site has Jetpack installed, but it's connected to a different WordPress.com account than the one being accessed through the app, the 'Enable Site Stats' button is unusable. As such, I would expect the button to either be inaccessible or to display a helpful error message when tapped.

### Actual behavior

The button remains accessible through the Stats menu and tapping on the button produces an unhelpful `unable to activate site stats` error. This resulted in confusion in 6298399-zd-woothemes.

### Steps to reproduce the behavior

1. Log into the Jetpack app with an initial account, which we'll refer to as `account1`.
2. Install the Jetpack plugin on a self-hosted site to connect it to a second WordPress.com account, `account2`.
3. In the app, under `account1`, go through the steps to log into a self-hosted WordPress site using the credentials for the site from step 2.
4. After logging in, navigate to the app's Stats section.
5. Observe the 'Enable Site Stats' button and tap it.

##### Tested on Pixel 6, Android 13, JPAndroid 22.4-rc-1

**Comment by irfano** [comment] 2024-03-31 14:27
Duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/8607

**Closed as not planned by irfano** 2024-03-31 14:27 UTC
Labels: [Type] Bug, [Pri] Medium, Stats, Jetpack App
