### ISSUE TITLE
Change the post author

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-Android#10336] opened 2019-08-06 21:34 UTC
### Expected behavior

The user would like to change the post author using the app.

### Actual behavior

This change isn't possible unless the user accesses the post editor using a browser.

### Additional context

#2255172-zen

**Comment by designsimply** [comment] 2019-09-19 22:19
Thank you for the report @leandroalonso !

Closing as a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/4230.

**Closed by designsimply** 2019-09-19 22:19 UTC
Labels: Posting/Editing, [Type] Enhancement
