### ISSUE TITLE
Stats screen - Can’t navigate to the left tab when swiping

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/WordPress-Android#16386] opened 2022-04-22 14:49 UTC
### Expected behavior

The user can navigate using the swipe gesture through the different tabs of the Stats screen.

### Actual behavior

The transition when trying to navigate to the left tab by swiping can't be completed. 

### Steps to reproduce the behavior

1. Go to the Stats screen.
2. Tap on the "Days" tab.
3. Swipe right to navigate to the left tab "Insights".
4. Observe that at some point when swiping, it goes back to the "Days" tab.

##### Tested on Samsung Galaxy S20 FE 5G, Android 11, WPAndroid 19.7-rc-1

https://user-images.githubusercontent.com/14905380/164738692-b2c386e5-b322-4264-a309-b980515bec02.mp4

**Comment by ravishanker** [comment] 2022-09-27 06:42
This is likely to happen if gesture is  hold, drag and release than the swipe (fling) to move between tabs.  

There are also at least four different gestures in play on this screen.  Swipe (fling) between tabs, pull-to-refresh, the new predictive gesture to go back on newer versions of android and the scroll.

I'm going to close this since there isn't anything to be fixed here.  This entire Stats feature is also likely to be re-written soon.

**Comment by thehenrybyrd** [comment] 2022-11-10 10:23
I run into this somewhat frequently, and it frustrates me every time. It's hard to reproduce intentionally, because if I'm paying close attention I usually do the swipe (fling) correctly. However, if I'm just navigating around, it's easy to get stuck in a spot where doing the same gesture over and over won't swipe between tabs. 
When these moments happen, I can only swipe if I slow myself down and focus.

I'm not sure how close the swipe (fling) gesture and the go back gesture are, but as far as I can tell I'm drawing a straight line every time (and I'm not getting the go back behavior):

https://user-images.githubusercontent.com/15107387/201065042-6ae0be88-b4bb-4824-ad92-75e296418b2e.mp4

Is it possible to make the app slightly more generous in accepting that swipe gesture? Or is that an OS thing out of our control?

Leaving this closed for now, but may re-open in case of more reports.

**Comment by thehenrybyrd** [comment] 2022-11-24 13:35
Opening this back up because I ran into the issue again during testing of JP Android 21.2-rc-3.
Below is a video; you can see that when the swipe gesture is slightly off from horizontal, the pull-to-refresh icon appears briefly. When the swipe gesture is straight across, you can see the app attempt to flip to the next screen, but fail.

One other note on this is that I've never experienced it in Reader or Notifications (which allow the same gesture for switching between tabs). I only encounter it in Stats.

This makes me wonder whether the screens are listening for a different set of gestures.

https://user-images.githubusercontent.com/15107387/203796088-10815bbe-8266-470f-bf55-83acddbc31b9.mp4

**Comment by antonis** [comment] 2023-05-17 13:32
I was able to reproduce the behaviour described in the issue but after having a look at the related implementation I agree with @ravishanker's [comment above](https://github.com/wordpress-mobile/WordPress-Android/issues/16386#issuecomment-1259054275) that there is not much to fix. I'm closing this issue.

**Closed as completed by antonis** 2023-05-17 13:32 UTC
Labels: [Type] Bug, [Pri] Medium, Stats
