### ISSUE TITLE
Logout then login gives you an empty notification screen

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1788] opened 2014-08-27 08:13 UTC
1. Be logged in or Login.
1. Go to Notifications and check you have some.
1. Logout.
1. Login.
1. Go to Notifications, you'll see an empty screen.

The only way to get notification back in sync is to kill and restart the app.

**Comment by rachelmcr** [comment] 2015-12-02 16:56
I tested this twice in 4.8-rc-3 following the steps above (the second time, I also completely closed the app before logging in again) and couldn't reproduce. Both times the notifications loaded after login.

Closing as resolved.

**Closed by rachelmcr** 2015-12-02 16:56 UTC
Labels: Notifications, [Type] Bug
