### ISSUE TITLE
Default selected website after logging in

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-Android#5964] opened 2017-05-29 16:07 UTC
### Expected behavior
After I log in I expect my default site to be selected.

### Actual behavior
The site displayed initially is my sandbox (self hosted + Jetpacked linked to my account), which I almost never use, I have no idea why.

### Steps to reproduce the behavior
Log in to your account and then check to which site you are redirected. If it works correctly for you, ping me and we can troubleshoot together.

**Comment by elibud** [comment] 2017-05-29 16:23
nope, this does not look real.

**Comment by elibud** [comment] 2017-05-29 16:30
I am reopening this, so @oguzkocer can take a quick look to see if there is any possibility that I haven't lost my mind.

**Comment by oguzkocer** [comment] 2017-06-13 11:06
@elibud I kind of forgot about this issue after my Helpshift rotation, sorry for getting back to it so late. I've been unable to reproduce it, logging out and logging back in defaulted me to my primary site. I also changed my primary site on Calypso and tried again and it worked still. So, I think we are safe to close this one.

**Closed by oguzkocer** 2017-06-13 11:06 UTC
Labels: Login, Site Picker, [Pri] Medium, [Type] Bug

**Comment by elibud** [comment] 2017-06-13 12:22
@oguzkocer thanks a lot for checking, I might be losing my mind after all 😱

**Comment by oguzkocer** [comment] 2017-06-13 12:26
@elibud There might be an edge case or something might have happened on server-side. Unless we can find out the steps to reproduce the issue, not much we can do about it. Still, thanks for reporting this, because if this happens to someone else, at least we have all this documented here.
