### ISSUE TITLE
Image not loading on Android app

### ISSUE THREAD

**Issue by ravirajcm** [wordpress-mobile/WordPress-Android#9939] opened 2019-05-26 00:06 UTC
### Expected behavior
The image should be visible when it loads all blogs in the list
The site support only HTTP, not HTTPS (HTTPS is not forced) and when the Android app load it is showed a blank image.

<img width="606" alt="Screen Shot 2019-05-25 at 7 58 24 PM" src="https://user-images.githubusercontent.com/1651643/58375699-d1b0fc80-7f27-11e9-87e6-bcade004625e.png">

### Actual behavior
Blank image on loading. not loading.

### Steps to reproduce the behavior
Open wordpress app -> add custom blog url -> Login with creds -> Blog posts 

##### Tested on [device], Android [version], WPAndroid [version]
Android 6.0 and above.

##### Issue
Android logs say
`java.io.FileNotFoundException(No content provider: https://brightersight.ca/eds-blog/wp-content/uploads/2019/05/640px-Flag_of_the_Canadian_Forces.svg_.png?w=1032&h=660)`

The problem is "It's trying to load image from HTTPS but as I mentioned earlier. our website running without ssl. How come wordpress android app force images to load from https even our domain itself is running from http ??????

our blog is at https://brightersight.ca/eds-blog

original image url is, without https
http://brightersight.ca/eds-blog/wp-content/uploads/2019/05/640px-Flag_of_the_Canadian_Forces.svg_.png?w=1032&h=660

**Comment by designsimply** [comment] 2019-05-29 18:40
I tested using version [12.5 beta](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/12.5-rc-1) and I found that I am able to see featured images appear in the Blog Posts list and the Drafts list on an HTTP-only site without any problems.

<img src="https://user-images.githubusercontent.com/1119271/58581522-f994ae80-820c-11e9-9886-d2a6cc08584c.png" width="270" alt="Screenshot_20190529-121908">
<p style="clear:both;"><sub>Blog Posts list showing featured images on an HTTP-only site, tested with WPAndroid alpha-171 (12.5 beta) on Pixel 3 Android 9.</sub></p>

<sup>Original image URL, without HTTPS: http://designsimply.com/wp-content/uploads/wcbuf-2013.001.png</sup>

Did this problem start for you with version 12.4 of the WordPress for Android app? What version are you using currently?

Can you go to http://brightersight.ca/eds-blog/wp-admin/options-general.php and please let me know exactly what appears in the fields for `WordPress Address (URL)` and `Site Address (URL)`?

Can you please also double check your `wp-config.php` file to verify that you do not have any SSL-related variables set in that file? (You shouldn't have this if your site is already operating successfully as HTTP-only, but I know those variables can exist and so I think it would be good to confirm they have not been set incorrectly just in case.)

There are two possible ways to connect a Jetpack site in the app: 

1. As a self-hosted site which you described as "Open wordpress app -> add custom blog url -> Login with creds -> Blog posts"
2. The site should appear automatically if you log in with the same WordPress.com username used to connect the site in Jetpack.

Can you try switching the way you are connecting to the site? Instead of this: "Open wordpress app -> add custom blog url -> Login with creds -> Blog posts", can you go to My Site > Switch Site and longpress the brightersight.ca/eds-blog site to remove it. Then log out of the app and log back in as the Jetpack-connected user which you should be able to see on this page near the bottom right in the "Account connection" section: http://brightersight.ca/eds-blog/wp-admin/admin.php?page=jetpack#/dashboard

**Comment by designsimply** [comment] 2019-05-29 18:49
Another report of not being able to see images in the post list for a Jetpack site installed in a subdirectory and connected to the app as a self-hosted site was reported in 2042414-zen and here are the descriptions from that report for reference:

<blockquote>1.) Nothing shows up in the media section.
2.) The app doesn’t display featured images in the posts section (they make it easy for me to sift through them).</blockquote>

<blockquote>I’ve also repeatedly tried to remove each website from the WordPress app and re-add them. [For one site] the blog posts show the featured images . . . for a while. Within 15-30 minutes, they disappear again. [Another] website doesn’t show media files or featured images at all.</blockquote>

<blockquote>With Jetpack installed, I do see images in the posts themselves. However, if I click on an image in a post, I get a “media could not be found” error message.</blockquote>

The sites in that report are using HTTPS though.

@ravirajcm are you able to see images in the Media section in the app for the brightersight.ca/eds-blog site?

**Comment by ravirajcm** [comment] 2019-05-29 19:01
Thank you @designsimply for the response. 
Android WordPress app version is 12.4
![Screen Shot 2019-05-29 at 2 53 46 PM](https://user-images.githubusercontent.com/1651643/58583502-24d5c880-8222-11e9-8b1a-9e0bf34c70a3.png)
I am using WordPress app first time, and no idea if that issue is started from 12.4.

Wordpress URLs is with http only. `http://brightersight.ca/eds-blog`
![Screen Shot 2019-05-29 at 2 57 36 PM](https://user-images.githubusercontent.com/1651643/58583541-4767e180-8222-11e9-8185-4fcf4e5af40f.png)

I don't have anything related to https in my wp-config.php

Yes, I am able to see images in media sections.

**Comment by designsimply** [comment] 2019-05-29 19:24
@ravirajcm thanks. Can you try switching the way you are connecting to the site? Please go to My Sites > Switch Site and long press the site to remove it. Then log out of the app and log back in as the same username you used to connect Jetpack and make sure the `brightersight.ca/eds-blog` site appears (you should not have to add it using the "+" option). Then can you check/refresh the Blog Posts list again and if the images still aren't appearing could you check to see if you can find the exact same error message in the logs again?

**Comment by ravirajcm** [comment] 2019-05-31 02:19
It's the same still trying to load it from https.

`05-30 22:18:23.526 8996-8996/? W/Glide: Load failed for https://brightersight.ca/eds-blog/wp-content/uploads/2019/05/comic-characters-2024772_960_720-1.jpg?w=1032&h=660 with size [984x294]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There were 2 causes:
    com.android.volley.NoConnectionError(javax.net.ssl.SSLPeerUnverifiedException: Hostname brightersight.ca not verified:
        certificate: sha256/2Emgbdya/FmPZwyqzmXQJWGWjrFj8+TP32kthTY9ViY=
        DN: CN=*.rteng.pro,OU=PositiveSSL Wildcard,OU=Domain Control Validated
        subjectAltNames: [*.rteng.pro, rteng.pro])
    java.io.FileNotFoundException(No content provider: https://brightersight.ca/eds-blog/wp-content/uploads/2019/05/comic-characters-2024772_960_720-1.jpg?w=1032&h=660)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    com.android.volley.NoConnectionError(javax.net.ssl.SSLPeerUnverifiedException: Hostname brightersight.ca not verified:
        certificate: sha256/2Emgbdya/FmPZwyqzmXQJWGWjrFj8+TP32kthTY9ViY=
        DN: CN=*.rteng.pro,OU=PositiveSSL Wildcard,OU=Domain Control Validated
        subjectAltNames: [*.rteng.pro, rteng.pro])
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    com.android.volley.NoConnectionError(javax.net.ssl.SSLPeerUnverifiedException: Hostname brightersight.ca not verified:
        certificate: sha256/2Emgbdya/FmPZwyqzmXQJWGWjrFj8+TP32kthTY9ViY=
        DN: CN=*.rteng.pro,OU=PositiveSSL Wildcard,OU=Domain Control Validated
        subjectAltNames: [*.rteng.pro, rteng.pro])
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class com.android.volley.NoConnectionError: javax.net.ssl.SSLPeerUnverifiedException: Hostname brightersight.ca not verified:
        certificate: sha256/2Emgbdya/FmPZwyqzmXQJWGWjrFj8+TP32kthTY9ViY=
        DN: CN=*.rteng.pro,OU=PositiveSSL Wildcard,OU=Domain Control Validated
        subjectAltNames: [*.rteng.pro, rteng.pro]
      Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL
    There was 1 cause:
    java.io.FileNotFoundException(No content provider: https://brightersight.ca/eds-blog/wp-content/uploads/2019/05/comic-characters-2024772_960_720-1.jpg?w=1032&h=660)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class java.io.FileNotFoundException: No content provider: https://brightersight.ca/eds-blog/wp-content/uploads/2019/05/comic-characters-2024772_960_720-1.jpg?w=1032&h=660
05-30 22:18:23.536 8996-8996/? I/Glide: Root cause (1 of 2)
    com.android.volley.NoConnectionError: javax.net.ssl.SSLPeerUnverifiedException: Hostname brightersight.ca not verified:
        certificate: sha256/2Emgbdya/FmPZwyqzmXQJWGWjrFj8+TP32kthTY9ViY=
        DN: CN=*.rteng.pro,OU=PositiveSSL Wildcard,OU=Domain Control Validated
        subjectAltNames: [*.rteng.pro, rteng.pro]
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:158)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)
     Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname brightersight.ca not verified:
        certificate: sha256/2Emgbdya/FmPZwyqzmXQJWGWjrFj8+TP32kthTY9ViY=
        DN: CN=*.rteng.pro,OU=PositiveSSL Wildcard,OU=Domain Control Validated
        subjectAltNames: [*.rteng.pro, rteng.pro]
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:308)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at org.wordpress.android.fluxc.network.OkHttpStack.performRequest(OkHttpStack.java:66)
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:97)
        	... 1 more
05-30 22:18:23.536 8996-8996/? I/Glide: Root cause (2 of 2)
    java.io.FileNotFoundException: No content provider: https://brightersight.ca/eds-blog/wp-content/uploads/2019/05/comic-characters-2024772_960_720-1.jpg?w=1032&h=660
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1092)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:944)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:867)
        at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:22)
        at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:13)
        at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)`

**Comment by designsimply** [comment] 2019-06-05 23:50
@malinajirka could the app be trying to force images to load as HTTPS for sites that are HTTP-only as @ravirajcm has suggested? If not, can you see why there would be volley errors about SSL certs in the app logs as noted above?

**Comment by malinajirka** [comment] 2019-06-17 07:30
I have just quickly looked at this issue and there are some places in the app where we force https. Having said that none of the places I found seemed related to this issue - unless the posts are marked as private. It looks like a good ticket for groundskeeping and it's definitely worth investigating;).

https://github.com/wordpress-mobile/WordPress-Android/blob/ac56c495d4f5cecf2a50f349576f23515679d8b1/WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java#L63

https://github.com/wordpress-mobile/WordPress-Android/blob/0dd529ca01120d1c2fc8b09f3db6707be0bc1b9a/WordPress/src/main/java/org/wordpress/android/networking/GlideRequestFactory.kt#L39

**Comment by designsimply** [comment] 2019-08-20 20:23
Passing along some feedback received about this issue in mobile support:

> Another issue with the images is that the featured image, once set up, is not showing on the draft post. Similarly, the featured image is not showing on any of the published posts either. When I was not signed into the wordpress.com account then those images were available on the app.

* Type: (jetpack_connected - XML-RPC)
* Android device name: Samsung SM-G950F
* WPAndroid 12.9 (as of 2019-08-20)
* HTTPS is being used.
* Site has quite a few plugins installed.
* User was logged in as self-hosted and was asked to log in via WP.com in the app and they started seeing this problem after doing that step.

<sup>(internal reference: 2274213-zen)</sup>

**Comment by develric** [comment] 2020-03-12 10:15
Investigated this yesterday and sharing some findings below; I'm mostly referring to the original issue at the start of this ticket.

In the below I used:
- Pixel 3 Emu with API 28 level
- current develop (vanilla 14.3)
- jurassic.ninka for https
- an old and full of dust RaspberryPI on top of which I put WordPress for http (some fun is good from time to time 😊)

### Adding self-hosted site by address (with or without connected JP)
- http site cannot load featured image ❌
- https site can load featured image ✅

### Adding self-hosted site logging in WP.com (so with connected JP)
- both http and https work ✅

Looking into the code I think the key is in how we judge a site to be `private` as Jirka was suggesting above. In more detail we use the function `getResizedImageUrl` (both from `ReaderUtils` and from `ReaderUtilsWrapper`) to which we need to pass an `isPrivate` parameter to mark the site/post as private or not. AFAIU we are overlapping the concept of being a site private with that of being photon capable [here](https://github.com/wordpress-mobile/WordPress-Android/blob/fa2b2ab9cf6308b6072ac114a254f49176321fa0/WordPress/src/main/java/org/wordpress/android/ui/posts/FeaturedImageHelper.kt#L143), [here](https://github.com/wordpress-mobile/WordPress-Android/blob/fa2b2ab9cf6308b6072ac114a254f49176321fa0/WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt#L386) and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/fa2b2ab9cf6308b6072ac114a254f49176321fa0/WordPress/src/main/java/org/wordpress/android/ui/pages/PageItemViewHolder.kt#L120).

There we judge a site as private when it's not accessed via WP.com and not private

``` 
    /**
     * @return true if the site is WPCom or Jetpack and is not private
     */
    public static boolean isPhotonCapable(SiteModel site) {
        return SiteUtils.isAccessedViaWPComRest(site) && !site.isPrivate();
    }
```

so enforcing the https [here](https://github.com/wordpress-mobile/WordPress-Android/blob/fa2b2ab9cf6308b6072ac114a254f49176321fa0/WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java#L73)

Also in the http case that fails we are actually able to load images in image picker while selecting a featured image in post settings

| fails to load post featured image from http site | can load images from http site in picker  |
|---|---|
| ![image](https://user-images.githubusercontent.com/47797566/76509315-1d4d7c00-6450-11ea-90be-8ce71bf69ec7.png) | ![image](https://user-images.githubusercontent.com/47797566/76509291-132b7d80-6450-11ea-94db-f96c44e93b60.png) |

Because we do not condition explicitly on the [private state](https://github.com/wordpress-mobile/WordPress-Android/blob/fa2b2ab9cf6308b6072ac114a254f49176321fa0/WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java#L131) (a part for photon)

Not sure about which should the intended behavior in what described above. In my understanding we should maybe decouple the site private state from the the site being photon capable. Pinging @malinajirka and @planarvoid in case you have some better clue/advice 🙇‍♂️.
cc @designsimply 

**NOTE:** about the issue reported also when accessing the http site with WP.com and JP connected, as per above I was not able to reproduce; my best guess is that there was some JP configuration issue (I sometimes had in the past random issues when having the site in a subfolder as it seems the case here, but cannot be sure it is the real cause of course since I could not reproduce)

**Comment by planarvoid** [comment] 2020-03-12 12:51
hey @develric , I think you have the right idea. I'm not sure why the code was written this way but it seems that the `ReaderUtilsWrapper#getResizedImageUrl` was misused, the parameter `isPrivate` and the `!SiteUtils.isPhotonCapable(connector.site)` do not mean the same thing. I think it would be smart to just test all the possible scenarios and try to rewrite/rethink the way it works now. I don't have any insight about why the logic was implemented this way but it's obvious that the private self-hosted sites are a scenario that was missed. I'd suggest extracting the logic, documenting it and testing it so our choices are saved for future generations :-)

**Closed** 2020-11-10 00:56 UTC
Labels: Mobile Request, Post List, [Type] Bug
