### ISSUE TITLE
No jump to specific faq section

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7754] opened 2018-05-15 20:18 UTC
When we implemented the new Login flow, jumping to a specific Helpshift FAQ section never got updated and apparently fell through the cracks. [See this line](https://github.com/wordpress-mobile/WordPress-Android/blob/39d3b88cb348d17f4710abc22ec8669b624ff757/WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java#L652).

Opening this ticket to record the fact. No immediate need to implement the functionality unless we decide to.

**Comment by elibud** [comment] 2018-05-16 10:57
@oguzkocer I'm assigning this over to you so it's not left unassigned.

**Comment by oguzkocer** [comment] 2018-05-16 15:29
@elibud There is nothing to assign to me right now, otherwise we would have made it part of the Zendesk project. This is related to the unused (and not designed) usage in the login project and we removed the existing code in #7755 because I verified with @hypest that it's not something we will do right now (since login project is over).

Can you please unassign the issue from me? Thanks!

**Comment by oguzkocer** [comment] 2018-05-16 16:37
> Well isn't this functionality something we want to implement?

Not as part of the Zendesk project because I specifically asked @hypest if it's something that needs to be done and he said no. That's why I removed the existing code for it.

> Wasn't it left out by mistake?

That's a question for @hypest.

------------------------

To be perfectly clear, this issue came out of some unused code in the login project. As far as I know there is no design or plan to implement anything like this. It looked to me like it was just added there in case it proved useful (which is something I strongly disagree with).

Anyway, if you think we need to implement this, I'd much prefer if it starts with a design and planned out implementation details _before_ the issue is assigned to me.

**Comment by elibud** [comment] 2018-05-16 16:43
Oh I see, that makes sense, thanks for the context @oguzkocer 

@hypest please let us know if this was left out by mistake or by design, thansk.

**Comment by oguzkocer** [comment] 2018-05-16 16:47
> Oh I see, that makes sense, thanks for the context

Happy to help @elibud 🙇

**Comment by hypest** [comment] 2018-05-18 11:47
> @hypest please let us know if this was left out by mistake or by design, thanks.

I think we just didn't design those _in_ @elibud . Weren't left out on purpose either.

Context: Before the new Login, when an error occurred, we would set the "faqId", "sectionId" properties so if user chose to go to the Helpshift FAQ from the error screen, we would jump directly to a relevant FAQ article.
In the new Login design though, we designed the error responses and follow up actions in a way that's easier to understand by the user so, the jump to Helpshift FAQ became less of an imperative.

**Comment by elibud** [comment] 2018-05-18 15:57
Got it, I'm just going to close this one then. Thank you both.

**Closed by elibud** 2018-05-18 15:57 UTC
Labels: Login
