### ISSUE TITLE
Logging out and then swiping/tapping back returns user to Me view

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#14632] opened 2021-05-12 16:01 UTC
### Expected behavior
 The app appears to enter a weird state when the user logs out and then taps/swipe back from the prologue view

### Actual behavior
Expect that the user is taken out of the app

### Steps to reproduce the behavior
- Fresh install or delete all data
- Launch App
- Login with WP.com account
- From My Site:  Tap Me -> Logout -> Confirm logout
- Note that you are taken to the Login Prologue view
- Tap the device Back Button or swipe back
- The Me View is shown

##### Tested on [device], Android [version], WPAndroid [version]
Google Pixel 5, Android Version:11, WPAndroid: 17.2 and 16.9 ( I did not try the versions in-between 16.9 & 17.2)

**Comment by develric** [comment] 2021-05-13 09:30
Thanks for documenting this @zwarm 🙇 . I was able to reproduce this one on current 17.3 beta, but it seems something that is there for a long time as well (went back to 14.3 and it was already there). Given this and the fact that AFAIU it seems a pretty edge case, I'm assigning a Low priority for now. I will try to queue this in my tomorrow last day of GK, but eventually it seems a good issue to tackle in the next GK rounds I guess. cc @thehenrybyrd

**Comment by renanferrari** [comment] 2021-06-22 19:18
This seems to be a duplicate of #12377, so I'm closing that in favor of this.

**Closed as completed** 2021-06-23 14:07 UTC
Labels: [Type] Bug, [Pri] Low, Login
