### ISSUE TITLE
Edits made on the web aren't reflected in the app (Android only)

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#12168] opened 2020-05-14 22:17 UTC
Steps to reproduce:

1. In the app, create a new post and publish it.
1. On the web, edit the post and make changes to the title and content.
1. In the app, go to My Site > Blog Posts.
1. Pull to refresh.
1. Open the post published in step 1.
1. Check to see if the edits to the title and content are visible in the app.
1. Check to see if the same edits are visible in More > History.

**Result:** edits to a published post made on the web are not reflected in the editor in the app. Changes to the post title are visible but changes to the content are **not** visible in the editor even though they are visible in revisions history. ([1m15s](https://cloudup.com/c8T9J3dhCur)) Everything works normally on iOS. ([3m13s](https://cloudup.com/cQXKD1vpIer))

Made with app|Updated on web|Posts List after edit
---|---|---
<img src="https://user-images.githubusercontent.com/1119271/81990336-331c2080-95fc-11ea-8754-2bc52dda0010.png" width="200" alt="Screenshot_20200514-113258">|<img src="https://user-images.githubusercontent.com/1119271/81990335-32838a00-95fc-11ea-8cb7-920a9effaf58.png" width="200" alt="Screenshot_20200514-113614">|<img src="https://user-images.githubusercontent.com/1119271/81990334-32838a00-95fc-11ea-9cad-b111de413a43.png" width="200" alt="Screenshot_20200514-115852">
Editor in app after web edit|Revision in app after web edit|
<img src="https://user-images.githubusercontent.com/1119271/81990333-32838a00-95fc-11ea-9e98-e0189a17be06.png" width="200" alt="Screenshot_20200514-115904">|<img src="https://user-images.githubusercontent.com/1119271/81990332-31eaf380-95fc-11ea-922f-b6ef3edb03ea.png" width="200" alt="Screenshot_20200514-115916">

<p style="clear:both;"><sup>Tested with WPAndroid 14.8-rc-3 on Pixel 3 Android 10 on a WordPress.com.</sup></p>

**Comment by zwarm** [comment] 2020-06-30 13:28
@designsimply - I’m having trouble replicating the issue too.

These are the scenarios I tried for 15.0-rc-2, 15.0-rc-3, and alpha-231 (latest develop)

1. Fresh install
2. Created a new post (from the dashboard FAB) and published it
3. On the web, edited the post (title and content) and updated it
4. In the app navigated to My Site > Blog Posts
5. The post was there, no need to PTR
6. Navigated to History which shows edits


1. In the app navigated to My Site > Blog Posts
2. Tapped the FAB to create a new post and published it
3. On the web, edited the post (title and content) and updated it
4. I remained on the post list on the app, so I did a PTR
5. The post showed on results of PTR
6. Navigated to History which shows edits

I downloaded the 14.9 release and had some inconsistencies with the history, but nothing that a PTR didn’t fix. 

Have you had the chance to take a look at 15.0 yet?

**Comment by rachelmcr** [comment] 2020-07-24 14:59
I'm also unable to reproduce this issue. @designsimply There's something really wrong with your test post — I see the edits in the published post on the web, but even in the web editor (not just the app editor) the original post contents appear. I wonder if something went wrong with the update on the web side?

**Comment by hypest** [comment] 2020-10-12 11:04
> I'm also unable to reproduce this issue. @designsimply There's something really wrong with your test post — I see the edits in the published post on the web, but even in the web editor (not just the app editor) the original post contents appear. I wonder if something went wrong with the update on the web side?

Based on Rachel's comment, this is most probably not mobile related so, closing. Please, feel free to re-open if it turns out to be a mobile one, thanks!

**Closed by hypest** 2020-10-12 11:04 UTC
Labels: Posting/Editing, [Pri] High, [Type] Bug
