### ISSUE TITLE
Publish confirmation dialog shown on sync changes on scheduled post

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10464] opened 2019-08-30 10:18 UTC
### Expected behavior
When the user clicks on "sync" on a scheduled post, the publish confirmation dialog is not shown.

### Actual behavior
When the user clicks on "sync" on a scheduled post, the publish confirmation dialog is shown. 

<img src="https://user-images.githubusercontent.com/2261188/64013396-fcf74900-cb1f-11e9-9412-e0ad698a5847.png" alt="Smiley face" height="350">

### Steps to reproduce the behavior
1. Post List
2. Schedule a post
3. Turn on airplane mode
4. Make changes to the post
5. Press back
6. Go to the Scheduled tab
7. Turn off airplane mode
8. Click on "Sync"

**Comment by rachelmcr** [comment] 2019-09-24 14:41
This is a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/8351. I'll go ahead and close that issue since this one is already prioritized in groundskeeping.

**Closed** 2019-12-24 14:07 UTC
Labels: Post List, Posting/Editing, [Pri] Medium, [Type] Bug
