### ISSUE TITLE
Crash report: 7.2/7.2.1 NPE in MediaBrowserActivity

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#5871] opened 2017-05-10 12:30 UTC
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.media.MediaBrowserActivity}: java.lang.NullPointerException: url
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.access$900(ActivityThread.java:150)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: url
       at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:60)
       at android.content.ContentResolver.getType(ContentResolver.java:329)
       at org.wordpress.android.ui.media.MediaBrowserActivity.uploadList(MediaBrowserActivity.java:698)
       at org.wordpress.android.ui.media.MediaBrowserActivity.handleSharedMedia(MediaBrowserActivity.java:900)
       at org.wordpress.android.ui.media.MediaBrowserActivity.onCreate(MediaBrowserActivity.java:173)
       at android.app.Activity.performCreate(Activity.java:6285)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.access$900(ActivityThread.java:150)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by daniloercoli** [comment] 2017-05-10 13:02
This is a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/5666 and should already be fixed in `7.3`.

**Closed by daniloercoli** 2017-05-10 13:02 UTC
Labels: [Pri] Medium, [Type] Crash
