### ISSUE TITLE
SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=14

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-Android#13273] opened 2020-10-30 15:23 UTC
**Sentry Url**: https://sentry.io/share/issue/83d65e73445b4d87ad38a068e49b2dd6/
**User Count**: 38
**Count**: 1557
**First Release**: org.wordpress.android-12.4
**First Seen**: May 24, 2019 9:46:39 AM UTC
**Last Seen**: Oct 30, 2020 6:23:14 AM UTC
**24 Hours**: 13
**30 Days**: 193

```
Crashed in non-app: android.database.sqlite.SQLiteConnection in nativeExecuteForCursorWindow
org.wordpress.android.fluxc.persistence.PostSqlUtils in getPostsByLocalOrRemotePostIds at line 214
org.wordpress.android.fluxc.store.PostStore in getPostsByLocalOrRemotePostIds at line 512
org.wordpress.android.viewmodel.posts.PostListItemDataSource in getItemsAndFetchIfNecessary at line 72
org.wordpress.android.viewmodel.posts.PostListItemDataSource in getItemsAndFetchIfNecessary at line 41
org.wordpress.android.fluxc.model.list.datasource.InternalPagedListDataSource in getItemsInRange at line 51
org.wordpress.android.fluxc.model.list.PagedListPositionalDataSource in loadRangeInternal at line 58
org.wordpress.android.fluxc.model.list.PagedListPositionalDataSource in loadInitial at line 40
Called from: androidx.paging.PositionalDataSource in dispatchLoadInitial
 ```

**Comment by designsimply** [comment] 2020-10-30 17:29
Also see https://github.com/wordpress-mobile/WordPress-Android/issues/10057 / https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1726 as a similar issue that has been at the top of our Groundskeeping Android prioritized list and was worked on recently. ❤️

<sup>(internal reference: p4a5px-2F5-p2)</sup>

**Comment by malinajirka** [comment] 2020-11-02 08:58
I've looked into this issue and here are things I found:
- We've seen a similar crash at various places throughout the app - https://github.com/wordpress-mobile/WordPress-Android/issues/10057 - sentry merged some "unrelated" crashes. (We've seen it even in Woo app https://github.com/woocommerce/woocommerce-android/issues/572) 
- We increased Cursor window size to 5MB in 0371731434b4456f0d37c7388b2e763fdb7d5865, but apparently it didn't solve the issue. 
- The issue first occurred more than a year ago and related issues started occurring years ago so I don't think the "Blocking" priority is appropriate. Wdyt @emilylaguna ?
- The solution @planarvoid implemented in the Stats store isn't imo applicable for this scenario. We are loading just PostModels - no other sub-depdendencies. I think the issue is caused by "mContent" field which contains the whole content of each post and it can be quite big.

I can think of three possible solutions:
1. Load full "mContent" field only when we actually need it - I think we really need it just for upload+editor and we could always load only a single post there. There is a chance it'd still crash if the "mContent" field for the single post was too big.
2. We could try paginating db requests - again, it might still crash if the "mContent" field was too big.
3. Somehow break down the mContent field - store it in parts in another table.

Unfortunately, all these solutions are quite difficult to implement. I think we should first be able to reproduce the crash before we dive into any of them.

**Comment by malinajirka** [comment] 2020-11-02 09:24
Another ideas for solutions:
4. Store only lets say 3000 characters of mContent into the db and store the rest into a file.
5. Look if we can somehow zip the mContent. It might not help.
6. Catch the exception and somehow modify the post so it fits the cursor window and show something like "Post is too big and can't be open on mobile".

**Comment by malinajirka** [comment] 2020-11-02 10:09
I was able to reproduce the crash:
1. Generate 100kb of text and save it into the clipboard (eg on https://www.lipsum.com/)
2. Open a new post on the web
3. Paste the text 50 times (50x 100kb)
4. Publish the post
5. Go to Post List in the app and notice the app crashes

Solutions 1, 2 wouldn't solve this issue. Solution 5 would solve it only for some posts and there would still be a limit on post size.

**Comment by designsimply** [comment] 2020-11-29 21:48
**Events in the last 90d:** 1,700
**Users affected in the last 90d:** 36
**Limited to:** Android 9 and Android 10
<sub>WORDPRESS-ANDROID-14T: https://sentry.io/share/issue/83d65e73445b4d87ad38a068e49b2dd6/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1041580030&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/100553913-474d0580-324e-11eb-9fb4-b122af669745.png)</a>

**Comment by designsimply** [comment] 2020-11-30 02:29
I agree that we can lower this issue from blocking priority and have changed it to medium.

> I think we should first be able to reproduce the crash before we dive into any of them.

I have added this issue to Groundskeeping with an ask for someone to timebox trying to reproduce the crash and leaving notes with what they've tried.

**Comment by designsimply** [comment] 2021-01-22 17:53
**Events in the last 90d:** 1,900
**Users affected in the last 90d:** 41
**Limited to:** Android 9+
<sub>WORDPRESS-ANDROID-14T: https://sentry.io/share/issue/83d65e73445b4d87ad38a068e49b2dd6/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1041580030&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105526719-01397e80-5ca0-11eb-9ecc-87b533f33868.png)</a>

**Comment by designsimply** [comment] 2021-03-15 17:41
Steady numbers but still happening in the latest release.

**Events in the last 90d:** 2,000
**Users affected in the last 90d:** 42
**Limited to:** Android 9+
<sub>WORDPRESS-ANDROID-14T: https://sentry.io/share/issue/83d65e73445b4d87ad38a068e49b2dd6/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1041580030&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/111196818-59e01600-8583-11eb-87a7-02e1c711979a.png)</a>

**Comment by jd-alexander** [comment] 2021-03-17 20:16
@malinajirka thanks for the thorough investigation you have done so far 🙇🏾 

> We increased Cursor window size to 5MB in 0371731, but apparently it didn't solve the issue.

In your reproduction steps, the fact that you reproduce the crash with a 5MB post (Paste the text 50 times (50x 100kb)) is it safe to say that we could indeed increase the `5MB` cursor window to a higher value to solve the issue? 

I checked around and I found folks increasing the cursor window to values between the range of 10MB and 100MB ( [in Expensify Cash](https://github.com/Expensify/Expensify.cash/commit/8fc6d16a21a3699826ce7909b93d3ce2ff37a589)).

 I could definitely give this a test with some really large posts if it's an option worth considering. I have also started looking into the performance implications of this change and if this path is taken, performance tests could be run.
 
So to reiterate the ideas I have so far are: 

1. Increase the `CursorWindowSize` to 20MB. 
2. Log the size of the `mContent` field to Sentry to gain an average value that could help prevent these crashes.
3. Check the user's device memory dynamically and utilize this to create a size. ( i.e if this is applicable to CursorWindows)
4. Did [strict mode](https://github.com/wordpress-mobile/WordPress-Android/blob/a9eeed79f6d85fd3a3a55157ff9b2932248c00cc/WordPress/src/debug/java/org/wordpress/android/WordPressDebug.java#L52) give any other insights?

Let me know what you think 🙇🏾

**Comment by malinajirka** [comment] 2021-03-18 14:02
Thanks @jd-alexander for following up on this. Your plan sounds good to me. It probably won't solve this issue entirely, but it could at least limit the number of occurrences. Let's start with the first step and monitor if it changes the trends.

**Comment by jd-alexander** [comment] 2021-03-18 15:37
Thanks for the feedback @malinajirka. Once I complete the PR, I will ask you for a review! 🙇🏾 If we notice improvements in WP Android occurrence of this after the change has been released for a while we can also introduce this change to Woo as well.

**Comment by irfano** [comment] 2024-05-29 13:48
I'm reopening the issue since it still crashes.

**Comment by irfano** [comment] 2024-05-29 14:33
https://github.com/wordpress-mobile/WordPress-Android/issues/18727

**Closed as not planned by irfano** 2024-05-29 14:33 UTC
Labels: [Pri] Medium, Posting/Editing, [Type] Crash
