### ISSUE TITLE
Unable to go back from verification code screen

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#20152] opened 2024-02-08 15:11 UTC
### Expected behavior

I should be able to navigate back from the screen that asks for a verification code.

### Actual behavior

In certain circumstances, I can't go back from this screen. When I tap back (to the password screen), the app immediately returns me to the verification code screen.

### Steps to reproduce the behavior

1. Locate a WP.com account with app-based 2FA enabled
2. Add the account's username and password to Google Password Manager (or Smart Lock, not sure if they're the same thing).
3. Open the JPAndroid app
4. When the system prompt offers to log you in with the saved account, accept it
5. The app takes me straight to the verification code screen as expected
6. Tap back, and notice that you go back to the password screen momentarily, before the app takes me back to the verification code screen

### Screen recording

https://github.com/wordpress-mobile/WordPress-Android/assets/1898325/03849edd-aa5f-4a3c-94a4-c9b55fd94339

**Comment by guarani** [comment] 2024-02-08 15:33
👋 @irfano, do you think this could be related to https://github.com/wordpress-mobile/WordPress-Android/pull/20102? I wanted to see if this was a new issue, so I tested 24.1, but then recalled that the bug you fixed prevents me from getting to the verification code screen. I haven't tested earlier versions.

**Comment by irfano** [comment] 2024-02-08 15:46
This is on the same screen, but it's already an existing issue.

**Comment by irfano** [comment] 2024-02-08 15:46
Duplicate of #14950

**Closed as not planned by irfano** 2024-02-08 15:46 UTC
Labels: [Type] Bug, [Pri] Medium, Login

**Comment by guarani** [comment] 2024-02-08 15:53
Thanks for finding the duplicate 🙇
