### ISSUE TITLE
Youtube URLs not saved in blog post

### ISSUE THREAD

**Issue by sophiegyo** [wordpress-mobile/WordPress-Android#8062] opened 2018-07-19 13:47 UTC
### Expected behavior
Using the Share button on a Youtube video allows the video URL to publish to a blog entry.

1. Open Youtube app
2. Select video
3. Press "Share"
4. Select WordPress app in list of available apps
5. Paste Youtube video URL in new post
6. Publish post
7. View video in post

**OR**

1. Open Youtube app
2. Select video
3. Press "Share"
4. Copy Youtube video link
5. Open WordPress app
6. Paste Youtube video URL in new post
7. Publish post
8. View video in post

### Actual behavior
Post contains video title in post title area, but the entry content is empty.

### Steps to reproduce the behavior
1. Open Youtube app
2. Select video
3. Press "Share"
4. Select WordPress app in list of available apps
5. Paste Youtube video URL in new post
6. Publish post
7. Post has video name in title, but no embedded video or video URL in entry content.

**OR** 

1. Open Youtube app
2. Select video
3. Press "Share"
4. Copy Youtube video link
5. Open WordPress app
6. Paste Youtube video URL in new post
7. Publish post
8. Post has video name in title, but no embedded video or video URL in entry content.

With both procedures, empty entry content is confirmed both on computer and in the app.

##### Tested on [device], Android [version]
Samsung Note 8 (report from user), Android version 8.0
Huawei P9 Lite (mine), Android 7.0

Reference: #4540933-hc

**Comment by rachelmcr** [comment] 2018-08-22 10:46
Thanks for the report! I tested this on my Nexus 9, Android 7.1.1, WPAndroid alpha-125 and couldn't reproduce the issue.

Here are the steps I took:
1. Open Youtube app
2. Select video
3. Press "Share"
4. Select WordPress app in list of available apps
5. Select the site I want to publish to. This created a new post with a pre-filled title and the Youtube link pre-filled in the post content. (I didn't have to paste the URL myself.)
6. Publish post
7. View video in post

Are you still seeing the issue when you test now, or is it resolved?

**Comment by SiobhyB** [comment] 2018-08-24 10:07
We had another report of this issue in 1344370-z. The user followed the same steps outlined by Rachel (they didn't paste the URL themselves) but the URL was automatically stripped out when they pressed publish.

They're on version 10.6 of the Android app and were attempting to share to a self-hosted site that isn't connection via Jetpack.

I'm a bit stumped as I wasn't able to replicate after following those steps myself. In my testing, the YouTube URL was successfully shared to a post on both WordPress.com and self-hosted test sites. I tested on my Pixel, Android 9, WPAndroid apha-235.

The user did mention that the sharing worked in previous versions of the app and I wonder whether any issue has been fixed with the latest release. I'll check whether they're interested in trying the beta and report back.

**Comment by SiobhyB** [comment] 2018-09-03 12:01
The above user got back to let us know they're still seeing the problem with version 10.7 of the app. They tested both using YouTube's share button and copying/pasting the URL to the YouTube video directly, both actions result in the URL being stripped out.

I haven't been able to replicate at all in my testing so wonder if this is specific to older Android devices.

They're on an Xperia Z5 (E6653) and Android 7.1.

**Comment by daniloercoli** [comment] 2018-10-02 13:49
This issue was fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/8204

Ref: https://github.com/wordpress-mobile/WordPress-Android/issues/8201

**Closed by daniloercoli** 2018-10-02 13:49 UTC
Labels: Posting/Editing, [Type] Bug
