### ISSUE TITLE
Out-dated post saved in the app overrides up-to-date post on the web

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9338] opened 2019-02-27 11:02 UTC
JetPack site

### Expected behavior
1. Create a post in the app. 
2. Edit the post on the web. 
3. Pull-to-refresh in the app
4. The up-to-date version of the post is fetched from the web.

### Actual behavior
1. Create a post in the app. 
2. Edit the post on the web. 
3. Pull-to-refresh in the app
4. The app overrides the changes made on the web with the last version of the post saved in the app

##### Tested on [device], Android [version]
WordPress 10.7
Samsung SM-N950U

1834402-zen

cc @oguzkocer

**Comment by oguzkocer** [comment] 2019-02-27 16:21
@malinajirka Did you by any chance reproduce this issue? Just of the top of my head, unless I am missing something, this should ever happen. @mzorz and I worked on post conflict resolution together recently, but all we do is mark a post as conflicted if the post is modified in both web and app at the same time. There is no push action unless the user specifically tells us that they want to keep the web version. Here is the PR for that: #8989

P.S: I am afk today, on support rotation rest of the week and in a meetup the next week, so I wanted to reply immediately (even without testing) to keep the conversation moving.

**Comment by malinajirka** [comment] 2019-02-27 16:35
I've tried it on a WordPress.com site and it worked as expected. I'll try it on a self-hosted site with Jetpack tomorrow.

**Comment by richards1052** [comment] 2019-02-27 19:41
I'm on as self hosted site and i'm the user who experienced the issue. It's happened before as well.

**Comment by oguzkocer** [comment] 2019-02-27 21:42
Thanks @richards1052, that helps! That likely means it's not a result of #8989.

I still don't think refreshing the post list is causing this issue, because we don't push anything to the server as part of that fetch, but there might be a step in between pull-to-refresh and the push.

@malinajirka Thanks for checking, let me know how it goes. I'll try to reproduce as well if you can't.

**Comment by richards1052** [comment] 2019-02-28 00:59
To reproduce the behavior I experienced:

1. open WP mobile and open new post.
2. save post in draft mode in WP mobile.
3. open WP on desktop and open post previously saved in mobile app draft mode.
4. add content to post on desktop, then publish in desktop mode.
5. open WP mobile and pull-to-refresh.

What happened to me is that this post, which was in draft mode in WP mobile, not only remained in draft mode, but it reverted the published post back to the draft mode version.

In fact, I suspect that WP mobile is not refreshing any posts which are created and saved in this manner.  For some reason, content first created in mobile mode, then changed in desktop mode, can't be updated in mobile mode to reflect added content in desktop.

**Comment by malinajirka** [comment] 2019-02-28 09:08
I've tested it again on WordPress.com Site, Self-hosted site and Self-hosted site with Jetpack. I'm not able to reproduce the behavior on any of them:(. 

However, I've discovered another bug #9347 -> the app creates two drafts in some cases. I'm wondering whether it's not the source of a confusion. 
1. The app creates two identical drafts
2. The user modifies and publishes one of them using a browser
3. When they return back to the app the second identical draft is at the top of the list (so it may seem the app deleted the content of the published post and changed its state back to "draft")

@richards1052 Could you please double check it's not the case (check the published post really disappeared/was overridden)? Thank you very much! I really appreciate it!

**Comment by malinajirka** [comment] 2019-03-03 18:20
I have an idea what my cause the issue.
https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/48aa6bce1b13ffb10a03957a80831661a5f46c72/fluxc/src/main/java/org/wordpress/android/fluxc/store/PostStore.java#L622

When we detect the post has been changed in the remote, we check it's not locally changed and if it's not locally changed we fetch it from the remote. However, before the fetch is complete, the user can open the "out-dated" post and start editing it. When the fetch is complete the remote version of the post is saved into the db, however, it gets overridden by the "auto-save" feature soon after that.

Wdyt @oguzkocer ? I'll try to reproduce it unless you tell me I'm missing something.

**Comment by oguzkocer** [comment] 2019-03-03 19:02
> When we detect the post has been changed in the remote, we check it's not locally changed and if it's not locally changed we fetch it from the remote. However, before the fetch is complete, the user can open the "out-dated" post and start editing it. When the fetch is complete the remote version of the post is saved into the db, however, it gets overridden by the "auto-save" feature soon after that.

Yes, that's definitely possible, but also I'd consider it an edge case. I'd imagine it to be pretty hard to reproduce even when we know how to reproduce it. That doesn't seem to fit the description @richards1052 gave, so I am not sure if this is the same issue or not.

**Comment by elibud** [comment] 2019-06-05 20:14
@diegoreymendez is this one you can add to your offline project/posting improvements?

**Comment by malinajirka** [comment] 2019-06-06 07:53
We still have not been able to reproduce this issue - Perhaps, the scenario I described [here](https://github.com/wordpress-mobile/WordPress-Android/issues/9338#issuecomment-468194484) is what actually happened. I'd suggest closing this issue and re-open it if it comes up again. Wdyt?

**Comment by elibud** [comment] 2019-06-06 13:50
Sounds good, let's close it and we can get back to it if we hear from someone else.

**Closed by elibud** 2019-06-06 13:50 UTC
Labels: Post List, [Pri] High, [Type] Bug

**Comment by richards1052** [comment] 2019-06-06 16:15
I originally reported this as a bug.  It's only happened to me twice so far (I use the app to publish comments more than writing posts).  But each time was disastrous in that I lost all the work I'd done on the original post in the browser.  If it happens again, I report again and try to be precise to see if it's possible to reproduce.

**Comment by elibud** [comment] 2019-06-06 17:31
@richards1052 really sorry to hear that! We've been trying to get to the bottom of this one with no luck. Do you think that what Jirka previously described [here](https://github.com/wordpress-mobile/WordPress-Android/issues/9338#issuecomment-468194484) might've happened?
