### ISSUE TITLE
Media uploads sometimes fail with NoHttpResponseException

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#3304] opened 2015-10-06 08:55 UTC
Started getting this bug when uploading posts with images (or individual images, e.g. through adding a gallery or using the new visual editor). The post/image upload will get stuck, and the upload will never complete. Posts with no images upload successfully.

Log:

<img width="1010" alt="nosara-tracks-media-upload-error" src="https://cloud.githubusercontent.com/assets/9613966/10304406/36b6ae7e-6c1a-11e5-8086-5836a123e1ea.png">

Notes:
* Only happens on mobile devices (the bug doesn't occur when using emulators or when using a device proxied through Charles or Fiddler) - specifically, a Nexus 4, a Nexus 6 and a Nexus 9.
* Occurs 100% of the time on some days, and on other days it never happens
* Tested on `develop` and on the current beta
* Have only been able to test this on a single Wi-Fi network (in Germany)

cc @daniloercoli

**Comment by daniloercoli** [comment] 2015-10-06 09:53
I think main problem here is with the connection that get stuck for some reason when there are pictures attached to the post, and both the image uploading and the Nosara client fail.
Nosara Client should not interfere with the app main queue, and in most of the cases the nosara tracking code should ping the server after the uploading is started. (The client ping the server at 30secs interval).

Is this happening on a self-hosted site or on wpcom, both?

**Comment by aforcier** [comment] 2015-10-06 09:58
@daniloercoli It's happening on both.

**Comment by daniloercoli** [comment] 2015-10-06 10:10
I just double checked the Nosara Client code, and it's unlikely it can stop the uploading of a picture. That exception, "Error while sending the events to the server" is correctly caught, and there should not be a crash of the app or of the picture uploading service.

Maybe the server cuts the connections due to many concurrent requests made from the app?
I can't replicate the issue here, but will try again.

**Comment by aforcier** [comment] 2015-10-06 10:23
I guess the Nosara error is just a symptom of the same problem then. I tried again and this time found this when uploading media directly to the media library:

<img width="951" alt="media-upload-fail-log" src="https://cloud.githubusercontent.com/assets/9613966/10306065/ab94ace6-6c24-11e5-93cc-b2fc1dc491c7.png">

The Nosara error log is printed out periodically, I suppose not only in relation to media requests.

Maybe this is just some strange router irregularity. I'll update the title and labels since it doesn't look like Nosara is related.

**Comment by rachelmcr** [comment] 2015-12-10 15:30
I haven't been able to reproduce the failure with NoHttpResponseException, either. I found one older user-reported issue (but no others) with this failure in the logs: https://android.forums.wordpress.org/topic/cant-connect-to-hosted-wordpress-site

We could keep trying to reproduce and investigate the issue. Alternately, given that we have very few user reports of this issue, we could close it for now and reopen if it becomes more of an issue later on.

**Comment by aforcier** [comment] 2015-12-10 17:17
I was never able to reproduce this anywhere but that one single Wi-Fi network, which makes me wonder if it was some sort of router hardware failure. I'm not sure we can do any more unless someone runs into this bug under more illuminating circumstances.

**Comment by rachelmcr** [comment] 2015-12-10 17:23
That was my thought, too. I'm closing this issue, and we can reopen if we get another report with more details for investigating it. Thanks!

**Closed by rachelmcr** 2015-12-10 17:23 UTC
Labels: Media, [Type] Bug
