### ISSUE TITLE
Crash on many versions: RuntimeException: Canvas: trying to draw too large bitmap

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5701] opened 2017-04-20 08:45 UTC
https://www.fabric.io/automattic/android/apps/org.wordpress.android/issues/584116ea0aeb16625b8423b7

Seems possibly related to trying to display very large images. Added the "Media" label for that reason. Feel free to remove if not relevant.

```
Fatal Exception: java.lang.RuntimeException: Canvas: trying to draw too large(132986880bytes) bitmap.
       at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:260)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1420)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
       at android.widget.ImageView.onDraw(ImageView.java:1286)
       at android.view.View.draw(View.java:18313)
       at android.view.View.updateDisplayListIfDirty(View.java:17291)
       at android.view.View.draw(View.java:18075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17286)
       at android.view.View.draw(View.java:18075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17286)
       at android.view.View.draw(View.java:18075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.draw(View.java:18316)
       at android.widget.ScrollView.draw(ScrollView.java:2774)
       at android.view.View.updateDisplayListIfDirty(View.java:17291)
       at android.view.View.draw(View.java:18075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17286)
       at android.view.View.draw(View.java:18075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17286)
       at android.view.View.draw(View.java:18075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17286)
       at android.view.View.draw(View.java:18075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.updateDisplayListIfDirty(View.java:17286)
       at android.view.View.draw(View.java:18075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
       at android.view.View.draw(View.java:18316)
       at com.android.internal.policy.DecorView.draw(DecorView.java:850)
       at android.view.View.updateDisplayListIfDirty(View.java:17291)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:666)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:672)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:780)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3093)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2889)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2483)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1490)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7027)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
       at android.view.Choreographer.doCallbacks(Choreographer.java:702)
       at android.view.Choreographer.doFrame(Choreographer.java:638)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by nbradbury** [comment] 2017-04-23 19:49
Looking at the various logs, this appears to be an editor issue rather than a media one. I'm seeing a lot of instances of `WordPress-EDITOR: Image tapped` before the crash - perhaps the `ImageSettingsDialogFragment` is trying to load a full-sized image?

**Comment by daniloercoli** [comment] 2017-06-08 11:05
Yes, `ImageSettingsDialogFragment` was loading the full picture. Closing this for now since these kind of bugs has been fixed along the way in Media prj.

**Comment by daniloercoli** [comment] 2017-06-28 08:13
It's still happening in 7.6. From the log I see the `Me` activity as the last one tracked.  Maybe it's a problem displaying the profile picture?

**Comment by struggggle** [comment] 2017-07-08 13:53
Dear developers,
I am analyzing WordPress using a static code checker. I find several code regions that loading full images from URL sites. Maybe one of them is the root causes of this bug. Maybe you should resize the image before displaying and optimize all of them. Below are the details:
(1) https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/services/AztecImageLoader.java#L25

(2) https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java#L141

(3) https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/ImageSettingsDialogFragment.java#L365

Hope I can help improve WordPress.

**Comment by daniloercoli** [comment] 2017-07-10 10:32
Thanks for your feedback @struggggle!
>(1) https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/services/AztecImageLoader.java#L25

Right. This is going to be changed soon. Anyway I will add a patch asap for those who already use Aztec in betas and alphas.

> (2) https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java#L141

This should not be a problem, since `downloadBitmap` is always called with a Photon URL. Photon pictures are small in size. https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/push/GCMMessageService.java#L578 
Also `downloadBitmap` catches exceptions. 

> (3) https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/ImageSettingsDialogFragment.java#L365

Right, this should not load the full size picture.

**Comment by zubairehman** [comment] 2017-08-30 07:12
**I my case, moving the (hi-res) splash bitmap from drawable to drawable-xxhdpi was the solution.**

I had the same problem. I didn't suspect my splash screen to be the problem, since it is displayed when the app is started, but it turned out the splash screen is the problem.

The splash screen in my case has xxhdpi resolution, and it was mistakenly placed in the drawable folder, instead of drawable-xxhdpi. This made Android assume the splash screen had mdpi resolution and scale the image to 3*3 times it's required size and trying to create a bitmap.

**Comment by mushtaq99** [comment] 2018-08-09 05:37
@hypest  did you solved the problem i am facing the same problem

Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@6d43381
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1271)
       at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:261)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1415)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:528)
       at android.widget.ImageView.onDraw(ImageView.java:1306)
       at android.view.View.draw(View.java:17588)
       at android.view.View.updateDisplayListIfDirty(View.java:16527)
       at android.view.View.draw(View.java:17338)
....

**Comment by hypest** [comment] 2018-08-09 12:39
👋 @mushtaq99 , I think `Canvas: trying to use a recycled bitmap` is most probably not related to the issue in this ticket.

**Comment by designsimply** [comment] 2019-07-11 22:33
**30-day impact:** ~7 per day
**Users affected:** 59 in the last 30d
**Last seen in:** 12.6

<sup>https://sentry.io/share/issue/06479f2a38234c8abad668f173724b9f/</sup>

**Comment by designsimply** [comment] 2019-10-10 22:47
**90-day impact:** ~6 per day
**Users affected in the last 90 days:** 161

<sup>https://sentry.io/share/issue/06479f2a38234c8abad668f173724b9f/</sup>

**Comment by designsimply** [comment] 2019-11-06 04:37
**90-day impact:** ~7 per day
**Users affected in the last 90 days:** 159
**Last seen in:** 13.4
**Limited to:** 

<sup>https://sentry.io/share/issue/06479f2a38234c8abad668f173724b9f/</sup>

**Comment by designsimply** [comment] 2019-11-14 21:59
> From the log (filtering on 7.6 only) I see the `Me` activity as the last one tracked. Maybe it's a problem displaying the profile picture?

I checked logs today, filtering for 13.5, and in 8 out of 13 of them it looked like a problem trying to display very large images for updated posts in the Reader. @daniloercoli I could use a gut check on that interpretation though. 🙂

**Comment by designsimply** [comment] 2019-12-04 23:28
**Users affected in the last 90 days:** 139
<sup>https://sentry.io/share/issue/06479f2a38234c8abad668f173724b9f/</sup>

I tried these steps to trigger a crash:

1. In the app, open the Reader stream for another site you're following where you can add a new post.
1. On the web, go to the site and add a new post with a very large image.
1. In the app, go to Reader and pull to refresh.

**Result:** no crash.

Can you suggest other testing scenarios to potentially try?

**Comment by designsimply** [comment] 2019-12-18 18:49
**Users affected in the last 90 days:** 154
<sub>https://sentry.io/share/issue/06479f2a38234c8abad668f173724b9f/</sub>

**Comment by jd-alexander** [comment] 2019-12-27 20:49
So based on my investigation I think the devices are operating in an environment with memory constraints and they are crashing when attempting to load a large image. Currently, we are using the device's viewport to calculate the image size that should be loaded and then passing the Photon URL generated from that size to Glide. To solve this we could 

1.   lessen the image quality.
2. Calculate the memory that will be needed to load the image and check the available memory and then utilize that value to determine the options that will be used to create the bitmap in a memory-efficient way. 

I haven't been able to reproduce this as yet, but I will keep on doing so. let me know if anyone has any thoughts on this so I can know if I should attempt any of the ideas I have shared.

**Comment by designsimply** [comment] 2020-01-24 00:48
**Users affected in the last 90 days:** 164
<sub>https://sentry.io/share/issue/06479f2a38234c8abad668f173724b9f/</sub>

**Comment by jd-alexander** [comment] 2020-03-16 17:14
An update. So I looked into this again. There's a crash I noticed that occurred because almost 15 images are present in a blog post and a user attempts to view them in the image preview. This causes 15 instances of the `MediaPreviewFragment` to be created and the app runs out of memory.

A solution for this case would be to limit the number of fragments that are loaded on-screen so that all instances don't have to be created especially because the user won't be viewing all the images at the same time.

**Comment by designsimply** [comment] 2020-05-01 20:23
[10](https://sentry.io/organizations/a8c/discover/results/?field=timestamp&field=release&field=os&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1021144835+release%3Aorg.wordpress.android-14.6.1&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29) events have been tracked for this crash in 14.6.1 since it was released 9d ago on Apr 22.

**Number of users affected in the last 90d:** 149
<sub>https://sentry.io/share/issue/06479f2a38234c8abad668f173724b9f/</sub>

**Comment by designsimply** [comment] 2020-05-19 16:55
[25](https://sentry.io/organizations/a8c/discover/results/?field=timestamp&field=release&field=os&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1021144835+release%3Aorg.wordpress.android-14.6.1&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29) events have been tracked for this crash in 14.7 since it was released 15d ago on May 4.

**Number of users affected in the last 90d:** 126
**Number of events in the last 90d:** 1300
<sub>https://sentry.io/share/issue/06479f2a38234c8abad668f173724b9f/</sub>

**Comment by designsimply** [comment] 2020-05-28 03:31
**Events in the last 90d:** 1300
**Events in the last 9d since 14.8 was released:** [21](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1021144835+version%3A14.8&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29)
**Users affected in the last 90d:** 123
<sub>https://sentry.io/share/issue/06479f2a38234c8abad668f173724b9f/</sub>

**Closed** 2020-06-05 00:00 UTC
Labels: Posting/Editing, [Type] Crash

**Comment by abdenourz** [comment] 2021-04-29 15:10
seems to the problem 
not working
