### ISSUE TITLE
Wrong Gravatar in Notifications

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5100] opened 2017-02-01 11:05 UTC
A user reported that they sometimes see one person’s Gravatar used for other people in their notifications stream. <can't attach the screenshot>.

I have not yet reproduced this issue, but the user says it happens consistently.

Maybe related to: https://github.com/wordpress-mobile/WordPress-Android/issues/4709

**Comment by nbradbury** [comment] 2017-02-01 16:19
When I looked into #4709, the problem _appeared_ to be that the cell containing the gravatar was recycled while the image request was still underway, so when the request completed it set the gravatar to the one requested prior to recycling. This is a tough one to reproduce but I have seen it happen.

**Comment by nbradbury** [comment] 2017-02-01 16:33
Notes:
* The same problem can be see in the reader's list of liking users
* Calling `setImageDrawable(null)` in `onBindViewHolder()` does not solve the problem
* Perhaps `setImageDrawable(null)` in `onViewRecycled()` would work?

**Comment by daniloercoli** [comment] 2017-02-01 18:23
Can't we keep a reference to the last requested URL in `ImageLoader.ImageListener` and compare it with `response.getRequestUrl()` in its `onResponse` method?

**Comment by daniloercoli** [comment] 2017-02-02 09:17
Hey @nbradbury - Would you mind to try this branch https://github.com/wordpress-mobile/WordPress-Android/tree/issue/5100-wrong-avatar to see if it fixes the issue?

**Comment by nbradbury** [comment] 2017-02-02 14:39
@daniloercoli I've been running that branch all morning and can't repro the duplicated avatars, but I'm also not seeing any instances where `mUrl` no longer matches `mRequestedUrl` so it would be premature to say the problem is solved.

**Comment by daniloercoli** [comment] 2017-02-02 17:09
@nbradbury Same here. I've tried proxied and throttled, both with no luck. Wasn't able to reproduce the issue.

You've mentioned above that `onDetechedFromWindow()` calls `cancel` on the underlying network call, and I checked with a breakpoint that the code is reached. It is, `cancel` is called, but I don't see any difference in Charles Proxy. Connections don't appear cancelled. All connections seems to go their way to the server, even those that should be cancelled. Resulting of this, on slow network connections, is a long delay for those gravatars that are actually on the screen.This is because all network connections are enqueued in the queue, and processed like sequentially, if you scroll down quickly the queue is saturated with all the gravatars.
Will try again tomorrow on a real device.

**Comment by nbradbury** [comment] 2017-02-03 10:58
Looking at the `ImageLoader` code, it doesn't look like canceling actually stops a request if it's underway. Instead, it removes the request from the queue and doesn't deliver the response.

Given that I don't think this would cause the wrong avatar (since the listener is never fired), although it certainly could cause the saturation you're seeing.

**Comment by daniloercoli** [comment] 2017-02-03 11:05
Yes, I've just tested on a real device with a different proxy software and saw the same issue. Anyway, I will open a "tentative" PR for this issue.

**Comment by maxme** [comment] 2017-02-16 13:04
Fixed via #5111

**Closed by maxme** 2017-02-16 13:04 UTC
Labels: Mobile Request, Notifications, [Pri] High, [Type] Broken Window, [Type] Bug
