### ISSUE TITLE
Featured Image Appears Blank in Post List in Certain Cases

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#8823] opened 2018-12-19 16:11 UTC
### Expected behavior

If a post has a featured image then, ideally, I'd expect it to display alongside the post in the app's post list.

If there are technical reasons an app can't display a post's featured image, then I wouldn't expect a blank space to display alongside the post in the post list.

### Actual behavior

If a third-party plugin is used to add a featured image from a URL, the app will display a blank space alongside the post in the post list. This blank space is where a featured image would usually appear.

### Steps to reproduce the behavior

1. Log into the /wp-admin area for a self-hosted within a web browser.
2. Install the [Featured Image From Url](https://wordpress.org/plugins/featured-image-from-url/) plugin.
3. Create a new post in the classic editor and add a featured image to it from a URL.
4. Save your changes and view the post in the app's post list.

Screenshot of the results:

![screenshot_20181219-160403](https://user-images.githubusercontent.com/2998162/50232232-5c556480-03a8-11e9-90b8-c26e35f14878.png)

##### Tested on Pixel, WordPress alpha-142, Android 9

This was first reported to us in 1648665-z.

Some similar past issues: https://github.com/wordpress-mobile/WordPress-Android/issues/6279, https://github.com/wordpress-mobile/WordPress-Android/issues/5197

**Comment by malinajirka** [comment] 2019-02-20 10:25
@SiobhyB Thanks for creating the issue! I've just tried to follow the provided steps and the image is correctly displayed. 

![screenshot_1550657636](https://user-images.githubusercontent.com/2261188/53084230-b2f23280-3500-11e9-9a57-58b04ebbe3e5.png)
- I created the site on http://poopy.life/
- I installed the plugin
- I created the post in Chrome (wpadmin) and I added a public image url from wikipedia
- I used Android 8 and 9 emulators

Can you please confirm the bug is fixed in the current beta version (10.8) or point me in the right direction how to reproduce it. Thanks!

**Comment by SiobhyB** [comment] 2019-03-05 15:17
@malinajirka: I just want through the steps to replicate again and can confirm this is now fixed. 🎉 Thank you!

**Comment by oguzkocer** [comment] 2019-03-06 05:23
@malinajirka This might be happening when the post doesn't have a featured image but a regular one in it. We try to show these images as featured and I think it might not be loading correctly in some cases. I am going to reopen it to make sure I won't forget to check it out. Feel free to ignore it for now.

**Comment by malinajirka** [comment] 2019-03-28 09:10
Good idea @oguzkocer !

I've tested the same steps, but I haven't put the image url into the "feature image from url" input, but into the post content area. The image is being displayed correctly.

![Screenshot_2019-03-28_at_08_43_49](https://user-images.githubusercontent.com/2261188/55144695-af764a80-5141-11e9-9a2f-e44cddb84475.jpg)

**Comment by malinajirka** [comment] 2019-04-08 08:58
@oguzkocer and I has decided to close this issue as we are not able to reproduce it. We'll re-open it if the issue is still present.

**Closed by malinajirka** 2019-04-08 08:58 UTC
Labels: Post List, [Type] Bug

**Comment by oguzkocer** [comment] 2019-04-08 15:43
Just to clarify, we have been testing this issue in our post filters branch and not `develop`. So, the issue might have been fixed in that branch only and it should be merged fairly soon-ish.
