### ISSUE TITLE
Reader images disappear

### ISSUE THREAD

**Issue by philipjohn** [wordpress-mobile/WordPress-Android#4984] opened 2017-01-04 09:42 UTC
### Expected behavior

When scrolling through the reader, featured images always appear

### Actual behavior

Sometimes images do not show on posts that come back into view, even if they were visible before they went out of view.

I've found two causes of this:

* Scrolling up and down the reader
* Returning from viewing a single post.

### Steps to reproduce the behavior

Scrolling:

1. Open the reader to "Followed Sites"
2. Scroll up and down through posts with featured images.

Single post:

1. Open the reader to "Followed Sites"
2. Open a single post
3. Press back to return to the reader.

##### Tested on Motorola Moto X Force, Android alpha-31

![screenshot_20170104-093510](https://cloud.githubusercontent.com/assets/136342/21638181/245fd232-d262-11e6-95b5-e511a5f47956.png)

**Comment by maxme** [comment] 2017-01-04 09:47
Duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/4951 - This should be fixed in alpha-32

**Closed by maxme** 2017-01-04 09:47 UTC
Labels: [Status] Duplicate
