### ISSUE TITLE
Duplicate posts in the post list after publishing

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5258] opened 2017-02-24 12:09 UTC
Steps:

1. Open the post list.
1. Create a new post and hit publish.
1. Go back to "My site".
1. Open the post list.
1. You should see a duplicated post (local only).

Might be a local id issue or a post list adapter quirk?

Note: the duplicated post is removed on refresh and that never happens if you don't go back to "My site" during upload.

Demo video: https://cloudup.com/c0WTpG7u5X1

**Comment by maxme** [comment] 2017-02-24 13:27
The duplicate post is in the DB:

<img width="737" alt="screen shot 2017-02-24 at 14 24 19" src="https://cloud.githubusercontent.com/assets/40213/23305006/f642edfe-fa9c-11e6-8af3-3c7aaa8accde.png">

I looked at the PUSH_POST action but we're correctly setting the local post id [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/5063be5c53aa238b2ddfdd1041d5957ec43c108a/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostRestClient.java#L159-L159)

**Comment by oguzkocer** [comment] 2017-03-01 09:59
I must have tried this out in different speeds for at least 15 times and can't reproduce it. It's either fixed or it doesn't happen every time or on all device types. Note that, I tested on both emulator and Google Pixel.

I did find another issue I can reliably reproduce, I'll open a new issue for it.

**Comment by oguzkocer** [comment] 2017-03-02 09:47
I just tried this again and still can't reproduce it. I am leaning towards closing it.

@maxme would you like to try again to see if you can reproduce it? Maybe there is another element to it that I am missing.

**Comment by maxme** [comment] 2017-03-02 09:48
I'll try again on a recent branch

**Comment by maxme** [comment] 2017-03-02 09:53
I was able to repro, same problem (duplicate post with the same remote post id)
<img width="473" alt="screen shot 2017-03-02 at 10 52 44" src="https://cloud.githubusercontent.com/assets/40213/23501984/676a187a-ff36-11e6-82bd-fbe397565016.png">

**Closed** 2017-03-06 07:08 UTC
Labels: fluxc-integration
