### ISSUE TITLE
Site Picker: Jetpack site missing from the site picker.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3952] opened 2016-04-12 01:37 UTC
This might be a bit of an edge case, but check this out: 
I have a ghost Jetpack site named "aerychtest-appfog".  The site no longer exists and I've never bothered clearing it from Jetpack because testing broken things is fun. ;) 

This site is still returned from the /me/sites REST API endpoint, is visible in the iOS app's list of blgos, and its visible in the Android app if I look under Notification Settings.  However, its absent from the site picker.  Is the site picker intentionally filtering out sites if Jetpack reports them as broken?  If so I'd expect it to be also absent from Notification Settings. 

Regardless, my expectation was to still see the site in the list.
### Notification Settings (Present)

![screenshot_20160411-202753](https://cloud.githubusercontent.com/assets/1435271/14447429/3efd65ec-0025-11e6-8f15-c4427b8da74d.png)
### Site Picker (Absent)

![screenshot_20160411-202735](https://cloud.githubusercontent.com/assets/1435271/14447434/46d2ebe8-0025-11e6-95ec-0a4b4413f06e.png)

**Comment by maxme** [comment] 2016-04-12 06:06
> However, its absent from the site picker. Is the site picker intentionally filtering out sites if Jetpack reports them as broken? If so I'd expect it to be also absent from Notification Settings.

We're not listing Jetpack sites at all in the Site Picker due to the use of XMLRPC calls only in certain part of the app. This won't be fixed until the integration of wpstores.

**Comment by lancewillett** [comment] 2016-05-09 21:20
+1 to showing Jetpack sites in the Site Picker — my current feeling was I had to go to the + (plus) icon and add via "Add self-hosted site" somehow. I think most authors probably won't notice right away unless they switch from the iOS or desktop app to managing with Android.

**Comment by rachelmcr** [comment] 2016-05-10 11:40
Related issue for showing Jetpack sites in the site picker automatically: https://github.com/wordpress-mobile/WordPress-Android/issues/3023

**Comment by daniloercoli** [comment] 2016-12-16 10:58
This is actually a duplicate of #3023. Closing this ticket and keep the other one open, even though both of them will be address with FluxC.

**Closed by daniloercoli** 2016-12-16 10:58 UTC
Labels: Jetpack, Site Picker, [Type] Bug
