### ISSUE TITLE
Notifications: Loses place in notifications after leaving/returning to the app

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#5732] opened 2017-04-24 16:03 UTC
### Expected behavior

I expect that if I am swiping through my notifications, leave the app, and then return to the app, I will return to the same notification where I left off.

### Actual behavior

If I am swiping through my notifications, leave the app, and then return to the app, I see the notification where I left off for a moment and then the screen refreshes. The refresh takes me back to the first notification I viewed.

h/t @catehstn for spotting this issue.

### Steps to reproduce the behavior

1. Open your notifications.
2. Tap to open a notification detail.
3. Swipe through several notifications.
4. Leave the app.
5. Return to the app and wait a few seconds.

Result: The screen refreshes and the first notification detail appears. (You can also see this refresh occur if you only opened one notification, but in that case nothing will change since you haven't swiped away from it.)

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-49.

**Comment by mzorz** [comment] 2017-11-14 13:12
This is a dupe of #5988 

Already addressed in https://github.com/wordpress-mobile/WordPress-Android/pull/6189

Just tested it and couldn't reproduce - even tried setting  the "don't keep activities" mode and confirm it stays at the right notification screen for both horizontal scrolling (that is, swiping left-right on the notification detail screen) and vertical scrolling in the Notifications tab in the app's main screen, retaining its position at all times.

Closing via #6189

**Closed by mzorz** 2017-11-14 13:12 UTC
Labels: Notifications, [Pri] Medium, [Type] Bug
