### ISSUE TITLE
NullPointerException: Error parsing reader interests

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#15912] opened 2022-02-08 11:02 UTC
**Sentry Url**: https://sentry.io/share/issue/485d1a2d35e2424aa69294a0882f5d05/
**User Count**: 28
**Count**: 1765
**First Release**: 19.0-rc-1
**First Seen**: 2022-01-12T01:15:21.109000Z
**Last Seen**: 2022-02-08T10:37:34Z
**24 Hours**: 277
**30 Days**: 1811

```
NullPointerException: Error parsing reader interests [{"slug":"love","title":"Love","score":110.7},[{"slug":"travel","title":"Travel","score":4446},{"slug":"photography","title":"Photography","score":4231},{"slug":"books","title":"Books","score":3922},{"slug":"art","title":"Art","score":3580},{"slug":"blogging","title":"Blogging","score":1963},{"slug":"technology","title":"Technology","score":1373},{"slug":"entertainment","title":"Entertainment","score":1261},{"slug":"politics","title":"Politics","score":1009},{"slug":"movies","title":"Movies","score":907}]] at index 1.
     at org.wordpress.android.ui.reader.repository.usecases.ParseDiscoverCardsJsonUseCase.parseInterestCard(ParseDiscoverCardsJsonUseCase.kt:63)
     at org.wordpress.android.ui.reader.repository.usecases.GetDiscoverCardsUseCase$get$2.invokeSuspend(GetDiscoverCardsUseCase.kt:46)
     at org.wordpress.android.ui.reader.repository.usecases.GetDiscoverCardsUseCase$get$2.invokeSuspend(GetDiscoverCardsUseCase.kt:46)
     at org.wordpress.android.ui.reader.repository.usecases.GetDiscoverCardsUseCase$get$2.invoke(null:8)
     at org.wordpress.android.ui.reader.repository.usecases.GetDiscoverCardsUseCase$get$2.invoke(null:4)
     at org.wordpress.android.ui.reader.repository.usecases.GetDiscoverCardsUseCase.get(GetDiscoverCardsUseCase.kt:33)
     at org.wordpress.android.ui.reader.repository.ReaderDiscoverDataProvider$reloadPosts$2.invokeSuspend(ReaderDiscoverDataProvider.kt:149)
     at org.wordpress.android.ui.reader.repository.ReaderDiscoverDataProvider$reloadPosts$2.invoke(null:8)
     at org.wordpress.android.ui.reader.repository.ReaderDiscoverDataProvider$reloadPosts$2.invoke(null:4)
     at org.wordpress.android.ui.reader.repository.ReaderDiscoverDataProvider.reloadPosts(ReaderDiscoverDataProvider.kt:148)
...
(16 additional frame(s) were not displayed)
```

**Comment by guarani** [comment] 2022-02-08 12:49
I was unable to reproduce this. I created a new account using WPAndroid 19.2-rc-1, navigated to Reader, and added the topics listed in the above JSON snippet (Love, Travel, etc).
I then browsed Reader's tab Following, added and removed topics in Reader settings, etc. I never saw a crash or any issues.

It might be worth checking with WPAndroid 19.1 (current production version) because the version I tested is still in beta.

**Comment by zwarm** [comment] 2022-02-08 15:35
This issue isn't resulting in a user crash. The error event is captured and explicitly sent to sentry. See `ParseDiscoverCardsJsonUseCase`.
```
} else {
                val errorMsg = "Error parsing reader interests $jsonInterests at index $i."
                if (BuildConfig.DEBUG) {
                    throw NullPointerException("Debug build crash: $errorMsg")
                } else {
                    crashLogging.sendReportWithTag(exception = NullPointerException(errorMsg), tag = AppLog.T.READER)**
                }
            }
```

It appears that the json is not formatted properly. It is being handled correctly within the app and not causing a user crash. I am moving the priority down to medium and removing the crash label. Will need to dig into the API.

Notice there are two arrays within the response, when there should only be one.

`[{"slug":"love","title":"Love","score":110.7},[{"slug":"travel","title":"Travel","score":4446},{"slug":"photography","title":"Photography","score":4231},{"slug":"books","title":"Books","score":3922},{"slug":"art","title":"Art","score":3580},{"slug":"blogging","title":"Blogging","score":1963},{"slug":"technology","title":"Technology","score":1373},{"slug":"entertainment","title":"Entertainment","score":1261},{"slug":"politics","title":"Politics","score":1009},{"slug":"movies","title":"Movies","score":907}]]`

**Comment by guarani** [comment] 2022-02-08 17:25
Thanks for verifying, @zwarm!

**Comment by zwarm** [comment] 2022-02-28 14:42
@bluefuton RE: this [comment](https://github.com/wordpress-mobile/WordPress-Android/pull/15773#issuecomment-1005288176) on #15773 that was looking for the API response. Thanks

**Comment by bluefuton** [comment] 2022-02-28 20:39
Thanks @zwarm. Looks like an array merge is going wrong somewhere.

Do we know the API request URL? That would help with debugging.

**Comment by zwarm** [comment] 2022-03-03 19:59
@bluefuton  - sorry for the delay - missed this in my inbox. 

`https://public-api.wordpress.com/wpcom/v2/read/tags/cards?refresh=1&locale=en_US&tags=tag1%2C+tag2%2C+tag3%2C`

The tags params will change depending on the user selection.

**Comment by bluefuton** [comment] 2022-03-03 21:46
Thanks @zwarm! To clarify, I know the usual request format but I'm interested in the specific combination of tags requested to produce the [broken JSON output](https://github.com/wordpress-mobile/WordPress-Android/issues/15912#issuecomment-1032742396).

**Comment by zwarm** [comment] 2022-03-04 14:36
>   ... I'm interested in the specific combination of tags requested to produce the [broken JSON output]

Sorry @bluefuton , we don't have the query params for this crash. I will look into logging additional information, but at the point of capturing the crash, the request is long gone.

**Comment by bluefuton** [comment] 2022-03-06 22:10
Thanks @zwarm. If we could add the API request URL to the logging, at least we'll have that info next time around to help us.

I'm not in a position to help out with the endpoint fix at the moment unfortunately. Do we have an API wrangler in the mobile division now?

**Comment by zwarm** [comment] 2022-03-07 21:29
@bluefuton - While testing my enhanced logging,  I randomly received the error using the following tags:  'love', 'travel', 'photography', 'books', 'art', 'blogging', 'technology', 'entertainment', 'politics', 'movies' . I could not repeat the error, as subsequent requests work fine. 

> Do we have an API wrangler in the mobile division now?

Yes, but I believe they are working on higher priorities. 

However, it is now hack week and my original hack item has been closed, so I am going to move onto this issue. 🤞  that I find a clue and am able to make a fix. If I come up with something on the API side, I'll _probably_ (more than _likely_) ask you for a review on the diff :)

**Comment by bluefuton** [comment] 2022-03-07 22:22
> I'll probably (more than likely) ask you for a review on the diff :)

Sounds good :)

**Comment by zwarm** [comment] 2022-03-13 22:56
FYI. I have a [diff](D76517-code) ready for the fix, but I need to finish up testing on iOS before it can land.

**Comment by bluefuton** [comment] 2022-03-21 11:56
> I could not repeat the error, as subsequent requests work fine.

I _think_ this could be different requests hitting different Elasticsearch shards (so producing different results).

> I have a [diff](https://github.com/wordpress-mobile/WordPress-Android/issues/D76517-code) ready for the fix

Great! :)

**Comment by zwarm** [comment] 2022-04-08 14:17
The diff has been deployed. Thanks for the assistance @bluefuton . Closing this issue.

**Closed as completed by zwarm** 2022-04-08 14:17 UTC
Labels: [Pri] Medium, Reader
