### ISSUE TITLE
IOOBE in SpannableStringBuilder: setSpan has end before start

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#8118] opened 2018-07-30 09:51 UTC
```
Fatal Exception: java.lang.IndexOutOfBoundsException: setSpan (733 ... 732) has end before start
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1258)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:102)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:50)
       at org.wordpress.aztec.AztecText.toPlainHtml(AztecText.kt:1138)
       at org.wordpress.aztec.AztecText.hasChanges(AztecText.kt:1117)
       at org.wordpress.android.editor.AztecEditorFragment.getContent(AztecEditorFragment.java:868)
       at org.wordpress.android.ui.posts.EditPostActivity.updatePostObject(EditPostActivity.java:1264)
       at org.wordpress.android.ui.posts.EditPostActivity.access$900(EditPostActivity.java:179)
       at org.wordpress.android.ui.posts.EditPostActivity$4$1.run(EditPostActivity.java:560)
       at java.lang.Thread.run(Thread.java:760)
```

5b4072a46007d59fcdd8e216-fabric
session:5B5E802D038100016C4DF6E3C5F0F70D_DNE_0_v2

**Comment by designsimply** [comment] 2019-05-07 18:59
Closing as a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/8107 (which references the same exact Fabric report number).

**Closed by designsimply** 2019-05-07 18:59 UTC
Labels: Aztec, [Type] Crash
