### ISSUE TITLE
After spamming comment app notifies "comment successfully approved!"

### ISSUE THREAD

**Issue by zandyring** [wordpress-mobile/WordPress-Android#8947] opened 2019-01-11 19:10 UTC
### Expected behavior
After I spam a comment via the app, I expect that if I get a notification, it would read "Comment successfully spammed"

### Actual behavior
After spamming a comment via the app, I get a notification that the comment was successfully approved. It hasn't been (fortunately).

### Steps to reproduce the behavior
Open app, navigate to Notifications.
Open a comment notification
Tap on Spam
Close the app or otherwise carry on with your day, and await the notification.

##### Tested on [device], Android [version]
App version: alpha-144
Moto x4 running Android 9 Pie

**Comment by designsimply** [comment] 2019-04-11 18:56
Moving to the `Prioritized` list so we can check up on this one and give it attention if spammed comments still misbehaving. Thank you for reporting this issue @zandyring !

**Comment by zandyring** [comment] 2019-04-23 17:20
Noting that the last time I spammed a comment on my phone, this DIDN'T happen - I assumed it was fixed!

App version now is Alpha-166
Android v9
Moto x4

**Comment by designsimply** [comment] 2019-04-23 17:26
Cool. In that case, we'll just want to test, verify, and close the issue. ☺️

**Comment by daniloercoli** [comment] 2019-04-24 10:50
I've spent hrs trying to debug this issue with poor results. 
The notifications and push notifications code is async and decoupled resulting in high difficulties when trying to debug to reproduce the problem.

I was able to get the notification only once - with an old version of the app - and it was saying something like "Comment approved". 
Tested several times, but not able to get any notification at the moment, nor the one that says "Comment successfully spammed", or the problematic one. When i mark a comment as spam, and close the app nothing happens. Same if I left the app open in foreground on the notifications screen.

Where does the message "Comment approved" is created/used in the global system notifications on the app side? cc @mzorz  The part of the app that uses this wording is the comment screen, where a Toast is shown with the "Approved|spammed" message when the action is taken.

**Comment by zandyring** [comment] 2019-04-24 13:42
> Tested several times, but not able to get any notification at the moment, nor the one that says "Comment successfully spammed", nor the problematic one. 

I also haven't gotten a "correct" notification when I spam comments. There's no notification at all.

**Comment by mzorz** [comment] 2019-04-24 14:33
hi 👋 been looking into this! Interesting indeed, and as rightfully described it's not easy to reproduce :).

#### Analysis
The only place where `Comment approved!` message notification is shown in code is (supposedly) when a notification's quick action has been triggered and [has completed](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java#L397).
I can think of the following situation as a possible case:
If the `NotificationsProcessingService` (used mainly for notifications quick actions processing) is running, which also means the class has been [registered with FluxC's dispatcher](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java#L148) and as such [`onCommentChanged()` subscription callback gets called not only for actions triggered from the service but also for any kind of actions on the FluxC database](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java#L620). If the network is slow enough, this could mean something you do to [moderate (approve/spam) a comment on the app's Notifications tab](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsListFragment.java#L529), after already having approved a comment as a quick action, will also get collected by the registered callback.
Furthermore, the callback assumes there are only effectively `like/reply/approve`  actions (as that's the design for quick actions), and maps [a successful FluxC level action `CommentAction.PUSH_COMMENT` to be equal to approving](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java#L624-L629), when it might actually not be the case.
Hence, tapping on a quick action and then opening the app while the action is taking place, and spaming something there can lead to this situation. Difficult to reproduce, but still plausible. There are still other reasons why the Service could still exist in memory even if not really running, and given it hasn't been destroyed it will still be "listening" to FluxC events, producing these notifications as well.

#### Solution
Been looking into FluxC's code to see if we can match the API responses to which notifications quick action triggered them, and it seems we do have `event.changedCommentsLocalIds` in the response's payload, so in theory it should suffice to be able to compare triggered actions and responses by their Comment's local ids to make sense of what to notify the user about and what not (that is, for the time being, we should only produce notifications for quick action buttons-triggered actions within the `NotificationsProcessingService`, and none in particular for handling those that are triggered from the app's main screens).
Even if not easy to reproduce, I think we can surely add this check as it's reasonable to add anyway - I'll try and put a PR with this shortly 👍

**Comment by daniloercoli** [comment] 2019-04-24 15:40
> Hence, tapping on a quick action and then opening the app while the action is taking place, and spaming something there can lead to this situation. 

Just to report that I was able to reproduce the problem yesterday, unfortunately only once, and on an old version of the app, without using Quick Actions. I was manually testing the app, and i'm sure I didn't use Quick Action buttons since was in the app and tapped on the spam button in notification details screen, and send back the app to BG.

The message "Comment approved" was there in the notification center, and it was very alarming from a user point of view. I don't remember if I swipe over this new notification, or it disappeared automatically (because of a badge reset).

**Comment by mzorz** [comment] 2019-04-24 16:03
Thanks for the comment @daniloercoli ! That reinforces that it's definitely coming from FluxC registered callback in `NotificationsProcessingService` though  (because it's the place where that notification can only come from) so, will put a PR along those lines. Will also try to reproduce as well 👍

**Comment by daniloercoli** [comment] 2019-04-24 16:23
Yes, @mzorz it is the service.... I was able to reproduce it once again while testing other things 🚒 

Steps to repro:
- Make a comment with an external account (the comment should go under moderation)
- Make another comment with the same account is fine. (the comment should go under moderation)
- Open the app without going via the notification center and go to Notifications
- Open a notification and mark it as spam
- Send the app to GB
- Wait.... you should see the notification with "comment approved" text, appearing for a couple of secs. code executed: https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java#L628

**Comment by mzorz** [comment] 2019-04-24 17:46
Awesome! Thanks for the steps to repro! :D

**Closed** 2019-05-02 11:23 UTC
Labels: Notifications, [Type] Bug
