### ISSUE TITLE
Reader: Get correct subscriber count for sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#9371] opened 2019-03-06 13:09 UTC
### Expected behavior

I expect the subscriber count on the site Reader feed in the app to match the count I see in the web Reader.

### Actual behavior

The subscriber count doesn't always match what I see in the web Reader.

The discrepancy seems to be from the endpoint used. The web Reader seems to use the `/read/sites/$site` endpoint for sites (although it also [distinguishes between the subscriber counts for sites and feeds](https://href.li/?https://github.com/Automattic/wp-calypso/blob/df8fe9e82dae71d8df9b78fe7a725e04e4067311/client/blocks/reader-feed-header/index.jsx#L39)) whereas the app is using `/read/feed/$feed_url_or_id`. For some reason those endpoints return different subscriber counts for the same site.

### Steps to reproduce the behavior

1. In the web Reader, go to the Search: https://wordpress.com/read/search
2. Search for a site.
3. In the search results, select and view the site feed. Note the subscriber count.
4. In the app, open Reader > Search.
5. Search for the same site.
6. In the search results, select and view the site feed. Note the subscriber count.

For example, the en.blog.wordpress.com web feed: https://wordpress.com/read/feeds/25823

![screenshot 2019-03-06 12 58 34](https://user-images.githubusercontent.com/8658164/53882962-b06aff00-400f-11e9-90c6-2833eb1c481c.png)

Compared to the app feed:

![screenshot_20190306-125859](https://user-images.githubusercontent.com/8658164/53883480-04c2ae80-4011-11e9-8f99-ae6ea9aae920.png)

##### Tested on [moto e5 play], Android [8.1.1], WPAndroid [alpha-155]

h/t @charliescheer for the initial report (internal ref: p4a5px-2lS-p2)

**Comment by rachelmcr** [comment] 2019-03-06 13:14
Note that the same issue occurs if you follow the site and view the site feed from your Followed Sites list.

This differs from the iOS behavior, which shows the correct subscriber count in that case.

**Comment by rezzap** [comment] 2019-03-11 20:16
We have another report of this here it seems: 1859508-zen

The user recently changed the site address and after doing so the follower count in the app shows only 2 followers while the browser reader version shows the correct 2,338 followers.

**Comment by charliescheer** [comment] 2019-06-05 22:16
another report here 2087171-zen

**Comment by malinajirka** [comment] 2019-08-14 07:25
This is an interesting issue, but tbh I'm not sure what is the proper solution, since I don't know the history.

We get the subscribes count from three endpoints in the app:
1. /read/sites/$site
2. /read/feed/$feed_url_or_id
3. /read/following/mine
The subscribes counts from `1.` and `3.` seems to be in sync. However, the count from `2.` tends to be higher 🤷‍♂ .

[The logic in the app](https://github.com/wordpress-mobile/WordPress-Android/blob/661a8964c8859b8216859641bfe8cd6addead176/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSiteHeaderView.java#L107) is pretty simple. If we have `feed_id` use the `2.` endpoint. If we don't have `feed_id` use `1.` endpoint.

The difference in the number of subscribers can be easily reproduced on Discovery blog.
![subscribers](https://user-images.githubusercontent.com/2261188/63001296-a0cfcc00-be73-11e9-8100-5fed7d8e86b5.gif)
As you can see on the gif, we show different counts even within the app. Depending on whether you are looking at a site or a feed. Which from user's (and even mine) point of view are the same thing, but apparently there is a difference:).

All in all I believe this issue should be fixed on the server side. Unless I'm missing something, imho all three endpoints should return the same subscribers count. 

Another solution is to stop using `2` endpoint, but I'm worried to make such change without completely understanding the context.

@nbradbury Do you by any chance remember some details which might help us resolve this issue? Thanks!

**Comment by nbradbury** [comment] 2019-08-14 09:17
> Do you by any chance remember some details which might help us resolve this issue?

I remember that there were always issues with feeds vs sites, but I don't remember the details (it's been a while!). Probably best to ask in the Reader P2 or Slack channel (I'll send you links privately).

**Comment by bluefuton** [comment] 2019-08-23 02:42
Thanks for reporting this @rachelmcr and for writing it up on +readersquad @malinajirka.

I've just shipped D31816-code which enables the `/read/feed/` endpoints to return the site's subscriber count where available. The counts should now be consistent between the site and feed endpoints.

**Closed by bluefuton** 2019-08-23 02:42 UTC
Labels: Mobile Request, Reader, [Type] Bug
