### ISSUE TITLE
IllegalStateException: Site already exists - seems like an issue with domain suggestions endpoint

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13417] opened 2020-11-18 09:09 UTC
**Sentry Url**: https://sentry.io/share/issue/0ea7aaaad4c24aa7aa4efe640a719494/
**User Count**: 290
**Count**: 1941
**First Release**: org.wordpress.android-12.6
**First Seen**: 2019-06-19T13:33:15Z
**Last Seen**: 2020-11-18T07:40:42Z
**24 Hours**: 6
**30 Days**: 119

```
IllegalStateException: Site already exists - seems like an issue with domain suggestions endpoint
     at org.wordpress.android.ui.sitecreation.services.SiteCreationServiceManager$createSite$1.invokeSuspend(SiteCreationServiceManager.kt:132)
```

**Comment by renanferrari** [comment] 2020-11-18 23:42
Hey @malinajirka, would you mind looking into this? It seems like you have worked around the area of the codebase that is coming up in the logs and would have the necessary context to better evaluate this issue.

I'm labeling this issue as medium priority ([high severity, low impact](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/docs/issue-triage.md#prioritization)) but feel free to change it as you see fit.

**Comment by designsimply** [comment] 2020-11-19 04:18
Note: I've already tested signup for 16.2 beta testing and didn't spot a crash in the domain suggestions in my test. I did notice that free .blog subdomains started appearing for me in this release (scroll to 2:07 in [this video](https://cloudup.com/cxsy1kpDJ2m) to see what I mean) and they weren't there in the 16.1 or 16.0 releases (and probably others as well). Should I expect to see those suggestions or only *.wordpress.com domain suggestions in the site creation flow?

**Comment by malinajirka** [comment] 2020-11-19 12:11
Thanks for the ping;).

@designsimply It seems the link to the video is broken - it targets an ios ticket with a video which lasts only a few seconds.

AFAIR `.blog` domains should appear in all releases if you select "Blog" site type. They shouldn't appear for other site types. 

There was an API issue a year ago where they stopped appearing for a couple of weeks/months (more info p99Zz8-SA-p2). But that was fixed almost a year ago. Are we sure that .blog domains were not being suggested in 16.0 and 16.1. AFAIK this is all driven from the API, so the app version shouldn't change what we display on the UI.

As for the crash itself. AFAIK this crash can appear in the app in two scenarios:
1. Two users pick the same domain name in about the same time and they both hit "Create Site" button. Only the first user gets the domain and the second one gets the exception.
2. The suggested domains API endpoint returns a domain which is already taken.

It's a bit difficult to know which of these is happening and trying to find a bug on the API without even being sure there is a bug might be a waste of time. So I'd suggest improving the way we handle this scenario in the apps [here](https://github.com/wordpress-mobile/WordPress-Android/blob/33e77f6dc9c8e98409b0526c43c40596237bdc5a/WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceManager.kt#L132). We could redirect the user back to the "select domain" screen and show an error message saying that the selected domain was not available. Having said that, I don't remember the code well enough to estimate such task. I can look into it during my groundskeeping in two weeks.

**Comment by designsimply** [comment] 2020-11-20 22:45
> @designsimply It seems the link to the video is broken - it targets an ios ticket with a video which lasts only a few seconds.

Thanks for catching that! It was an incorrect copy/paste and I've now fixed the link in the previous comment.

> Are we sure that .blog domains were not being suggested in 16.0 and 16.1?

I record my signup tests from beta testing most of the time. Here are two example videos from the past few releases. Note that these were either installed from the Play Store via the beta program or by using the APK from the GitHub releases page (probably this).

* https://cloudup.com/cToXZ6Mb5ps (v16.1-rc-1, scroll to 2:52)
* https://cloudup.com/czr3RBmwPnG (v16.0-rc-1, scroll to 2:14)
* https://cloudup.com/criFqqp_Q5i (v15.7-rc-1, scroll to 2:20)

**Comment by malinajirka** [comment] 2020-11-23 09:00
> I record my signup tests from beta testing most of the time. Here are two example videos from the past few releases. Note that these were either installed from the Play Store via the beta program or by using the APK from the GitHub releases page (probably this).

It seems none of the sites created on these videos is a Blog (2x professional, 1x blank canvas) -> so IMO it's expected that .blog domains are not being suggested. Wdyt?

**Comment by designsimply** [comment] 2020-11-29 21:40
You are correct! This makes sense now. I wasn't making the connection that only the Blog option in the create site flow would show .blog domain suggestions—in my mind, blank (and all of them actually) would show .blog suggestions. Heh. 

Thank you for the explanation @malinajirka. I will add this issue to our Groundskeeping project board since you mentioned you'd pick it up in the next rotation. 👍

**Comment by designsimply** [comment] 2020-11-29 21:45
**Events in the last 90d:** 1,900
**Users affected in the last 90d:** 296
<sub>WORDPRESS-ANDROID-22Z: https://sentry.io/share/issue/0ea7aaaad4c24aa7aa4efe640a719494/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1077609763&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/100554312-1a4e2200-3251-11eb-88d1-753e8a8f8f14.png)</a>

**Comment by malinajirka** [comment] 2020-11-30 17:21
The root cause of these crashes is explained and fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/13500.

**Closed as completed** 2020-12-02 11:30 UTC
Labels: [Pri] Medium, [Type] Crash, Site Creation
