### ISSUE TITLE
Hide stats for users who are not admins/editors

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#6159] opened 2017-06-27 09:14 UTC
This one comes from a ticket in Calypso: Automattic/wp-calypso#8078

### Expected behavior
Stats should be hidden for non-admin/editor roles on .com sites.

### Actual behavior
Stats are not hidden for non-admin/editor roles on .com sites.

### Steps to reproduce the behavior
1. Sign in as a contributor to a .com site and notice that `Stats` is still available

**Comment by rachelmcr** [comment] 2017-11-13 16:03
Note that the related Calypso issue is a suggestion that will change the expected behavior. (Current expected behavior is that all members of the site have access to stats, per the [user roles](https://en.support.wordpress.com/user-roles/).)

Since stats are currently expected to be accessible for all members on .com sites, I'm going to go ahead and close this issue. We can reopen if a decision is made to change the .com behavior.

**Closed by rachelmcr** 2017-11-13 16:03 UTC
Labels: Low Hanging Fruit, [Pri] Low
