### ISSUE TITLE
Reader: Reader Blog post's sometimes appear out of order

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#4598] opened 2016-10-04 08:39 UTC
### Expected behavior
Posts in Reader Blog view of followed site appear in order of publication.

### Actual behavior
In some cases posts in Reader Blog view of followed site appear in out of order.

### Steps to reproduce the behavior

Here is the video that illustrates problem: 
https://cloudup.com/cOpwyYiRFrr

Open "Followed Sites" tab in reader.
Click on the blog name (pick one with lot's of posts) of a a post to open Reader Blog screen.
Look at post dates to make sure they are in correct order.
Open first post, wait for it to load.
Return to Reader Blog screen.
Notice how the lists changes and some posts are displayed without chronological order.

PS. Sometimes it takes couple of tries to reproduce this behaviour.

Tested with alpha-23 on Nexus 5x 6.0.0

**Comment by rachelmcr** [comment] 2016-10-05 13:31
This looks like a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/4585. Closing as a duplicate; please reopen if that issue doesn't cover the behavior you're seeing.

**Closed by rachelmcr** 2016-10-05 13:31 UTC
Labels: Reader
