### ISSUE TITLE
Reader: Can't unfollow site that was followed in Calypso Reader from post card

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#13601] opened 2020-12-14 23:04 UTC
Steps to reproduce:
- Clear the app data.
- Follow a wpcom site in Calypso.
- Refresh the Following tab in the app's Reader.
- Confirm that posts from followed iste have loaded into Reader.
- From the dropdown menu of the post from Followed site try to unfollow it.
- Confirm that site was not unfollowed (check in Calypso or Reader Settings).
- Unfollow site in Reader Settings and confirm that it was unfollowed in Calypso and it's posts are gone from the Followed tab in the app.

I have a feeling that the response of [this](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/services/update/ReaderUpdateLogic.java#L298) method does not include a feed ID, which we use to determine if the site is followed.

**Comment by designsimply** [comment] 2020-12-15 03:46
I noticed that in https://github.com/wordpress-mobile/WordPress-Android/issues/11358 it says the expected behavior is:

> In Reader > Settings > Followed Sites, when unfollow a site and make a configuration change, we want the unfollowed site to remain listed.

It's confusing though. @develric can you help me understand the intended behavior? I have seen the behavior @khaykov reported above and had assumed the purpose was to give people time to re-follow a site if they unfollow it by mistake, but that's really only an assumption I had made on my part.

Also 🙂   https://github.com/wordpress-mobile/WordPress-Android/issues/11856 might be worth a look if you're fiddling with the follow/unfollow actions.

**Comment by develric** [comment] 2020-12-15 14:26
Hey @designsimply 👋 . 

>had assumed the purpose was to give people time to re-follow a site if they unfollow it by mistake

Yep that is correct. Currently we keep a site in the list when unfollowed in case the user changes his mind and we remove it once the user leave that screen; what happens is that we end up removing it from the list also on config changes in that same screen that seems an unwanted behaviour. 

Maybe it's superfluous but to be sure we are on the same page 😄 , just want to notice that the #11358 is related to the Followed Sites list in the reader settings (that seems to work for Klym), while if I'm not wrong, the issue here is in changing follow site state in the reader post cards menu like here

<p align=center><image src="https://user-images.githubusercontent.com/47797566/102224769-a8c7d200-3ee6-11eb-890c-dd06ee712ffe.png" width=300/></p>

UPDATE: added the above note in the original issue so to make it clearer.

**Comment by develric** [comment] 2020-12-15 15:09
Was thinking to the #11856 and I remember that I noticed something similar at some point in the past where the followed site button is disabled while waiting for the response confirmation from the endpoint, that can take some time. Not sure how well it fits with the current implementation of the follow site button behaviour in the various app places, but wondering if we should use a similar approach to what we did with the following conversation button recently, where we present a `shimmer` effect to the user while waiting for the endpoint response like here below. wdyt?

<p align=center><image src="https://user-images.githubusercontent.com/47797566/102232695-bcc40180-3eef-11eb-9935-f2827c15843f.gif" width=300/></p>

**Comment by khaykov** [comment] 2020-12-15 18:41
As @develric said the issue is in changing the Follow state from the post menu. The problem is not that the posts remain in the Reader (that's expected) but that the site is not actually being Unfollowed.

**Comment by designsimply** [comment] 2020-12-16 00:00
Okay! Yeah, I think it can actually be kind of hard to tell whether something really was unfollowed in this context. 🙂

Thank you everyone for the explanations!

> wondering if we should use a similar approach to what we did with the following conversation button recently, where we present a shimmer effect to the user while waiting for the endpoint response

I totally noticed that tapping the "following conversation" felt like it worked a million times better when I tested it in beta, so I am in favor of this. 😊

**Comment by daniloercoli** [comment] 2024-02-27 16:13
I was unable to reproduce the problem on version 24.2 and later. Closing this issue.

**Closed as completed by daniloercoli** 2024-02-27 16:13 UTC
Labels: [Type] Bug, [Pri] Low, Reader
