### ISSUE TITLE
Some notification badges are not visible in the first load

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#12629] opened 2020-08-10 20:56 UTC
We got a report that some notification badges are not visible in dark mode (10y anniversary and 100 likes were mentioned).

[![Image from Gyazo](https://i.gyazo.com/ad90524bf7b97ad0c0b2eba879e1eaee.png)](https://gyazo.com/ad90524bf7b97ad0c0b2eba879e1eaee)

### Expected behavior
All notification badges are visible in both dark and light modes.

### Actual behavior
Some notification badges are not visible in dark mode.

### Steps to reproduce the behavior
I was able to reproduce this only once, by opening a plan related notification from the `Unread` tab. After I opened notification again from `All` tab the badge was visible.

Additional info:
- Not sure if the badge type matters for this.
- I looked a the code that loads badge image and did not see anything suspicious or related to dark mode or theme change.
- The person who reported the issue mentioned that they had an automatic dark/light mode switch on their device.

The original report is from Pixel 3 XL, Android 10 (API 30), WPAndroid alpha-235

The only time I was able to reproduce this issue was on Pixel 2, API 29 emulator.

**Comment by designsimply** [comment] 2020-08-14 02:43
I saw this problem while testing notifications in WPAndroid 15.5-rc-1. My device appearance is set to Dark Theme and the App Settings > Appearance in WPAndroid is set to System Default. I also observed that if I re-visited the same screen in Dark Theme later that the badge appeared normally. Light Theme seems fine regardless.

<img src="https://user-images.githubusercontent.com/1119271/90208183-6f028580-dda5-11ea-92dc-d7308c9db711.jpg" width="270" alt="Screenshot_20200812-115013"> <img src="https://user-images.githubusercontent.com/1119271/90208182-6e69ef00-dda5-11ea-8f52-06f28107ad8c.jpg" width="270" alt="Screenshot_20200812-115025">
<p style="clear:both;"><sup>Tested with WPAndroid 15.5-rc-1 on Pixel 3 Android 10.</sup></p>

**Comment by develric** [comment] 2021-04-19 21:33
Just noting this seems to be still valid; I was only able to get it once in current develop (at this point in [history](https://github.com/wordpress-mobile/WordPress-Android/tree/a860d8b29eb097aed016d28092021c4fa756a2c4)) with dark mode as well.

<p align=center><image src="https://user-images.githubusercontent.com/47797566/115306020-84675500-a167-11eb-9020-b605e068fabf.png" width=300/></p>

**Comment by thehenrybyrd** [comment] 2022-11-08 08:22
I wasn't able to reproduce (with a "first post" notification) in WP Android 21.1-rc-2. 
I created a new site, published the first post, and checked it initially from the "unread" tab. The notification icon loaded just fine.
Since this appears intermittent, I'll leave the issue open for now. However, if it becomes stale again with no further reports it should be closed.

**Comment by antonis** [comment] 2024-03-04 16:32
I was able to reproduce on light mode too


https://github.com/wordpress-mobile/WordPress-Android/assets/304044/14eefb20-0808-4d1f-bf16-8dda6992233f

I think the issue doesn't have to do with the dark or light mode but with a failure to refresh the screen after the image is downloaded. When you go back to the list and in the notification the image loads correctly.

**Comment by antonis** [comment] 2024-03-08 14:35
Changing the title of the issue from
> Some announcement badges are not visible in dark mode

to `Some notification badges are not visible in the first load` for accuracy

**Comment by antonis** [comment] 2024-03-15 07:15
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/20431

**Closed by antonis** 2024-03-15 07:15 UTC
Labels: [Type] Bug, [Pri] Low, Notifications, Dark Mode
