### ISSUE TITLE
Previous Paragraph block removed when adding an Image block on a Jetpack site

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#14915] opened 2021-06-24 03:43 UTC
It was reported in 4079191-zd-woothemes that adding an Image block after a Paragraph block will remove the Paragraph block in the editor.

I was able to reproduce this on a Jetpack site but not on a WordPress.com simple site.

### Expected behavior

I expect the Paragraph block will not be removed after I add an Image block after it.

### Actual behavior

The Paragraph block was removed when I added an Image block underneath it.

### Steps to reproduce the behavior

1. Select a Jetpack site in the app.
2. Go to My Site > Blog Posts and create a new post.
3. Type the post title, type some text on the first Paragraph block and tap the space below the block to create a second empty Paragraph block.
4. Tap "+" icon and select the Image block to add an image.
5. See that the first Paragraph block was removed and the Image block added through Step 4 is the first block in the editor.

**Screen recording**

https://user-images.githubusercontent.com/40906847/123199100-cfdc0d80-d4e0-11eb-81ba-361a761650b5.mp4

##### Tested on OPPO Reno 4, Android 11, WPAndroid 17.6-rc-3

**Comment by thehenrybyrd** [comment] 2021-06-24 10:29
I was able to reproduce this as well on a Jetpack site, with the Image Block as well as Spacer Block (or any other block). As soon as I tap the "+", the insertion point appears just after the title, and my initial paragraph block is removed.

These exact steps don't do it for me on a WordPress.com site, however if I tap the title and then the empty paragraph block  before adding the image block (or other block), I can reproduce. This would be similar to the instructions to reproduce in https://github.com/wordpress-mobile/gutenberg-mobile/issues/3636

This will likely be fixed with: 
https://github.com/WordPress/gutenberg/pull/32831 and https://github.com/WordPress/gutenberg/pull/32110
but we should make sure to test with Jetpack as well when the fix comes.

**Comment by dcalhoun** [comment] 2021-06-24 15:01
I was also able to reproduce this specific issue using WPAndroid 17.6-rc-3. Notably, as already mentioned, reproducing does not require blurring the post title for Jetpack sites. 

I was **not** able to reproduce the issue on the latest WPAndroid `release/17.6` branch, so https://github.com/WordPress/gutenberg/pull/32831, which should be include in the next WPAndroid 17.6 release candidate, appears to fix this Jetpack site issue.

**Comment by dcalhoun** [comment] 2021-06-24 17:29
WPAndroid 17.6-rc-4 is now available. I was unable to reproduce this issue in that latest release candidate. 🎉

**Closed as completed** 2021-06-24 17:51 UTC
Labels: [Type] Bug
