### ISSUE TITLE
Segfault Crash

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15235] opened 2021-08-24 10:31 UTC
**Sentry Url**: https://sentry.io/share/issue/ab1e2ab600d540aa964a361d54a1dd5d/
**User Count**: 582
**Count**: 1431
**First Release**: 17.7-rc-2
**First Seen**: 2021-07-04T09:26:28.771000Z
**Last Seen**: 2021-08-24T09:24:50Z
**24 Hours**: 24
**30 Days**: 1234

```
null: Segfault

```

Saw this one on Sentry today, quite an obscure one with not much data nor stacktrace to help 😒 … but seems the events are still steadily happening and building up since 17.7, so figured it could be worth tracking and checking.

**Comment by ravishanker** [comment] 2021-08-25 00:10
It is hard to reproduce issue.   Need to monitor and investigate further.   

Most likely suspect is a [null pointer dereference](https://source.android.com/devices/tech/debug/native-crash).  Possibly in [parsing](https://stackoverflow.com/questions/54999797/signal-11-sigsegv-code-1-segv-maperr-crash-only-on-some-devices) a Gson [somewhere](https://stackoverflow.com/questions/47836896/signal-11-sigsegv-code-1-segv-maperr-fault-addr-0x7f4485ff1820/47923830#47923830) using Java classes

**Comment by fluiddot** [comment] 2021-11-15 15:37
Not sure if the original issue was related to the Sentry library but I recently noticed that the stacktrace references the method `sentry_get_modules_list` which is defined by Sentry.

I looked for opened/closed issues on the Sentry repository ([`getsentry/sentry-java`](https://github.com/getsentry/sentry-java/issues)) that might be related and found [this one](https://github.com/getsentry/sentry-java/issues/1549) with a similar problem. It states that the crash was addressed in [version `5.1.0`](https://github.com/getsentry/sentry-java/releases/tag/5.1.0) by bumping `sentry-native` to 0.4.12. The current Sentry version defined in `Automattic-Tracks-Android` is `5.0.1`, so I'm wondering if bumping Sentry to version `5.1.0` or newer might help.

**Comment by fluiddot** [comment] 2021-11-26 15:01
I see a reference to Hermes (`facebook::hermes::detail::hermesFatalErrorHandler`) in a recent [Sentry event](https://sentry.io/share/issue/ab1e2ab600d540aa964a361d54a1dd5d/), so potentially this crash could be related to React Native library. It might be a coincidence but, the first event was originated in version `17.7` which is also the one where the React Native upgrade to version `0.64` was released 🤔 .  

<img width="246" alt="Screenshot 2021-11-26 at 15 58 32" src="https://user-images.githubusercontent.com/14905380/143599594-8b0ac065-f209-4dec-9096-445450de2214.png">
<img width="265" alt="Screenshot 2021-11-26 at 15 58 38" src="https://user-images.githubusercontent.com/14905380/143599603-0487373e-9a7e-4632-a608-0f70f03c40cb.png">

**Comment by ParaskP7** [comment] 2022-02-14 14:07
![image](https://user-images.githubusercontent.com/9729923/153878552-c0b8180e-4b73-42ed-9e2a-f1f4c26e39a2.png)

FYI: It seems that [this event](https://sentry.io/organizations/a8c/issues/2492758389/?environment=release&project=1438088&query=release%3A19.1.1+error.unhandled%3Atrue&sort=freq) has been spiking for the past [3 months](https://sentry.io/organizations/a8c/discover/results/?end=2022-02-14T14%3A01%3A46&field=title&field=release&field=environment&field=user.display&field=timestamp&name=android%3A%3AThread%3A%3A_threadLoop&project=1438088&query=issue.id%3A2492758389&sort=-timestamp&start=2021-11-16T14%3A01%3A46&yAxis=count%28%29). Maybe it is worth to investigate it again as part of groundskeeping, wdyt? 🤔

**Comment by ovitrif** [comment] 2022-08-05 14:47
@thehenrybyrd Following up on the internal discussion (↗️ ref: pbArwn-52u-p2#comment-6335) we can see in the graph of the [past 3 months](https://sentry.io/organizations/a8c/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=android%3A%3AThread%3A%3A_threadLoop&project=1438088&query=issue.id%3A2492758389&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29) that the [Sentry event](https://sentry.io/organizations/a8c/issues/2492758389/?environment=release&project=1438088&query=release%3A19.1.1+error.unhandled%3Atrue&sort=freq) has indeed started to show a recent downturn, therefore we might consider re-evaluating its priority in the near future 👍 .

<img width="811" alt="90daystrend" src="https://user-images.githubusercontent.com/4588074/183100878-6170d154-50be-4113-92c6-3a0dffc78a70.png">

**Comment by thehenrybyrd** [comment] 2022-08-11 07:33
Thanks for following up on this and giving an update @ovitrif! As we're seeing a significant decrease, I'll lower the priority on this one to low.

**Comment by antonis** [comment] 2024-03-22 15:27
The issue exists since version 17.7 and the crash rate remains low

**Comment by irfano** [comment] 2024-05-29 13:34
This occurred 20 times on May 26 and became one of the top crashes.

**Comment by antonis** [comment] 2024-05-29 13:43
> This occurred 20 times on May 26 and became one of the top crashes.

Checking the events I think they are all from the same user running WordPress `19.2` on a [SM-S908B
device](https://www.gsmarena.com/samsung_galaxy_s22_ultra_5g-11251.php) with Android 14 :(

**Comment by irfano** [comment] 2024-05-30 06:15
Fixed by #20911

**Closed as completed by irfano** 2024-05-30 06:15 UTC
Labels: [Pri] Low, Core, [Type] Crash
