### ISSUE TITLE
Reader: Can't follow some sites from the reader settings screen.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4001] opened 2016-04-22 15:16 UTC
I noticed this trying to follow a particular site.  To reproduce: 

Open the reader
Open the reader's settings screen
At the bottom of the screen try to follow either: `http://arstechnica.com` or `arstechnica.com`. 
I get an error saying `unable to follow this blog`

I tried again with mashable.com and got the same error. 

Both can be followed from the web.

**Comment by nbradbury** [comment] 2016-04-22 18:02
It looks like this is caused by `read/feed/{url}` failing. For example, `read/feed/http%3A%2F%2Fmashable.com` currently fails with "undefined - missing_url." I'm checking with reader squad about this endpoint.

**Comment by nbradbury** [comment] 2016-04-22 20:05
Problem was fixed on the backend.

**Closed by nbradbury** 2016-04-22 20:05 UTC
Labels: Reader, [Type] Bug
