### ISSUE TITLE
Login - "Logging in" progress dialog is never dismissed if you left the app during login

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6700] opened 2017-10-09 12:57 UTC
If you switch to another app when the app is actually logging you to your site ( "Logging in" progress dialog is on the screen) there is no way to dismiss the progress dialog, and you are stuck on that screen. Doesn't matter how long you wait.

![device-2017-10-09-145603](https://user-images.githubusercontent.com/518232/31339103-139f7b7a-ad02-11e7-853e-df928d563bcf.png)

Fix is to close the app and restart it from scratch. Once restarted the app, you are already logged to WP with the credentials given on the step above. 

I bet there is a receiver that is un-registered on backgrounding the app.

**To reproduce**
Clean app-> insert email -> choose insert password -> tap login -> progress dialog is on the screen. Left the app. Going back to WP and the progress dialog is always there.

**Comment by daniloercoli** [comment] 2017-10-09 13:03
Additional info: One restarted your logged to WP, but the site list is empty. The app will auto-synch the info and populates the "My Sites" screen, but for a small amount of time (10 secs) in my case, the My site screen had the empty view shown (The Drake) suggesting me to start a new site.

**Comment by hypest** [comment] 2017-10-19 13:03
The issue is actually more general. The same progress dialog stays on screen even on the first screen (email input) if the app is put in the background and resumed a little bit later. The root cause is that the Fragments listen for the response events from FluxC but only when in the Resumed state. Putting the app in the background causes the Fragments to Pause and deregister their listeners, missing the response events that come after that.

**Comment by theck13** [comment] 2017-11-08 22:39
> A possible solution is to use a more long-lived mechanism, like a service.

Can we repurpose your service model included in https://github.com/wordpress-mobile/WordPress-Android/pull/6825 for this?

**Comment by hypest** [comment] 2017-11-09 07:51
Hey @theck13 , for sure. That's basically my "secret plan" after we can get the signup service PR merged and its usage matures. 💯

**Closed** 2017-11-27 16:08 UTC
Labels: Login, [Type] Bug
