### ISSUE TITLE
NullPointerException: site.wpApiRestUrl must not be null

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#16516] opened 2022-05-10 17:01 UTC
**Sentry Url**: https://sentry.io/share/issue/05feac231f9e41e692fabfed2ef829d5/
**User Count**: 50
**Count**: 417
**First Release**: 19.7-rc-1
**First Seen**: 2022-04-21T18:09:07.306000Z
**Last Seen**: 2022-05-10T16:30:42Z
**24 Hours**: 95
**30 Days**: 419

```
NullPointerException: site.wpApiRestUrl must not be null
     at org.wordpress.android.fluxc.store.ReactNativeStore.executeWPAPIRequest(ReactNativeStore.kt:122)
     at org.wordpress.android.fluxc.store.ReactNativeStore.executeWPAPIRequest(ReactNativeStore.kt:97)
     at org.wordpress.android.fluxc.store.ReactNativeStore.access$executeFetch(ReactNativeStore.kt:30)
     at org.wordpress.android.fluxc.store.ReactNativeStore.access$executeWPAPIRequest(ReactNativeStore.kt:30)
     at org.wordpress.android.fluxc.store.ReactNativeStore.access$executeFetch(ReactNativeStore.kt:30)
     at org.wordpress.android.fluxc.store.ReactNativeStore.access$executeWPAPIRequest(ReactNativeStore.kt:30)
     at org.wordpress.android.fluxc.store.ReactNativeStore$executeRequest$2.invokeSuspend(ReactNativeStore.kt:73)
     at org.wordpress.android.fluxc.store.ReactNativeStore$executeRequest$2.invoke(null:8)
     at org.wordpress.android.fluxc.store.ReactNativeStore$executeRequest$2.invoke(null:4)
     at org.wordpress.android.fluxc.tools.CoroutineEngine.withDefaultContext(CoroutineEngine.kt:34)
...
(12 additional frame(s) were not displayed)
```

**Comment by mchowning** [comment] 2022-05-11 17:09
I think this can be closed as a duplicate of https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1579. I'm taking another look at how we can fix this, but I think we can close this issue. Feel free to reopen if you disagree.

**Closed as completed by mchowning** 2022-05-11 17:09 UTC
Labels: [Type] Crash
