### ISSUE TITLE
Pin Lock: Pin lock on post preview after dismissing Open dialog.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#234] opened 2013-10-29 18:17 UTC
Nexus 4.
To reproduce, have a secondary browser installed, and pin lock activated.

From the post list, view a post preview that has an image wrapped in a link
Tap the image.
You see a dialog asking which browser to open the link in (chrome, firefox).
Wait a couple of seconds and dismiss the dialog via the back button. 

You are prompted to enter your pin even though it doesn't seem like you've left the app.

**Comment by rachelmcr** [comment] 2015-12-02 16:28
I couldn't reproduce the issue with the exact steps above; tapping the image opened the link in the in-app browser instead of bringing up the dialog.

However, I reproduced it with the Share icon:
- From the post list, view a post preview
- Tap the Share icon in the top right
- You see a dialog asking where to open the share link
- Wait a couple seconds and dismiss the dialog (either by tapping or using the back button)
Result: You are prompted to enter your pin.

Tested in 4.8-rc-3, Nexus 9, Android 6.0.

**Comment by maxme** [comment] 2015-12-02 16:34
I fear there is no clean way to fix this, once the user is out of the app (sharing is one of these situation), they will be prompted for their Pin when they come back.

**Comment by rachelmcr** [comment] 2015-12-02 17:00
Is that expected even if I don't complete the sharing action? That is, the sharing dialog appears, but even if I don't take any further action (just wait a couple seconds with the dialog open and then go back) I get the pin lock.

If that's expected, I suggest we close this issue as a wontfix.

**Comment by maxme** [comment] 2015-12-02 17:40
"Expected" not really, but the share dialog is an external action. There is a dirty fix: rewrite the share dialog, so we don't exit the app before actually sharing anything, that's a lot of work and it makes sharing non standard.

Closing as a wontfix is the best solution.

**Closed by maxme** 2015-12-02 17:40 UTC
Labels: core, wontfix, [Type] Bug
