### ISSUE TITLE
Bug: Categories have no check boxes

### ISSUE THREAD

**Issue by mavhc** [wordpress-mobile/WordPress-Android#9887] opened 2019-05-20 15:15 UTC
### Expected behavior
Create new blog post, menu>post settings>Categories. Categories have check boxes, or some way to see which are selected

### Actual behavior
I get a correctly indented list of categories, but no indication of which are currently selected

### Steps to reproduce the behavior

Installed Wordpress 5.2, added a few categories, in a nested structure.

On android: Create new blog post, menu>post settings>Categories.

New page opens, with list of Categories, all nested correctly.

But there's no check boxes, no highlighting, no way to tell which are selected.

Clicking them seems to have random effects on whether they're selected or not.

##### Tested on Hudl 2 , Android 5.1, WPAndroid 12.3.2
and
Honor 7, Android 6.0, WPAndroid 12.3.2

Also same problem with another site I have access to, running Wordpress 5.1.1

**Comment by designsimply** [comment] 2019-05-22 22:41
Good find! Tested and confirmed that Post settings > Categories checkboxes appear to show up only every other time the categories are viewed while editing a post. ([3m28s](https://cloudup.com/cFxTE7Nt1IG))

![post-settings-category-selection-38s](https://user-images.githubusercontent.com/1119271/58213708-64476680-7cb0-11e9-8192-0fa8e3d34c36.gif)
<sub>Tested with WPAndroid alpha-171 on Pixel 3 Android 9 using a self-hosted WordPress site `open-bear.jurassic.ninja` and wp-cli command `wp term generate category --count=100` to add several categories.</sub>

**Comment by mavhc** [comment] 2019-05-24 10:37
My other problem was the ticks weren't showing up at all, but on closer inspection, the reason is they're white ticks on a white background, can see them as the tap animation happens.

**Comment by mavhc** [comment] 2019-05-28 16:41
Ticks are visible on Android 8.1, don't show on Android 6.0 (Honor 7), don't show on Android 5.1 (Hudl 2)

**Comment by mavhc** [comment] 2019-05-28 18:01
Ticks don't show on Android 6.0 (Moto G) either

**Comment by charliescheer** [comment] 2019-06-06 22:30
I had a user reporting this same problem in this issue 2037072-zen.  I tested on my Android device and am coming up with the same problem.

Galaxy Tab A
Android 5.1.1
WordPress alpha-171

**Comment by mavhc** [comment] 2019-07-22 14:14
Had a report that the checks/ticks are visible on Android 7.1.2 (lineageos, no google play service) on a Sony Experia Z5 Compact. So fixed somewhere between 6.0 and 7.1.2

**Comment by mavhc** [comment] 2019-07-22 15:33
Android 7.0 on a Galaxy Tab A 10" shows the checks/ticks too.

I wonder if it's a problem with a background/foreground colour not being set, and the default changed for Android 7?

**Comment by monotron** [comment] 2019-07-22 20:26
Will attempt a fix and report back.

**Comment by designsimply** [comment] 2019-08-01 19:47
Thanks @monotron! How's this going? Need help with anything?

**Comment by malinajirka** [comment] 2020-04-23 10:08
@jd-alexander Could you please check if this issue was fixed in the PR mentioned above? Thanks

**Comment by jd-alexander** [comment] 2020-04-23 18:04
Hey @malinajirka Thanks for the ping 🙏 I didn't end up fixing the issue because I couldn't reproduce it most times I tried. It is still occurring? 
 I mainly made UI changes instead that wasn't merged due to overlap with a lot of changes taking place in the dark mode feature.

**Comment by designsimply** [comment] 2020-08-12 17:25
I re-tested this issue today using WPAndroid 15.5 beta and I am no longer able to replicate the problem described where category selection did stay consistent when opening and closing Categories from Post or Page > More > Post Settings > Categories.

I believe this was fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11025. Props @jd-alexander. 🎉

Here are the screenshots from my test showing how the interface looks currently:

<img src="https://user-images.githubusercontent.com/1119271/90046983-708d5a00-dc8e-11ea-9f93-019fb0ed0bf4.jpg" width="270" alt="Screenshot_20200812-112017"> <img src="https://user-images.githubusercontent.com/1119271/90046990-71be8700-dc8e-11ea-8985-76d7fbb558b5.jpg" width="270" alt="Screenshot_20200812-111957">

<p style="clear:both;"><sup>Tested with WPAndroid 15.5-rc-1 on Pixel 4 Android 10.</sup></p>

**Closed** 2020-08-12 17:26 UTC
Labels: Posting/Editing, [Type] Bug, good first issue
