### ISSUE TITLE
Audio shortcode is not rendered correctly / doesn't play in the Reader

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4428] opened 2016-07-26 15:29 UTC
### Expected behavior

I expect audio embedded with the `[audio]` shortcode to either be embedded in the Reader or to appear as a link that I can tap to listen to the audio file.
### Actual behavior

The audio shortcode is not rendered at all, leaving a blank space in the Reader:

![2016-07-26 15 27 12](https://cloud.githubusercontent.com/assets/8658164/17144294/29e4865a-534e-11e6-9709-5573c58bab86.png)
### Steps to reproduce the behavior
1. Create a new post
2. Embed an audio file in the post with the `[audio]` shortcode ([shortcode details in the Codex](https://codex.wordpress.org/Audio_Shortcode))
3. Publish the post
4. View the post in the Reader

Result: A blank space appears where the audio embed should be in the post.

**Comment by nawabhussain** [comment] 2016-09-11 16:52
@rachelmcr I tested the same on Oneplus One but it seemed to work fine. Can you confirm if the bug is still there ?

**Comment by rachelmcr** [comment] 2016-09-12 09:27
I tested again and the embeds are appearing now, but the length displayed on the embed is 0:00 and tapping the play button doesn't play anything:

![2016-09-12 09 25 49](https://cloud.githubusercontent.com/assets/8658164/18431110/6dc5797e-78d3-11e6-97da-c1a30340a376.png)


Tested on Nexus 9, Android 7.0, WPAndroid alpha-20

**Comment by oguzkocer** [comment] 2017-04-17 12:20
@rachelmcr I can't reproduce this issue anymore. I've tried on both device and the emulator multiple times and everything seems to be working as expected.

Closing this now, please let me know if you can reproduce it and we'll re-open it. Thanks!

**Closed by oguzkocer** 2017-04-17 12:20 UTC
Labels: Reader, [Pri] Medium, [Type] Broken Window, [Type] Bug
