### ISSUE TITLE
SQL Connection for database WordPress leaked on login

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5411] opened 2017-03-15 11:09 UTC
Found the following error in console when logging with a 2FA account:
```
E/WordPress-API: onAuthenticationChanged has error: NEEDS_2FA - Please enter the verification code generated by your Authenticator mobile application.
W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
I/art: Do partial code cache collection, code=248KB, data=201KB
I/art: After code cache collection, code=246KB, data=200KB
I/art: Increasing code cache capacity to 1024KB
W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
W/IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
I/WordPress-UTILS: App goes to background
I/WordPress-UTILS: ConnectionChangeReceiver.setEnabled false
W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.wordpress.android/databases/wordpress' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.wordpress.android/databases/wordpress' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.wordpress.android/databases/wordpress' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
D/AutoManageHelper: onStart true {0=com.google.android.gms.internal.zznr$zza@8783c6f}
```

**Comment by hypest** [comment] 2017-11-08 14:11
Can't reproduce this with my 7.1.2 Nexus 5X and app versionCode 487. I'm assuming it appears when backgrounding the app while the 2FA screen is on?

Closing for now as non reproducible. Please, feel free to reopen if it still persists. Thanks!

**Closed by hypest** 2017-11-08 14:11 UTC
Labels: Login, [Pri] Medium, [Type] Bug
