### ISSUE TITLE
Stories: Text alignment tool doesn't align text

### ISSUE THREAD

**Issue by aleone89** [wordpress-mobile/WordPress-Android#14279] opened 2021-03-18 14:32 UTC
### Expected behavior

When creating a story and adding text > aligning text, the expectation is that the text aligns as set on the story. 

Editor mode: 

Left align

<img width="270" alt="https://cdn-std.droplr.net/files/acc_662189/Ewnd2Z" src="https://user-images.githubusercontent.com/1119271/112070609-a901ea00-8b33-11eb-8a17-6f363979dea2.png">

Right align 

<img width="270" alt="https://cdn-std.droplr.net/files/acc_662189/FK0lff" src="https://user-images.githubusercontent.com/1119271/112070616-ae5f3480-8b33-11eb-94f2-f05eb87065fe.png">

### Actual behavior

The text defaults to the center of the story.

Viewing the story: https://carrottopsallotment.com/2021/03/17/then-and-now/

### Steps to reproduce the behavior

Please see: https://wordpress.com/support/wordpress-editor/blocks/story-block/

1. Create new story > select media
2. Add text overlay 
3. Align text using text align tool in the bottom left hand corner 
4. View story

**Comment by aforcier** [comment] 2021-05-21 03:10
This is working as designed - the button is changing the justification of the text, which only has a visible effect on multiline text, here's an example:

![wp-stories-text-alignment](https://user-images.githubusercontent.com/9613966/88620387-dbf4fa80-d0d8-11ea-9732-c078378d79d2.gif)

The added view is always placed in the center of the slide, and the text can be dragged to wherever the user would like it positioned. The justification of the text can't be changed by dragging though, which is what the text justification button is intended for.

I'll close this for now but if we receive multiple instances of feedback about this we could consider a new design pass on the text feature.

**Closed as completed** 2021-05-21 03:11 UTC
