### ISSUE TITLE
Visual Editor: Formatting applied before typing is lost

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#3863] opened 2016-03-14 19:38 UTC
### Steps to reproduce the behavior
Open a new post.  Select formatting (bold, or italic).  Start typing.  The format button is deselected, and plain text is added.

### Expected behavior
I can start my post with formatted text

### Actual behavior
My formatting is lost and I have to reapply it.

##### Tested with alpha-3 on Nexus 6P, Android 6.0.1 (physical device as well as emulator shown below)

![wp-android-visual-editor-1](https://cloud.githubusercontent.com/assets/7233112/13757414/aa86a0da-e9fa-11e5-873c-fd4278d4c809.gif)

**Comment by aforcier** [comment] 2016-03-14 21:40
Duplicate of https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/204, closing (but keeping the demo GIF).

**Closed by aforcier** 2016-03-14 21:40 UTC
