### ISSUE TITLE
[Bug] Username Changer Full Screen Dialog Appears and Disappears during Sign-up

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#18204] opened 2023-03-30 14:00 UTC
### Expected behavior

While testing `UsernameChangerFullScreenDialogFragment` via #18158 using the below test instructions I should have seen a screen when I could have updated my username while sign-up was ongoing.

Test instructions:
1. Launch the app and sign up.
2. At the last step of the signup flow, you'll see a screen where you can update your username.
3. Tap the Username.
4. Ensure it doesn't crash.

### Actual behavior

The actual behavior was the although the screen was shown for a second, it then disappeared right after (see [comment](https://github.com/wordpress-mobile/WordPress-Android/pull/18158#pullrequestreview-1362677997) and then further discussion on the matter).

### Steps to reproduce the behavior

See `Test instructions` above.

**Comment by RenanLukas** [comment] 2023-08-10 21:30
Hey @ParaskP7 , thanks for reporting this issue.

I've tried following the steps to reproduce three times and the `"Change username"` screen appeared as expected every time. I've also changed the initial username successfully. Maybe this was already fixed by another PR? Or perhaps I'm missing something in my testing setup.

<img width="413" alt="image" src="https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/881fb485-9629-485b-b2f4-179793e3d191">

**Comment by ParaskP7** [comment] 2023-08-11 08:29
👋 @RenanLukas and thanks so much for looking into this issue, I am glad it is working as expected on your side! 🥇 

I don't think you are missing something, and, I am not sure if another PR fixed this issue already, maybe, maybe not. 🤷

I would need to test this again myself and verify that this issue is working on my side too. 😊

**Comment by ParaskP7** [comment] 2023-09-11 12:33
👋 @RenanLukas and apologies for only getting back to you on that just now! 😊

**Comment by ParaskP7** [comment] 2023-09-11 12:40
> I would need to test this again myself and verify that this issue is working on my side too. 😊

👋 @RenanLukas and apologies for only getting back to you on that just now! 😊

I tried it again today and this problem seems to be persisting on my side, see recording below:

https://github.com/wordpress-mobile/WordPress-Android/assets/9729923/1d75c4c4-fb20-4fdc-a919-77bc21f3754e

Let me know what you think and thanks again for your help! 🙇

**Comment by RenanLukas** [comment] 2023-09-19 19:19
👋 @ParaskP7 thanks for checking it again. At this point I don't have a hypothesis 🤔
For now I'm removing myself as assignee so this issue appears in the Android maintenance week board.

**Comment by antonis** [comment] 2023-11-23 15:39
I've tested the latest version `23.7` on a Pixel 5 (Android 14) and wasn't able to reproduce this issue.

**Comment by antonis** [comment] 2024-03-11 12:51
I revisited the issue testing the latest version of the app (`24.4`) and I'm still not able to reproduce on a Pixel 5/8 with Android 14.

https://github.com/wordpress-mobile/WordPress-Android/assets/304044/8589cbce-7c1b-409d-bb3c-5ba1e8501143

I also checked the analytics for the [username search](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/BaseUsernameChangerFullScreenDialogFragment.java#L364) event and the number of events sourcing from the `signup_epilogue` looks good.

<img width="1477" alt="Screenshot 2024-03-11 at 2 14 13 PM" src="https://github.com/wordpress-mobile/WordPress-Android/assets/304044/2a55e6c4-2c20-4662-b0e3-28d4a8e8afac">

I'll lower the priority of the issue to `Medium` given that this might happen on an edge case scenario and we don't have steps that reproduce this consistently.

**Comment by dangermattic** [comment] 2024-03-11 12:51
Thanks for reporting! 👍

**Comment by ravishanker** [comment] 2024-03-13 10:14
Closing as the last three investigations were not able to reproduce the issue nor there were any user reported issues either.  

@ParaskP7 - Please feel free to re-open it if you can still reproduce it with the latest version. 🙇

**Closed as completed by ravishanker** 2024-03-13 10:14 UTC
Labels: [Type] Bug, [Pri] Medium, Signup
