### ISSUE TITLE
Missing Sharing/Like Buttons From In-App Browser

### ISSUE THREAD

**Issue by nellofn** [wordpress-mobile/WordPress-Android#8007] opened 2018-07-09 14:39 UTC
### Expected behavior
If I open a blog post from the app, I expected to see the post's sharing and like buttons.

Here's an example screenshot if I open the post directly in a mobile browser:
![screen shot 2018-07-09 at 10 36 50 am](https://user-images.githubusercontent.com/17755234/42456959-27c923b0-8364-11e8-8b69-208797392c97.png)

### Actual behavior
The sharing and like buttons are missing from blog posts when viewed from the app. If I tap on the world icon to view the post in the mobile browser, the buttons are not visible either. 

What I've found is that if the post url doesn't have the **?preview=true** ending, the buttons are visible.

I can confirm that I'm able to replicate the behavior in version 10.3 of the app. Here's an example screenshot, using the same post as above:

![screen shot 2018-07-09 at 10 36 15 am](https://user-images.githubusercontent.com/17755234/42456986-39d11554-8364-11e8-94bd-50e9e0618301.png)

### Steps to reproduce the behavior

- Navigate to My Site > View Site.
- Tap through to a blog post that has sharing/like buttons, or tap the world icon in a post within the app when in preview mode

##### Tested on BLU Studio Selfie 5.1, Android 10.3

**Comment by nellofn** [comment] 2018-07-09 14:41
A user also reported this on 292487-h, using version 10.3

**Comment by rachelmcr** [comment] 2018-08-22 10:40
I labelled this a bug, since the behavior doesn't match the user's expectations for a published post, but I'm not sure. I'd encourage users to use the app sharing icon (in the top right corner — looks like it is in the three-dot menu in your screenshot) instead of webview sharing buttons for the best experience on mobile.

**Comment by rachelmcr** [comment] 2019-04-15 12:33
I confirmed that in https://github.com/wordpress-mobile/WordPress-Android/pull/5546 we explicitly improved the experience for using the native sharing feature (rather than changing the preview behavior/showing sharing buttons) in cases like this.

I'm changing this to an enhancement issue and requesting design feedback — perhaps we can do something to make the native sharing option clearer, especially on small screens where the sharing icon in the top right is currently hidden behind an ellipsis menu.

**Comment by designsimply** [comment] 2019-06-14 08:11
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/9649 where design feedback was provided for a broader use case that covers missing sharing options in webviews.

**Closed by designsimply** 2019-06-14 08:11 UTC
Labels: Sharing, Webviews, [Type] Enhancement
