### ISSUE TITLE
Featured images not working when selected from WP Media Library

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2456] opened 2015-03-24 09:22 UTC
1. Create a new post with the app.
2. Tap the image icon and choose “Select from media library” or choose an image from the "Site images" tab with the media picker (for 3.9+)
3. Choose an image then tap it to edit and tick the box next to “Use as featured image”.
4. Publish the post.

**Comment by rachelmcr** [comment] 2015-12-03 17:28
Tested and reproduced in 4.8-rc-3. This should be resolved when the new editor launches.

**Comment by rachelmcr** [comment] 2016-03-22 17:44
I tested in the new editor, version alpha-4, and featured images work when selected from the media library. I tested both by adding the image and selecting "Use as featured image" as described above, and by adding a featured image in the post settings.

Closing since this is resolved in the new editor.

**Closed by rachelmcr** 2016-03-22 17:44 UTC
Labels: Media, posting/editing, [Type] Bug
