### ISSUE TITLE
Woocommerce Product Page Stats not appearing in wpAndroid stats

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-Android#9696] opened 2019-04-23 21:11 UTC
I was alerted to this issue in #1973665-zen If you are looking at a jetpack site that is using woocommerce, and check out the jetpack stats in a web browser you will see stats for all of the different types of posts including woocommerce product pages, however when you look in the stats for WPAndroid the woocommerce product pages do not appear.

Stats from web browser:

<img src="https://user-images.githubusercontent.com/1119271/56618201-153de100-65df-11e9-970d-e97fba4f266e.png" width="270" alt="Screen Shot on 2019-04-23 at 16-09-37">

stats from wpAndroid:

<img src="https://user-images.githubusercontent.com/1119271/56618164-fc353000-65de-11e9-8cf4-ca2387a0a520.png" width="270" alt="Screen Shot on 2019-04-23 at 16-09-48">

I was able to replicate in alpha 162 - Android 5.1.1

**Comment by designsimply** [comment] 2019-04-23 21:52
@charliescheer this appears to be a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/9167. Can you please a comment there with your findings + screenshots?

**Closed by designsimply** 2019-04-23 21:52 UTC
Labels: Stats, [Type] Bug
