### ISSUE TITLE
Confusing/Unhelpful Error at Login When XML-RPC Is Blocked

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#8459] opened 2018-10-21 20:36 UTC
### Expected behavior

If I enter the URL for a WordPress site that blocks XML-RPC, I expect to receive a helpful error message that informs me why I'm not able to log into that site via the app.

### Actual behavior

The following error appears when a URL for a WordPress site that blocks XML-RPC is entered:

"Couldn't connect to WordPress site. There is no valid WordPress site at this address. Check the site address (URL) you entered."

Screenshot:

![screenshot_20181021-212857](https://user-images.githubusercontent.com/2998162/47272133-ed5eb980-d578-11e8-921f-e18e466db158.png)

### Steps to reproduce the behavior

1. Navigate to the app's login screen and select the "Log in by entering site address" option.
2. Submit the URL to a site that blocks XML-RPC.

##### Tested on Pixel, alpha-132 of WordPress for Android

As per this convo, more informative error messages were displaying in the Android app until at least March: 

https://a8c.slack.com/archives/C9JMWK5HQ/p1520333424000220-slack-happier-hes

It seems the code for these errors are defined here:

https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/network/discovery/SelfHostedEndpointFinder.java

**Comment by SiobhyB** [comment] 2018-10-21 20:44
iOS version: https://github.com/wordpress-mobile/WordPress-iOS/issues/10293

**Comment by aerych** [comment] 2018-10-22 17:59
A few thoughts: 
- We need to harmonize the messages shown between WPAndroid and WPiOS.
- This might be a good time to switch from our current self-hosted discovery logic to querying `public-api.wordpress.com/rest/v1.1/connect/site-info` or use this call as a fall back.
- When all else fails we might check for the [presence of the WP REST API](https://developer.wordpress.org/rest-api/using-the-rest-api/discovery/) to confirm we're dealing with a self-hosted site.
- In cases where we can't identify a WordPress site it would be nice if we could tweak the message shown to allow for cases the apps are wrong.

**Comment by planarvoid** [comment] 2018-10-23 08:13
@aerych 
> We need to harmonize the messages shown between WPAndroid and WPiOS.
> querying public-api.wordpress.com/rest/v1.1/connect/site-info
> check for the presence of the WP REST API  

All of these make sense as a new project. I think switching to the other endpoint is not a short time fix. Quoting the docs - "RSD is the least-preferred method of autodiscovery" and we still use it - so we should definitely plan this. If we get a list of sites that are showing the incorrect message, we could investigate them and try to fix them.

**Comment by shiki** [comment] 2019-07-19 01:15
@planarvoid Is PR https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/943 supposed to fix this issue? I'm not sure how to reproduce this so I thought I'd ask you first.

**Comment by planarvoid** [comment] 2019-07-22 09:08
@shiki I don't think so. I think the issue is much bigger and this only added some additional information in one certain case. I don't remember the details though

**Comment by malinajirka** [comment] 2019-08-14 08:24
I like Aerych's proposal, but I completely agree with Vojta. It might be better to handle it in a small project and not as a quick groundskeeping fix.

@SiobhyB I've tried the following and all the messages looked ok
1. Forbidden XML-RPC (403 error)
<img width="402" alt="Screenshot 2019-08-14 at 10 18 33" src="https://user-images.githubusercontent.com/2261188/63005655-420f5000-be7d-11e9-8eff-29033a65cfea.png">
2. Missing XML-RPC methods
<img width="410" alt="Screenshot 2019-08-14 at 10 18 53" src="https://user-images.githubusercontent.com/2261188/63005671-49cef480-be7d-11e9-8759-bea72038ced3.png">
3. Blocked XML-RPC (405 error)
<img width="407" alt="Screenshot 2019-08-14 at 10 19 09" src="https://user-images.githubusercontent.com/2261188/63005681-4d627b80-be7d-11e9-8de7-4af02293ac91.png">

Can you please confirm it works as expected and close the issue. 

Thank you!

**Comment by oguzkocer** [comment] 2020-01-30 17:25
@malinajirka Do you know the steps to reproduce each scenario in the app? If so, could you document them? I know we can manually trigger each one from the code, but I am not entirely sure how to setup the site to do it.

**Comment by malinajirka** [comment] 2020-01-31 10:21
@oguzkocer IIRC the testing steps are the same for all the errors. The only thing that changes is the URL of the self-hosted site. I used the URLs from the `test.properties` in FluxC. The file is private, so I'd rather not share it publicly. 

1. Click on "Log in"
2. Click on "Log in by entering your site address"
3. Enter the URL and click on "Next"
4. Notice the error.

The urls in the test.properties has the following comments
1. # Self hosted - Forbidden XML-RPC (403 error)
2. # Self hosted - Missing XML-RPC methods
3. # Self hosted - Blocked XML-RPC (405 error)

Let me know if you need more info ;)

**Comment by oguzkocer** [comment] 2020-01-31 17:09
Thanks @malinajirka!

@designsimply I've also verified that we are getting the messages we expect from the server for each case as documented by Jirka [in this comment](https://github.com/wordpress-mobile/WordPress-Android/issues/8459#issuecomment-521151590).

My suggestion is to close this issue. If we feel further improvement is necessary, we can open a new issue describing the expectations. I think the current messages are very descriptive and any further improvement here will have diminishing returns.

---

Related to the discussion we were having on Slack about a way for HEs to test/reproduce the issue, I think these error messages will likely be enough. If we feel they are lacking in this regard, it'd be good to document why that is in a separate issue and figure out the best way to tackle it.

**Comment by SiobhyB** [comment] 2021-03-21 16:24
> @SiobhyB I've tried the following and all the messages looked ok. Can you please confirm it works as expected and close the issue.

@malinajirka, sorry that I missed your ping originally! I was on sabbatical at the time and pretty much wiped all emails when I was back. 🤦‍♀️ I'm seeing the "missing XML-RPC methods" error when testing a few examples but there also still seem to be some cases where the generic "couldn't connect to WordPress site" error is show, such as the site listed in 3829320-zen. I also see a more recent issue was created in https://github.com/wordpress-mobile/WordPress-Android/issues/12401 for this. I'm happy for this older one to be closed in favour of that one.

**Comment by malinajirka** [comment] 2021-03-22 14:20
No worries at all @SiobhyB! These two issues seem quite similar. I'd suggest closing this one as you suggested. We might also consider assigning the other issue to groundskeeping if you feel it should be prioritized. Wdyt?

**Comment by designsimply** [comment] 2021-03-22 23:56
+1 to closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/12401 and adding to Groundskeeping. I'll do both. 👍

**Closed by designsimply** 2021-03-22 23:56 UTC
Labels: Login, [Type] Bug
