### ISSUE TITLE
Post's representative image sticks to the screen after viewing all post's comments.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-Android#18353] opened 2023-05-02 16:52 UTC
Post's representative image sticks to the screen after viewing all post's comments.

Reported here: p4a5px-2SC-p2

### Expected behavior
Representative image shouldn't cover the post content.

### Actual behavior
Post content is covered by a representative image after tapping `View all comments` and returning to post view.

<details><summary>Video</summary>
<video width="300" src="https://user-images.githubusercontent.com/42008628/235729455-186a63b7-ad72-41d3-a61a-d8a1fe23effd.mp4">
</details> 

### Steps to reproduce the behavior
Set up: Post with images, NO featured image, and some comments.

1. My Site > Comments.
2. Tap a comment from the target post.
3. Tap the post title to view the post.
4. Scroll down and tap `View all comments`
5. Tap `Back` to return to post view.
6. ❌ Notice that an image is loaded at the top of the screen, covering the post content as you scroll up.

OR

1. Reader > Tap post to view it.
2. Scroll down and tap `View all comments`
3. Tap `Back` to return to post view.
4. ❌ Notice that an image is loaded at the top of the screen, covering the post content as you scroll up.

##### Tested on Samsung Galaxy Note 20, Android 12, JPAndroid / WPAndroid 22.3

**Comment by daniloercoli** [comment] 2024-02-27 16:03
I was unable to reproduce the problem on version 24.2 and later. Closing this issue.

**Closed as completed by daniloercoli** 2024-02-27 16:03 UTC
Labels: [Type] Bug, [Pri] Low, Reader, Comments
