### ISSUE TITLE
Empty editor opened after clicking on existing page item

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#11339] opened 2020-02-19 11:54 UTC
### Expected behavior
When I click on page in the page list, the editor is opened with the title and content of the page.

### Actual behavior
When I click on page in the page list, the editor is opened with an empty title and content.

### Steps to reproduce the behavior
Update 2/28/2020: The issue happens only when you click on the page item after the first 20 pages were loaded but FluxC is still loading more. In order to reproduce this issue, either make sure to use a site with a lot of pages or change [this](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/7cf14c3b2b1001bf50ae46bc39b0d3f67533d13a/fluxc/src/main/java/org/wordpress/android/fluxc/store/PostStore.java#L72) to 1.

1. My Site
2. Site Pages
3. Click on one of the existing pages
4. Notice the editor is empty
If you leave the editor and click on the page again, it works. However, if you leave back to My Site and repeat the steps it'll fail again. It seems it's failing on the first page you open after entering the page list screen.

##### Tested on [device], Android [version], WPAndroid [version]
Emulator, Pixel 2, Android 9
I've tested the behavior in both Aztec and Gutenberg.

**Comment by khaykov** [comment] 2020-02-22 01:15
Hm. I was not able to reproduce this issue with Aztec or GB.

**Comment by malinajirka** [comment] 2020-02-25 11:24
It seems to work as expected on a hw device. But it keeps happening to me on emulators - I've tested it on API 22, 27, 28, 29.
![empty-editor](https://user-images.githubusercontent.com/2261188/75243198-b7af8d80-57c9-11ea-8d76-57551f9c8190.gif)

**Comment by designsimply** [comment] 2020-02-27 19:28
I ran into this problem during beta testing using WPAndroid 14.3-rc-1 on Pixel 3 Android 10. ([1m44s](https://cloudup.com/c4nKtfu-Ir2))

I noticed errors like this in the logs:

```
10 - [Feb-27 19:11 API] Dispatching action: PostAction-FETCHED_REVISIONS
11 - [Feb-27 19:11 API] Dispatching action: TaxonomyAction-FETCHED_TERMS
12 - [Feb-27 19:11 API] Volley error on https://public-api.wordpress.com/rest/v1.1/sites/5276229/post/0/diffs/?locale=en_US - exception: null
13 - [Feb-27 19:11 API] StackTrace: com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

14 - [Feb-27 19:11 API] Dispatching action: PostAction-FETCHED_REVISIONS
15 - [Feb-27 19:11 DB] Site found by (local) ID: 88
16 - [Feb-27 19:11 DB] Updating site: https://design5279.wordpress.com
17 - [Feb-27 19:11 API] An error occurred while fetching History revisions
18 - [Feb-27 19:11 API] An error occurred while fetching History revisions
19 - [Feb-27 19:11 EDITOR] EditPostRepository: Transaction is writing on a locked thread [dalvik.system.VMStack.getThreadStackTrace(Native Method), java.lang.Thread.getStackTrace(Thread.java:1720), org.wordpress.android.ui.posts.EditPostRepository.reportTransactionState(EditPostRepository.kt:149), org.wordpress.android.ui.posts.EditPostRepository.access$reportTransactionState(EditPostRepository.kt:36), org.wordpress.android.ui.posts.EditPostRepository$updateAsync$1.invokeSuspend(EditPostRepository.kt:119), kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33), kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56), android.os.Handler.handleCallback(Handler.java:883), android.os.Handler.dispatchMessage(Handler.java:100), android.os.Looper.loop(Looper.java:214), android.app.ActivityThread.main(ActivityThread.java:7356), java.lang.reflect.Method.invoke(Native Method), com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)]
```

Full logs: [WordPress Application log.txt](https://github.com/wordpress-mobile/WordPress-Android/files/4263600/WordPress.Application.log.txt)

Happens in both Aztec and Gutenberg. Happens for pages with or without revisions. Happens for newer and older pages and it doesn't matter whether the page was published with the app or on the web. For me, it's intermittent, sometimes the page opens and sometimes it doesn't but it fails most often after leaving and re-opening the Site Pages list and then tapping the post for the first time after the list is opened.

**Comment by designsimply** [comment] 2020-02-27 19:36
Checked and it's also happening for me in 14.2. ([28s](https://cloudup.com/cKkQacoLzYr))

**Comment by malinajirka** [comment] 2020-02-28 11:19
It's happening even in 13.6. I have investigated the cause and I believe I understand why it's happening. I can't think of an easy fix right now, so I'd recommend assigning this ticket to prioritised Groundskeeping.

[This line](https://github.com/wordpress-mobile/WordPress-Android/blob/20a93a60f1c0a89226a9a4de5b299fe4931342c5/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostRepository.kt#L221) loads the page from the local database. The issue is that [this line](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/7cf14c3b2b1001bf50ae46bc39b0d3f67533d13a/fluxc/src/main/java/org/wordpress/android/fluxc/store/PostStore.java#L904) deleted the item from the database and the item has a different localId now.
This usually isn't an issue as we update all localIds throughout the app as soon as the item [is deleted and re-added in FluxC](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/7cf14c3b2b1001bf50ae46bc39b0d3f67533d13a/fluxc/src/main/java/org/wordpress/android/fluxc/store/PostStore.java#L904). However, page list is a bit specific. We start `fetchpages` request, but [we use a suspend function](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/47883cad2190d112584daefecee9e5960d6f5d5e/fluxc/src/main/java/org/wordpress/android/fluxc/store/PageStore.kt#L178) which fetches 20items at a time and is [resumed when all the items are fetched](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/47883cad2190d112584daefecee9e5960d6f5d5e/fluxc/src/main/java/org/wordpress/android/fluxc/store/PageStore.kt#L217).
This has an undesired side-effect -> [the `pageMap` in the VM isn't updated until all the items are fetched](https://github.com/wordpress-mobile/WordPress-Android/blob/f3b6ee7c08c31ed82c432d77c4f794af98aadf0d/WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt#L217) .
So when the user opens page list or pulls to refresh and opens the editor, the following happens
1. User opens page list, [pages are loaded from local db](https://github.com/wordpress-mobile/WordPress-Android/blob/f3b6ee7c08c31ed82c432d77c4f794af98aadf0d/WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt#L193) and [fetchPages/reload is invoked](https://github.com/wordpress-mobile/WordPress-Android/blob/f3b6ee7c08c31ed82c432d77c4f794af98aadf0d/WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt#L196)
2. FluxC sends a request for the first 20 items to the server and receives a response -> it deletes all pages from the local database
3. User clicks on one of the pages -> [the app finds the page in the `pageMap`](https://github.com/wordpress-mobile/WordPress-Android/blob/f3b6ee7c08c31ed82c432d77c4f794af98aadf0d/WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt#L451) and starts the editor  -> the issue is that the entry in `pageMap` is out of date and has a localId which doesn't exist anymore since it was deleted in step 2
4. Editor is opened but it's empty
5. In the meantime, FluxC finishes requesting all the items and resumes the coroutine
6. The `pageMap` gets updated, but it's too late since the user is already on an empty editor

**Comment by malinajirka** [comment] 2020-02-28 11:25
>Hm. I was not able to reproduce this issue with Aztec or GB.

@khaykov I've investigated the issue and it's happening only when certain conditions are met. I've updated the "steps to reproduce".

**Comment by oguzkocer** [comment] 2020-03-09 16:48
This issue is targeting the current frozen milestone which is about to be released. I am bumping it to `14.5` which is when a PR that lands to `develop` in the next 2 weeks will be released. If it's more urgent than that, please make sure to target `release/14.4` branch which will be available later today and update the milestone for the issue accordingly.

**Comment by oguzkocer** [comment] 2020-03-23 18:00
This issue is targeting the current frozen milestone which is about to be released. I am bumping it to `14.6` which is when a PR that lands to `develop` in the next 2 weeks will be released. If it's more urgent than that, please make sure to target `release/14.5` branch which will be available later today and update the milestone for the issue accordingly.

**Closed** 2020-04-01 12:56 UTC
Labels: Pages List, Posting/Editing, [Pri] High, [Type] Bug
