### ISSUE TITLE
Aztec editor image captions won't save

### ISSUE THREAD

**Issue by zandyring** [wordpress-mobile/WordPress-Android#5295] opened 2017-02-28 15:23 UTC
### Expected behavior
When adding captions to images using the Aztec editor, I'd expect to see captions.

### Actual behavior
Captions don't get added.

### Steps to reproduce the behavior
1. Add image to post
2. Tap on image to add details to image
3. Add caption
4. Tap "save"
5. See message saying "changes saved" - notice that there is no caption - HTML isn't updated to reflect the added caption.

##### Tested on [device], Android [version]
Moto G (3rd Gen), Android 6.0, WP app alpha-36

**Comment by theck13** [comment] 2017-02-28 15:34
This is a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/5296.

**Closed by theck13** 2017-02-28 15:34 UTC
