### ISSUE TITLE
Crash in editor and instant post of a draft

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#9470] opened 2019-03-25 12:06 UTC
A user has reported a crash in the editor. The steps how they got to the crash are:
* Create a new post
* Add some placeholder text to the editor
* Add an image after the placeholder text
* Add a footer after the image
* Go back to the placeholder text and hold "Backspace" button to delete the placeholder
* The app crashes
* The draft gets instantly published

The crash doesn't happen on a reopened local draft. Even though it is published, the app still shows the post as "Local draft". 

The user uses a device with Android 8.

It is likely related to https://github.com/wordpress-mobile/WordPress-Android/issues/8828

**Comment by mzorz** [comment] 2019-03-26 18:13
I was able to reproduce this after following the steps described by another user in 1905371-zen
The steps here seem to be ok. 

I'm using a Pixel 2 with Android 8.1

**Comment by mzorz** [comment] 2019-03-26 18:17
> The crash doesn't happen on a reopened local draft.

This is not true for me - I can reproduce the crash each time I re-open the draft.

How I managed to reproduce:
1. start a new draft
2. add some text, especially 2 or 3 lines with words separated by spaces
3. add some images
4. add some more text
5. scroll up to the beginning of the text
6. select the last word in the text (only happens with the last word in text before the first image starts)
7. tap and hold the _backspace_  key
8. observe the crash

**Comment by mzorz** [comment] 2019-03-26 18:21
Excellent news: have been able to reproduce on the Aztec demo app. Will create an issue there and link here

**Comment by mzorz** [comment] 2019-03-26 18:24
issue filed in https://github.com/wordpress-mobile/AztecEditor-Android/issues/798

**Comment by mzorz** [comment] 2019-03-26 20:19
Closing, dupe of https://github.com/wordpress-mobile/AztecEditor-Android/issues/729, more info on #8828

**Closed by mzorz** 2019-03-26 20:19 UTC
Labels: Aztec, [Type] Bug, [Type] Crash
