### ISSUE TITLE
Uploading Videos Through Jetpack Application Doesn't Get Uploaded to VideoPress

### ISSUE THREAD

**Issue by muffinpeace** [wordpress-mobile/WordPress-Android#16365] opened 2022-04-19 16:19 UTC
### Expected behavior

Uploading videos using the Jetpack application while VideoPress is enabled should upload the videos on our end.

### Actual behavior

Videos are uploaded on site's storage instead of VideoPress. 

### Steps to reproduce the behavior

1. Install and activate Jetpack using a WordPress.com account.
2. Purchase or add a Jetpack VideoPress.
3. Ensure VideoPress is enabled by going to Settings -> Performance on the WordPress.com dashboard.
4. Install Jetpack mobile application and connect to the WordPress.com account that connected Jetpack.
5. Upload a video by going to Media and clicking on the "+" button.
6. This was initially reported by a user on zen-4956800

**Comment by leandroalonso** [comment] 2022-04-25 16:22
@antonis (I'm pinging you given @hypest is off for the next few days), by any chance, do you know anyone who can help us with more info regarding video uploading?

The issue is mentioned as Jetpack but it happens for both Jetpack and WordPress. When uploading a video it doesn't use VideoPress, instead is displayed using HTML5. You can see the difference here:

* Uploaded with the app: https://fantastic-orca.jurassic.ninja/2022/04/25/videopress/
* Uploaded on .com: https://fantastic-orca.jurassic.ninja/2022/04/25/videopress-2/

Notice the difference between the players.

**Comment by antonis** [comment] 2022-04-26 13:46
Thank you for the ping @leandroalonso 🙇 
My understanding is that this is more of a missing feature than a bug since `gutenberg-mobile` does not support VideoPress at this point (along with other Jetpack features). There are also some open issues related to this ([like this one](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1152)).

**Comment by foleynotrose** [comment] 2022-04-26 15:02
Thanks @antonis. I've updated the user with the news, suggesting that they upload directly from phone to VideoPress via a web browser, rather than using the app.

**Comment by leandroalonso** [comment] 2022-04-26 18:54
Thanks for the context, @antonis!

@foleynotrose I'll close this issue given it's a missing feature instead of a bug. Feel free to reopen it if you think we need it, thanks!

**Closed as completed by leandroalonso** 2022-04-26 18:54 UTC
Labels: [Type] Bug, Media
