### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a n...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12342] opened 2020-07-03 05:06 UTC
**Sentry Url**: https://sentry.io/share/issue/f8446ccce4b44145a970421331426f4f/
**User Count**: 8
**Count**: 8
**First Release**: org.wordpress.android@15.1+885
**First Seen**: 2020-07-01T01:00:06.894000Z
**Last Seen**: 2020-07-03T05:00:21Z
**24 Hours**: 7
**30 Days**: 8

```
NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference
     at org.wordpress.android.ui.prefs.SiteSettingsInterface.loadCachedSettings(SiteSettingsInterface.java:1072)
     at org.wordpress.android.ui.prefs.SiteSettingsInterface.init(SiteSettingsInterface.java:998)
     at org.wordpress.android.ui.publicize.PublicizeButtonPrefsFragment.lambda$getSiteSettings$2(PublicizeButtonPrefsFragment.java:317)
     at org.wordpress.android.ui.publicize.-$$Lambda$PublicizeButtonPrefsFragment$zgqQzY4Y2akf99aaj80pPoNLyJM.run(null:2)
...
(1 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment] 2020-07-10 17:13
This NPE has about 60 users since Jun 30, 2020. Is this a reoccurance of #6915? Adding to groundskeeping.

**Comment by designsimply** [comment] 2020-10-16 20:38
**Events in the last 90d:** 884
**Users affected in the last 90d:** 683
<sub>WORDPRESS-ANDROID-F99: https://sentry.io/share/issue/f8446ccce4b44145a970421331426f4f/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1757110691&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96306605-39546580-0fbd-11eb-8d9e-87d59cd727fa.png)</a>

**Comment by designsimply** [comment] 2020-11-26 03:30
**Events in the last 90d:** 1,100
**Users affected in the last 90d:** 629
<sub>WORDPRESS-ANDROID-F99: https://sentry.io/share/issue/f8446ccce4b44145a970421331426f4f/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1757110691&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/100304868-f216a880-2f5c-11eb-8edd-4d5dd97b7767.png)</a>

**Comment by develric** [comment] 2020-12-01 14:11
I looked into this and I have a good news and an awesome news 😄 .

#### Good news
I think this happens because (following links are from 16.1 version) in [PublicizeButtonPrefsFragment](https://github.com/wordpress-mobile/WordPress-Android/blob/338b9f7585175a6388ce020024a8d385d5b39233/WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeButtonPrefsFragment.java#L322) we call a postDelayed

```
new Handler().postDelayed(() -> mSiteSettings.init(true), FETCH_DELAY);
```

where the `init` function calls the `SiteSettingsInterface -> loadCachedSettings` in which we reference an mContext that can eventually been set to null in the [clear function](https://github.com/wordpress-mobile/WordPress-Android/blob/338b9f7585175a6388ce020024a8d385d5b39233/WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java#L202) before the `init` is actually scheduled. It's not the only path I think, but one way I found to trigger this is the following (tested with 16.1):

- In a fresh install login. You are landed into My Site
- Set airplane mode
- Go into `Sharing` then tap on `Manage`. Note you are landed back into My Site and you get the crash (it could take few seconds).

I have a fix for it, but remember, I also have an awesome news, so go ahead reading 😄 

#### Awesome news
I think the issue is fixed by a modification that maybe was not done to target this issue specifically but that is already merged into current develop (and landing in the 16.3 upcoming release). This happens because we use an injectable [ResourceProvider](https://github.com/wordpress-mobile/WordPress-Android/blob/b9c9634f9b03a2b31862174a985abceeeeabdfdd/WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java#L180) instead of using the Context directly. (cc @planarvoid who I think worked on that. Funny thing is I was going with a pretty similar solution 😜 ).

Hey @designsimply , I think I would not do any additional modification. I would continue monitoring the issue and if the above assumption is correct we should not see this issue from 16.3 on and we can close the isse. If we still see that, well...well we should review the assumption and further dig into it 🙃 , let me know wdyt.

**Note for myself:** I actually already know this but always good to repeat to myself. If you find a way to replicate with the version(s) from the issue, before you define a solution check the develop! 😄

**Comment by designsimply** [comment] 2020-12-02 00:31
sgtm! thank you for the excellent notes and explanation!

**Comment by designsimply** [comment] 2021-01-21 21:08
I checked in on this crash today and found that there were no new events recorded for it in v16.3+. 🎉"

Recommend closing.

**Closed** 2021-01-22 15:10 UTC
Labels: Site Settings, [Type] Crash
