### ISSUE TITLE
Followed tag not added to the list after configuration changes.

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#11354] opened 2020-02-21 00:07 UTC
Was able to reproduce this in 13.0 and also current develop (14.2).

### Expected behavior
In `Reader Settings` > `Followed Tags`, adding a tag after configuration change should result in the tag being added to the list of followed tags.

### Actual behavior
In `Reader Settings` > `Followed Tags`, adding a tag after configuration change results in the tag not being added to the list of followed tags.

### Steps to reproduce the behavior
- Go in `Reader Settings` > `Followed Tags`
- Add a tag and see it is correctly added to the list
- Rotate the device and try to add another tag
- Check that the Toast message say the tag was added but it is not added to the list

<p align="center">
  <img width="300" src="https://user-images.githubusercontent.com/2261188/74946482-a8ab9280-53f9-11ea-9e35-77b46b1af1d5.gif">
</p>

**Comment by ashiagr** [comment] 2021-06-07 05:55
Duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/14162. Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/14556.

**Closed by ashiagr** 2021-06-07 05:55 UTC
Labels: Reader, [Type] Bug
