### ISSUE TITLE
Reader: Load more sometime doesn't work

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#11997] opened 2020-05-22 11:21 UTC
Note: it might be worth waiting for the end of the [Reader Improvements project](https://github.com/orgs/wordpress-mobile/projects/63). 

### Expected behavior
More item get loaded whenever I reach bottom of the 'discover" tab and there are more items to load.

### Actual behavior
The load more event doesn't get triggered sometimes.

### Steps to reproduce the behavior
1. Install the app and navigate to the reader.
2. Discover will be selected as the default tab.
3. Scroll to the bottom and confirm that "load-more" works.
4. Switch to the Following tab (with either gesture or tab), and back to Discover.
5. Scroll to the bottom, and notice that the "load-more" doesn't work. Scrolling a bit up and down again triggers it as expected.

![load-more](https://user-images.githubusercontent.com/2261188/82662989-22d4f880-9c2f-11ea-9da4-c31ab624ffed.gif)

##### Tested on [device], Android [version], WPAndroid [version]
Emulator API 27

**Comment by RenanLukas** [comment] 2024-03-12 19:14
@daniloercoli  👋 

I wasn't able to reproduce this issue. It might've been fixed by our recent changes on the Reader, but I wanted to ask if you were able to reproduce it before closing the issue.

**Comment by RenanLukas** [comment] 2024-03-12 20:35
Thanks for also testing it, @daniloercoli. As discussed in DM I'm closing this ticket since we couldn't reproduce it.

**Closed by RenanLukas** 2024-03-12 20:35 UTC
Labels: [Type] Bug, [Pri] Low, Reader
