### ISSUE TITLE
Post List - published draft isn't automatically animated out of the drafts list

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9598] opened 2019-04-11 15:51 UTC
### Expected behavior
When I publish a post from Drafts, the post automatically disappears from the drafts tab and appears in the published tab.

### Actual behavior
When I publish a post from Drafts, the post won't disappear from the drafts tab and won't automatically appear in published tab. I need to manually pull-to-refresh.

![published-post-wont-disappear-from-drafts](https://user-images.githubusercontent.com/2261188/55971881-9e215800-5c82-11e9-8bed-b84784236001.gif)

### Steps to reproduce the behavior
1. Create a draft
2. My Site
3. Blog Posts
4. Drafts tab
5. Click on publish
6. Notice "uploading post" label is displayed, but when the uploading finishes the post doesn't disappear from the drafts tab

Note introduced in https://github.com/wordpress-mobile/WordPress-Android/pull/9590

##### Tested on [device], Android [version]
Emulator Android 9

**Comment by oguzkocer** [comment] 2019-04-12 17:38
I can't reproduce this issue anymore, closing it for now. @malinajirka Please feel free to re-open it if you can still reproduce it.

**Closed by oguzkocer** 2019-04-12 17:38 UTC
Labels: Post List, [Pri] High, [Type] Bug
