### ISSUE TITLE
Stats Widget: Wrong widget 5×2 size - It should be 5x1

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5642] opened 2017-04-13 07:50 UTC
Fix the widget 5×2 size. it uses extra line, while it could be 5×1.

Other info:
Tablet (Nexus 9) - stats widget is 3×1
Nexus 6P - stats widget was 5×1

**Comment by simison** [comment] 2018-02-23 17:27
Same with Mi A1, Android 8.0.0

![image](https://user-images.githubusercontent.com/87168/36607503-797d0460-18cf-11e8-858a-ffa8628c72a3.png)

**Comment by 0nko** [comment] 2018-03-09 20:30
I've tried >10 different configurations trying to emulate the mentioned devices but I can't reproduce the problem, so it seems to be device-specific. There is a project coming up that will redesign the stats widget anyway so I'm closing this issue.

**Comment by SiobhyB** [comment] 2018-08-29 09:48
Noting for posterity: We received another report of this issue in 1371328-z from someone using an Xperia XZ Premium on Android O. I haven't been able to replicate on my Pixel.

**Comment by ThorEgilGit** [comment] 2018-08-29 10:00
@SiobhyB - Yes, I have sent a screenshot to your support system showing the widget to be 2 rows high on my Sony Xperia XZ Premium (Model G8141) running Android 8.0.0 (Build number 47.1.A 12.270)

**Comment by simison** [comment] 2018-08-29 10:03
Confirming this is still the situation with WP 10.6 on Android 8.1.0 on device Mi A1:

I checked that changing "text size" from system preferences doesn't affect this.

![image](https://user-images.githubusercontent.com/87168/44780982-eb393980-ab8b-11e8-829d-589f98ce2df9.png)

**Comment by simison** [comment] 2018-08-29 10:06
Noting that Android supports different apps to manage your home screen (effectively _be_ your home-screen) — I think mine is currently with Google's home screen app, but each device manufacturer might ship with their own.

**Comment by ThorEgilGit** [comment] 2018-08-29 10:10
My home app is "Xperia Home" - The deafult app. I haven't installed any alternatives.

**Comment by daniloercoli** [comment] 2018-08-30 16:07
Reopened this issue, maybe we can find someone with a Xperia device in the team and get a quick fix out before the whole Stats refresh.

**Comment by ThorEgilGit** [comment] 2018-10-24 06:52
Would be nice if someone could look at this. Shouldn't be too hard to fix.

**Comment by ThorEgilGit** [comment] 2018-11-22 10:45
Now updated to Adnroid 9.0 on Sony Xperia XZ Premium (Model G8141). 
Still same problem.

**Comment by ThorEgilGit** [comment] 2019-01-28 12:21
2 years celebration coming up soon. Is this irritating and screen-wasting issue really so hard to fix?

**Comment by thehenrybyrd** [comment] 2019-04-26 10:54
Had another question about this in 1987803-z.

![androidwidget](https://user-images.githubusercontent.com/15107387/56803185-b2d92080-682a-11e9-8a29-14f22a092cd7.png)
The user would like to be able to fit stats from 3 blogs on the homescreen.

**Comment by designsimply** [comment] 2019-07-03 21:59
Tested with WPAndroid alpha-177 (12.8 alpha) on Pixel 3 Android 9 and confirmed that the "WordPress Today's Stats" widget is still taking up a lot of horizontal space it may not need:

<img src="https://user-images.githubusercontent.com/1119271/60627500-7a663d80-9dab-11e9-999e-0f4955e80c6b.png" width="270" alt="Screenshot_20190703-155704">

**Comment by 0nko** [comment] 2019-07-04 07:47
The widgets are being completely overhauled (https://github.com/wordpress-mobile/WordPress-Android/pull/10037) and the new ones are coming in 12.8, so I'll close this.

**Closed by 0nko** 2019-07-04 07:47 UTC
Labels: Mobile Request, Stats, [Pri] Medium, [Type] Broken Window

**Comment by ThorEgilGit** [comment] 2019-07-17 14:12
Just downloaded 12.8 - same problem with the Widget persists. Please reopen this issue.

And please don't close it again until the bug is fixed and verified.

**Comment by 0nko** [comment] 2019-07-17 14:29
@ThorEgilGit Is it happening with the new widgets (can you please provide a screenshot)? Because AFAIK the old ones are still there and those weren't touched.

**Comment by ThorEgilGit** [comment] 2019-07-17 15:18
Which new widgets? I can see only the same old one.

**Comment by ThorEgilGit** [comment] 2019-07-18 09:26
Ah.

Might have helped if you prefixed the names with "WordPress" so it was possible to find them.
And none of of these are a replacement for the old one really.
