### ISSUE TITLE
Confusing "Update" buttons in the Editor

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#9825] opened 2019-05-09 12:52 UTC
When editing a published post we offer 2 "Update" options:
- A textual button on the action bar.
- A menu item from the action bar sub menu.

![Screenshot_15574057931](https://user-images.githubusercontent.com/40213/57454471-33efd900-7269-11e9-966b-b2adbada28ca.png)

To add more confusion, when the user taps on the menu item from the sub menu, they gets a confirmation dialog that doesn't show from the other button (different code paths).

Having 2 different "saving" options make sense on a Draft or on a New post (Publish / Save as draft). But on a published post we should only have one option "Update". 

Note: we could eventually add a second option for published posts: "remotely save without publishing, this allows you to continue editing without publishing current modifications". Technically this would create a remote-auto save without publishing changes.

**Comment by yaelirub** [comment] 2019-05-14 22:17
@maxme , is this a duplicate of : https://github.com/wordpress-mobile/WordPress-Android/issues/9612 ?

**Comment by maxme** [comment] 2019-05-15 07:17
@yaelirub It might be related. Having the "Update" button in the action bar might a bug, if this is the case fixing it should fix this ticket and #9612

**Comment by shiki** [comment] 2019-05-22 18:30
Subscribing @wordpress-mobile/ravenclaw

**Comment by malinajirka** [comment] 2019-06-12 11:22
>we could eventually add a second option for published posts: "remotely save without publishing, 

We should be careful about adding this option as it would save only `title, content and excerpt` (other fields are not supported in `autosave`). It might confuse the users that each option is behaving a bit differently. On the other hand Calypso also uses the autosave and afaik it doesn't cause any UX troubles.

Both of these solutions sound good to me.
1. Show a publish confirmation dialog when you click on "Update" in the toolbar - it updates a published post, so it should require an explicit confirmation.
2a. Remove the "update" action from the submenu as it doesn't make sense to have two identical actions
2b. Replace the "update" action from the submenu with something like "save without publishing".

**Comment by maxme** [comment] 2019-06-12 11:45
> We should be careful about adding this option as it would save only `title, content and excerpt` (other fields are not supported in `autosave`). It might confuse the users that each option is behaving a bit differently. On the other hand Calypso also uses the autosave and afaik it doesn't cause any UX troubles.

Thanks for bringing this, I forgot about it. And you're right, it's probably confusing.

> Both of these solutions sound good to me.
> 
>     1. Show a publish confirmation dialog when you click on "Update" in the toolbar - it updates a published post, so it should require an explicit confirmation.
> 
>     2. a.Remove the "update" action from the submenu as it doesn't make sense to have two identical actions
>        b. Replace the "update" action from the submenu with something like "save without publishing".

Regarding the potentially confusing "save without publishing" option, I'd got with option 1.

**Closed** 2019-06-21 12:28 UTC
Labels: 3, Needs Design, Posting/Editing, [Pri] Medium, [Status] Needs Discussion, [Type] Enhancement
