### ISSUE TITLE
Check for Grammar and Spelling Mistakes

### ISSUE THREAD

**Issue by thabotswana** [wordpress-mobile/WordPress-Android#14703] opened 2021-05-24 10:29 UTC
>its just that theres no feature that detects your grammar mistakes and spelling errors, unlike the website

From a [4-star WPAndroid app review](https://play.google.com/console/u/1/developers/7957760354032996428/app/4973361825681449040/user-feedback/review-details?reviewId=gp%3AAOqpTOH8XnkI6E-ehRvI8meE-mdY_WMEcUZomVlG6RgqD8xKlOh8B8IwC2O3378RjoxB43Khv_38ql5Nxwj3yw&corpus=PUBLIC_REVIEWS).

**Comment by thehenrybyrd** [comment] 2021-05-25 08:00
I'm seeing spell check on WP Android with my Nokia 2, Android 7.1.1.
<img src="https://user-images.githubusercontent.com/15107387/119461279-363a0880-bd48-11eb-9a78-76c00e4ec422.png" width="40%">

On my Samsung Galaxy S21, Android 11, it seems the system spelling suggestions take care of everything.
<img src="https://user-images.githubusercontent.com/15107387/119461329-3e924380-bd48-11eb-8ba2-e5160feda990.jpg" width="40%">

@hypest could you help us understand what the expected behavior is here?

**Comment by mchowning** [comment] 2021-05-25 19:20
The Android system will take care of any spell checking (as long as it is enabled: `Settings > System > Languages & Input > Advanced > Spell Checker`). This won't provide any grammar checking though. We do not have anything specific in the app for spell or grammar checking.

> theres no feature that detects your grammar mistakes and spelling errors, _**unlike the website**_ 
> (emphasis added)

AFAIK Gutenberg does not offer any spelling or grammar checking on the web either beyond what the browser might provide. 🤔

**Comment by mchowning** [comment] 2021-05-26 14:59
I'll go ahead and close this since this is something that is handled by the OS (or by third-party keyboards like [Grammarly](https://play.google.com/store/apps/details?id=com.grammarly.android.keyboard&hl=en_US&gl=US)), but let me know if you have any questions or if you think we should keep this open.

**Closed as completed by mchowning** 2021-05-26 14:59 UTC
Labels: [Type] Enhancement
