### ISSUE TITLE
NullPointerException: site.wpApiRestUrl must not be null

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15079] opened 2021-07-27 09:25 UTC
**Sentry Url**: https://sentry.io/share/issue/bfb23541b38b41b8be6cb40b4e48fcda/
**User Count**: 111
**Count**: 1223
**First Release**: org.wordpress.android@17.3.1+1049
**First Seen**: 2021-05-21T14:36:32.722000Z
**Last Seen**: 2021-07-27T09:23:58Z
**24 Hours**: 34
**30 Days**: 635

```
NullPointerException: site.wpApiRestUrl must not be null
     at org.wordpress.android.fluxc.store.ReactNativeStore.executeWPAPIRequest(ReactNativeStore.kt:118)
     at org.wordpress.android.fluxc.store.ReactNativeStore.executeWPAPIRequest(ReactNativeStore.kt:93)
     at org.wordpress.android.fluxc.store.ReactNativeStore$executeRequest$2.invokeSuspend(ReactNativeStore.kt:69)
     at org.wordpress.android.fluxc.store.ReactNativeStore$executeRequest$2.invoke(null:10)
     at org.wordpress.android.fluxc.tools.CoroutineEngine.withDefaultContext(CoroutineEngine.kt:27)
     at org.wordpress.android.fluxc.store.ReactNativeStore.executeRequest(ReactNativeStore.kt:65)
     at org.wordpress.android.ui.posts.reactnative.ReactNativeRequestHandler$performGetRequest$1.invokeSuspend(ReactNativeRequestHandler.kt:34)
...
(8 additional frame(s) were not displayed)
```

**Comment by AmandaRiu** [comment] 2021-07-29 01:22
**Crash Triage:** 

After reviewing several crash events across different release versions I've determined that the actual error appears to be thrown by calling [`slashJoin(site.wpApiRestUrl, path)`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/30ddd953de81208daacd793c08ea9ff93de0448d/fluxc/src/main/java/org/wordpress/android/fluxc/store/ReactNativeStore.kt#L233) when `site.wpApiRestUrl = null`. Reading through the code this *shouldn't* happen, but this is all happening inside a suspended function called by React Native and there is a place where we set `site.wpApiRestUrl` to `null` and after checking several crash events one thing they all have in common is they have multiple "Updating site: site_url" log messages. Is it possible that these simultaneous updates are somehow stepping on each other causing a race condition where `site.wpApiRestUrl` is set to `null` just as `slashJoin(...)` is called? If so maybe a possible fix would be to only used a clone version of `SiteModel` or to make updates to `SiteModel` thread-safe.

**Comment by mchowning** [comment] 2021-07-29 14:53
I think this is a duplicate of https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1579. @malinajirka's [explanation for it](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1579#issuecomment-646079649) is the only thing that makes sense to me:

> It could theoretically be caused by a race condition - if a different thread modified the site object.

I'll go ahead and close this in favor of the other issue, but feel free to reopen this if you think we should leave this open.

**Closed as completed by mchowning** 2021-07-29 14:53 UTC
Labels: Media, [Type] Crash
