### ISSUE TITLE
Story block: Error when trying to take a photo

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/WordPress-Android#15795] opened 2022-01-05 12:07 UTC
**Describe the bug**
On the Story block, taking a photo for including it in the block fails with the error message `Error saving image`.

**NOTE:** This error is specific to Android as on iOS this functionality works as expected.

**To Reproduce**
1. Open the WordPress app on an Android device.
1. Open/create a post/page.
1. Add a Story block.
1. Tap on "ADD MEDIA".
1. Tap on the camera button.
1. Try to take a photo.
1. Observe that an error is displayed and the photo taken is not used in the block.

**Expected behavior**
Taking photos within the Story block should work without errors.

**Screenshots**

https://user-images.githubusercontent.com/14905380/148214432-6db80de9-bf84-4c8f-a578-63b0f6e30d3b.mp4

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE 5G
 - OS: Android 11
 - Version 18.8 (1143)

**Additional context**
N/A

**Comment by hypest** [comment] 2022-01-14 14:42
👋 @mzorz ! Since you've worked on this feature in the past, I wonder if you could give it a super quick look to help zoom in where the issue is on the code? Perhaps then we can find someone to dive in deeper and fix. Thanks!

**Comment by jhnstn** [comment] 2022-02-21 19:56
I'm unable to reproduce this on 
- WPAndroid 19.2-rc-3 
-  Android 12 / Pixel 6

**Comment by fluiddot** [comment] 2022-02-22 08:38
Maybe this issue was already addressed as part of https://github.com/wordpress-mobile/WordPress-Android/pull/15832.

**Comment by mkevins** [comment] 2022-03-04 03:47
I am also unable to reproduce this (as of 86225c24031aa7af40e3a2371a46884268aa9ced), and I also believe this was fixed in #15832. Closing :+1:

**Closed as completed by mkevins** 2022-03-04 03:47 UTC
Labels: [Type] Bug, Posting/Editing, Media
