### ISSUE TITLE
Crash report on many versions: RuntimeException: InputChannel is not initialized

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5664] opened 2017-04-17 10:38 UTC
```
Fatal Exception: java.lang.RuntimeException: InputChannel is not initialized.
       at android.view.InputEventReceiver.nativeInit(InputEventReceiver.java)
       at android.view.InputEventReceiver.<init>(InputEventReceiver.java:70)
       at android.view.ViewRootImpl$WindowInputEventReceiver.<init>(ViewRootImpl.java:6057)
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:637)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:313)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3176)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2488)
       at android.app.ActivityThread.access$900(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5441)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

55eaf425f5d3a7f76bcf5820-fabric

**Comment by hypest** [comment] 2018-01-09 10:39
Related bug report: https://issuetracker.google.com/issues/37018931

**Comment by designsimply** [comment] 2019-05-07 17:14
**30-day impact:** ~0.2 per day (or 6 crashes in the last 30d)
**Users affected:** 4
**Last seen in:** 12.1.2

<sup>(55eaf425f5d3a7f76bcf5820-fabric-android)</sup>

Leaving this open but lowering in priority because it is currently not being reported very frequently and because it has a bug report in Google's issue tracker with a designated priority, severity, and assignee.

**Comment by designsimply** [comment] 2019-10-10 22:38
**90-day impact:** 3
**Users affected in the last 90 days:** 2

<sup>https://sentry.io/share/issue/feacb7d19d3949ab96041ac2c635a9e1/</sup>

Low priority due to low volume.

**Comment by designsimply** [comment] 2019-11-06 04:28
**90-day impact:** 3
**Users affected in the last 90 days:** 2

<sup>https://sentry.io/share/issue/feacb7d19d3949ab96041ac2c635a9e1/</sup>

Candidate for closing.

**Comment by malinajirka** [comment] 2019-11-19 11:45
I can confirm the app crashes with this issue very sporadically. I double checked the issue isn't hidden in another entry in Sentry => closing.

**Closed by malinajirka** 2019-11-19 11:45 UTC
Labels: General, [Pri] Low, [Type] Crash

**Comment by XiaLeon** [comment] 2020-02-25 12:49
why was this issue closed? have you got it solved? @malinajirka Thanks!

**Comment by malinajirka** [comment] 2020-02-25 12:53
@XiaLeon Hello there, we haven't knowingly fix the issue but the crash-rate dropped close to zero so we decided not to focus on it.
