### ISSUE TITLE
Me > Log in to WP.com shows a blank screen after self-hosted login (WPAndroid)

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-Android#17413] opened 2022-11-02 13:34 UTC
Reproducible only on WPAndroid. JPAndroid works fine.

### Expected behavior
After logging in via site address,  I expected to see the login screen after navigating to Me > Log in to WordPress.com.

### Actual behavior
After logging in via site address, navigating to Me > Log in to WordPress.com shows a blank screen.

### Steps to reproduce the behavior
1. Create a Jurassic Ninja site
2. Log in via site address
3. Go to Me > Log in to WordPress.com
4. A blank screen is shown

**Comment by antonis** [comment] 2022-11-02 16:35
I've tried to reproduce the issue on a Pixel 5 (Android 13) without a success. After logging in I see the select site screen where I can select the desired site and proceed to the my site screen.

**Comment by ovitrif** [comment] 2022-11-02 18:05
I was also not able to reproduce this on the beta `21.1` version (Samsung S8+ Android 9):

https://user-images.githubusercontent.com/4588074/199566705-0a052e7a-ecbc-444b-a3f6-e30c9808ad8b.mp4

Second part from the preview is more relevant for this issue.

**Comment by thehenrybyrd** [comment] 2022-11-08 08:00
Seems this issue is likely related to https://github.com/wordpress-mobile/WordPress-Android/issues/17412. Both issues have proven difficult to reproduce, and in both cases reinstalling the app fixes the issue. 
I'll prioritize these as medium (high severity, low impact) for now, but this deserves more investigation if we run into it in betas again.

**Comment by guarani** [comment] 2023-11-02 20:53
👋 @momo-ozawa, I checked and couldn't reproduce this either. Do you think we should close this?

**Comment by irfano** [comment] 2024-03-20 12:21
I also tried to reproduce by testing different cases, but I was unable to do so.  I am closing this since there have been no further reports following Momo's case.

**Closed as not planned by irfano** 2024-03-20 12:21 UTC
Labels: [Type] Bug, [Pri] Medium, Self-hosted, Login
