### ISSUE TITLE
Crash when pasting text on Samsung Devices running Android 8

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-Android#8827] opened 2018-12-19 18:55 UTC
It appears we're getting a crash specific to Samsung devices with Android 8.

The relevant bits of the stack trace:

```
Fatal Exception: java.lang.IndexOutOfBoundsException: 51, -49
       at android.text.PackedIntVector.deleteAt(PackedIntVector.java:222)
       at android.text.DynamicLayout.reflow(DynamicLayout.java:317)
       at android.text.DynamicLayout.-wrap0(Unknown Source)
       at android.text.DynamicLayout$ChangeWatcher.reflow(DynamicLayout.java:750)
       at android.text.DynamicLayout$ChangeWatcher.onSpanChanged(DynamicLayout.java:779)
       at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1292)
       at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:647)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
       at android.widget.TextView.pasteClipBoardData(TextView.java:673)
       at android.widget.TextView.-wrap8(Unknown Source)
       at android.widget.TextView$TextViewClipboardEventListener$1.run(TextView.java:581)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

The `android.widget.TextView.pasteClipBoardData` part seems like the main issue AFAICT.

reference: 5a8aafe48cb3c2fa635d5605-fabric
marked as high priority as it's happening ~40 times/day and affecting ~1000 users

**Comment by marecar3** [comment] 2019-01-10 15:48
**Update :**

Also reproduced on Samsung Galaxy S9, Android 8.0 from browserstack.com account
App version : alpha: 144

**Comment by marecar3** [comment] 2019-01-10 16:48
Thanks @daniloercoli ! I have closed that one.

**Comment by designsimply** [comment] 2019-03-15 17:30
<blockquote>reference: 5a8aafe48cb3c2fa635d5605-fabric
marked as high priority as it's happening ~40 times/day and affecting ~1000 users</blockquote>

Noting that this crash is still happening in 11.9 and happened overall 1189 times (~40 times a day) for 440 users from Feb 14 - Mar 14, 2019.

**Comment by malinajirka** [comment] 2019-03-19 15:10
This seems a bit similar to https://github.com/wordpress-mobile/WordPress-Android/issues/8828.

Since we are able to replicate this issue, I'd suggest trying to disable the HardwareAcceleration ->if it fixes the crash, I believe we can merge these two tickets together. Simply add `android:hardwareAccelerated="false"` to `application` tag in AndroidManifest.xml. cc @daniloercoli

**Comment by malinajirka** [comment] 2019-03-19 19:18
I'm sorry for not being clear - I wasn't suggesting we should disable the hardwareAcceleration in the manifest in production. I suggested it only to test whether it fixes the crash so we can decide whether to merge the issues or not. 

I just want to make sure we won't release two fixes for both issues even though one fix would be enough. However, since it seems the fix for 8828 won't be merged any time soon if ever, so fixing this issue makes sense.

**Comment by daniloercoli** [comment] 2019-03-21 17:29
Fixed in https://github.com/wordpress-mobile/AztecEditor-Android/pull/795!
(Or we tried to fix it :))

**Closed by daniloercoli** 2019-03-21 17:29 UTC
Labels: [Pri] High, [Type] Crash

**Comment by designsimply** [comment] 2019-08-21 21:42
A user running WP 13.0.1 on a Samsung SM-A520F device with Android 8 is reporting seeing the following message when they try to paste content into the visual editor (they checked both Aztec and the block editor).

> Sorry, this feature is disabled on Android 8. Please use the Paste action instead.

<img src="https://user-images.githubusercontent.com/1119271/63470572-33e7a380-c42a-11e9-9639-a990e1344629.jpg" width="270" alt="Screenshot_20190821-121645_WordPress">

To double check, is this the expected behavior? If so, I think the best advice for the user will be to paste in HTML Mode or upgrade to the latest version of Android if at all possible. Do you agree?

<sup>(internal reference: 2291211-zen)</sup>

**Comment by malinajirka** [comment] 2019-08-22 09:19
>To double check, is this the expected behavior?

They should see both options "Clipboard and Paste". It seems they see only "Clipboard", which doesn't work as expected and hence is disabled. I'm not sure why they don't see regular "Paste" 🤷‍♂.

>If so, I think the best advice for the user 

Tbh I'm not sure:D. I think the feature is disabled in both visual and html editors. Newer version of Android isn't officially supported :(.

@daniloercoli any ideas?

**Comment by malinajirka** [comment] 2019-11-26 10:23
@jd-alexander Good find on the related issue ;). Since the new crash in Sentry seems to be happening only on Android 7, I'd consider creating a brand new issue with a link to this issue. Another option is to re-open this issue and update its title, but a lot of the comments might be confusing since they are explicitly mentioning Android 8.

**Comment by jd-alexander** [comment] 2019-11-28 18:56
I will opt for creating the new issue and linking it to this one :)
