### ISSUE TITLE
Editor: App becomes unresponsive when loading large posts

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8628] opened 2018-11-19 11:10 UTC
A user reports that the app brings up a black screen and becomes unresponsive (shows “Application Not Responding (ANR)” error dialog) when loading large posts. The post does eventually load in the editor after choosing to wait.

In the reported case, the word count for the post is about 20,500 words (400 kb of content) and has a large amount of HTML. I tested with a post that has about 30,000 words (400 kb of content) and reproduced the black screen briefly, but no ANR error dialog. It's possible that the ANR is related to Aztec processing the HTML in the post, as well as the text content.

We should keep an eye on how Gutenberg performs with posts like this.

Internal ref: p4a5px-2iV-p2

**Comment by designsimply** [comment] 2019-02-25 19:21
Tested and confirmed using Pixel 3, Android 9, WPAndroid alpha-153 (11.9 alpha) on a self-hosted site running WP 5.1 and Gutenberg 5.1.1. Reported at https://github.com/wordpress-mobile/gutenberg-mobile/issues/672.

**Comment by designsimply** [comment] 2019-03-19 17:32
Adding some links to sample data which can be used for testing large posts:

1. [Gutenberg Demo Post](https://github.com/dmsnell/gutenberg-document-library/blob/master/library/demo-post.html)
1. [Lipsum generator](https://www.lipsum.com/) (enter `10000`, select "words", click Generate Lorem Ipsum)
1. https://github.com/WordPress/gutenberg/issues/11782#issuecomment-438213916
1. https://github.com/WordPress/gutenberg/issues/10418#issuecomment-436431030

**Comment by drspaceboo** [comment] 2019-03-28 01:32
Could not recreate this in either master or develop. Tried both in emulator and on my Pixel 3.

**Comment by designsimply** [comment] 2019-05-09 19:29
This came up again in another user report and here are the steps to reproduce I came up with after reading their case:

1. Create a new post using the Aztec editor in the app on an Android Tablet.
1. Add 3000+ words.
1. Add at least 6 YouTube video embeds.
1. Add 45 to 85 images interspersed.
1. Try landscape and portrait modes.

I think the large number of images are the culprit in this case.

<sub>(internal references: p4a5px-2om-p2/#comment-9755 and 1953510-zen)</sub>

**Comment by mkevins** [comment] 2019-08-16 09:18
I have reproduced this using the steps described on Android emulator Nexus 5X, API 25 (Android 7.1.1).

I tried profiling, and noticed a large increase in memory usage (expected) when opening the post:
<img width="1441" alt="large-post-profile" src="https://user-images.githubusercontent.com/8507675/63157206-c3bbd500-c059-11e9-9a3e-d3ca27655381.png">

Interestingly, after exiting the post, and editing a much smaller post, the memory usage was still very high:
<img width="1438" alt="large-post-profile-2" src="https://user-images.githubusercontent.com/8507675/63157277-e77f1b00-c059-11e9-9915-cea07fdc096c.png">

This may be due to a delay in garbage collection, or it may indicate a memory leak of some kind. With usage that high, I would expect more aggressive garbage collection. Also, I noticed that after the initial network load (of the smaller post), the memory usage _slightly_ declined, indicating that garbage collection may be occurring.

I will try opening this same post on a "newer" emulator (with better specs), after modifying the run configuration to see if there are any clues in the more detailed profile.

**Comment by mkevins** [comment] 2019-08-16 13:18
I profiled the editor for using the large post on emulated Pixel 2 - Android 8.1 (API 27). First, I tried with Pixel 3 XL (API 29) but got a message that "Q devices are not yet supported" :man_shrugging:.

The overview shows the same general profile:
<img width="1406" alt="large-post-aztec-profile" src="https://user-images.githubusercontent.com/8507675/63168394-5b7bec00-c077-11e9-9ba1-30c6af4f859f.png">
 We can see the network spike coinciding with the rise in CPU, followed by the increase in memory consumption.

A more detailed look at the memory profile shows an increase in native memory consumption as the after the `AztecEditorFragment` is resumed. Java memory also increases, but to a lesser extent (native and Java memory represented by dark and light blue, respectively). We can also see that garbage collection is occurring throughout the duration of the profile. In particular, there is a high density of garbage collection events just as the editor begins to load. I'm not sure yet if there's something that can be optimized there, but it may be worth a closer look.

<img width="1410" alt="large-post-aztec-memory-profile" src="https://user-images.githubusercontent.com/8507675/63168089-80239400-c076-11e9-8213-fd8a9b5c49b0.png">

Talking a closer look at that proportion of the profile, sorted by allocation count for that selected duration, we can find the first occurrence of our app-specific package name, and sure enough, a large number of images are being loaded here, resulting in the allocations. Selecting an instance, we can see the call stack responsible for that particular allocation (in this case, they'll all be the same, as they are loaded as part of a loop).

<img width="1410" alt="large-post-aztec-memory-profile-load-images" src="https://user-images.githubusercontent.com/8507675/63169092-47d18500-c079-11e9-8213-e7144a774eb4.png">

Interestingly, this time when I opened the smaller post after the allocations already occurred on the larger post, I observed that memory consumption went down again:

<img width="1403" alt="small-post-aztec-profile" src="https://user-images.githubusercontent.com/8507675/63169445-3177f900-c07a-11e9-9851-6fc33a7731ad.png">

A closer look reveals the previous `EditPostActivity` destroyed, and the garbage collector freeing that memory once again.

<img width="1410" alt="large-post-aztec-memory-profile-edit-post-activity-destroyed" src="https://user-images.githubusercontent.com/8507675/63169551-6be19600-c07a-11e9-9702-8128b173ed33.png">

I'm not sure it the `EditPostActivity` was destroyed this time simply because I waited longer, so it was in the background for a longer time, or if it was because the second (smaller) post I opened was opened with the Gutenberg editor. In any case, it's natural for a lot of images to consume a lot of ram, and we cannot easily utilize optimizations available in implementations like RecyclerView since the whole post lives within a single EditText. My gut feeling is that solving this to handle very large posts performantly would require some non-trivial architecture changes. Still, there may be a win in the editor startup times if we can pin down what is triggering all the garbage collections.

**Comment by planarvoid** [comment] 2019-09-24 09:45
> In any case, it's natural for a lot of images to consume a lot of ram, and we cannot easily utilize optimizations available in implementations like RecyclerView since the whole post lives within a single EditText. My gut feeling is that solving this to handle very large posts performantly would require some non-trivial architecture changes. Still, there may be a win in the editor startup times if we can pin down what is triggering all the garbage collections.

I think you're absolutely right and there isn't anything we can do right now. Aztec was designed this way and loading big posts will always be slow. We must hope that moving to Gutenberg and refactoring of the EditPostActivity (which will start soon) will help with this problem.

**Comment by SiobhyB** [comment] 2021-03-31 15:45
I copied each of the writing samples Sheri listed in [this comment](https://github.com/wordpress-mobile/WordPress-Android/issues/8628#issuecomment-474484034) to a new post on my test site. I then opened them in the app and had the following results when attempting to edit each post: 

* [Gutenberg demo post](https://github.com/dmsnell/gutenberg-document-library/blob/master/library/demo-post.html): Loaded almost instantly, with no noticeable issues as I scrolled and navigated to Post Settings.
* [Lipsum generator](https://www.lipsum.com/feed/html) with 10000 words: Loaded almost instantly, with no noticeable issues as I scrolled and navigated to Post Settings.
* https://github.com/WordPress/gutenberg/issues/11782#issuecomment-438213916: The post took 14 seconds to load and the app froze when I attempted to navigate to Post Settings, ending with the `WordPress isn't responding` dialog and a crash.
* https://github.com/WordPress/gutenberg/issues/10418#issuecomment-436431030: Took slightly longer to load, around 4 second, but no noticeable issues as I scrolled and navigated to Post Settings. 

The above was tested on a Pixel 5, Android version 11, and version alpha-285 of the WordPress app.

I also found the following relevant issues open in the Gutenberg Mobile repository: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2628, https://github.com/wordpress-mobile/gutenberg-mobile/issues/1888

Leaving this issue open as I was able to replicate the app becoming unresponsive in the third example.

**Comment by SiobhyB** [comment] 2021-03-31 16:45
cc-ing @hypest to get a second opinion on closing this in favour of the two related reports I linked to from the Gutenberg Mobile repository. I think they overlap well with the issue I was able to reproduce but I may be missing a case for keeping this one open.

**Comment by hypest** [comment] 2021-04-01 10:29
Thanks for checking the current status of this ticket @SiobhyB !

> WordPress/gutenberg#11782 (comment): The post took 14 seconds to load and the app froze when I attempted to navigate to Post Settings, ending with the WordPress isn't responding dialog and a crash.

Just to be sure, did you try a converted-to-blocks version of that content or perhaps only copy pasted that content in Gutenberg's code editor? If the latter, the editor that will open up in native will be Aztec which indeed takes time and _freezes_ the UI upon loading. But, gutenberg-mobile won't actually freeze the UI. Here's the [test post I tried](https://stefanosuser.wordpress.com/?p=2532&preview=true) on my test site, after converting to blocks. In my testing on an Android 11 Pixel 2XL, the _editor_ loads instantly, the UI is responsive (example: the 3-dot menu in the top right), although the content itself does take its time to load (~41secs).

Can you try again? If you still find the app unresponsive then we should keep this ticket open, otherwise let's close it.

**Comment by SiobhyB** [comment] 2021-04-06 15:25
Thanks @hypest, I can confirm I'd copied/pasted that particular post into a classic editor block. 🤦‍♀️ It all works as you outlined if I convert to blocks then try loading the editor again. All the other posts were tested within the editor's converted-to-blocks version. I'll go ahead to close this issue for now, given that we won't be focusing efforts on the classic editor going forward.

**Closed by SiobhyB** 2021-04-06 15:25 UTC
Labels: Aztec, Mobile Request, Posting/Editing, [Type] Bug, gutenberg-mobile
