### ISSUE TITLE
Swiping a notification to dismiss should not dismiss all notifications

### ISSUE THREAD

**Issue by jblz** [wordpress-mobile/WordPress-Android#8268] opened 2018-08-31 22:28 UTC
### Expected behavior
Only the item swiped to be dismissed

### Actual behavior
The item disappears & then all app notifications disappear

### Steps to reproduce the behavior
Have more than one notification items, swipe one away

##### Tested on [device], Android [version]
Pixel, Android versions 8 & 9

**Comment by hypest** [comment] 2019-01-09 21:31
Tried app version 11.4 on a Pixel 2 XL running Android 9 and couldn't reproduce it when dismissing one of two notifications. I tried with one comment and one "Like" notification and been able to dismiss the "Like" only. Are there perhaps more specific steps to reproduce? Thanks!

**Comment by jblz** [comment] 2019-01-10 05:56
@hypest I'll keep an eye out for how to reproduce. Perhaps, the issue only surfaces if there are multiple of the same type (e.g. all comments)

**Comment by jblz** [comment] 2019-03-02 07:28
I'm still seeing this from time to time.

Here's what my notification drawer looked like when it occurred recently:

![545352016](https://user-images.githubusercontent.com/1587282/53678854-c042b600-3c92-11e9-8d71-3f6fabba4907.png)

...when I swiped away the bottom note, all three were dismissed.

**Comment by designsimply** [comment] 2019-04-11 18:54
Moving to the `Prioritized` list because even though we can always open the Notifications tab to see what’s up, it's annoying as the feeling is something may have just been missed. Thank you for raising the issue @jblz !

**Comment by jblz** [comment] 2019-04-11 19:44
Thanks, @designsimply!

I think I've noticed this happening more frequently when there are "non-standard" notification types in the list.  For example X-post notifications.  Perhaps that's related.

**Comment by malinajirka** [comment] 2019-08-12 12:48
I've looked into this issue, but it's difficult to fix since we are not able to reproduce it. I've tested different scenarios and everything worked as expected for me.

I have two guesses what might be causing the issue
1. The app crashes in the background when the notification is dismissed.
2. [We create a PendingIntent](https://github.com/wordpress-mobile/WordPress-Android/blob/4edecb81e2fcff53f111dfa5507bb4da1e418025/WordPress/src/main/java/org/wordpress/android/push/GCMMessageService.java#L801) which is processed when the notification is dismissed and this [line](https://github.com/wordpress-mobile/WordPress-Android/blob/ac56c495d4f5cecf2a50f349576f23515679d8b1/WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java#L222) doesn't work as expected (from an unknown reason). We invoke `notificationManager.cancel(GCMMessageService.GROUP_NOTIFICATION_ID);` and all notifications are dismissed

@jblz I'd be great if you could post the application log when this issue happens again. (Click on "Me" -> "Help & Support" -> "Application log". Thank you 🙇 

Note: I'll keep testing this issue on the production version of the app. Hopefully, I'll encounter it sooner or later.

**Comment by antonis** [comment] 2024-03-04 16:20
I'm closing the issue since I wasn't able to reproduce in the latest version of the app


https://github.com/wordpress-mobile/WordPress-Android/assets/304044/16b39c33-801a-4908-987d-1206538c61de

**Closed by antonis** 2024-03-04 16:20 UTC
Labels: [Type] Bug, Notifications
