### ISSUE TITLE
Push Notifications: Incorrect date shown in the new post notification

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#16757] opened 2022-06-16 04:36 UTC
It was reported in 5298277-zd-woothemes, that the app's notification for a new post showed the date as `31/12/1969`.

### Expected behavior

The user expects to see the correct date of the published post in the app notification.

### Actual behavior

The app displayed the date as `31/12/1969`.

**Screenshot**

![Screenshots_2022-06-14-22-08-38](https://user-images.githubusercontent.com/40906847/173992110-626b3269-f74d-4a3b-a86e-d1c4406c891c.png)

##### Reported on LGE LM-Q630, WPAndroid 20.0

**Comment by thehenrybyrd** [comment] 2022-06-16 08:20
@reginabally is there any more information we could use to try to reproduce this?
Some things that would be helpful:
- Does the user see the wrong date for only this blog?
- Are any other users reporting the same issue?
- Were you able to reproduce the issue?

Thanks!

**Comment by reginabally** [comment] 2022-06-17 07:17
Hey @thehenrybyrd Thanks for taking a look!

> Does the user see the wrong date for only this blog?

I've just followed up with the user asking them for more details. We'll report back when we heard back from them.

> Are any other users reporting the same issue?

I haven't been working on WP apps for quite some time, and this is the first report I came across. I've also asked the mobile support team if we've seen any other report.

> Were you able to reproduce the issue?

No, I haven't been able to reproduce it.

So far, the track history records look okay and the actual post was published on the correct date (details shared in the ticket). I don't know how to check the actual content of the notification we sent to the user to further troubleshoot this. I'm hoping someone in the dev team would know.

**Comment by erricgunawan** [comment] 2022-06-18 01:19
User from 5298277-zen reported back with the following:

> Since this year I noticed the error
> On some sites I see this incorrect date

Since they mentioned some other sites, I asked for more samples.

**Comment by igotdes** [comment] 2022-06-21 04:30
The user mentioned noticing the issue on two simple sites so far. They are linked in the ticket notes.

Probably a long shot, but from the screenshot, it looks like the user has a VPN active on their device. Could that be causing issues with the notification dates?

**Comment by antonis** [comment] 2024-03-06 13:51
My understanding is that this is not a native mobile issue but a web app issue that is still reproducible (see screenshots below). I'll close this issue and report on the web if there is no existing issue.

|Installing the web app|Enable notifications|Web vs Native notifications|
|---|---|---|
|![Screenshot_20240306_154155](https://github.com/wordpress-mobile/WordPress-Android/assets/304044/8728af53-ecf5-4bc0-8646-afbd7ae45f31)|![Screenshot_20240306_154356](https://github.com/wordpress-mobile/WordPress-Android/assets/304044/6a5a263c-6b38-4282-a2a8-cd5ea6eb6cac)|![Screenshot_20240306_154532](https://github.com/wordpress-mobile/WordPress-Android/assets/304044/f349c878-896e-4def-813e-a8cac39f6006)|

**Closed as completed by antonis** 2024-03-06 13:51 UTC
Labels: [Type] Bug, [Pri] Low
