### ISSUE TITLE
RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.WPWebViewAc...

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13195] opened 2020-10-21 10:46 UTC
**Sentry Url**: https://sentry.io/share/issue/1988ba5de5754cc0a29032b1c85e3ee9/
**User Count**: 85
**Count**: 326
**First Release**: org.wordpress.android@15.8-rc-2+927
**First Seen**: 2020-10-01T17:49:50.204000Z
**Last Seen**: 2020-10-21T09:32:45Z
**24 Hours**: 14
**30 Days**: 326

```
RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.WPWebViewActivity}: android.view.InflateException: Binary XML file line #42: Error inflating class org.wordpress.android.widgets.NestedWebView
     at org.wordpress.android.widgets.NestedWebView.<init>(NestedWebView.kt:27)
     at org.wordpress.android.widgets.NestedWebView.<init>(NestedWebView.kt:26)
     at org.wordpress.android.widgets.NestedWebView.<init>(NestedWebView.kt:null)
     at org.wordpress.android.ui.WPWebViewActivity.configureView(WPWebViewActivity.java:164)
     at org.wordpress.android.ui.WebViewActivity.onCreate(WebViewActivity.java:40)
     at org.wordpress.android.ui.WPWebViewActivity.onCreate(WPWebViewActivity.java:159)
...
(40 additional frame(s) were not displayed)
```

**Comment by develric** [comment] 2020-10-21 23:29
Could not reproduce this one; logs reports `Resources$NotFoundException: String resource ID #0x2040003` exception while creating `WPWebViewActivity` in various scenarios. In some of them (even if as said not the only scenario) the issue is triggered by `view_site_from_header` when opening a site in the main My Site header menu. @khaykov could you have a look into this in case something rings any bell to you? Thanks 🙇

**Comment by emilylaguna** [comment] 2020-10-26 20:45
👋 @khaykov I just wanted to follow up on this issue to see if you had a chance to look at this or if I should assign it to someone else?

**Comment by khaykov** [comment] 2020-10-27 11:36
@develric @emilylaguna Sorry, I was AFK for the past week, but looking at this issue I think I know what the problem is. I'll push a quick fix asap 👍

**Comment by emilylaguna** [comment] 2020-10-27 13:23
Awesome! Thanks for the heads up, and fixing it so quickly. 🙌

**Closed as completed** 2020-11-02 02:13 UTC
Labels: [Pri] Medium, [Type] Crash, Webviews
