### ISSUE TITLE
Offer to save/discard draft when exiting the editor

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4240] opened 2016-06-16 10:23 UTC
### Expected behavior

When a user exits the editor, the app should encourage the user to either save or discard the changes. For a new post, it can save/discard the entire draft; for changes made to an existing draft, it can update the draft or discard the changes.

This encourages saving drafts to the server (instead of defaulting to saving locally, which has higher risk of content loss e.g. if the user logs out or removes the app) and parallels how the Calypso and iOS editors encourage saving drafts.
#### Calypso

Calypso autosaves drafts and warns you if you are leaving the editor before changes have been saved (for new posts, drafts, and published/scheduled posts):

![screen shot 2016-06-16 at 11 10 12 am](https://cloud.githubusercontent.com/assets/8658164/16113203/1d982574-33b3-11e6-822c-b0f0de068964.png)
#### iOS

Tapping the back button to exit the iOS editor, with unsaved changes in the editor, brings up a prompt to save or discard the changes.

On a new post, it prompts you to Discard, Save Draft, or Keep Editing:

![2016-06-16 11 12 13](https://cloud.githubusercontent.com/assets/8658164/16113281/7a0b14c4-33b3-11e6-8a83-ed5078554853.png)

On an existing draft, it prompts you to Discard, Update Draft, or Keep Editing:

![2016-06-16 11 12 40](https://cloud.githubusercontent.com/assets/8658164/16113511/751cfcb0-33b4-11e6-9786-33929822392c.png)

On a published or scheduled post, it prompts you to Discard or Keep Editing (with the option to Update in the top right in the editor):

![2016-06-16 11 16 02](https://cloud.githubusercontent.com/assets/8658164/16113522/7bdc1ebe-33b4-11e6-9cbe-7c206a8d04a1.png)
### Actual behavior

Currently, tapping back to exit the editor in Android saves the changes locally but does not prompt you to save the changes to the server. This can result in confusion if the user is not familiar with the Status setting in post settings (to save the draft to the server) or content loss if the user only saves drafts locally and then logs out or removes the app.

**Comment by 0nko** [comment] 2016-06-22 17:30
Would it make sense to only show the dialog for non-empty content when changes are detected? This could be the decision logic:

| initial state              | save (online) | save (offline) | discard          |
|----------------------------|---------------|----------------|------------------|
| new post                   | draft         | local draft    | new post deleted |
| draft w/ local changes     | draft         | local changes  | no changes saved |
| published w/ local changes | published     | local changes  | no changes saved |
| local draft                | draft         | local draft    | no changes saved |

**Comment by rachelmcr** [comment] 2016-06-23 08:44
That looks like solid decision logic to me. A couple questions:

- In the iOS app, the only options for published posts are to discard the changes or keep editing (and update the published post using the Update button in the top right in the editor). What will the dialog look like for published posts as compared to drafts?
- Is there a way to dismiss the dialog (e.g. by tapping outside it) if I decide I want to keep editing the post?

cc @diegoreymendez in case you have additional insight based on the logic used in iOS.

**Comment by 0nko** [comment] 2016-06-23 13:16
> In the iOS app, the only options for published posts are to discard the changes or keep editing (and update the published post using the Update button in the top right in the editor). What will the dialog look like for published posts as compared to drafts?
Right now it's the same, but it's easy to change the wording for this case.
> Is there a way to dismiss the dialog (e.g. by tapping outside it) if I decide I want to keep editing the post?
Yeah, tapping outside the dialog or on the back button would just dismiss it and a user could keep editing.

**Comment by rachelmcr** [comment] 2016-06-23 17:02
I think it'd make sense to change the wording for published posts. That would keep it in line with the iOS behavior and make sure the user doesn't unintentionally publish changes to a published post.

**Comment by 0nko** [comment] 2016-06-24 09:22
So how would that work for published posts? Only allow publish & discard? Or should there be 3 options - publish, save changes locally & discard?

**Comment by rachelmcr** [comment] 2016-06-24 09:35
I was thinking of how iOS does it — it offers users two options:
- Discard
- Keep editing

If the user chooses to keep editing, they can update the published post as usual from the editor:

![iOS editor published posts](https://cloud.githubusercontent.com/assets/8658164/16113522/7bdc1ebe-33b4-11e6-9cbe-7c206a8d04a1.png)

**Comment by 0nko** [comment] 2016-06-24 09:48
OK cool.

**Comment by hypest** [comment] 2016-06-29 13:02
May I add my take as well. I think we should *not* present a user with a dialog at all. Calypso doing it (when autosave hasn't kicked in yet) is a different story as in Calypso, closing the tab (for example) will lead to data loss. On the mobile, tapping "back" doesn't present such a problem as we can always save the data a local draft.

Popups break the user flow, and though important some times, I don't think we should do it in this case.

**Comment by nbradbury** [comment] 2016-06-29 15:05
> Popups break the user flow, and though important some times, I don't think we should do it in this case.

FWIW, I agree with @hypest here.

**Comment by diegoreymendez** [comment] 2016-06-29 18:24
@nbradbury, @hypest - That also means the user won't be able to cancel their local changes anymore, though (unless we add a specific mechanism for that).

In principle that sounds fine, unless you want to drop your local changes for whatever reason (thinking for example of old changes that never got to synchronize, then you worked on your post using the web editor, then you go back to your device and have old local changes).

**Comment by hypest** [comment] 2016-06-30 10:52
Hey @diegoreymendez , sorry it wasn't very clear but my objection is actually about the _modal_ dialogs on Android. That is, the dialogs that require the user to decide on the spot before being able to move forward. We don't need to use such dialogs in this case.

The "cancel local changes" is actually a different matter. We already have a (non-modal) mechanism to allow the user to undo/revert the local changes which is displayed for a few seconds after the user exits the editor. We could expand on this if needed. Besides, we're already in the process of revising the whole undo/revert functionality (that is, to offer and expand on it).

**Comment by rachelmcr** [comment] 2016-07-01 07:33
The problem I see with the current behavior is that it defaults to saving locally, and users are getting confused about that. Some users don't think it's possible to sync their drafts to the server (as seen in app reviews) and the steps to save a draft to the server, rather than a local draft, are confusing (as seen both in user feedback and internal dogfooding). Users also sometimes log out or get logged out of the app and end up losing content because it was only ever saved as a local draft.

I suggested a modal dialog mainly because it's how the iOS app works and we don't see the same issues from iOS users, so it seems to be working there. However, if that isn't the preferred way to deal with this, I'd like to explore other solutions to encourage users to save drafts to the server (whether that's auto-save or a clearer route to save drafts).

**Comment by hypest** [comment] 2016-07-01 10:41
Thanks for the suggestion @rachelmcr , keep them coming actually!

I think we're on the same page here, trying to remove the "draft save" friction/confusion and make it more intuitive. The modal dialog is only a detail towards that goal and chances are high we can do without modals. AFAIU, @0nko is already working on a proposal that doesn't depend on modals.

**Comment by 0nko** [comment] 2016-07-01 12:29
I wanted to hear more opinions about the modal-less approach to avoid implementing something we don't want, so currently I'm doing some work on Aztec editor. Hopefully I'll get back to this next week.

**Comment by 0nko** [comment] 2016-11-08 09:27
So I noticed a few months have passed since we last talked about this thing. Is this still something we want to address?

**Comment by hypest** [comment] 2016-11-08 09:53
FWIW, I'd like to see a solution based on best effort (try to update online when possible and making sense) and SnackBars to gently prompt the user for extra actions. Thanks!

**Comment by rachelmcr** [comment] 2017-02-21 12:43
I'd like to nudge this issue again. Recent breakage with WordPress.com OAuth forcibly logged out a number of users, who subsequently lost any local drafts or changes they had made in the app. :( Losing those drafts is a giant breach of trust, and anything we can do to encourage users to save posts to the server (instead of locally) would massively help situations like this.

**Comment by 0nko** [comment] 2017-02-21 21:29
I'm currently busy with Aztec, but I have my groundskeeper rotation next week, so if it can wait I'll try to tackle it then.

**Comment by hypest** [comment] 2017-03-06 13:25
>  logged out a number of users, who subsequently lost any local drafts or changes they had made in the app. :( Losing those drafts is a giant breach of trust...
That's a very good point you raise there @rachelmcr . In that case, the real issue is the problem of having the drafts survive the logout/login barrier and we should prolly raise a different ticket for that. I mean, even with present ticket's (#4240) suggestion, the user can still decide to not publish the draft at the minute she is asked to and a forced logout/re-login will have the same effect of data loss.

**Comment by 0nko** [comment] 2017-03-06 13:32
#4305 solves this in a way, because drafts are automatically saved online. The problem is with published posts and when a device is offline, because posts are only saved locally in those cases.

**Closed** 2017-03-29 21:02 UTC
Labels: Posting/Editing, [Pri] High, [Type] Broken Window, [Type] Enhancement
