### ISSUE TITLE
Reader Post List: relative time spans are not localized

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#3693] opened 2016-02-01 17:37 UTC
In the Post list and Pages list, dates on the posts/pages are not localized. For example, these screenshots show the dates in English when the app's language is set to German:

![2016-02-01 17 27 00](https://cloud.githubusercontent.com/assets/8658164/12725376/51175cb2-c90a-11e5-9275-d3a17f3d97df.png)
![2016-02-01 17 27 06](https://cloud.githubusercontent.com/assets/8658164/12725378/52c19b9a-c90a-11e5-8064-aac544363a32.png)

Tested on Nexus 9, Android 6.0.1, app beta v. 5.0-rc-2.

**Comment by maxme** [comment] 2016-02-02 09:19
Most of the [DateTimeUtils](https://github.com/wordpress-mobile/WordPress-Android/blob/2a57008f7db7414a0ead50c7f1895878a906bda5/WordPress/src/main/java/org/wordpress/android/util/DateTimeUtils.java) functions are not localized, we should have a look at [getRelativeDateTimeString](https://developer.android.com/reference/android/text/format/DateUtils.html#getRelativeTimeSpanString(android.content.Context, long, boolean))

**Comment by nbradbury** [comment] 2016-02-02 11:47
Note that the date formatting relies on Android's `DateUtils.formatDateTime()`, which is locale-friendly based on the *device* language. The problem here is due to the language being chosen in the app rather than the device.

**Comment by rachelmcr** [comment] 2016-02-02 12:00
>The problem here is due to the language being chosen in the app rather than the device.

Good to know. I can confirm that dates are localized when I switch my device language.

That said, since we offer in-app language selection we really should localize the dates regardless of whether the language is set at the device or the app level, if possible.

**Comment by khaykov** [comment] 2016-02-14 02:15
Do you guys mind if I'll take a look at this issue? I have been poking around locale settings anyway.

**Comment by maxme** [comment] 2017-01-02 13:57
This is fixed in Post/Pages even with language being chosen in the app. But it's not in the Reader due to our homemade [`javaDateToTimeSpan`](https://github.com/wordpress-mobile/WordPress-Android/blob/2a57008f7db7414a0ead50c7f1895878a906bda5/WordPress/src/main/java/org/wordpress/android/util/DateTimeUtils.java#L34-L67)

**Comment by maxme** [comment] 2017-01-02 14:00
Updated issue title:

![screenshot-2017-01-02_14 58 11 65](https://cloud.githubusercontent.com/assets/40213/21590440/13d62720-d0fc-11e6-8290-ad82cd849a47.png)

**Comment by nbradbury** [comment] 2017-01-03 21:04
Just looked into this further. I *think* the problem is due to the reader using [javaDateToTimeSpan](https://github.com/wordpress-mobile/WordPress-Utils-Android/blob/develop/WordPressUtils/src/main/java/org/wordpress/android/util/DateTimeUtils.java#L30) from `WordPress-Utils`, which doesn't appear to have localized versions of the "ago" text - [see here](https://github.com/wordpress-mobile/WordPress-Utils-Android/blob/develop/WordPressUtils/src/main/res/values/strings.xml#L4).

**Comment by maxme** [comment] 2017-01-04 06:28
> Just looked into this further. I think the problem is due to the reader using javaDateToTimeSpan from WordPress-Utils, which doesn't appear to have localized versions of the "ago" text - see here.

That's one issue but not the only one, for instance in french: "1h ago" should be "il y a 1h" - so we need a "%s ago" format string.

The other issue is the "1d" coming from [DateTimeUtils](https://github.com/wordpress-mobile/WordPress-Android/blob/ede159c5e56810801529309bed4656033163b15f/libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/DateTimeUtils.java#L44-L60) and might require plurals depending of the language.

I'd much prefer to use the standard lib or a third party lib for displaying these.

**Comment by maxme** [comment] 2017-03-21 12:47
I had a look at the DateUtils functions, and the best we can do is: 
```java
DateUtils.getRelativeTimeSpanString(testTime, now, DateUtils.MINUTE_IN_MILLIS, DateUtils.FORMAT_ABBREV_ALL);
```

Difference with our current implementation, in English:

Our implementation |  DateUtils
--|--
now   |  0 min. ago
1m ago   |  1 min. ago
1h ago   |  1 hr. ago
Mar 11  |  Mar 11

Pros:
* It localized and respect language typography rules (spacing).
* Our implementation vs DateUtils results are similar (we can add the `now` option ourself).

Cons:
* It's a bit longer

**Closed** 2017-03-22 10:46 UTC
Labels: Reader, [Pri] Medium, [Status] Needs Design Review, [Type] Broken Window, [Type] Bug
