### ISSUE TITLE
NullPointerException: Error parsing reader interests [[{"slug":"books","title":"Books","score":22311},{"slug":"food","t...

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#16013] opened 2022-02-28 09:45 UTC
**Sentry Url**: https://sentry.io/share/issue/df6bbbe8ab6f4e94909057ec249f1db1/
**User Count**: 72
**Count**: 421
**First Release**: 19.0-rc-1
**First Seen**: 2022-01-12T03:35:40.301000Z
**Last Seen**: 2022-02-28T08:49:15Z
**24 Hours**: 1
**30 Days**: 409

```
NullPointerException: Error parsing reader interests [[{"slug":"books","title":"Books","score":22311},{"slug":"food","title":"Food","score":21626},{"slug":"technology","title":"Technology","score":20292},{"slug":"entertainment","title":"Entertainment","score":20226},{"slug":"movies","title":"Movies","score":20200},{"slug":"photos","title":"Photos","score":20106},{"slug":"politics","title":"Politics","score":20073},{"slug":"news","title":"News","score":20064},{"slug":"sports","title":"Sports","score":19412}]] at index 0.
     at org.wordpress.android.ui.reader.repository.usecases.ParseDiscoverCardsJsonUseCase.parseInterestCard(ParseDiscoverCardsJsonUseCase.kt:63)
     at org.wordpress.android.ui.reader.repository.usecases.GetDiscoverCardsUseCase$get$2.invokeSuspend(GetDiscoverCardsUseCase.kt:46)
     at org.wordpress.android.ui.reader.repository.usecases.GetDiscoverCardsUseCase$get$2.invokeSuspend(GetDiscoverCardsUseCase.kt:46)
     at org.wordpress.android.ui.reader.repository.usecases.GetDiscoverCardsUseCase$get$2.invoke(null:8)
     at org.wordpress.android.ui.reader.repository.usecases.GetDiscoverCardsUseCase$get$2.invoke(null:4)
     at org.wordpress.android.ui.reader.repository.usecases.GetDiscoverCardsUseCase.get(GetDiscoverCardsUseCase.kt:33)
     at org.wordpress.android.ui.reader.repository.ReaderDiscoverDataProvider$loadCards$2.invokeSuspend(ReaderDiscoverDataProvider.kt:134)
     at org.wordpress.android.ui.reader.repository.ReaderDiscoverDataProvider$loadCards$2.invoke(null:8)
     at org.wordpress.android.ui.reader.repository.ReaderDiscoverDataProvider$loadCards$2.invoke(null:4)
     at org.wordpress.android.ui.reader.repository.ReaderDiscoverDataProvider.loadCards(ReaderDiscoverDataProvider.kt:129)
...
(16 additional frame(s) were not displayed)
```

**Comment by zwarm** [comment] 2022-02-28 14:40
@AliSoftware This is a duplicate of #15912. See this [comment](https://github.com/wordpress-mobile/WordPress-Android/issues/15912#issuecomment-1032742396).

**Comment by zwarm** [comment] 2022-03-03 20:00
Closing this issue. It is a duplicate of #15912

**Closed as completed by zwarm** 2022-03-03 20:00 UTC
Labels: [Type] Crash
