### ISSUE TITLE
Reader: tiled galleries are not formatted as galleries

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#11779] opened 2020-04-29 23:04 UTC
Steps to reproduce:

1. On the web for a WP.com or Jetpack site, create a new post.
1. Add a paragraph.
1. Add a tiled gallery block with several images.
1. Add a few more tiled gallery blocks with various settings.
1. Add another paragraph.
1. Publish the post.
1. View the post in the Reader.

**Result:** tiled galleries don't look like galleries, the images are just stacked.

WPAndroid Reader | Chrome Android 10
---|---
<img src="https://user-images.githubusercontent.com/1119271/80655006-df75d880-8a3a-11ea-9d3c-bee58341fa2d.png" width="200" alt="Screenshot_20200429-125041">|<img src="https://user-images.githubusercontent.com/1119271/80655002-dbe25180-8a3a-11ea-8bac-436b695d7d94.png" width="200" alt="Screenshot_20200429-125050">

<p style="clear:both;"><sup>Tested with WPAndroid 14.7-rc-3 on Pixel 3 Android 10.</sup></p>

**Note:** it's possible this is intentional, if so please close this issue with an explanation. Thank you!

**Comment by designsimply** [comment] 2020-07-04 00:15
Quick note to say Tiled Gallery blocks still aren’t looking quite right in the Reader in 15.2-rc-1.

Chrome Android 10|Chrome Android 10|Reader detail WPAndroid
---|---|---
![Screenshot_20200703-121412](https://user-images.githubusercontent.com/1119271/86501748-1af19380-bd59-11ea-8047-f4491b67dbdc.png)|![Screenshot_20200703-121337](https://user-images.githubusercontent.com/1119271/86501746-1a58fd00-bd59-11ea-88d6-02bd44c4f188.png)|![Screenshot_20200703-121310](https://user-images.githubusercontent.com/1119271/86501743-16c57600-bd59-11ea-85a8-8c5f4dac7084.png)

<p style="clear:both;"><sup>Tested with WPiOS 15.2.0.0 TestFlight beta on iPhone 11 iOS 13.5.1.</sup></p>

<p style="clear:both;"><sup>(internal reference: p5T066-1ol-p2#comment-5299)</sup></p>

**Comment by malinajirka** [comment] 2020-07-07 07:03
This is expected behavior consistent with the web reader. We can change it, but we'd be changing both mobile and web reader.

**Comment by enejb** [comment] 2021-05-27 05:55
I came across this issue as well in my testing. The tile gallery looks pretty broken

See
<img width="200" src="https://user-images.githubusercontent.com/115071/119773349-59160b00-be75-11eb-851d-bbb248335dc5.png" />

**Comment by daniloercoli** [comment] 2024-02-26 10:32
Tiled galleries are rendered stacked on my mobile devices, but aside from this aspect they work fine on my blogs. Pictures are all available, and arranging them stacked is probably better than trying to render a tiled gallery on a small screen. I'm closing this issue for now since it's quite old, but we can reopen it later if we decide the layout of the tiled gallery needs improvement.

**Closed** 2024-02-26 10:32 UTC
Labels: [Type] Bug, Reader
