### ISSUE TITLE
Reader: opening a post from a topic screen and tapping back goes to discover.wordpress.com and not the topic screen previously opened

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#12920] opened 2020-09-09 22:54 UTC
Steps to reproduce:

1. Go to Reader > Discover.
1. Tap any topic.
1. Tap any post title.
1. Tap back button (top left).
1. Observe that discover.wordpress.com loads instead of taking you back to the topic you had opened previously.

**Result:** I expected that opening a post from a topic screen and tapping back would take me back to the topic but I am taken to the discover.wordpress.com site stream instead. ([28s](https://cloudup.com/cmqyYL643OJ))

Tap any topic|Tap any post|Tap back arrow|First you see the discover.wordpress.com header|Then the whole screen changes to discover.wordpress.com
---|---|---|---|---
<img width="416" alt="Screen Shot 2020-09-09 at Sep 9 3 46 58 PM" src="https://user-images.githubusercontent.com/1119271/92662586-60cc5a00-f2bc-11ea-935e-3f158a87a170.png">|<img width="416" alt="Screen Shot 2020-09-09 at Sep 9 3 47 08 PM" src="https://user-images.githubusercontent.com/1119271/92662585-6033c380-f2bc-11ea-9f21-4bd13ccc5887.png">|<img width="416" alt="Screen Shot 2020-09-09 at Sep 9 3 47 22 PM" src="https://user-images.githubusercontent.com/1119271/92662583-5f9b2d00-f2bc-11ea-9536-b92fc0c5a0d2.png">|<img width="416" alt="Screen Shot 2020-09-09 at Sep 9 3 47 32 PM" src="https://user-images.githubusercontent.com/1119271/92662581-5f029680-f2bc-11ea-91da-947461ad2224.png">|<img width="416" alt="Screen Shot 2020-09-09 at Sep 9 3 47 36 PM" src="https://user-images.githubusercontent.com/1119271/92662569-5b6f0f80-f2bc-11ea-9f5d-9a0df4bdc4ff.png">
<p style="clear:both;"><sup>Tested with WPAndroid 15.7-rc-1 on Pixel 3 Android 11.</sup></p>

**Comment by designsimply** [comment] 2020-09-09 23:09
Something similar happens when you open a post from a site stream then tap the share icon (top right) and dismiss the sharing bottomsheet—in that case just the header changes to discover.wordpress.com and the rest of the site stream remains in tact, but then they are are mismatched at that point. Pull to refresh doesn't change the header or the list of posts.

Video: [1m23s](https://cloudup.com/cwIqgeOapU3)
<sup>Tested with WPAndroid 15.7-rc-1 on Pixel 3 Android 11.</sup>

**Comment by malinajirka** [comment] 2020-09-10 07:06
I believe this is a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/11957. Wdyt?

**Closed as completed** 2020-09-10 08:15 UTC
Labels: [Type] Bug, Reader

**Comment by designsimply** [comment] 2020-09-10 12:29
Yes. Totally a duplicate. Thank you for catching that!
