### ISSUE TITLE
Clearly Labeled Drafts and Scheduled Posts 

### ISSUE THREAD

**Issue by sdixon194** [wordpress-mobile/WordPress-Android#8176] opened 2018-08-10 15:53 UTC
### Expected behavior

Selecting Blog Posts in the Android app should let me clearly choose what is published, a draft, or scheduled post, like the iPhone app: 

<img width="437" alt="iphone app" src="https://user-images.githubusercontent.com/33553323/43968129-3a644e66-9c94-11e8-9e42-181e2517db7d.png">

### Actual behavior

You have to scroll through a single list of posts to find the posts labeled "draft." 

<img width="394" alt="android draft" src="https://user-images.githubusercontent.com/33553323/43968108-2cccc102-9c94-11e8-9021-c31158e95f66.png">

**Comment by theck13** [comment] 2018-08-10 15:57
This is a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/7532.

**Closed by theck13** 2018-08-10 15:57 UTC
