### ISSUE TITLE
NullPointerException: site.wpApiRestUrl must not be null

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13460] opened 2020-11-24 08:45 UTC
**Sentry Url**: https://sentry.io/share/issue/0ba05632606442609bd4158f678d46c6/
**User Count**: 22
**Count**: 245
**First Release**: org.wordpress.android@16.0+946
**First Seen**: 2020-11-05T14:12:20.487000Z
**Last Seen**: 2020-11-24T06:58:19Z
**24 Hours**: 13
**30 Days**: 247

```
NullPointerException: site.wpApiRestUrl must not be null
     at org.wordpress.android.fluxc.store.ReactNativeStore.executeWPAPIRequest(ReactNativeStore.kt:115)
     at org.wordpress.android.fluxc.store.ReactNativeStore.executeWPAPIRequest(ReactNativeStore.kt:90)
     at org.wordpress.android.fluxc.store.ReactNativeStore$executeRequest$2.invokeSuspend(ReactNativeStore.kt:66)
     at org.wordpress.android.fluxc.store.ReactNativeStore$executeRequest$2.invoke(null:10)
     at org.wordpress.android.fluxc.tools.CoroutineEngine.withDefaultContext(CoroutineEngine.kt:27)
     at org.wordpress.android.fluxc.store.ReactNativeStore.executeRequest(ReactNativeStore.kt:62)
     at org.wordpress.android.fluxc.store.ReactNativeStore.executeRequest$default(ReactNativeStore.kt:60)
     at org.wordpress.android.ui.posts.reactnative.ReactNativeRequestHandler$performGetRequest$1.invokeSuspend(ReactNativeRequestHandler.kt:33)
...
(7 additional frame(s) were not displayed)
```

**Comment by leandroalonso** [comment] 2020-11-24 13:01
@mchowning can you help us with this one? It looks like that even [with the null checking](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/store/ReactNativeStore.kt#L109) the app is still crashing.

**Comment by mchowning** [comment] 2020-11-24 14:00
Sure @leandroalonso ! Any concerns if it's a week or two before I get to this?

[The following is mostly just a note for future me 🙂  ]

I'm wondering if it may be worth trying to not mutate the `site.wpApiRestUrl` until the very end of the recursive call (i.e., when a response is actually returned). Instead, we could keep the `wpApiRestUrl` as an explicit parameter that is passed around, which would avoid the possibility that multiple simultaneous calls could update `site.wpApiRestUrl` inconsistently (i.e., one call [setting it to null](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/6cf903abdf936d74468fd85733fd011982eb1891/fluxc/src/main/java/org/wordpress/android/fluxc/store/ReactNativeStore.kt#L148) when another call expects it not to be null).

**Comment by mchowning** [comment] 2020-11-24 14:29
I think this is basically a duplicate of https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1579. Should we close one of these and/or merge the issues in Sentry?

**Comment by leandroalonso** [comment] 2020-11-24 14:35
Oh, that's right! Thanks for pointing out @mchowning 

Duplicate of https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1579

**Closed as completed by leandroalonso** 2020-11-24 14:35 UTC
Labels: [Pri] Medium, [Type] Crash
