### ISSUE TITLE
Can't set a date in the past for draft/new posts

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6836] opened 2017-11-07 14:32 UTC
A user reported in HS that cannot set the publish date for a new post in the past.
![637537e123ea97530973c1e82104630c91ee59b7](https://user-images.githubusercontent.com/518232/32498664-955379d4-c3d0-11e7-81b1-3b3dbb177427.png)

On already published posts the user can set a "back-date" without issues.

**Comment by jblz** [comment] 2018-07-29 22:16
Came to report this myself. Had to drop to a web UI to complete my task.

**Comment by daniloercoli** [comment] 2019-01-14 16:39
> Edit: I tried removing this logic and the thing is that updating the post date doesn't automatically publish the draft and gets overriden by the Now field.
Edit2: Even though setting date to future is enabled, it doesn't really do anything for drafts. The date still gets set to Now.

It seems a bug that future/past date is not working as expected. 
I both tried on Calypso UI, and wp-admin on a self-hosted site, and was able to back date a draft.

**Comment by rachelmcr** [comment] 2019-03-13 16:46
The change in https://github.com/wordpress-mobile/WordPress-Android/pull/9322 makes this issue more severe, since new posts have a draft status (so there's no way to backdate the post without knowing that you have to switch to publish status first). cc @mzorz

**Comment by mzorz** [comment] 2019-03-16 14:12
Ok been investigating this - I'll add the information here for completeness.
 
It seems this particular condition has been introduced by design in https://github.com/wordpress-mobile/WordPress-Android/commit/a1d0acdfaca46cbe5df802b948bbd3627b1786a3
The PR containing this commit has a good explanation on what has been decided: https://github.com/wordpress-mobile/WordPress-Android/pull/6122.

Copying it here for ease:


```
Our solution:
1. Always use & show the `date` property in "Publish Date" and let the user update it to whenever they want (including past dates)
2. If the post is a draft, let the user set a future date. If a future date is set, treat it like the option 1.
3. Don't let the user set a past date for a draft. Theoretically they can do so if they select the current date and a prior time, but this doesn't matter too much. The only reason we do this is to avoid confusing the user due to 4 & 5.
4. If the post is a draft and if the `date` field is now or in the past, show "Immediately" instead
5. If 4 is true, just before a post is published, update the date field to current time which should be consistent with Calypso and wp-admin.

```

**Comment by mzorz** [comment] 2019-03-22 18:35
Opened a PR to fix this https://github.com/wordpress-mobile/WordPress-Android/pull/9466

**Comment by mzorz** [comment] 2019-03-27 12:01
Closing via #9466

**Closed by mzorz** 2019-03-27 12:01 UTC
Labels: Posting/Editing, [Type] Bug
