### ISSUE TITLE
Post/PageList: UI flicker when error occurs offline

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11357] opened 2020-02-21 00:39 UTC
## Expected behavior
The UI won't flicker when an error occurs during the upload process. 

## Actual behavior
The UI flickers and the only way to stop the behavior is to re-enable internet.

### Steps to reproduce the behavior
1. Go to my site. 
2. Go to Page List or Post List. 
3. Create two or more pages/posts in airplane mode and publish them. 
4. Turn off airplane mode so the upload can start and then turn it off quickly before the uploads finish.
5. Wait until the upload fails and the UI will begin to flicker.
 6. The result is in the video below is of the behavior you should be experiencing. 
[Video Link](https://drive.google.com/file/d/13HdstkiCnapfPhkcQ8h7LdiQOajVXzl5/view?usp=sharing)
7. Note: This behavior will only occur on Posts List on `develop` until the offline pages branch is merged into it. 
Tested on Google Pixel 4 XL, Android 10, WPAndroid `develop` ()

**Comment by malinajirka** [comment] 2020-02-21 11:29
@jd-alexander I've tried to reproduce the issue several times and it always works as expected for me. Could you perhaps record a video which includes even the steps which lead to this behavior? Thanks!

**Comment by jd-alexander** [comment] 2020-02-24 17:57
Yes, so for me what I did was:

1. Create a new post. 
2. Publish it and while it's uploading put the device in airplane mode. 
3. Go back to internet connectivity and then airplane mode again. 
4. The failure occurs and the flicker starts. 
5. [Click here to see a video of this happening. ](https://drive.google.com/file/d/13bjzB5KGyMlsZUUoeD7xokzEJ_6J3-3f/view?usp=sharing)

**Comment by oguzkocer** [comment] 2020-03-09 21:54
We're freezing `14.4` today, so this issue is being bumped to `14.5`. If you'd like it to ship with `14.4`, please merge it into `release/14.4` and ping me. If you don't think it'll be addressed in `14.5`, please make sure to update the milestone with the intended milestone.

**Comment by malinajirka** [comment] 2020-03-18 14:03
I still haven't been able to reproduce this issue. @jd-alexander could you please look into it, thanks!

**Comment by jd-alexander** [comment] 2020-03-18 14:29
@malinajirka will do!

**Comment by jd-alexander** [comment] 2020-03-19 02:59
Hey @malinajirka this issue occurs when there are more than one posts enqueued. I just reproduced it. I put several breakpoints within the `UploadService` trying to track down the issue but I haven't as yet. Simply put, something is triggering the retry of the queue, so the service fails to stop because the queue keeps on being processed.

**Comment by malinajirka** [comment] 2020-03-19 11:06
@jd-alexander Ohh, I've been able to reproduce it now. The issue is happening even on post list on `develop`. So it seems it's not related to our changes in the pages offline support project. I'd consider assigning it to the Groundskeeping project.

P.S. Could you please update the reproduction steps in the PR description so it's easier to reproduce for future devs. Thanks!

**Comment by jd-alexander** [comment] 2020-03-19 15:34
Happy you were able to reproduce. I will add to groundskeeping and do the reproduction update. Thanks 👍

**Closed** 2020-03-20 07:57 UTC
Labels: Offline Support, Pages List, [Type] Bug
