### ISSUE TITLE
Unable to logout from WP app after signing up

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-Android#18873] opened 2023-08-02 13:30 UTC
### Expected behavior
Post-signup, a user should have the option to logout

### Actual behavior
Post-signup, there’s no way for the user to logout since the profile icon was moved to the bottom tab bar

![Screenshot_20230802-125239](https://github.com/wordpress-mobile/WordPress-Android/assets/6711616/a8753511-7028-4f7d-9251-57236c4d7e52)

### Steps to reproduce the behavior
1. Sign up for a new account
2. After sign up, observe that there's no way to log out

**Comment by deveshpandee** [comment] 2023-08-05 22:33
Hey, I am interested to fix this issue. can you please assign this issue to me.

**Closed as completed** 2023-10-16 05:47 UTC
Labels: [Type] Bug, Account Management

**Comment by AjeshRPai** [comment] 2023-10-16 05:56
Hey @deveshpandee 

Sorry for not responding to your message earlier.  Thanks for your interest in fixing this issue, but since it affected many users, we worked on it and merged a fix before the next release. 

If you are interested in Contributing to WordPress Android, please look into the issues tagged with the label:"good first issue." Link [here](https://github.com/wordpress-mobile/WordPress-Android/issues?q=is:issue+is:open+label:%22good+first+issue%22+)

Also, @deveshpandee, if you are waiting on any Github issue related to WordPress Android, please feel free to ping me. I will check whether the issue is still valid and can assist you. 

Once again, Thanks for your interest in contributing to the above issue.
