### ISSUE TITLE
Retry is shown even after successfully uploading media to a post.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Android#9559] opened 2019-04-09 18:08 UTC
When you add an image from the local storage -> go back to post list screen -> “failed to upload media” label is displayed -> connected to the internet -> click on Retry -> notice the upload finishes successfully, but the red “Retry” button is still shown

**Comment by shiki** [comment] 2019-05-02 18:58
I'm having trouble reproducing this. Were you able to reproduce this, @maxme? 

Here's what I did:

<img width="320" src="https://user-images.githubusercontent.com/198826/57099493-c9bfbd00-6cd9-11e9-94f1-9b8405177f66.gif">

**Comment by maxme** [comment] 2019-05-03 08:43
I can't reproduce this one every time I try. But it happened once and I was able to record it: https://bia.is/s/l0BT/retry-failed.webm 

I'm not sure why the media upload service takes so much time to "try" to upload the file (in my other tries, it was very quick to fail, like in your previous screen record). I wonder if this is related.

I'm not sure this is an "offline" issue, this is probably bad error management of a failed media upload.

Also note: After this, the draft is uploaded, but the image source is local to the device and every tap on retry fails to upload that media.

**Comment by shiki** [comment] 2019-05-03 13:58
> Also note: After this, the draft is uploaded, but the image source is local to the device and every tap on retry fails to upload that media.

In my case, the upload worked after tapping on _Retry_. 

<img width="320" src="https://user-images.githubusercontent.com/198826/57093331-cb35b900-6cca-11e9-93a1-b0c9e07729a9.gif">

> I'm not sure this is an "offline" issue, this is probably bad error management of a failed media upload.

This is probably the case. Should we rename this issue to take a look at the media uploading instead?

**Comment by malinajirka** [comment] 2019-05-07 11:04
This issue seems semi-related to https://github.com/wordpress-mobile/WordPress-Android/issues/9704

**Comment by malinajirka** [comment] 2019-05-07 11:27
Possibly related to https://github.com/wordpress-mobile/WordPress-Android/issues/9802

**Comment by malinajirka** [comment] 2019-07-24 11:31
I'm not able to reproduce this issue. However, my bet is that it's directly related to https://github.com/wordpress-mobile/WordPress-Android/issues/9704. We've fixed the main cause of 9704, but it can still happen under some unknown circumstances. I'm closing this issue. We can reopen it if the issue will persist after 9704 is fixed.

**Closed by malinajirka** 2019-07-24 11:31 UTC
Labels: Offline Support, [Pri] Medium, [Status] Unreproduced, [Type] Bug
