### ISSUE TITLE
Page button not shown despite user having Editor role

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#13139] opened 2020-10-15 00:06 UTC
### Expected behavior

The app should allow site users with the `editor` role to manage (edit/add) pages. Only users with the `author`, `contributor`, or lesser roles are not meant to manage pages.

Roles and capabilities reference: https://wordpress.org/support/article/roles-and-capabilities/

### Actual behavior

**Tested on a self-hosted site**

The app doesn't show site editors the buttons/features that would allow them to manage Pages. For example, on the site screen, the Pages button is not shown, so users can't navigate to the Pages list screen.

| <img width="350" alt="Screenshot showing lack of Page button on site screen" src="https://user-images.githubusercontent.com/1898325/96058210-09904b00-0e61-11eb-9219-6e0b279f1065.jpg"> |
| -- |

### Steps to reproduce the behavior

1. Log into a site where the user is an `editor`
2. On the site screen, notice the lack of Pages button or functionality

**Comment by guarani** [comment] 2020-10-15 00:07
Related: https://github.com/wordpress-mobile/WordPress-iOS/issues/15111

**Comment by designsimply** [comment] 2020-10-15 17:38
Thank you for the report @guarani! I think this is a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/13057 so I'll close this issue. If you feel it's not a duplicate can you please re-open this issue again?

**Closed as completed by designsimply** 2020-10-15 17:38 UTC
Labels: [Type] Bug, Posts + Pages

**Comment by guarani** [comment] 2020-10-15 18:22
Thanks @designsimply, definitely a duplicate! I need to fine-tune my issue search skillz 😄
