### ISSUE TITLE
Show a warning message before signing out when local drafts are present

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2455] opened 2015-03-24 09:03 UTC
We get users from time-to-time who sign out of the app only to discover all their local drafts have disappeared when they sign back in again. It would be great if there was some kind of warning that these drafts will be lost if they continue with signing out.

**Comment by roundhill** [comment] 2015-03-26 16:11
I'm going to take a crack at #1989, which would also resolve this.

**Comment by roundhill** [comment] 2015-03-26 16:12
Actually this is basically a dupe of #1989, closing this one.

**Closed by roundhill** 2015-03-26 16:12 UTC
Labels: core, enhancement
