### ISSUE TITLE
Draft date and time stays as published date

### ISSUE THREAD

**Issue by sandymcfadden** [wordpress-mobile/WordPress-Android#2891] opened 2015-06-19 13:54 UTC
When you create a draft in the app and save it and then come back later to publish the draft it keeps the original draft creation date and time as the published date and time.

When publishing a draft through wp-admin it takes the date and time you actually publish instead.

**Comment by rachelmcr** [comment] 2015-11-25 13:01
I tested this again, and when I published a saved draft it published with the current date and time as expected (not the original draft creation date and time).

However, before I published the post, it still showed the original draft creation date and time under "Publish" in the post settings. This should be updated to the current date and time to reflect the settings that will be used when the post is published.

Device: Nexus 9
Android: 6.0
App version: 4.8-rc-1

**Comment by rachelmcr** [comment] 2016-02-02 17:49
I did further investigation, and this behavior is actually in line with how the Calypso editor displays the date on draft posts. It shows the last saved date until the draft is edited again or published, at which point it displays the current date/time. Given that the app has the same behavior, I'm going to go ahead and close this issue. If I've overlooked any outstanding problems from the original issue, please let me know!

We're also working on a new editor, and I'll keep an eye on how it displays/works with the date on draft posts.

**Comment by davoraltman** [comment] 2016-12-04 21:47
@rachelmcr I did more testing on this issue and I think that a bug exists in the mobile app. This is how it looks when using the Calypso desktop app:

I have a draft on my testing site.

<img width="1181" alt="screen shot 2016-12-04 at 10 03 40 pm" src="https://cloud.githubusercontent.com/assets/10340370/20869218/e6d9f23c-ba6d-11e6-8d57-250548c32787.png">

I publish the draft and Calypso displays the proper time when the post was published.

<img width="311" alt="screen shot 2016-12-04 at 10 03 59 pm" src="https://cloud.githubusercontent.com/assets/10340370/20869223/fd01b89c-ba6d-11e6-8c16-5381c4e6a4e3.png">

I double-check this in the Insights screen and all looks good.

<img width="713" alt="screen shot 2016-12-04 at 10 04 09 pm" src="https://cloud.githubusercontent.com/assets/10340370/20869228/384ee442-ba6e-11e6-9faa-1d2d9b2411aa.png">

Now, into the mobile app.

A few seconds after I published the article on my blog, this was set as the time it was published.

![screenshot_20161201-222658](https://cloud.githubusercontent.com/assets/10340370/20869363/48b2b9c8-ba71-11e6-8532-39df226d674f.jpg)

I also checked the Insights screen and it also displayed the original draft creation as the time the post was published.

![screenshot_20161201-222631](https://cloud.githubusercontent.com/assets/10340370/20869365/4fe6c342-ba71-11e6-9bf3-41e1a078d965.jpg)

What's also interesting is that, when I checked the WP Admin area of the site, it also shows the draft creation as the time the post was published. I guess it happened because I used Calypso and not WP Admin of the site.

<img width="593" alt="screen shot 2016-12-04 at 10 27 22 pm" src="https://cloud.githubusercontent.com/assets/10340370/20869460/e4a389ce-ba72-11e6-808f-e2993dc9e4d4.png">

I am using Asus Zenfone 3 Z012D running on Android 6.0.1. WordPress app version is alpha-29 at the moment. The post I used as an example in this case was published on December 1st (sorry I am late with this comment) and I am not sure if the same version was used on December 1st.

**Comment by rachelmcr** [comment] 2016-12-05 13:41
Thanks for the report, @davoraltman! It looks like this behavior has changed since it was previously tested; I also tested and confirmed the behavior you are now seeing. I'm reopening the issue.

**Comment by rachelmcr** [comment] 2017-04-25 08:36
Another user reported this issue in version 7.1. She started a draft on April 14, published the post on April 19, and the post's publish date was set to April 14.

Internal ref: 182275-h

**Comment by rachelmcr** [comment] 2017-04-25 08:55
Ah yes, there's a related Calypso issue here: https://github.com/Automattic/wp-calypso/issues/9014

**Comment by oguzkocer** [comment] 2017-07-05 12:50
Fixed via #6122 & #6185

**Closed by oguzkocer** 2017-07-05 12:50 UTC
Labels: Posting/Editing, [Pri] Medium, [Type] Broken Window, [Type] Bug
