### ISSUE TITLE
Retry Notification causes duplicate posts

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11245] opened 2020-02-05 20:18 UTC
### Expected behavior
The retry notification action will only upload one post. 

### Actual behavior
The retry notification action creates duplicate posts when doing the upload. 

Pages | Post 
--------|-------
<img src="https://user-images.githubusercontent.com/1509205/73879460-86771980-482a-11ea-8d1e-e6b0702f60f7.png" width="320">  | <img src="https://user-images.githubusercontent.com/1509205/73879466-87a84680-482a-11ea-8c3a-95cd3c00b239.png" width="320">

### Steps to reproduce the behavior
1. Publish a post and then go into airplane mode while it’s publishing. 
2. Wait until the upload fails and the notification is displayed in the status bar. 
3. Press retry on the notification
4. Go back online and the notification still exists.
5. If you press try again while it’s online and two posts are uploaded. 

Tested on Google Pixel 4 XL, Android 10, WPAndroid `develop` ()

**Comment by khaykov** [comment] 2020-02-23 17:58
I was not able to reproduce this, but something tells me this is plausible. Wanted to confirm couple of things:
- When you press "Retry" in the notification is the app still open in the foreground?
- Are the posts actually different as in do you actually see two duplicate posts on the website?

**Comment by jd-alexander** [comment] 2020-03-10 23:48
> When you press "Retry" in the notification is the app still open in the foreground?
Yes, it still is.

> Are the posts actually different as in do you actually see two duplicate posts on the website?
Yes, two seperate posts are seen. 

@khaykov  I am going to try and reproduce again and give clearer instructions here.

**Comment by malinajirka** [comment] 2020-04-03 10:18
I think this is not a bug in the client app but a design issue of our API. 

I think this is what happens:
1. WPAndroid sends "pushPost" request
2. The server receives the request and creates a new post in the server Database.
3. The server sends a response
4. WPAndroid goes offline before it can receive the response
5. WPAndroid goes online but the post is still marked as local draft since WPAndroid haven't received a success response from the server.
6. WPAndroid sends "pushPost" request
7. The server receives the request and creates a new post, since it doesn't know it's still the same post
8. The server sends a response
9. WPAndroid receives the response and marks `localDraft` as false
10. WPAndroid fetches all posts from the server, but the server already contains a duplicate which was created in step 7


I don't think there is any solution to this issue without changing the design of the API. Ideally, we'd introduce UUID which would be generated on the client when the post is created. This would help the server connect the dots and it wouldn't create a duplicate.

I'm closing this issue as `won't fix`. Please feel free to re-open the issue if I'm missing something.

**Closed by malinajirka** 2020-04-03 10:18 UTC
Labels: Pages List, Post List, [Type] Bug
