### ISSUE TITLE
Crash: Editing unknown html can cause PARAGRAPH error

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6584] opened 2017-08-24 13:59 UTC
```
Fatal Exception: java.lang.RuntimeException: PARAGRAPH span must start at paragraph boundary
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:600)
       at android.text.SpannableStringBuilder.change(SpannableStringBuilder.java:372)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:477)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:435)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:30)
       at org.wordpress.aztec.AztecText$showBlockEditorDialog$1.onClick(AztecText.kt:1083)
       at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:161)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5390)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:970)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniloercoli** [comment] 2017-12-06 10:04
For reference see : https://github.com/wordpress-mobile/AztecEditor-Android/pull/539

**Comment by 0nko** [comment] 2018-01-04 00:31
I can't reproduce this and I don't see any open in the Crashlytics. I'll close this and we can reopen.

**Closed by 0nko** 2018-01-04 00:31 UTC
Labels: Aztec, [Pri] Medium, [Type] Crash
