### ISSUE TITLE
Media: App crashes when editing image settings like caption, alt, description

### ISSUE THREAD

**Issue by catkit** [wordpress-mobile/WordPress-Android#8492] opened 2018-10-27 16:26 UTC
### Expected behavior
Save settings and not crash

### Actual behavior
After you upload an image and choose to edit the caption the app crashes

### Steps to reproduce the behavior
1. Add an image
2. Tap it to edit settings
3. Add caption, description or alt text.
4. Close the Settings screen
5. App crashes

##### Tested on Moto Z Play, Android 8, App 11.0

This was reported by a WordPress.com user on Live Chat, also using a mobile phone with Android 8 and the last App release.

I have tested it before updating my app to version 11.0, so I think this error was introduced with the last release.

**Comment by rachelmcr** [comment] 2018-10-29 11:18
Thanks for the report! I tested on a Moto e5 Play, Android 8.1.0, WPAndroid alpha-133 and couldn't reproduce the issue, so it's possible this will be resolved in version 11.1 or there's another factor (e.g. device, Android version, app settings, site settings) that is involved here.

**Comment by RafaelFunchal** [comment] 2018-10-30 16:37
I just tested it on my Android and I couldn't reproduce the issue either.

Phone: Moto Z2 Force
Android:  8.0.0 latest patch 2018-09-01
App: 11.0

**Comment by khaykov** [comment] 2018-10-30 17:19
I can reproduce the issue by adding Caption and setting image size to Full (or first to some other size, and then to Full).

**Comment by charliescheer** [comment] 2018-11-01 17:57
#1525237-zen looks like this is the same issue.

**Closed** 2018-11-02 10:08 UTC
Labels: Media, [Pri] High, [Type] Bug, [Type] Crash
