### ISSUE TITLE
Post Settings: general design revamping

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5811] opened 2017-05-02 08:06 UTC
The Post Settings screen is very outdated and needed some design love. @mattmiklic came to the rescue and proposed some changes to match Calypso and respect Material design:

![full](https://cloud.githubusercontent.com/assets/40213/25609127/197cf50c-2f1e-11e7-84a9-5fedf5439786.png)

Main changes:
* Re-ordered options
* Updated graphic style (coherent text size/headings/colors/margin/buttons)
* Options use dialogs (confirmation dialogs for most things, like we already use in Site Settings; a full screen dialog for location, tags and categories). This makes the main settings screen easier to understand at a glance.
* New features: (might need some work in FluxC) Stick to the front page, Pending review + Visibility (instead of current "Status"), Slug, Allow comments / Allow pingbacks (in doubt have a look at Calypso).

This ticket is related to https://github.com/wordpress-mobile/WordPress-Android/issues/5807  https://github.com/wordpress-mobile/WordPress-Android/issues/5808 https://github.com/wordpress-mobile/WordPress-Android/issues/5809 https://github.com/wordpress-mobile/WordPress-Android/issues/5810

**Comment by maxme** [comment] 2017-05-02 09:26
BTW, Might be worth opening a feature branch for this one and related tickets. Also feel free to split that one into small PRs for new features.

**Comment by tonyr59h** [comment] 2017-06-13 01:42
Adding a reminder here (ref #6050) to update the styling in `PostSettingsInputDialogFragment` so lower API's don't look so funky. ![](https://cldup.com/ybEpYBgaR1.png)

**Comment by oguzkocer** [comment] 2017-06-14 12:27
The issue mentioned above ^^ has been fixed in #6058.

**Comment by oguzkocer** [comment] 2017-06-15 11:14
The following issues are [reported](https://github.com/wordpress-mobile/WordPress-Android/pull/6058#pullrequestreview-44191952) by @tonyr59h in #6058. I think they are out of scope for that particular PR and some of them were planned to be fixed in following PRs. So, I think creating a checklist for them here is the best way to go about it:

- [ ] Adding a password isn't possible for private posts. Should we disable that field if marked private?
- [ ] When all categories on the web are removed the default category is auto-selected. I think we should emulate this behavior in the app for consistency. It'll automatically get assigned the default category once it's uploaded, but that might lead to confusion.
- [ ] Adding number tags (ie 1, 2) doesn't work, in fact any number tags added via the web (which does work) are removed if there are changes in the app.
- [ ] Post format behavior was a bit confusing. I started testing using the old web editor to verify the app changes then switched to the new one. Apparently on the new one the format is limited by the theme, but on the app you're able to set it to any and it works. It's out of scope of this PR so we should open a new ticket for limiting the choices to those supported by the theme.
- [ ] We should add ripple animations to each setting item
- [ ] Is it possible to style the date picker? Its dark theme stands out from the other dialogs
- [ ] For some reason it really stood out to me that the Tags dialog doesn't have a scrollbar while all the other dialogs with lists do 😆 On that topic, the Select categories dialog scrollbar doesn't go all the way to the top (looks like there's padding)
- [ ] My API 16 emulator crashes when loading the settings screen. The logs aren't very useful, looks like maybe a problem with vectors and Genymotion... Maybe stock emulators will work better. I'll try it out before merging.

**Comment by oguzkocer** [comment] 2017-06-30 14:31
@mattmiklic I've taken screenshots of every page/dialog and put it in a gallery: https://cloudup.com/c3JxM3onqqb Could you review these screenshots when you get a chance?

When we get the 👍 from you, I'll consider it as a pass for design review. Thanks!

**Comment by oguzkocer** [comment] 2017-07-03 12:39
> Adding a password isn't possible for private posts. Should we disable that field if marked private?

After finishing the implementation of this and some testing, I decided to drop it. The issue is that when there is already a password on the post it's not clear to the user what happens to the password or what we should do when they change the post's status back to public. If this is important, we should handle it after Post Settings revamp is merged in and probably throw some warnings to the user which means it requires some design work.

> When all categories on the web are removed the default category is auto-selected. I think we should emulate this behavior in the app for consistency. It'll automatically get assigned the default category once it's uploaded, but that might lead to confusion.

I tried this out and I don't think this is a good UX at all. This is another one of those things that's better thought through after the merge.

> Adding number tags (ie 1, 2) doesn't work, in fact any number tags added via the web (which does work) are removed if there are changes in the app.

The reason it works on Calypso is that they add a `#` before each tag and remove it when it's shown. Otherwise the API doesn't accept it. I'll see if I can fit this in before the merge, but it might need to be separated.

> Post format behavior was a bit confusing. I started testing using the old web editor to verify the app changes then switched to the new one. Apparently on the new one the format is limited by the theme, but on the app you're able to set it to any and it works. It's out of scope of this PR so we should open a new ticket for limiting the choices to those supported by the theme.

Yeap, this one definitely should be a new issue.

> Is it possible to style the date picker? Its dark theme stands out from the other dialogs

**Comment by oguzkocer** [comment] 2017-07-03 13:31
> For some reason it really stood out to me that the Tags dialog doesn't have a scrollbar while all the other dialogs with lists do

@tonyr59h Tags is a separate screen and it does have the scroll capability. Am I missing something?

**Comment by mattmiklic** [comment] 2017-07-05 17:30
> @mattmiklic I've taken screenshots of every page/dialog and put it in a gallery: https://cloudup.com/c3JxM3onqqb Could you review these screenshots when you get a chance?

Just took a look, all of those are looking good to me. 👍

**Closed** 2017-07-06 09:53 UTC
Labels: Design, Posting/Editing, [Pri] High, [Type] Broken Window, [Type] Enhancement
