### ISSUE TITLE
Crash: Unable to activate theme after searching

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#6895] opened 2017-11-21 20:54 UTC
### Expected behavior
To be able to search for a theme and then preview/activate it

### Steps to reproduce the behavior
1) Open the Themes page
2) Search for a theme (try "Twenty")
3) Tap the theme card to try and preview
-- At this point it gives the error "Could not load theme"
4) Tap the ellipsis and select Activate
5) Watch the app crash

I didn't see anything useful in the application logs (several successful theme searches, but no errors).

https://cloudup.com/cBwynrIU6bZ

**Comment by rachelmcr** [comment] 2018-09-17 15:50
I tested again on my Nexus 9, Android 7.1.1, WPAndroid alpha-127 and can no longer reproduce this crash (or the error loading the theme). Closing as it looks like this is resolved, but please reopen if you're still experiencing this crash.

**Closed by rachelmcr** 2018-09-17 15:50 UTC
Labels: Themes, [Pri] High, [Type] Bug, [Type] Crash
