### ISSUE TITLE
Show embeds in Post previews

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#5009] opened 2017-01-09 22:54 UTC
### Expected behavior

I expected to be able to see oEmbeds working for post previews in the app.

### Actual behavior

Embeds just look like plain links in post previews.

<img alt="screenshot_2017-01-09-15-02-47" src="https://cloud.githubusercontent.com/assets/1119271/21786409/f69edfbe-d680-11e6-9f8c-0944235cc627.png" width="300" />

### Steps to reproduce the behavior

1. Install WPAndroid 6.5-rc-1.
1. Create and publish a post with a kickstarter, reddit, twitter moments, or facebook news embed.
1. From the Posts page in the app, click the title of the post to see a preview.
1. Check to see if the embed is working there.

##### Tested on Samsung Galaxy Tab4 (SM-T330NU), Android 5.1.1

**Comment by daniloercoli** [comment] 2017-01-26 11:02
It seems there is a problem when you publish a post that contains embeds from the mobile apps.
oEmbeds are broken, both on the web and on mobile.

If the same post is published on the web, oEmbeds work as expected.

**Comment by daniloercoli** [comment] 2017-01-26 15:07
Pasting content into an empty Visual editor can sometimes insert “&#x200b;” magically at the beginning of the post. This character is the ZERO WIDTH SPACE character - http://www.fileformat.info/info/unicode/char/200b/index.htm -  and once inserted in `the_content` breaks most of the regular expressions on WP server. As resulting of this, oEmbeds don't work.

If you use the old "legacy" editor in wp-android the issue is not there, and you can paste links without any issue. 

Working on a patch.

**Comment by daniloercoli** [comment] 2017-01-26 16:33
Related to  #5007, #4910, and #5009.

**Comment by daniloercoli** [comment] 2017-02-01 14:22
Addressed in #5067

**Closed by daniloercoli** 2017-02-01 14:22 UTC
Labels: Posting/Editing, [Pri] Medium, [Type] Broken Window, [Type] Enhancement
