### ISSUE TITLE
Quick Guide dashboard card is not visible

### ISSUE THREAD

**Issue by salimbraksa** [wordpress-mobile/WordPress-Android#20547] opened 2024-03-28 03:15 UTC
| Expected ( 24.4 ) | Actual ( 24.5 ) |
| --------- | ------ | 
| <video src="https://github.com/wordpress-mobile/WordPress-Android/assets/9609223/00df941b-5ac3-4b9e-a032-8f1455a77175"></video> | <video src="https://github.com/wordpress-mobile/WordPress-Android/assets/9609223/b8f8119b-39ca-44dc-bdc0-1647b52d8ffd"></video> |

_Courtesy of @jarvislin for the screen recordings._

### Steps to reproduce the behavior
1. Install Jetpack and Login
2. Select a site
3. Tap "Show me around"
4. Verify the "Quick Guide" card is not visible

**Comment by dangermattic** [comment] 2024-03-28 03:15
Thanks for reporting! 👍

**Comment by AjeshRPai** [comment] 2024-03-28 05:39
Hey @salimbraksa 

I am assigning this issue to me as this might have been introduced by the changes from this https://github.com/wordpress-mobile/WordPress-Android/pull/19869

**Comment by antonis** [comment] 2024-03-29 12:46
[Comparing the changes between `24.4` and `24.5`](https://github.com/wordpress-mobile/WordPress-Android/compare/24.4...release/24.5) I didn't identify any commit suspicious for the introduced bug.
Given that we are at the end of the beta cycle and the issue is fixed with the new architecture in https://github.com/wordpress-mobile/WordPress-Android/pull/19869 I suggest to mark the issue as fixed in `24.6`. This would also avoid possible conflicts when `release/24.5` is merged into `trunk` due to the refactoring.

**Comment by AjeshRPai** [comment] 2024-04-24 06:53
As @antonis  mentioned, this is fixed in `24.6`

**Closed as completed by AjeshRPai** 2024-04-24 06:53 UTC
Labels: [Type] Bug, Quick Start, My Site Dashboard
