### ISSUE TITLE
Toggles Set to Off (Despite Being On)

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#7841] opened 2018-06-01 08:08 UTC
In 284047-h a user reported that the toggles under My Site > Settings appear to be switched off with the latest version of the app (10.0). They sent in the following screenshots to show this:

![c6352081-dcea-48f5-a399-fdb89f0d49d6 1](https://user-images.githubusercontent.com/2998162/40829223-b892419a-657a-11e8-9f13-e52c683a810d.png)

![6674fdcc-cb4d-425a-b3f3-89904e02333c 1](https://user-images.githubusercontent.com/2998162/40829232-bea891d8-657a-11e8-8ecb-41a94356155f.png)

They’re unable to turn the toggles back on (they’re simply unresponsive) and comments are still enabled on their site.

More details, including links to the user's site and logs they sent in here: p4a5px-2d8-p2

##### Tested on Redmi 3S, Android 6.0.1, version 10.0 of the WordPress app.

**Comment by SiobhyB** [comment] 2018-06-01 10:47
Another report in 284918-h from someone using Android 5.1 and on version 10.0 of the WordPress app:

> how do I activate comment on my post. I keep pressing the allow comment button but it's not working..

**Comment by SiobhyB** [comment] 2018-06-01 16:35
From a three star review:

> It's a great app. However am not able to edit my discussion settings. I am not able to allow comments

The user is on Android 4.1 and using version 10.0 of the app.

**Comment by SiobhyB** [comment] 2018-06-01 16:56
From a four star review:

> Can not enable comments

The user is on Android 6.0 and using version 10.0 of the app.

**Comment by khaykov** [comment] 2018-06-01 20:59
I have a hard time reproducing this issue. Looking at the logs it feels like the user toggles a switch, and it immediately toggles back.

**Comment by SiobhyB** [comment] 2018-06-04 14:58
This came up again in 283773-h for a user trying to edit the settings for their WordPress.com site.

The user has a Samsung Galaxy S3 Mini and Android 4.4. 

> When I try turning it on nothing works. It's as if the toggle button just wouldn't move everything is off at the discussion settings and nothing is movable there.

**Comment by khaykov** [comment] 2018-06-04 17:32
Ok, I was able to reproduce it finally. Working on figuring out what is going on.

**Comment by nellofn** [comment] 2018-06-22 15:52
This came up again in 288332-h, the user sent screenshots this time but I also asked the user to double check their app version and requested logs. I'll update once I hear back from the user.

**Comment by SiobhyB** [comment] 2018-06-24 08:50
Reopening as the user has sent in their logs, and they're having the issue in version 10.2 of the app. The logs can be found in 288332-h.

cc: @khaykov

**Comment by khaykov** [comment] 2018-07-06 16:04
I'm swamped with quick start issues right now, so I'll unassign myself for the moment. I'll get back to it when I'm done, if no one will pick it up in the meantime.

**Comment by daniloercoli** [comment] 2019-03-19 16:54
I was not able to replicate the issue on my testing devices:
- Samsung S9 - Android 9
- LG Nexus 5 - Android 7.1
- Samsung Galaxy S6 - Android 5.0.0

**Comment by elibud** [comment] 2019-06-05 20:16
We haven't seen any reports since July 2018, closing this one. If we hear from more users having this issue please reopen.

**Closed by elibud** 2019-06-05 20:16 UTC
Labels: Site Settings, [Pri] High, [Type] Bug
