### ISSUE TITLE
Deleting a post doesn't work if you just deleted one

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-Android#9515] opened 2019-04-04 16:54 UTC
### Steps to reproduce the behavior

Imagine you have a bunch of autosaved drafts that you want to get rid of:

1. Go to the posts list
2. Tap delete on the first post, the post is deleted
3. Tap delete on next post, nothing happens
... When you delete the first one, there's a notice at the bottom saying "Post deleted      UNDO". After a few seconds it gets dismissed.
4. Tap delete on next post, once that notice is gone, deleting works again.

So, in reality, you can delete posts after deleting one, but you have to wait for about 3 seconds between posts

**Comment by oguzkocer** [comment] 2019-04-05 00:05
This is a duplicate of #8592 and closed in favor of the original issue.

**Closed by oguzkocer** 2019-04-05 00:05 UTC
Labels: Post List, [Type] Bug
