### ISSUE TITLE
Reader: Missing featured image when subfilter component is used

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#13069] opened 2020-10-07 06:08 UTC
### Expected behavior
Featured image of a post should be displayed in the "following" Reader tab no matter whether the subfilter component is being used or no filter is set.

### Actual behavior
Featured images on some posts are displayed only when no filter is set.

### Steps to reproduce the behavior
1. Open Following tab
2. Find a post with a featured image
3. Use the filter to show posts only from the site of the post
4. Check if the post still has featured image 
5. Repeat until you encounter a post with a missing featured image

<img src="https://user-images.githubusercontent.com/2261188/95293765-5e85fd00-0874-11eb-8d1d-acb927f95b35.gif" width="250px" />

(Example post https://wpstoriesdemo.mystagingwebsite.com/?p=125)

##### Tested on [device], Android [version], WPAndroid [version]
Emulator API 23 and 29

cc @aforcier since you worked on a similar thing recently. Feel free to ignore this ping and leave it for groundskeeping.

**Comment by malinajirka** [comment] 2020-10-07 06:32
I've just double checked if this issue could be related to posts from other blogs, but I can confirm it's happening even when the only site I follow is "wpstoriesdemo.mystagingwebsite.com".

**Comment by aforcier** [comment] 2020-10-07 06:35
@malinajirka can you check this while proxied (with cleared app data)?

I believe the cause might be that two different endpoints are used for the feed and the filter view, and for Jetpack sites one respects the beta block setting and the other does not. Proxying should return the same results for both endpoints.

**Comment by malinajirka** [comment] 2020-10-07 06:58
@aforcier I can confirm it works when proxied. Does it mean we can close the issue ?:)

**Comment by aforcier** [comment] 2020-10-07 07:06
@malinajirka great! Yep we can close it, the block will be promoted to production before stories ship to users. 👍

**Closed as completed by aforcier** 2020-10-07 07:06 UTC
Labels: [Type] Bug, Reader
