### ISSUE TITLE
Post list: video uploads show [video] or [wpvideo] tags

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6401] opened 2017-07-26 14:36 UTC
comes from https://github.com/wordpress-mobile/WordPress-Android/pull/6358#issuecomment-318059263

### Expected behavior
Post list items should not show technical tags  - either just display visual content in a visual way (i.e. thumbnails) or text content.

### Actual behavior
The Post list shows the `[video]` tag when the post is finished uploading in Aztec as of #6358, or the `[wpvideo]` tag in the Visual Editor. Also if there are no images in the post but a video is in there, it seems to me the post item resizes itself as if it were to hold a featured image, but it shows a blank space instead

### Steps to reproduce the behavior
**CASE A: Aztec**
1. start a new draft
2. include a video
3. once the video uploads, or even before it finishes, go back to the Posts list.
4. it shows the `[video]` tag:

![screenshot_20170726-104448](https://user-images.githubusercontent.com/6597771/28624564-ddc61934-71ef-11e7-8143-5bc3b2d68ebd.png)

if the Post has a successfully uploaded video, the full tag is displayed in the post list
<img width="320" alt="screen shot 2017-07-26 at 10 50 08 am" src="https://user-images.githubusercontent.com/6597771/28624699-4eb124e0-71f0-11e7-94db-f9050b2f0758.png">

**CASE B: Visual Editor**
1. start a new draft
2. include a video
3. once the video uploads, or even before it finishes, go back to the Posts list.
4. it shows the `[wpvideo]` tag:

<img width="320" alt="screen shot 2017-07-26 at 11 35 26 am" src="https://user-images.githubusercontent.com/6597771/28626882-94c7fec6-71f6-11e7-9967-f62690b9b923.png">

**Comment by daniloercoli** [comment] 2017-07-27 08:35
This is a dupe of https://github.com/wordpress-mobile/WordPress-Android/issues/5370. Moving the discussion there and pinging @nbradbury on this one, since we may need to change `ReaderImageScanner` class.

**Closed by daniloercoli** 2017-07-27 08:35 UTC
Labels: Media, Post List, [Type] Bug

**Comment by mzorz** [comment] 2017-07-27 11:54
Thank you @daniloercoli ! I should have checked first 🙇
