### ISSUE TITLE
Can't login when building from source

### ISSUE THREAD

**Issue by Ghedeon** [wordpress-mobile/WordPress-Android#7974] opened 2018-07-02 09:51 UTC
### Expected behavior
The user should be able to log in via email

### Actual behavior

1. 2FA disabled. Login fails, an error occurs:
```
{"error_context":"AuthenticationErrorType","error_description":"Client cannot use "password" grant_type","error_type":"UNSUPPORTED_GRANT_TYPE"}
```
2. 2FA enabled. Login fails, an error ossurs: 
```
E/Volley: [24246] BasicNetwork.performRequest: Unexpected response code 401
```
Note: Despite the fact that it doesn't pass on the first try, on the next launch of the app the user appears as logged in.

### Steps to reproduce the behavior
Set `wp.oauth.app_id` and `wp.oauth.app_secret` as described in `README`.
Build, install, try to log in.

##### Tested on [device], Android [version]
OnePlus 5T, Android 8.1.0

**Comment by sudhirkhanger** [comment] 2018-07-05 16:23
I am also unable to log-in due to error - `Client cannot use "password" grant_type`.

![screenshot_1530801152](https://user-images.githubusercontent.com/841656/42335333-ac64bad6-809d-11e8-88b3-38c39660513f.png)

**Comment by niranjan-uma-shankar** [comment] 2018-07-07 13:39
I'm seeing a similar error. When I build from source and install the APK on my phone (running Android 6.0 marshmallow), I get the error - `Unknown client ID`

![al-blurrd](https://user-images.githubusercontent.com/1269602/42411404-17f56e18-8219-11e8-9415-1f42a69a51ce.png)

My Android Studio shows the following errors:

> E/Volley: [54602] BasicNetwork.performRequest: Unexpected response code 400 for https://public-api.wordpress.com/oauth2/token
> E/WordPress-API: Authentication error
> E/WordPress-API: onAuthenticationChanged has error: INVALID_CLIENT - Unknown client_id.
> E/WordPress-NUX: Server response: Unknown client_id.
> E/FirebaseInstanceId: Token retrieval failed: INVALID_PARAMETERS

**Comment by elibud** [comment] 2018-09-07 15:14
@theck13 can you look into this please?

**Comment by jorgecasariego** [comment] 2018-09-07 18:42
@niranjan-uma-shankar I had this same problem testing from the emulator. In my case I had a problem with the internet connection in the emulator. After closing and opening another emulator it worked without problem.

**Comment by theck13** [comment] 2018-09-14 00:43
The `Client cannot use "password" grant_type` error is caused by trying to login with an account different from the WordPress.com account used to create the OAuth credentials in the [applications manager](https://developer.wordpress.com/apps/).  @Ghedeon and @sudhirkhanger, can you confirm that you are using the same WordPress.com account with which you created the client ID and client secret?

The `Unknown client_id` error is caused by using an unknown client ID value.  @niranjan-uma-shankar, can you confirm that you have followed the directions in the [OAuth2 Authentication](https://github.com/wordpress-mobile/WordPress-Android#oauth2-authentication) section?

Note that these credentials allow login only and not signup.  New accounts must be created using the [official app](https://play.google.com/store/apps/details?id=org.wordpress.android) or [on the web](https://wordpress.com/start).  I have added all these details credentials in https://github.com/wordpress-mobile/WordPress-Android/pull/8307.

**Comment by theck13** [comment] 2018-09-14 12:51
I'll close this issue since the associated pull request has been merged and @sudhirkhanger confirmed the expected behavior.  Feel free to reopen this if you find different behavior, @Ghedeon and @niranjan-uma-shankar.

**Closed by theck13** 2018-09-14 12:51 UTC
Labels: Login, [Type] Question
