### ISSUE TITLE
Network-activated plugins appear as inactive

### ISSUE THREAD

**Issue by jeherve** [wordpress-mobile/WordPress-Android#7575] opened 2018-03-30 13:52 UTC
### Steps to reproduce the behavior

1. Start from a site that is part of a multisite network. Plugins should be network activated on that network.
2. Connect the site to your WordPress.com account via Jetpack.
3. Check the site in the Android app (tested on a HTC U11, WPAndroid Alpha 105)
4. Go to the Plugins menu.

The network activated plugins will be marked as inactive, although they are in fact active:

![screenshot_20180323-234420](https://user-images.githubusercontent.com/426388/38140047-66248b76-3432-11e8-8afb-ccb91cd95d48.png)

Related: #7346, #7367

**Comment by oguzkocer** [comment] 2018-06-04 20:30
This is a duplicate of #7346 which will be fixed with #7367. This will not actually change the status though, only the label, as the mobile clients can only show what the API returns, so if there is any issue with that, it needs to be fixed on the server side. /cc @lezama @enejb

**Closed by oguzkocer** 2018-06-04 20:30 UTC
Labels: Jetpack Plugins, [Type] Bug
