### ISSUE TITLE
Site settings: when changing settings in wp-admin, it should be possible to see changes on app

### ISSUE THREAD

**Issue by v18** [wordpress-mobile/WordPress-Android#3686] opened 2016-01-31 18:22 UTC
Steps:
1. Open WordPress app (already logged as a user with a site)
2. Go to wp-admin > Settings > General for your site
3. Change the site title and save
4. Go to the Site Settings page for the site on the app, and see that the old site title is displayed instead
5. Try to refresh the page by pulling down, and see that it's not possible

You can get the app to display the new title by swiping the WordPress app from the recent apps list and opening it again.

Note that this behaviour doesn't happen in MyProfile: when making changes directly on the web, it's possible to see them in the app almost immediately by going to a different page and then returning to My Profile.

**Comment by tonyr59h** [comment] 2016-02-10 22:08
The settings are pulled each time the Site Settings screen is accessed. If you're on that screen you won't get the updates until you leave and go back. Sounds like the way you tested it should show the updates, but I'm unable to reproduce. What device/version/build number are you testing with?

**Comment by tonyr59h** [comment] 2016-02-12 20:47
After working through this with @v18 we came to the conclusion that this is not an issue, just takes a few seconds to update the settings changes when entering the settings screen. Closing.

**Closed by tonyr59h** 2016-02-12 20:47 UTC
Labels: Site Settings, [Type] Bug
