### ISSUE TITLE
Image upload returns parse error

### ISSUE THREAD

**Issue by seanhawkridge** [wordpress-mobile/WordPress-Android#5588] opened 2017-04-05 18:37 UTC
I'm trying to upload an image from within a post or from within the Media section of the app.

The image appears to upload (the progress bar fills up), but the upload fails at the last moment and returns `parse error. not well formed`

I'm using a OnePlus 2, with version 7.0 of the app.

**Comment by Arrappathor** [comment] 2017-04-06 09:07
Samsung Galaxy S3 i9300 LineageOS 14.1 
I do have the same issue since app-version 7.0.
The files in 
/storage/emulated/0/WordPress/images 
end now with a dot - f.i.: "wp-1548654755."
earlier files didn't have that dot.

**Comment by maxme** [comment] 2017-04-06 10:06
Thanks @seanhawkridge and @Arrappathor - we're investigating this issue, can you confirm your trying to upload to a self hosted site?

**Comment by seanhawkridge** [comment] 2017-04-06 10:11
@maxme yes, to a self hosted site. I asked the hosting company to take a look too, but they couldn't see anything in the logs on their side. Thanks!

**Comment by Arrappathor** [comment] 2017-04-06 10:44
@maxme. 
Yes, selfhosted website on Raspberrypi2 with Raspbian.
Worked flawlessly until update to app-version 7.0
Thanks!

**Comment by maxme** [comment] 2017-04-07 07:22
@seanhawkridge @Arrappathor I tried a bunch of scenarios but I'm not able to reproduce the problem. I wonder if it's related to your self hosted installation. Can one of you create a test user and send me the credentials by email: blackhole+zlyufn@bia.is

**Comment by seanhawkridge** [comment] 2017-04-07 07:26
@maxme done

**Comment by maxme** [comment] 2017-04-07 13:37
Thanks again @seanhawkridge 

Fixed via https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/405
Fix will ship with 7.1

**Closed by maxme** 2017-04-07 13:37 UTC
Labels: Media, [Pri] Blocking, [Type] Bug
