### ISSUE TITLE
Proposition: Migrate local drafts to drafts status

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#10194] opened 2019-07-10 15:05 UTC
This is a discussion ticket.

###  Proposition

In the next version upgrade (12.9 -> 13.0?), override status of local drafts (and only local drafts), from `Publish` to `Draft`. Don't change status if different from `Publish`.

### Why

- Prior to this PR https://github.com/wordpress-mobile/WordPress-Android/pull/9322 (version 12.0) - new posts were created with the "Publish" status as default status.
- Since we started to auto upload local drafts, this caused an issue with local draft being automatically uploaded.

By migrating local drafts, and forcing the status to Draft, this will fix future issue of this kind.

cc @wordpress-mobile/ravenclaw

**Comment by malinajirka** [comment] 2019-07-11 05:53
Just a few notes: 
- If the user clicks on "Publish" and the upload fails, I believe we create a local draft with "Publish" status. If we migrate even these posts, when the user clicks on "Retry", the post won't be published and will be uploaded to the server as a draft. I'm a bit concerned it might be confusing to change this behavior just for one release and then changing it back. We might want to consider migrating only posts which have `lastModified` older than a certain date. 
- Another thing I'd consider is using the same approach for private, pending and scheduled statuses. I realize those were never default, but if the users were used to keeping them as local drafts, they might still be surprised if some old posts/pages will get published.

Wdyt?

**Comment by shiki** [comment] 2019-07-15 13:30
With the proposed plan in paCBwp-c7-p2, I don't think we need to do this anymore. That is because local drafts with `PUBLISHED` status will no longer be automatically uploaded unless the user has explicitly confirmed it. 

| | LOCAL DRAFT Status |  User confirmed intent to publish? | Action |
|-|--------|-------|---|
|q| `DRAFT`       |   n/a | auto-upload |
|r| `PUBLISHED`       |   ❌   | ignore |
|s| `PUBLISHED`       |   ✔️  | auto-upload |

Note that for (s), we cannot do this with the auto-uploader yet. We're working on that in https://github.com/wordpress-mobile/WordPress-Android/issues/10174#issuecomment-511394264. For now, users can publish these local drafts by manually clicking the _Publish_ button while online. 

Explicit confirmation is being discussed in https://github.com/wordpress-mobile/WordPress-Android/issues/10021.

**Comment by malinajirka** [comment] 2019-08-21 08:53
I'm closing this ticket as all local drafts with un-confirmed changes are uploaded as Drafts - https://github.com/wordpress-mobile/WordPress-Android/blob/1a3fb61ea6e449e8e1cfac38bbfc15347820aa39/WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java#L277

**Closed by malinajirka** 2019-08-21 08:53 UTC
Labels: Offline Support, [Pri] High, [Status] Needs Discussion, [Type] Enhancement
