### ISSUE TITLE
Posts showing Duplicates in Reader Followed Sites Filter

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-Android#12938] opened 2020-09-11 11:00 UTC
### Expected behavior

I'd expect posts to only show up once in the Reader when scrolling through the feed.

### Actual behavior

Some posts seem to be showing up as duplicates. I've not been able to consistently reproduce this, but I have done it twice now. 

### Steps to reproduce the behavior

1. Navigate to the Reader feed in the Android app
2. Click on the gear icon to open Followed Sites
3. Select a site that you have previously followed (two site URLs that worked to show duplicate posts for me were newly followed and URLs can be found in internal link p1599820296037700-slack-C02A4RLLV) One of these was Jetpack and the other was WordPress.com simple site. I haven't replicated this on all sites though.
4. See the duplicate images. 

More details and a video in the ticket here: 3281533-zen

Following the same steps in browser or iOS doesn't show the duplicate posts for the same sites. 

##### Tested on Samsung Tab A, Android 10, WPAndroid 15.7-rc-1 (but the user is most likely on 15.6 which I'll be confirming)

**Comment by designsimply** [comment] 2020-09-15 15:06
Thank you for the report @rezzap!

I tested with 15.6 (App Store version) and 15.7-rc-2 (TestFlight beta) and was unable to replicate. ([5m37s](https://cloudup.com/c3RjEwjFrGm))

I noticed that in the original user report at 3281533-zen the user mentioned there were actual duplicate posts that had been created by mistake on the site. If that's what the Reader is picking up (and caching) then I wonder if this may be a case of the Reader seeing actually duplicated posts that were created and deleted on the site and still cached in the Reader for a while.

It's hard to say though because I did also notice a few duplicate posts during WPAndroid 15.7 beta testing and I couldn't detect a pattern at the time and am still looking for steps to reproduce. Not sure if that's a separate issue. It's worth keeping an eye on since there is a lot of work happening on the Reader right now. (internal reference: p5T066-1vr-p2#comment-5808)

**Comment by designsimply** [comment] 2020-10-19 21:48
Possibly related: https://github.com/wordpress-mobile/WordPress-Android/issues/11350

**Comment by ashiagr** [comment] 2021-06-08 12:24
Looks like a side-effect of #4633 -> #4707.
Another one related: #11036.

Consistently able to reproduce on an atomic site:

https://user-images.githubusercontent.com/1405144/121190851-10088280-c889-11eb-8d56-60b6497c4b90.mp4

Tested on `Pixel 5`, `Android 11`, `WPAndroid 17.5-rc-1`

**Comment by ashiagr** [comment] 2021-06-09 13:37
This one is a tricky issue. I am able to get duplicate posts on Atomic/ Jetpack sites. While I am not able to reproduce it on a simple site, the issue might still exist for them. 

### History 

- #4633 
Post storage allows multiple copies of the same post. Separate columns exist for `date_published`, `date_tagged` and `date_liked`, and the correct date column is chosen for sorting based on the tag stream.

- #4707
Posts in the desired blog are queried using an empty tag name since after requesting posts in a specific blog they're stored in the post table without a tag.

- #3165
Earlier, when the reader updated a single post, it used the` read/sites/$siteid/posts/$postid` endpoint to get the latest version of that post, and it overwrote the local post with the one returned by that endpoint. This endpoint didn't return all of the information that we may have for a post (including the word count), which means this information was lost when we overwrote it. 

    This was resolved by [copying specific fields from the server post to the local post](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderPostActions.java#L184-L214), so the existing information isn't lost.

### Findings
1. Multiple posts from `read/sites/$siteid/posts` endpoint in [`ReaderPostLogic.handleUpdatePostsResponse`](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/services/post/ReaderPostLogic.java#L264)  are not updated in the same way as the single post in [`ReaderPostAction.handleUpdatePostResponse`](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderPostActions.java#L184-L214). 

2. [Jetpack sites return different `pseudo_id` for the same post](https://cloudup.com/c9JjIaxLhFq) in below endpoints:
`/read/following`
`read/sites/$siteid/posts/$postid` and `read/sites/$siteid/posts` 
    It is the same for simple sites. 

    This results in duplicate posts for Jetpack sites as the `ReaderPostTable.addOrUpdatePosts` method makes a new post entry during multiple posts update as primary key (`pseudo_id` + `tag_name` + `tag_type`) will be different from the one already saved from `/read/following` endpoint. 

### Proposed Solution

Whatever logic is applied to a single blog post update in #3165, if applied to the multiple blog posts update, can prevent the creation of duplicate posts for this scenario.  

I'll try to create a PR and we can test it out.

**Comment by thabotswana** [comment] 2021-06-14 13:10
Another report for a Simple site: 4054918-zen

Samsung SM-G980F
WPAndroid 17.4

**Comment by ashiagr** [comment] 2021-06-28 04:54
Pending: D63092-code deploy, #14957 merge.

**Comment by ashiagr** [comment] 2021-06-28 10:43
Closing it now.
#14957 merged, D63092-code deployed.

**Closed as completed by ashiagr** 2021-06-28 10:43 UTC
Labels: [Type] Bug, Reader, [Status] Needs Manual Testing
