### ISSUE TITLE
🤖[Notifications] Sometimes user avatars don't load immediately

### ISSUE THREAD

**Issue by lmischner** [wordpress-mobile/WordPress-Android#20286] opened 2024-02-23 21:30 UTC
### Expected behavior
If a user has an active avatar, it should be displayed.

### Actual behavior
I haven't figured out the pattern, as I've seen it happen for both single and multiple avatars, but sometimes it doesn't immediately load until you navigate in and out of the notification details

https://github.com/wordpress-mobile/WordPress-Android/assets/103850310/d96de84d-d1d6-4f4c-aee6-298851b30643

### Steps to reproduce the behavior
Not sure exactly, but to resolve you can tap into the notification details and back again

**Comment by dangermattic** [comment] 2024-02-23 21:30
Thanks for reporting! 👍

**Comment by antonis** [comment] 2024-04-17 10:27
I'm not able to reproduce this anymore. Probably it is already fixed with the recent Gravatar changes https://github.com/wordpress-mobile/WordPress-Android/pull/20432
Feel free to reopen if this is not the case.

**Closed as completed by antonis** 2024-04-17 10:27 UTC
Labels: [Type] Bug, [Pri] Medium, Notifications
