### ISSUE TITLE
Android: “Mark as sticky” is not available in the app

### ISSUE THREAD

**Issue by nozomimimi** [wordpress-mobile/WordPress-Android#7953] opened 2018-06-28 17:46 UTC
### Expected behavior
"Mark as sticky" is not available in the app. (It exists on Calypso, see the image below)
It'd be nice if we could bring this feature to the mobile app.

[![https://gyazo.com/34adebf76bbdd998b2253835e1eb3474](https://i.gyazo.com/34adebf76bbdd998b2253835e1eb3474.png)](https://gyazo.com/34adebf76bbdd998b2253835e1eb3474)

**Comment by rachelmcr** [comment] 2018-09-04 10:39
Closing this as a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/6263. I'll make a note there about the design!

**Comment by jd-alexander** [comment] 2021-09-16 15:29
Reopening this ticket since the issue is related to an option in Post Settings and not in the Block Editor itself.

**Closed** 2021-09-21 17:36 UTC
Labels: [Type] Enhancement, Post List, Design Needed
