### ISSUE TITLE
"Your Stats are booming" Notification doesn't open native stats

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2939] opened 2015-07-01 09:00 UTC
![stats-booming-issue-01](https://cloud.githubusercontent.com/assets/518232/8451037/4337da8c-1fe0-11e5-9a95-0d06a11eb879.gif)

**Comment by daniloercoli** [comment] 2015-07-07 08:41
Hey @roundhill - What is the status of this? (If you remember it needs to be fixed server side).

**Comment by roundhill** [comment] 2015-07-13 16:15
@daniloercoli sorry, was out last week. I believe @dmsnell was having a look at this.

**Comment by roundhill** [comment] 2015-08-06 16:20
Hey @dmsnell I think you said you couldn't reproduce this? Any insight?

**Comment by roundhill** [comment] 2015-09-10 15:42
Fixed on wp.com

**Closed by roundhill** 2015-09-10 15:42 UTC
Labels: Stats
