### ISSUE TITLE
Login: in dark mode the carrot is not visible

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/WordPress-Android#19561] opened 2023-11-08 01:06 UTC
### Expected behavior
That when you are in dark mode that you can see the line between characters on the login form.

### Actual behavior
See
![Screenshot_20231107-170254](https://github.com/wordpress-mobile/WordPress-Android/assets/115071/fedbd1db-1995-48a0-9791-1f5b928a12fc)

### Steps to reproduce the behavior
IN Dark mode type a username. Move the curser to the middle 
notice that it is hard to see.

**Comment by NataliaDrause** [comment] 2024-06-13 14:38
Upon further investigation I found the following:
- the issue is also present in the light mode,
- the bug appears only after the validation kicks in, i.e. the cursor disappears when input is invalid,

It could be related to the cursor color that gets overwritten for `com.google.android.material.textfield.TextInputLayout`. This might need some tweaks.
It also could be related to the focus of the field being lost after the error appears. Possibly fixed with 
`mSiteAddressInput.requestFocus();` in \WordPress-Login-Flow-Android\WordPressLoginFlow\src\main\java\org\wordpress\android\login\LoginSiteAddressFragment.java on `showError` method.
Worth also checking z-index for the cursor part.

**Closed as completed** 2024-06-17 15:40 UTC
Labels: [Type] Bug, [Pri] Low, Login
