### ISSUE TITLE
Editor overflow menu not shown on API17

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#7622] opened 2018-04-10 01:01 UTC
### Expected behavior
Editor should show the overflow menu icon on all supported OS versions

### Actual behavior
The menu is inaccessible on API 17

### Steps to reproduce the behavior
1. start the app on a API 17 device
2. start a draft
3. observe the overflow menu is not shown

<img width="246" alt="screen shot 2018-04-09 at 9 55 27 pm" src="https://user-images.githubusercontent.com/6597771/38530516-5c0f5d16-3c41-11e8-9399-753750f33d51.png">

**Comment by daniloercoli** [comment] 2018-04-10 11:44
Can't reproduce it in `develop` on a Nexus 4 - 4.2.2 - API17.

Let me try to find a Samsung S3 then.

**Comment by daniloercoli** [comment] 2018-04-10 13:30
I can reproduce it on a Samsung S3, anyway it seems the default behavior on phones with traditional navigation hardware keys.

`Android phones with traditional navigation hardware keys don't display the virtual navigation bar at the bottom of the screen. Instead, the action overflow is available from the menu hardware key. The resulting actions popup has the same style as in the previous example, but is displayed at the bottom of the screen.`
Ref: https://developer.android.com/design/patterns/compatibility.html


Closing this as per chat convo.

**Closed by daniloercoli** 2018-04-10 13:30 UTC
Labels: Posting/Editing, [Pri] High, [Type] Bug
