### ISSUE TITLE
Light Mode: Russell Theme: Editor text is white on a white background 

### ISSUE THREAD

**Issue by azollafox** [wordpress-mobile/WordPress-Android#19725] opened 2023-12-04 16:35 UTC
### Expected behavior
When I'm writing I should be able to see all text I'm adding, no matter what theme I select for my site or the appearance of my app

### Actual behavior
If I select the Russell theme and the light mode appearance on my Android device the text becomes unread able because it is white on a white background

### Steps to reproduce the behavior
1. Set your device's appearance to light mode
2. Set your site's theme to Russell: https://wordpress.com/theme/russell
3. Open up a post or page editor in the app

**Comment by twstokes** [comment] 2023-12-06 13:38
This should be resolved in https://github.com/WordPress/gutenberg/pull/56752 and may be a duplicate of https://github.com/wordpress-mobile/gutenberg-mobile/issues/6431. I'll close this - the fix should land on 23.8.

**Closed as completed by twstokes** 2023-12-06 13:38 UTC
