### ISSUE TITLE
Runtime Exception in EditPostActivity (PARAGRAPH span must start at paragraph boundary)

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#8634] opened 2018-11-20 21:02 UTC
```
Fatal Exception: java.lang.RuntimeException: PARAGRAPH span must start at paragraph boundary
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:688)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:102)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:54)
       at org.wordpress.aztec.AztecText.toPlainHtml(AztecText.kt:1159)
       at org.wordpress.aztec.AztecText.hasChanges(AztecText.kt:1138)
       at org.wordpress.android.editor.AztecEditorFragment.getContent(AztecEditorFragment.java:910)
       at org.wordpress.android.ui.posts.EditPostActivity.updatePostObject(EditPostActivity.java:1373)
       at org.wordpress.android.ui.posts.EditPostActivity.access$900(EditPostActivity.java:187)
       at org.wordpress.android.ui.posts.EditPostActivity$4$1.run(EditPostActivity.java:598)
       at java.lang.Thread.run(Thread.java:818)
``` 
5be59441f8b88c2963352fa1-fabric

**Comment by daniloercoli** [comment] 2018-11-21 09:04
See also: https://github.com/wordpress-mobile/AztecEditor-Android/issues/649

**Comment by designsimply** [comment] 2019-05-07 19:11
**30-day impact:** ~4 per day
**Users affected:** 63
**Last seen in:** 11.2

<sup>(5be59441f8b88c2963352fa1-fabric-android)</sup>

**Comment by designsimply** [comment] 2019-07-11 21:54
**30-day impact:** ~1 per day
**Users affected:** 23 in the last 30d
**Last seen in:** 12.5

<sup>https://sentry.io/share/issue/25e98c90786e4e0f9eac0d4d617a2283/</sup>

**Comment by designsimply** [comment] 2019-10-10 22:51
**90-day impact:** 92 or ~1 per day
**Users affected in the last 90 days:** 38

<sup>https://sentry.io/share/issue/25e98c90786e4e0f9eac0d4d617a2283/</sup>

**Comment by designsimply** [comment] 2019-11-06 23:11
**90-day impact:** ~1 per day
**Users affected in the last 90 days:** 33

<sup>https://sentry.io/share/issue/25e98c90786e4e0f9eac0d4d617a2283/</sup>

Pretty rare crash. Okay to close?

**Comment by malinajirka** [comment] 2019-11-19 13:43
I found crashes in Sentry which seem somewhat related. The app crashes in different places, but the root cause of the issue is probably the same. I still think it's a low priority issue (perhaps an OS issue), but I'm not sure if we still want to close it.

[0](https://sentry.io/organizations/a8c/issues/1022238753/), [1](https://sentry.io/organizations/a8c/issues/1178107948/), [2](https://sentry.io/organizations/a8c/issues/1178107948/), [3](https://sentry.io/organizations/a8c/issues/1080669619/), [4](https://sentry.io/organizations/a8c/issues/1217554623/), [5](https://sentry.io/organizations/a8c/issues/1328068369/), [6](https://sentry.io/organizations/a8c/issues/1325248254/), [7](https://sentry.io/organizations/a8c/issues/1324409633/), [8](https://sentry.io/organizations/a8c/issues/1046360753/), [9](https://sentry.io/organizations/a8c/issues/1101700019/), [10](https://sentry.io/organizations/a8c/issues/1107322276/), [11](https://sentry.io/organizations/a8c/issues/1300936935/), [12](https://sentry.io/organizations/a8c/issues/1300552051/), [13](https://sentry.io/organizations/a8c/issues/1108567798/), [14](https://sentry.io/organizations/a8c/issues/1126690462/), [15](https://sentry.io/organizations/a8c/issues/1031109802/), [16](https://sentry.io/organizations/a8c/issues/1014702969/), [17](https://sentry.io/organizations/a8c/issues/1062172588/), [18](https://sentry.io/organizations/a8c/issues/1210303055/), [19](https://sentry.io/organizations/a8c/issues/1192554358/), [20](https://sentry.io/organizations/a8c/issues/1183738381/).

cca 250 events in the last 90 days.

**Comment by designsimply** [comment] 2019-12-18 18:19
@malinajirka what do you think about merging all of those the Sentry issues you linked? Any reason not to merge them?

**Comment by malinajirka** [comment] 2019-12-19 09:14
@designsimply Hmm, tbh I'd rather keep them separate. It's just a hypothesis that the root cause if the same. The stacktraces are a bit different, so I think it might help the person who will look into this issue to find the cause.

**Comment by designsimply** [comment] 2020-05-01 20:23
I searched for "PARAGRAPH span must start at paragraph boundary" in Sentry and found approximately 415 events for 66 users in the last 90 days.

For Sentry Issue [WORDPRESS-ANDROID-CF](https://sentry.io/share/issue/25e98c90786e4e0f9eac0d4d617a2283/), [zero](https://sentry.io/organizations/a8c/discover/results/?field=timestamp&field=release&field=os&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1022238753+release%3Aorg.wordpress.android-14.6.1&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29) events have been tracked for this crash in 14.6.1 since it was released 9d ago on Apr 22.

**Comment by designsimply** [comment] 2020-05-19 16:58
[5](https://sentry.io/organizations/a8c/discover/results/?field=timestamp&field=release&field=os&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1022238753+release%3Aorg.wordpress.android-14.7&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29) events have been tracked for this crash in 14.7 since it was released 15d ago on May 4.

**Number of users affected in the last 90d:** 24
**Number of events in the last 90d:** 182
<sub>https://sentry.io/share/issue/06479f2a38234c8abad668f173724b9f/</sub>

**Comment by designsimply** [comment] 2020-05-28 03:37
**Events in the last 90d:** 185
**Events in the last 9d since 14.8 was released:** [2](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1022238753+version%3A14.8&sort=-timestamp&statsPeriod=14d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29)
**Users affected in the last 90d:** 24
<sub>https://sentry.io/share/issue/25e98c90786e4e0f9eac0d4d617a2283/</sub>

Note: a search for "PARAGRAPH span must start at paragraph boundary" in Sentry currently returns 7 issues, so I think it's worth checking on those before closing this even though there is a very low number of occurrences from the latest release.

**Comment by designsimply** [comment] 2020-06-26 22:33
All righty. A search for `"PARAGRAPH span must start at paragraph boundary"` returns 160 events in the last 90d:

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=%22PARAGRAPH+span+must+start+at+paragraph+boundary%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85905995-452bda00-b7ca-11ea-81e2-01813c7fb8a6.png)</a>

And `issue.id:1022238753` seems to be one instance of those:

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1022238753&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85906122-9c31af00-b7ca-11ea-9c73-98a6b558ab90.png)</a>

Leaving it open and low priority because the occurrences are low but still happening in recent releases.

**Comment by designsimply** [comment] 2020-08-10 21:35
Slightly lower events per day are happening for `"PARAGRAPH span must start at paragraph boundary"` with 32 in the last 30d, and the number perday is slightly lower as well but still happening in recent releases.

[![image](https://user-images.githubusercontent.com/1119271/89831710-8595ac00-db1b-11ea-9845-25a09a4cef4c.png)](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=%22PARAGRAPH+span+must+start+at+paragraph+boundary%22&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29)

**Comment by designsimply** [comment] 2020-10-14 23:36
Still fairly low frequency for this one. Following are the search results for "PARAGRAPH span must start at paragraph boundary" and showing a 30-day graph.

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=%22PARAGRAPH+span+must+start+at+paragraph+boundary%22&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96056426-c4115500-0e43-11eb-894f-0625e81f6daa.png)</a>

**Comment by designsimply** [comment] 2020-11-26 02:42
Still low priority.

**Comment by designsimply** [comment] 2021-01-21 19:30
<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=%22PARAGRAPH+span+must+start+at+paragraph+boundary%22&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105389596-3d53dd00-5bd5-11eb-97c0-24800a081f28.png)</a>

**Events in the last 90d:** 212
**Users affected in the last 90d:** 5
**Limited to:** Android 6 & 7
**Culprit:** android.text.SpannableStringInternal in setSpan
<sub>WORDPRESS-ANDROID-CF: https://sentry.io/share/issue/25e98c90786e4e0f9eac0d4d617a2283/</sub>

There are now more events overall in the last 90d for `PARAGRAPH span must start at paragraph boundary`  than the last time I checked in on this one, but still pretty low and it has been open a long long time and has only affected 5 people that we know of in the last 90d and is limited to Android 6 & 7 so I'd like to recommend closing this one.

**Closed** 2021-01-22 11:06 UTC
Labels: Aztec, [Pri] Low, [Type] Crash
