### ISSUE TITLE
Reader Comments: Unable to post comments

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#13091] opened 2020-10-08 15:17 UTC
### Expected behavior
When responding to comments via the Reader, I expected the comment to be posted or the comment icon to be disabled if the user wasn't able to post a comment

### Actual behavior
When responding to comments via the Reader, the comment fails to post for some sites and the user sees the "Couldn\'t post your comment" toast.

##### Tested on [Emulator], Android [10], WPAndroid [15.8]

**NOTE**: This is also happening on **iOS** and **older Android** versions (earliest tested was March 2020)

### Research
- I was able to reproduce this by attempting to post a comment to a Business/Atomic site blog post, while in the role of a "Follower" of the site. 
- The request url: https://public-api.wordpress.com/rest/v1.1/sites/{siteId}/posts/{postId}/replies/new?locale=en_US
The response from the **API is 400** with {"**error":"unknown_token","message":"Unknown Token**"}.
- If I add myself to the site as a Subscriber “Can read and comment on posts and pages.”, then I am able to post a comment successfully.
- For additional information see 3381662-zen
- The comment settings are as follows:
<img src="https://user-images.githubusercontent.com/506707/95476305-1ee31200-0955-11eb-97d8-d2c7e0215a30.png"  width="200" alt="Screenshot">

**Comment by designsimply** [comment] 2020-10-08 17:16
@zwarm thanks for the bug report! I'd like to help test this. ~May I ask if the Business/Atomic site you tested with was private or public?~ EDIT: nevermind! I saw the support ticket reference and figured it out.

**Comment by azollafox** [comment] 2020-10-08 18:00
Looks like this might be a result of this issue: https://github.com/Automattic/wp-calypso/issues/46284

**Comment by designsimply** [comment] 2020-10-08 19:20
Thanks @sarahfg! Tested and confirmed using the following steps.

To prepare:

* Set up a WordPress.com Business site with plugins installed.
* Make sure the following settings are *on* in My Site > Manage > Settings > Discussion:
  * "Let visitors use a WordPress.com, Twitter, Facebook, or Google account to comment."
  * "Comment author must fill out name and e-mail"
  * "Users must be registered and logged in to comment"
* Make sure the following settings are *blank* in My Site > Manage > Settings > Discussion:
  * "Comment moderation"
  * "Disallowed comments"
* Follow the site in the Reader from a different user account.

To test:

1. Log in to the WPAndroid app as the user following the site setup earlier.
1. Open the site in the Reader.
1. Try to leave a comment on any post in the site mentioned.

Results: cannot post a comment and the following error is returned: "Couldn't post your comment." ([59s](https://cloudup.com/c2adHjJ0K-l))

<img src="https://user-images.githubusercontent.com/1119271/95502864-be110500-0967-11eb-87f9-c8eca04cebd9.png" width="270" alt="Screen Shot 2020-10-08 at Oct 8 1 08 38 PM">
<sup>Tested with WPAndroid 15.9-rc-1 on Pixel 3 Android 11 on WordPress.com Business site artindesignco.blog while logged in to the Android app as WordPress.com user design5279reader.</sup>

```
78 - [Oct-08 19:01 STATS] 🔵 Tracked: reader_article_commented_on, Properties: {"blog_id":160502386,"post_id":287,"is_jetpack":true,"feed_id":96299076,"feed_item_id":0}
79 - [Oct-08 19:01 READER] submitting comment
80 - [Oct-08 19:01 READER] comment failed
81 - [Oct-08 19:01 READER] null
82 - [Oct-08 19:01 READER] StackTrace: com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

83 - [Oct-08 19:01 UTILS] trackLastActivity, activityId: Reader
84 - [Oct-08 19:01 API] Dispatching action: AccountAction-FETCH_ACCOUNT
85 - [Oct-08 19:01 MAIN] ReaderTracker: started MAIN_READER
86 - [Oct-08 19:01 READER] reader post list > resumed from paused state
87 - [Oct-08 19:01 READER] TRACK READER ReaderPostListFragment > START Count [mIsTopLevel = true]
88 - [Oct-08 19:01 API] WhatsNewStore: fetchWhatsNew
89 - [Oct-08 19:01 API] Dispatching action: AccountAction-FETCHED_ACCOUNT
90 - [Oct-08 19:01 SUGGESTION] service destroyed
```

<details>
<summary>Full app logs for the timestamp matching the video</summary>

```
WordPress - 15.9-rc-1 - Version code: 930
Android device name: Google Pixel 3

01 - [Oct-08 19:00 API] Dispatching action: AccountAction-FETCHED_ACCOUNT
02 - [Oct-08 19:00 READER] reader service > all tasks completed
03 - [Oct-08 19:00 READER] reader job service > all tasks completed
04 - [Oct-08 19:00 STATS] 🔵 Tracked: select_interests_shown
05 - [Oct-08 19:00 READER] reader job service > destroyed
06 - [Oct-08 19:00 NOTIFS] Register token action succeeded
07 - [Oct-08 19:00 NOTIFS] Server response OK. The device_id: 38441076
08 - [Oct-08 19:00 UTILS] trackLastActivity, activityId: My Site
09 - [Oct-08 19:00 STATS] The passed blog obj is null or it's not a wpcom or Jetpack. Tracking analytics without blog info
10 - [Oct-08 19:00 STATS] 🔵 Tracked: my_site_tab_accessed
11 - [Oct-08 19:00 MAIN] ReaderTracker: stopped MAIN_READER
12 - [Oct-08 19:00 STATS] 🔵 Tracked: me_tab_accessed
13 - [Oct-08 19:00 STATS] 🔵 Tracked: support_opened, Properties: {"origin":"ME_SCREEN_HELP"}
14 - [Oct-08 19:00 UTILS] trackLastActivity, activityId: Help Screen
15 - [Oct-08 19:00 UTILS] App goes to background
16 - [Oct-08 19:00 STATS] 🔵 Tracked: application_closed, Properties: {"time_in_main_reader":1,"last_visible_screen":"Help Screen","time_in_reader_paged_post":0,"time_in_app":24,"time_in_subfiltered_list":0,"time_in_reader_filtered_list":0}
17 - [Oct-08 19:00 MAIN] ConnectionChangeReceiver successfully unregistered
18 - [Oct-08 19:00 UTILS] App comes from background
19 - [Oct-08 19:00 STATS] 🔵 Tracked: application_opened
20 - [Oct-08 19:00 READER] notifications update job service > job scheduled
21 - [Oct-08 19:00 NOTIFS] notifications update job service > created
22 - [Oct-08 19:00 UTILS] Remote config updated: false
23 - [Oct-08 19:00 NOTIFS] notifications update service > completed
24 - [Oct-08 19:00 NOTIFS] notifications update job service > all tasks completed
25 - [Oct-08 19:00 NOTIFS] notifications update job service > destroyed
26 - [Oct-08 19:00 UTILS] trackLastActivity, activityId: Help Screen
27 - [Oct-08 19:00 UTILS] trackLastActivity, activityId: My Site
28 - [Oct-08 19:00 API] Dispatching action: AccountAction-FETCH_ACCOUNT
29 - [Oct-08 19:00 API] WhatsNewStore: fetchWhatsNew
30 - [Oct-08 19:00 API] Dispatching action: AccountAction-FETCHED_ACCOUNT
31 - [Oct-08 19:00 UTILS] trackLastActivity, activityId: Reader
32 - [Oct-08 19:00 STATS] 🔵 Tracked: reader_accessed
33 - [Oct-08 19:00 MAIN] ReaderTracker: started MAIN_READER
34 - [Oct-08 19:00 STATS] 🔵 Tracked: reader_following_shown
35 - [Oct-08 19:01 STATS] 🔵 Tracked: reader_reader_tag_followed, Properties: {"tag":"outdoors"}
36 - [Oct-08 19:01 STATS] 🔵 Tracked: select_interests_picked, Properties: {"quantity":1}
37 - [Oct-08 19:01 READER] add tag succeeded
38 - [Oct-08 19:01 READER] reader post list > newInstance (tag)
39 - [Oct-08 19:01 READER] reader post list > creating post adapter
40 - [Oct-08 19:01 READER] reader posts task already running
41 - [Oct-08 19:01 READER] reader post list > creating post adapter
42 - [Oct-08 19:01 READER] TRACK READER ReaderPostListFragment > START Count [mIsTopLevel = true]
43 - [Oct-08 19:01 READER] reader post list > updating tag Followed-Sites, updateAction=REQUEST_NEWER
44 - [Oct-08 19:01 READER] reader post service > job scheduled
45 - [Oct-08 19:01 READER] reader post job service > created
46 - [Oct-08 19:01 READER] reader post job service > started
47 - [Oct-08 19:01 READER] requested posts response = CHANGED
48 - [Oct-08 19:01 READER] reader post job service > all tasks completed
49 - [Oct-08 19:01 READER] reader post job service > destroyed
50 - [Oct-08 19:01 READER] TRACK READER ReaderPostListFragment > STOP Count [mIsTopLevel = true]
51 - [Oct-08 19:01 MAIN] ReaderTracker: stopped MAIN_READER
52 - [Oct-08 19:01 UTILS] trackLastActivity, activityId: Reader
53 - [Oct-08 19:01 API] Dispatching action: AccountAction-FETCH_ACCOUNT
54 - [Oct-08 19:01 MAIN] ReaderTracker: started MAIN_READER
55 - [Oct-08 19:01 READER] reader post list > resumed from paused state
56 - [Oct-08 19:01 READER] TRACK READER ReaderPostListFragment > START Count [mIsTopLevel = true]
57 - [Oct-08 19:01 API] WhatsNewStore: fetchWhatsNew
58 - [Oct-08 19:01 API] Dispatching action: AccountAction-FETCHED_ACCOUNT
59 - [Oct-08 19:01 READER] TRACK READER ReaderPostListFragment > STOP Count [mIsTopLevel = true]
60 - [Oct-08 19:01 MAIN] ReaderTracker: stopped MAIN_READER
61 - [Oct-08 19:01 STATS] 🔵 Tracked: reader_article_comments_opened, Properties: {"blog_id":160502386,"post_id":287,"is_jetpack":true,"feed_id":96299076,"feed_item_id":0}
62 - [Oct-08 19:01 READER] reader comments > refreshComments
63 - [Oct-08 19:01 READER] updating post
64 - [Oct-08 19:01 SUGGESTION] service created
65 - [Oct-08 19:01 READER] reader comment service > created
66 - [Oct-08 19:01 READER] updating comments
67 - [Oct-08 19:01 SUGGESTION] suggestion service > updating suggestions for siteId: 160502386
68 - [Oct-08 19:01 SUGGESTION] suggestion service > updating tags for siteId: 160502386
69 - [Oct-08 19:01 READER] updating comments
70 - [Oct-08 19:01 SUGGESTION] stopping suggestion service
71 - [Oct-08 19:01 SUGGESTION] null
72 - [Oct-08 19:01 SUGGESTION] StackTrace: com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

73 - [Oct-08 19:01 SUGGESTION] stopping suggestion service
74 - [Oct-08 19:01 READER] reader comments > refreshComments
75 - [Oct-08 19:01 READER] reader comment service > destroyed
76 - [Oct-08 19:01 READER] reader comments > refreshComments
77 - [Oct-08 19:01 READER] reader post list > saving instance state
78 - [Oct-08 19:01 STATS] 🔵 Tracked: reader_article_commented_on, Properties: {"blog_id":160502386,"post_id":287,"is_jetpack":true,"feed_id":96299076,"feed_item_id":0}
79 - [Oct-08 19:01 READER] submitting comment
80 - [Oct-08 19:01 READER] comment failed
81 - [Oct-08 19:01 READER] null
82 - [Oct-08 19:01 READER] StackTrace: com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

83 - [Oct-08 19:01 UTILS] trackLastActivity, activityId: Reader
84 - [Oct-08 19:01 API] Dispatching action: AccountAction-FETCH_ACCOUNT
85 - [Oct-08 19:01 MAIN] ReaderTracker: started MAIN_READER
86 - [Oct-08 19:01 READER] reader post list > resumed from paused state
87 - [Oct-08 19:01 READER] TRACK READER ReaderPostListFragment > START Count [mIsTopLevel = true]
88 - [Oct-08 19:01 API] WhatsNewStore: fetchWhatsNew
89 - [Oct-08 19:01 API] Dispatching action: AccountAction-FETCHED_ACCOUNT
90 - [Oct-08 19:01 SUGGESTION] service destroyed
91 - [Oct-08 19:01 UTILS] trackLastActivity, activityId: My Site
92 - [Oct-08 19:01 STATS] The passed blog obj is null or it's not a wpcom or Jetpack. Tracking analytics without blog info
93 - [Oct-08 19:01 STATS] 🔵 Tracked: my_site_tab_accessed
94 - [Oct-08 19:01 READER] TRACK READER ReaderPostListFragment > STOP Count [mIsTopLevel = true]
95 - [Oct-08 19:01 MAIN] ReaderTracker: stopped MAIN_READER
96 - [Oct-08 19:01 STATS] 🔵 Tracked: me_tab_accessed
97 - [Oct-08 19:01 READER] reader post list > saving instance state
98 - [Oct-08 19:01 STATS] 🔵 Tracked: support_opened, Properties: {"origin":"ME_SCREEN_HELP"}
99 - [Oct-08 19:01 UTILS] trackLastActivity, activityId: Help Screen
```
</details>

**Comment by designsimply** [comment] 2020-10-08 19:32
I also verified that I was unable to leave a comment via the Reader web. ([47s](https://cloudup.com/cCePGrhjfuW))

> Sorry - there was a problem posting your comment.

> Could not retrieve comments for requested post

> Could not add a reply to this post.

<img src="https://user-images.githubusercontent.com/1119271/95503893-3af0ae80-0969-11eb-8e83-0171f1c90d3a.png" width="270" alt="Screenshot_20201008-131850">
<sup>Tested with WPAndroid 15.9-rc-1 on Pixel 3 Android 11 on WordPress.com Business site (with plugins installed) artindesignco.blog while logged in to the WordPress.com with Chrome on my Android 11 device as user design5279reader.</sup>

**Comment by designsimply** [comment] 2020-10-08 19:34
Closing in favor of https://github.com/Automattic/wp-calypso/issues/46284 as it appears this is a problem happening upstream. Please leave a comment here or create a new issue if you feel there is an app-specific problem and I will re-investigate. Thank you!

**Closed as completed by designsimply** 2020-10-08 19:34 UTC
Labels: [Type] Bug, Reader, Comments
