### ISSUE TITLE
Reader: Wrong post is loaded after orientation change

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#4599] opened 2016-10-04 09:10 UTC
**Steps to reproduce:**

Go to Liked Posts, Followed Sites or Reader Blog.
Open any post.
Change device orientation.
The post that goes before the one you loaded, appears in post view. (sometimes you need to change the orientation back to original for wrong post to appear).

Video to illustrate the problem:
https://cloudup.com/cP_UswVjfPf

Tested on alpha-23 with Nexus 5x 6.0.0 and Nexus 5 5.0.0

**Comment by hoverduck** [comment] 2017-01-19 16:44
I was unable to reproduce on my Nexus 6P / 7.1.1 / alpha-33.  @khaykov are you still seeing the problem?

**Comment by nbradbury** [comment] 2017-01-29 21:00
@hoverduck I'm pretty sure we can close this one. This was most likely due to a mistake I made in how posts were stored which has since been resolved by #4633 and #4707.

**Closed** 2017-01-30 20:28 UTC
Labels: Reader, [Pri] Low, [Type] Bug
