### ISSUE TITLE
Invalid "queued post" state on post list

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10522] opened 2019-09-25 08:47 UTC
Posts are sometimes displayed in "queued post" state even when they are actually not present in the upload queue.

### Steps to reproduce the behavior
1. Connect to a self-hosted site
2. Open an existing draft
3. Add an image and wait until its upload finishes
4. Click on back
5. Notice the "Queued post" label and the progress displayed over the item

![queued-post-invalid-state](https://user-images.githubusercontent.com/2261188/65584837-cf1bed80-df81-11e9-97db-883f13124556.gif)

**Comment by shiki** [comment] 2019-09-26 02:16
@malinajirka I'm still working on this. But feel free to take over if you run out of things to work on. 😄 

## What I know so far

- There is a `PostUploadModel` that is never deleted which I believe is the cause of the “Queued post” label. 
- The `PostUploadModel` is only deleted on `UploadStore.handlePostUploadedOrAutoSaved`. On self-hosted sites, we don't reach this because we don't attempt to auto-save after exiting the editor. I think it's a happy accident that this works on WPCom. For WPCom, we attempt auto-save so: 
    1. `handlePostUploadedOrAutoSaved` is called
    2. `PostUploadModel` is deleted
    3. The user will not see “Queued post”
- This does not happen on `develop`. It looks like it's only happening in the `master-auto-upload` branch. This is because we removed auto-uploading for existing drafts when pressing the _Back_ button. 

## Possible solution

I'm evaluating whether we should delete the `PostUploadModel` in `UploadStore.handleMediaUploaded()`. Not quite sure if this will affect other parts of the system.

**Comment by malinajirka** [comment] 2019-09-26 06:47
Nice analysis Jayson! ;)

This is a second bug where we have troubles with queueing posts when we are trying to upload just a media file.

>I'm evaluating whether we should delete the PostUploadModel in UploadStore.handleMediaUploaded(). Not quite sure if this will affect other parts of the system

I can't say for sure without investigating it, but my first guess would be that we are relying on it 
when we are uploading a post -> if the post has local media, we enqueue the post but we upload its media first. Would we delete the `PostUploadModel` after the first media upload finishes?

**Comment by malinajirka** [comment] 2019-09-27 09:26
I'm moving this ticket out of Offline Support project as I'm able to reproduce this bug on a published post on `develop`.

**Comment by shiki** [comment] 2019-09-27 12:57
Fixed by #10533. This should land in `develop` soon.

**Closed by shiki** 2019-09-27 12:57 UTC
Labels: Post List, Posting/Editing, Self-hosted, [Pri] Medium, [Type] Bug
