### ISSUE TITLE
Image added at the beginning of the post instead of the end

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#8134] opened 2018-08-02 10:03 UTC
### Expected behavior
When trying to append another image after another already there at the end of the post, the new image should be appended.

### Actual behavior
The new image is inserted at the beginning of the post.

### Steps to reproduce the behavior
* Start a new post
* Add an image to the post
* Place the cursor after the image, tap Enter to go to the next line and add another image
* This second image gets added to the beginning of the post

##### Tested on [device], Android [version]
Nexus 5X running Android v7.1.2, app version alpha-121

**Comment by hypest** [comment] 2018-08-02 10:04
This seems to stem from some weird cursor related issue, where the cursor jumps to the beginning of the post when Activity changes.

**Comment by planarvoid** [comment] 2018-10-11 12:57
Most of the times I couldn't reproduce this issue but there is a way to do it all the times:
• start uploading an image in a new post
• click on the image and dismiss the popup
• start uploading a second image
• the second image is placed before the first image
• try scrolling - the popup always appears after a scroll
• after the upload is completed, scrolling results in opening the first image details

**Comment by planarvoid** [comment] 2018-10-12 09:54
@hypest could you double check that this issue is still happening?

**Comment by planarvoid** [comment] 2018-10-12 14:04
We've tested this on Nexus 5x and the bug doesn't seem to be there. What is happening is:
* You insert an image to an empty post
* You click below the image on the left side of the screen
* The cursor moves to the left of the image
* You click below the image to the right side of the screen
* The cursor moves to the right of the image

This seems like an intentional behaviour so I'll close this issue.

**Closed by planarvoid** 2018-10-12 14:04 UTC
Labels: Media, Posting/Editing, [Pri] High, [Type] Bug

**Comment by hypest** [comment] 2018-10-12 14:22
Checked again with the same phone and OS version but with app version 10.9.1 (version code 621) and I can't replicate the issue. The second image gets added after the first one as it should be expected. Feel free to close this ticket as no longer happening.

> The only way I got something similar was when I clicked on an image that was being uploaded with the following steps:
> ...
> I don't think that's a bug though and it's not that common

I'd say that that's a different issue and it should be more prominent on slower connections. Let's open a new, different ticket with those steps, wdyt?
