### ISSUE TITLE
[Site Creation] Site Preview extra black bar

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#9082] opened 2019-01-23 20:38 UTC
We are hiding the admin bar in the site preview page to avoid confusion for users, but it's currently leaving an extra black bar in the landscape orientation. I think this could be frustrating experience for a new user. I am not yet sure whether this needs to be addressed in the backend or in the client, so I am opening an issue here for now.

![screenshot_1548275759](https://user-images.githubusercontent.com/662023/51635510-f0c16280-1f24-11e9-8cb3-23b16359759f.png)

**Comment by SylvesterWilmott** [comment] 2019-02-07 12:11
There is a theme specific pseudo-class that is added here on a media query for larger screens. This is why the problem is only present on tablets.

`@media screen and (min-width: 48.9375em)
body:not(.custom-background-image).admin-bar:before {
    top: 32px;
}`

This is unique to this theme though.

**Comment by oguzkocer** [comment] 2019-02-07 15:39
Thanks @SylvesterWilmott! @kwonye mentioned that this theme will not actually be used in the new sites, so we might not need to do anything about it. Let's wait for the server side changes for now.

**Comment by kwonye** [comment] 2019-02-07 17:08
Great news, @oguzkocer! Just tested and all sites created with our new Site Creation do not have the black bar on top. I believe we can close this issue out.

**Comment by oguzkocer** [comment] 2019-02-07 17:11
Sounds good, thanks @kwonye!

**Comment by kwonye** [comment] 2019-02-07 17:13
Nevermind so sorry, Didn't have it in landscape mode properly. It definitely shows. One way iOS solves this is by limiting the width to 800 OR we simply show the masterbar.

@oguzkocer @SylvesterWilmott do either of you have an opinion on whether we should do this?

**Comment by oguzkocer** [comment] 2019-02-07 18:18
I don't think we should show the `Get Started` bar. Even in another place it'd be confusing, but telling the users that they can start creating sites just after they created a site is extremely confusing if you ask me. Not that they can tap on the bar and go anywhere from it, but still.

If it's present in the current themes, I think we should try to do something about it. The best solution I can think of is to have `hide_getstartedbar=true` parameter in the url similar to `hide_masterbar=true`. If that's not possible, or it'd implemented in the far future, I am open to any css hack. Regardless of which hack we use, it's going to be unpleasant, so no strong opinions on that.

**Comment by malinajirka** [comment] 2019-02-08 09:18
>If it's present in the current themes, I think we should try to do something about it. The best solution I can think of is to have `hide_getstartedbar=true` parameter in the url similar to `hide_masterbar=true`.

This options definitely sounds like the best solution! Using a css hack sounds a bit risky to me, especially since the API can start returning a different theme in the future and it might break old versions of the app. Tbh for me it's either a backend fix or do nothing about it.

**Comment by diegoreymendez** [comment] 2019-05-15 14:00
Moving to the Site Creation Improvements project, to wrap up the original project board.

**Comment by diegoreymendez** [comment] 2019-05-15 14:10
I'm trying to understand this issue but even in the initial image in this thread I'm not sure what the extra black bar is.

The site above looks consistent with what I'm seeing in my iPhone, in my Android phone and in Safari (while logged out).

@shiki - Can I ask you to double check what I'm seeing and let me know if you find anything that's obviously off?  Right now I'm trying to assess whether it makes sense for us to focus on this, or if it's fine and consistent across platforms.

**Comment by shiki** [comment] 2019-05-15 23:29
@diegoreymendez That black bar is Android's taskbar that is visible by default for all apps. I was able to reproduce this on a tablet, Pixel C, Android 8.0. I was **not** able to reproduce this on a phone, PIxel 3, Android 9.0. 

![2019-05-15 17-25-49 gifcask 2019-05-15 17_28_41](https://user-images.githubusercontent.com/198826/57816003-e70f7500-7736-11e9-8aa9-90edff8eeba9.gif)

**Comment by shiki** [comment] 2019-05-15 23:45
Actually, scratch that. I was talking about a different thing. 🤦‍♂ Updated my comment above. ☝️

**Comment by malinajirka** [comment] 2019-05-16 13:22
This is the blackbar this issue is about (I used the image from the description).
![51635510-f0c16280-1f24-11e9-8cb3-23b16359759f](https://user-images.githubusercontent.com/2261188/57856722-e0900480-77ed-11e9-87fa-e6b1426311eb.jpg)

I have been able to reproduce the issue, even though I still think it should be fixed either on the backend or we should consider closing it with "Won't fix - minor issue".
![Screenshot_1558012938](https://user-images.githubusercontent.com/2261188/57856958-69a73b80-77ee-11e9-87b2-155bc247b927.png)

cc @diegoreymendez @shiki

**Comment by malinajirka** [comment] 2019-05-16 13:24
Ohh, I actually just noticed I can't reproduce the issue with "blog" segment, but I can reproduce it with "business" segment.

**Comment by shiki** [comment] 2019-05-16 13:28
@malinajirka Good find. I was only using Blog at that time. I agree that this should be fixed in the backend.

**Comment by diegoreymendez** [comment] 2019-05-16 15:18
Closing as won't fix for now.  It's not great to have that bar there, but it's an issue with the theme and not really in the Apps.

**Closed by diegoreymendez** 2019-05-16 15:18 UTC
Labels: Site Creation, [Status] Wontfix, [Type] Bug, good first issue
