### ISSUE TITLE
Publicize: Error Connecting To Social Media Profiles

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#8652] opened 2018-11-22 10:31 UTC
### Expected behavior

I expected to be able to connect my WordPress.com site to my Twitter account or other social media accounts so that future blog posts are automatically shared.

### Actual behavior

After going through the steps to connect to my Twitter account, when I have connected more than one Twitter account in the past, a toast message comes up with an error and the site isn't connected.

Similar errors occur for other social media accounts I try to connect (LinkedIn, Facebook).

### Steps to reproduce the behavior

1. Navigate to My Site > Sharing.
2. Tap on "Twitter" and choose the option to "Connect".
3. Enter your username and password for Twitter.
4. Select your Twitter account in the Connecting Twitter modal.

If you don't see the Connecting Twitter modal, and your Twitter account is connected successfully, delete the connection and repeat the steps above using a second Twitter account. The second time, you will see the Connecting Twitter modal with both Twitter accounts.

Result: A toast message comes up with the error "An error occurred."

##### Reported in 1581544-z, WordPress for Android 11.1.1

**Comment by rachelmcr** [comment] 2018-11-22 10:51
I confirmed the issue, and confirmed that it's only happening with Twitter (not other publicize connections) and only on Android (works as expected on iOS & web).

When I try to connect to Twitter I get the following in my app log:

```
92 - [Nov-22 10:44 SHARING] null
93 - [Nov-22 10:44 SHARING] StackTrace: com.android.volley.ServerError
at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:179)
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)
```

**Comment by SiobhyB** [comment] 2018-11-23 11:02
We had a report of an error connecting to Facebook in 1587043-z, also.

I tested and was able to reproduce the error when attempting to connect to a Facebook page. 

I also tested connecting to LinkedIn within the Android app and saw an error there too. 

I don't have a Tumblr account to test with.

**Comment by rachelmcr** [comment] 2018-11-23 11:17
Here's the specific Volley error I'm getting — I'm now seeing it on different Publicize connections, not just Twitter, and regardless of the locale:

```
11-23 11:08:33.246 8823-8898/? E/Volley: [1553] BasicNetwork.performRequest: Unexpected response code 400 for https://public-api.wordpress.com/rest/v1.1/sites/154199540/publicize-connections/new?locale=en_US
```

**Comment by rachelmcr** [comment] 2018-11-23 15:34
I just checked the user reports, and I think the issue we see when testing in the alpha version is different from what these users are running into.

In 1581544-zen the user reports this error after entering their Twitter details:

> Unable to verify account name or password

That suggests an authentication error. Can we confirm exactly where that error appears (i.e. does it come from Twitter or from the WP app)?

In 1587043-zen the logs indicate that something is blocking the user's device from connection to the WordPress.com API altogether.

**Comment by rachelmcr** [comment] 2018-11-23 15:50
Other testing results:

I see the same behavior on my moto e5 play with Android 8.1 and my Nexus 9 with Android 7.1.1.
I updated to alpha-138 and get the same results, and I switched back to the release version 11.2 (from the play store) and also get the same results there.

When I use a new test account and site, instead of the issue described above I get this error immediately after selecting Connect on any sharing service (before I have a chance to log in to the service):

> Invalid/missing request nonce

**Comment by rachelmcr** [comment] 2018-11-23 16:34
I investigated this issue with @planarvoid and we concluded that the error is related to the Connecting Twitter modal that appears when you have connected multiple Twitter accounts in the past. I also see that modal for other services (LinkedIn, Facebook) that result in the same error, regardless of the number of accounts previously connected. I updated the original issue based on those finding.

Since it isn't breaking _all_ new connections, and the user reports seem to have a different root cause, it isn't as urgent as it seemed at first. I've marked it for priority groundskeeping but we should monitor for further reports in case there's an uptick in reports of the exact error we see in testing.

**Comment by SiobhyB** [comment] 2018-11-23 16:59
@rachelmcr: Thanks again for looking into this! I've followed up with the user in 1581544-zen to get those extra details.

We also have another report in 1588765-z from a user trying to connect to Facebook.

**Comment by rachelmcr** [comment] 2018-11-23 17:44
I did a quick sweep through issues and am finding a number of reports (including much older versions) that fit this issue:

* 1590155-zen (two Twitter accounts, error with new connection). Report: Nov 23, WPAndroid 11.2.
* 1578303-zen (Twitter and Facebook, user reported seeing "an error occurred"). Report: Nov 19, WPAndroid 11.1.1.
* 1554553-zen (Maybe - reports an error trying to connect Twitter and Facebook). Report: Nov 9, WPAndroid 10.4.
* 1552260-zen (Twitter works, but for Facebook user reported seeing "an error occurred"). Report: Nov 8, WPAndroid 10.4.
* 1340131-zen (Facebook, user reported seeing "an error occurred"). Report: Aug 11, WPAndroid 10.5.2.
* 1338004-zen (Facebook, LinkedIn, Twitter - user reported seeing "an error occurred"). Report: Aug 10, WPAndroid 10.5.2.
* 1326304-zen (Facebook, user reported seeing "an error occurred"). Report: Aug 5, WPAndroid 10.4.
* 1311276-zen (Facebook, user reported seeing "an error occurred"). Report: Jul 29, WPAndroid 104.

It looks like the earliest report of this issue is in 10.4, which released in July. One important thing to note is that this release coincides with the point where Facebook removed the ability to publicize to Facebook profiles (you can only connect to pages now). **I wonder if this error is occurring for accounts where there was previously a Facebook profile connected.**

**Comment by rezzap** [comment] 2018-11-24 20:17
User has reported that the issue is specific to their WP App and not showing in Twitter. They also mentioned having troubles to share any post from the app in particular, so I'm wondering if this is more related to authentication with the app. I have asked them to log out and back in to their WordPress.com account to confirm if the issue still happens after doing so.

**Comment by rezzap** [comment] 2018-11-26 20:04
The user in 1590155-zen did confirm this only happened when they try to add a new connection. Despite the old connection being broken in Publicize Report and not displaying in the site as connected on a browser, when clicking to connect through Twitter, the option displayed in the app also showed the old connection. 

![screenshot_20181126-102239](https://user-images.githubusercontent.com/10325627/49038912-3cba8a00-f1b6-11e8-907f-3a6cd8a4c09a.jpg)


When trying to connect through a browser, they were able to connect to the new Twitter account.

I also wanted to note that Publicize Report showed the new connection 'ok' after the user had tried to add it through the app even though it wasn't actually connected.

**Comment by SiobhyB** [comment] 2018-12-01 17:16
A two star review in Google Play:

> Can't seem to connect to my social media accounts... I get error messages always

**Comment by SiobhyB** [comment] 2018-12-01 18:42
A four star review in Google Play:

> Good app Little problem though...I am yet to configure it to automatically share my blog posts on the social media platforms. It keeps showing "an error occurred".

**Comment by rezzap** [comment] 2018-12-04 14:33
Another report of this same issue was mentioned in 1612501-zen. 

The user was able to connect through the browser, but before doing so old connections were showing in Publicize RC.

**Comment by designsimply** [comment] 2019-03-18 16:47
Tested and confirmed using WPAndroid alpha-156 (12.0 alpha) on Pixel 3 Android 9 with a WordPress.com Business site (simple, no plugins). ([24s](https://user-images.githubusercontent.com/1119271/54547199-e3e04e80-496a-11e9-8963-d7ab1e9c0226.gif))

<img src="https://user-images.githubusercontent.com/1119271/54547245-fce8ff80-496a-11e9-9d7a-8a6bd08a1fd4.png" width="200" alt="sharing-connections-screen"> <img src="https://user-images.githubusercontent.com/1119271/54547247-fd819600-496a-11e9-8e6d-4914951d7a41.png" width="200" alt="connecting-twitter"> <img src="https://user-images.githubusercontent.com/1119271/54547246-fd819600-496a-11e9-8d64-320d584a77a6.png" width="200" alt="connecting-twitter-error">

**Comment by designsimply** [comment] 2019-03-18 16:48
I am moving this to the Prioritized Android list in Groundskeeping for review because there have been several user reports and low app star ratings because of it.

**Comment by designsimply** [comment] 2019-04-03 23:51
Adding `[Pri] High` to this issue because of the high number of user reports and because it has been confirmed a few times over.

**First report:** 132 days ago on Nov 22, 2019 
**User impact:** 19 reports and low app store ratings referenced by happiness engineers.
**Validity:** tested and confirmed by 3 people.

**Closed** 2019-04-16 20:43 UTC
Labels: Sharing, [Pri] High, [Type] Broken Window, [Type] Bug
