### ISSUE TITLE
Block editor: Immediately after adding a new block, show the keyboard to start typing

### ISSUE THREAD

**Issue by arunsathiya** [wordpress-mobile/WordPress-Android#10015] opened 2019-06-10 15:57 UTC
### Expected behavior

Immediately show the keyboard to start typing when a new block (like `Paragraph` block) is added. A click on the block editing region should not be necessary to show the keyboard.

### Actual behavior

A click on the block editing region is required to show the keyboard.

### Steps to reproduce the behavior

- Enable block editor on the app settings
- Choose a website, and create a post/page
- Click on the `+` icon at the bottom left, and add a block like `Paragraph` block

##### Tested on [device], Android [version], WPAndroid [version]

Tested on OnePlus 5 with Android 9. WordPress Android 12.6-rc-1 

##### Notes

Likewise, when one is already typing on a block and uses the `Enter` key available on the keyboard, a new `Paragraph` block is added but the keyboard is immediately closed. It would be great to have the keyboard open in this case as well, to continue typing.

This enhancement request is similar to https://github.com/wordpress-mobile/WordPress-Android/issues/5859 which is for Aztec editor

#enhancement #block-editor

**Comment by arunsathiya** [comment] 2019-06-11 13:17
I also had a chance to test on iOS, and the keyboard seems to stay open when adding new blocks. The same behaviour should be seen on Android.

**Comment by designsimply** [comment] 2019-07-08 23:30
I tested with alpha-177 (12.8 alpha) and found I couldn't reproduce the issue in that version as you described it. I am able to immediately start typing after adding a block or after pressing enter.

@arunsathiya thank you for the report and apologies for not catching up with it sooner! I'm going to close this issue for now with a note to say to please reply back to re-open if you are still experiencing the same problem (because in that case I may have missed a requirement when I tested). If you're still having trouble, we'll want to open a new issue at https://github.com/wordpress-mobile/gutenberg-mobile/issues.

**Closed by designsimply** 2019-07-08 23:30 UTC
Labels: Posting/Editing, [Type] Enhancement

**Comment by arunsathiya** [comment] 2019-07-09 03:28
Thanks for checking, @designsimply! I am not seeing alpha-177 (12.8 alpha) on [the releases page](https://github.com/wordpress-mobile/WordPress-Android/releases) but on https://github.com/wordpress-mobile/WordPress-Android/releases/tag/12.8-rc-2, I see alpha-178. 

I tested with it, and I am not able to reproduce the original error either. Something must have changed between my report and the latest releases. ✅ 

Also taking this opportunity to ask -- what's the difference between https://github.com/wordpress-mobile/WordPress-Android/issues and https://github.com/wordpress-mobile/gutenberg-mobile/issues? Do general WordPress Android issues go on the former, while only the Gutenberg ones go on the latter?

**Comment by designsimply** [comment] 2019-07-11 19:54
> What's the difference between https://github.com/wordpress-mobile/WordPress-Android/issues and https://github.com/wordpress-mobile/gutenberg-mobile/issues? Do general WordPress Android issues go on the former, while only the Gutenberg ones go on the latter?

Exactly. Editor issues go to `gutenberg-mobile` while most other kinds of WPAndroid app issues go to `WordPress-Android`.
